### ISSUE TITLE
AttributeError: 'JobTypeChoice' object has no attribute 'ThermoIntDftEam'

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1006]
The JobType "ThermoIntDftEam" was working before. But now it complains as following:

"AttributeError: 'JobTypeChoice' object has no attribute 'ThermoIntDftEam'"

Maybe pyiron has been updated lately? Any suggestion for this? 

Thank you very much in advance.

**Comment by pmrv** [comment]
`ThermoIntDftEam` is in pyiron_mpie.  It should only appear in `project.job_type` after you `import pyiron_mpie`.

**Comment by lfzhu-phys** [comment]
Thanks a lot for your answer. I tried "import pyiron_mpie", but it complained:
-----------
 "ModuleNotFoundError: No module named 'pyiron.base'"
------------
Does that mean I need to independently install pyiron_mpie on the cluster? Any tutorial for this? I am totally out with respect to this issue.

Thank you very much.

**Comment by sudarsan-surendralal** [comment]
Can you type the following lines:

```
import pyiron_mpie
print(pyiron_mpie.__file__)
```
I think you might be using an older version of `pyiron_mpie`.

**Comment by pmrv** [comment]
That seems to be related to the pyiron->pyiron,pyiron_base split. It sounds like you haven't updated pyiron_mpie for a while.

**Comment by pmrv** [comment]
@lfzhu-phys If you know where `pyiron_mpie` is installed in your user directory on the cluster, you can run `git pull` in this folder.

**Comment by lfzhu-phys** [comment]
@pmrv @sudarsan-surendralal  Thanks a lot for the hints:) I didn't do the update for rather long time. 

Finally it works well now:) Thanks again:)
