### ISSUE TITLE
Does dimension in Atoms matter?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1012]
I just realised that some functions in `Atoms` actually check the dimension. Do we still support different dimensions than 3? If so, do we have active users who could test the functionalities?

I'll mention this one at the next pyiron meeting.

**Comment by sudarsan-surendralal** [comment]
This is legacy code. I'm not sure if any of us users actually use it so please feel free to remove this.

**Comment by samwaseda** [comment]
So we came to the conclusion today at the meeting that we don't really support it, at least as long as there's no one who could make use of it.
