### ISSUE TITLE
ElasticMatrixJob?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron#1025]
@yury-lysogorskiy, @jan-janssen what is the status of [ElasticMatrixJob](https://github.com/pyiron/pyiron_mpie/blob/master/pyiron_mpie/interactive/elastic.py)? It is on the private MPIE repo, and Yury is listed as author (Jan as maintainer) -- but Yury doesn't even have access to this repo!

For the software taskforce I'm trying to put together a piece of code for giving concentration-dependent elastic constants so we can make a toy demo coupling pyiron and DAMASK. Between ElasticMatrixJob and @dgehringer's SQS code that Jan wrapped into pyiron, my job is pretty easy since I just need to string the two pieces together.

ElasticMatrixJob doesn't have unit tests, but so far it's filling my needs perfectly and I'm happy with it. But it's private and hidden so I don't want to use it in public without finding out what's up. Is this code OK to move somewhere public and start using? If Yury is the author we should get him in the commit history somehow.

**Comment by jan-janssen** [comment]
I recently shared it here https://github.com/jan-janssen/lanl-pyiron/blob/master/elastic/elastic.ipynb

**Comment by liamhuber** [comment]
@jan-janssen great! :smile:

@yury-lysogorskiy, do you mind if we just move it over to [pyiron_contrib](https://github.com/pyiron/pyiron_contrib)? (It should probably stay out of pyiron/pyiron until there are unit tests.) Jan, that will be an easier place for me to import it from than your notebook 😉

**Comment by yury-lysogorskiy** [comment]
Aha! Here it is! And I was wondering where ElasticMatrix was, so I reimplemented it again in my [pyiron fork](https://github.com/yury-lysogorskiy/pyiron/blob/icams/atomic-properties/pyiron/atomistics/master/elasticmatrix.py)
So, which scenario would you suggest best for me to work on pyiron? Separate fork or some other repos?

**Comment by jan-janssen** [comment]
We currently work on structuring the pyiron development a bit more:

- pyiron_base for the core components, everything which is not atomistic - this should be stable and ideally covered by unit tests
- pyiron currently our stable atomistic code again we are working on the unit test coverage
- pyiron_contrib community developments these can be based on either pyiron_base or pyiron and are openly shared with the community. 
- pyiron_mpie we still maintain a private pyiron repository to give people to work on their ideas before publishing. 

In principle I am open to adding the Elastic Matrix to either pyiron or pyiron_contrib and I would suggest pyiron_contrib for now. But I see the code is derived from an GPL licensed code which is a bit critical as pyiron is licensed under BSD. If we get the confirmation of the authors that we can license it under BSD in particular as @yury-lysogorskiy reimplemented it that would be great and we should include the original publication as well. The other option would be to release a pyiron_gpl version. 
While I personally do not care about licenses too much we plan to join a larger open source organization, therefore we have to be a bit more careful about the licenses.

**Comment by liamhuber** [comment]
Hi Yury! As Jan suggests, if you're willing to work on pyiron_contrib that would certainly be my preference.

I just pushed a [new branch](https://github.com/pyiron/pyiron_contrib/tree/elastic_constants) (still working on it, no PR yet) where you can [see the application](https://github.com/pyiron/pyiron_contrib/blob/elastic_constants/pyiron_contrib/atomistic/atomistics/master/sqselastic.py) I have in mind. In my ideal world, the elastic.py module would site right next to it at pyiron_controb/atomistic/atomistics/master/elastic.py. 

I guess this will have to wait until we resolve the difference in licenses. That was a good thing to consider, Jan, and I would not have had the wherewithal to remember and check!

**Comment by jan-janssen** [comment]
@liamhuber Is this issue solved? Can you close it? 

**Summary:** 
@samwaseda Developed a new approach to calculate elastic constants which is available in https://github.com/pyiron/pyiron/pull/1079 . I tried to contact the primary author of the original code and did not get any reply, so we decided to drop the elastic matrix job from the main repository and do not plan to create a `pyiron_gpl` repository as that might be too confusing for new users.
