### ISSUE TITLE
Jobs from pyiron_mpie not shown

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1033]
I was trying to load `KMC` and realized that I don't have any of the jobs from `pyiron_mpie` in the list of job types. How can I make them appear again?

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron/issues/1006 
Just 
`import pyiron_mpie`

**Comment by samwaseda** [comment]
!!!! It's the third time that I'm posting the same question ... XD sorry
