### ISSUE TITLE
ThermoBulk class and its documentation

### ISSUE THREAD

**Issue by caglayanoaras** [pyiron/pyiron#1041]
Dear all,
I am calculating expansion coefficient, heat capacity and isothermal bulk modulus using different potentials and structures for my master thesis. While I was wandering in the repo, I have found [ThermoBulk class](https://github.com/pyiron/pyiron/blob/6b821416cd498d0bbc24f39b54acd03a48325ad1/pyiron/atomistics/thermodynamics/thermo_bulk.py) . I have 2 issues about that:

1. There are some minor problems in the class. For instance, it does not raise an error if you don't have an equally spaced temperature array. However, DeltaT is defined as T[1]-T[0]. Additionally, some plot methods are outdated and do not work.
2. My second and bigger issue is that I could not find any documentation about it. I believe I can provide a more comprehensive [phonopy_example ](https://github.com/pyiron/pyiron_jupyter_book/blob/master/notebooks/phonopy_example.ipynb) notebook. In the current documentation notebook, lattice parameters do not show up in the plot(cell 26) which is a minor issue.

I am new to pyiron and will be happy to hear your thoughts.

**Comment by jan-janssen** [comment]
Hi @caglayanoaras, 
Welcome to the pyiron community, we are always happy to meet new users and in particular new contributors. I quickly added an example to explain the Thermobulk module: 
https://github.com/pyiron/pyiron/blob/thermobulk/notebooks/Thermodynamics_QHA.ipynb
In addition we are working on a more extensive thermodynamics example to calculate phase diagrams using the quasi harmonic approximation: 
https://github.com/jan-janssen/NiCr-pyiron-example/blob/master/phasediagram_csv.ipynb
Finally we are currently in process of organising a workshop on thermodynamic calculations. The workshop is a virtual event via zoom. So in case you are interested you can read more about the workshop on: 
https://workshop.materialsgenomefoundation.org

**Comment by pmrv** [comment]
@caglayanoaras Feel free to open a PR with your notebook! 

As for you wanting to calculate expansion coefficients & heat capacity, for now it's probably easiest to setup a number of jobs at different temperatures and compute the derivatives yourself with the help of [PyironTables](https://github.com/pyiron/pyiron/blob/master/notebooks/data_mining.ipynb).

**Comment by jan-janssen** [comment]
@caglayanoaras Can you give us some feedback if the suggestions helped you solve your problem? I just saw you in the pyiron meeting but I forgot to bring up this issue. By the way can you briefly tell me who you are working with, then I can also add you to the pyiron developer group.

**Comment by caglayanoaras** [comment]
@jan-janssen Thank you very much for your interest. I have no problem for now. My main advisor is Raynol. Liam and Tilmann are also involved. I will be happy to be in the group.

**Comment by jan-janssen** [comment]
Great you should have received the invitation via email and you can also access it via https://github.com/orgs/pyiron/invitation
