### ISSUE TITLE
Importing MD simulations

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#1066]
I used to import VASP data using the following code:
```python
pr = Project('Data')
path_to_import = 'path/to/data'
pr.import_from_path(path=path_to_import, recursive=True)
```
And, it is working, but when I try it with MD simulations, it does not work!

**Comment by samwaseda** [comment]
You mean MD simulations with LAMMPS?

**Comment by ibrsam** [comment]
> You mean MD simulations with LAMMPS?

Yes.

**Comment by jan-janssen** [comment]
LAMMPS import is not supported currently, the issue is that LAMMPS input files can be very complex and hence the output is complex to parse as well. Typically the quickest way is to redo the simulation with pyiron.

**Comment by pmrv** [comment]
Maybe this method would be better on the VASP job class, so it doesn't look like it is more general?

**Comment by jan-janssen** [comment]
It also works for the KMC job and in general it should be implemented for more codes like Sphinx.

**Comment by pmrv** [comment]
@ibrsam Would you mind updating the docstrings of 
```python
Project.import_from_path
Project.import_single_calculation
```
to briefly reflect that in a separate pull request?  A short sentence mentioning VASP & KMC would be enough.

**Comment by ibrsam** [comment]
@pmrv  Sure, That is a good idea!

**Comment by ibrsam** [comment]
@pmrv Sure, that is a good idea!
