### ISSUE TITLE
Murnaghan doesn't work with interactive

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1076]
```
lmp = pr.create_job('Lammps', 'lmp')
lmp.structure = pr.create_structure('Fe', 'bcc', 2.855312531)
lmp.potential = 'Fe_C_Becquart_eam'
lmp.server.run_mode.interactive = True
murn = pr.create_job('Murnaghan', 'murn')
murn.ref_job = lmp
murn.run()
```

And I know where's the problem (and I guess I raised this issue some time ago), but since I'm working on something different right now I don't fix this one now.

**Comment by jan-janssen** [comment]
I thought it works if you do: 
```
murn = lmp.create_job('Murnaghan', 'murn')
```

**Comment by samwaseda** [comment]
Oh it does. Interesting :D. But still this is an issue that has to be fixed.

**Comment by jan-janssen** [comment]
Yes, it is still open in pyiron_base https://github.com/pyiron/pyiron_base/issues/19

**Comment by samwaseda** [comment]
Ah here we go perfect
