### ISSUE TITLE
Murnaghan changes volume of ref_job

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1077]
```
lmp = pr.create_job('Lammps', 'lmp')
lmp.structure = pr.create_structure('Fe', 'bcc', 2.855312531)
lmp.potential = 'Fe_C_Becquart_eam'
lmp.server.run_mode.interactive = True
murn = lmp.create_job('Murnaghan', 'murn')
murn.run()
murn.ref_job.structure.cell[0,0]

>>> 2.947482349164692
```

It's not a real problem, but I don't think that's what should be happening (and it's causing a problem to me elsewhere).

**Comment by samwaseda** [comment]
At least this is not what happens when the job is interactive.

**Comment by jan-janssen** [comment]
But when you reload the normal job after the run is finished: 
```
murn.run()
murn = pr.load(murn.job_name)
murn.ref_job.structure.cell[0,0]
```
Then this also gives a wrong volume right? Basically the reference job is not designed to be accessed after the calculation. Instead it is recommended to use `murn.get_structure()`

**Comment by jan-janssen** [comment]
```
murn = pr.load(murn.job_name)
murn.ref_job.structure.cell[0][0]
>>> 2.756773938411933
```

**Comment by samwaseda** [comment]
There's not way to recover the structure from the job? In particular, without `pr` would be nice.

**Comment by jan-janssen** [comment]
In the current implementation the reference job is just used as a template to generate the jobs and it is deleted afterwards.

**Comment by samwaseda** [comment]
That's fine, I just want the original structure.

**Comment by jan-janssen** [comment]
To my knowledge this is not supported.

**Comment by samwaseda** [comment]
Hm ok
