### ISSUE TITLE
Electronic occupancy matrix has a wrong shape

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1085]
Thanks Sam for the comments, I ran a couple of calculations with spin and more than one ionic steps, the shape of the occupancy matrix does not change and remains the same as (kpoints, nbands).  I have made the function shorter as you suggested and added a docstring. 
If this satisfies your comments, you can resolve the conversation. Thanks.

_Originally posted by @sravankumarkb in https://github.com/pyiron/pyiron/pull/1080#discussion_r509596841_

**Comment by samwaseda** [comment]
So essentially the occupancy matrix has two axes, but I expect 4 for `ionic_steps` x `k-points` x `bands` x `spins`.

**Comment by sudarsan-surendralal** [comment]
Thanks for pointing this out! I'll work on this today afternoon!

**Comment by liamhuber** [comment]
We might need another label, because I also don't see this matching [code smell](https://en.wikipedia.org/wiki/Code_smell#Common_code_smells)

**Comment by samwaseda** [comment]
Wait this is a bug

**Comment by liamhuber** [comment]
> Wait this is a bug. Why did you remove it? 

@samwaseda, I have to confess I didn't dig into the code yet, but from the comments here it sounds like it was the output being formatted wrongly. Is the occupancy matrix used somewhere else such that the wrong shape causes the code to crash? If it's really just the *output* being the wrong shape, I can see both your *and* Jan's perspectives that it is/n't a bug...

**Comment by samwaseda** [comment]
Oh ok it’s not impossible that it was just the shape but the only one possible explanation for this error to happen I can come up with was because it parsed the occupancy of only one spin.

**Comment by jan-janssen** [comment]
I would like to reserve the `bug` label for urgent issues, like the failing of the `plot3d()` function and we should try to fix bugs in less than a week to keep pyiron functional. Given this definition, the issue with the occupation matrix to my understanding was mainly that Sudarsan's code used a different structure than Sam'a code, both agreed to use Sam's format in the future but to my knowledge Felix was using the previous implementation based on Sudarsan's code before so it is also working, it is just working not in the way we documented on the webpage.

**Comment by samwaseda** [comment]
> I would like to reserve the `bug` label for urgent issues, like the failing of the `plot3d()` function and we should try to fix bugs in less than a week to keep pyiron functional. Given this definition, the issue with the occupation matrix to my understanding was mainly that Sudarsan's code used a different structure than Sam'a code, both agreed to use Sam's format in the future but to my knowledge Felix was using the previous implementation based on Sudarsan's code before so it is also working, it is just working not in the way we documented on the webpage.

From your statement, I'd have exactly the opposite conclusion: `plot3d` is just some small plot problem which will have hardly any consequence. On the other hand, a wrong occupancy matrix might have serious unexpected consequences, which has to be fixed urgently. I have to admit that the title I first gave probably gave you the impression that it was just the shape, but from the beginning I knew that VASP must have been parsing only one spin, which was the reason why I set bug for this one (which I just checked was very much the case). So in the end, I'd still claim bug is the correct label.
