### ISSUE TITLE
Data Types in Exported PyironTable

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#1088]
I am using `PyironTable` to analyze my calculations and data are stored with the same data type from pyiron. For example, the column `structure` has datatypes of `pyiron.atomistics.structure.atoms.Atoms`. Also, I need to save the data into excel or any other format that can work for anyone who does not access to the raw data. But, when I save it using `df.to_excel()`, all data are saved with datatype `str`. 

To make it more clear, if I am using `structure.cell[ind_0]` this will not work, because `str has no Attribute cell`. 

Is there anyway to solve this problem?

**Comment by pmrv** [comment]
There's no way around data to converting to `str` when using pandas `to_excel()`, at least not from our side.  If you need to share ASE structures annotated with different information I would either use the `Atoms.info` dictionary to save that information and then save the structures [with ASE](https://wiki.fysik.dtu.dk/ase/ase/io/io.html) into a format that saves `info`, too (I haven't check which do). Or put the structures to separate files and put their filenames into the pandas table, then export the table.
