### ISSUE TITLE
How import/export finished jobs for archiving?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#1089]
After the discussion in #1066 and another private conversation I wonder if it is possible to "export" a finished job such that I can copy the HDF file somewhere else and then later "import" again, potentially another/later pyiron installation.  It seems that with @jan-janssen recent efforts to allow jobs to be run on other clusters already need to allow this type of functionality, but maybe without public interface yet.

**Comment by jan-janssen** [comment]
The difficulty is resolving the dependencies of individual jobs, basically you can easily copy all the database entries but then you also have to update all the master ids and their corresponding child ids and this was never fully implemented. When submitting the job to a remote cluster the case is easier as we know the dependence of the jobs and typically only copy a master with its children. I am not even sure if submitting a full pipeline job works at the moment.

**Comment by pmrv** [comment]
The main use case in archiving should be that you can take a finished simulation, put it one tape for a few years and then still can look at results later (if only with an [at that point] older pyiron version).  Therefore I think it would be a start already to be able to export/import single jobs and their data.  For job groups and their dependencies it would probably be best to put them in a single file and avoid the id problems you mention.

**Comment by jan-janssen** [comment]
We did this once back in 2017 when migrating from user specific databases to a central database: 

```
from pyiron.project import Project
from copy import deepcopy
from pyiron.core.settings.jobtable import _job_dict
import pickle
pr = Project()
initial_path = pr.project_path.split('/')[0]
list_of_job_entries = _job_dict(database=pr.db, sql_query=None, user=pr.user, project_path=initial_path, recursive=True)
list_of_job_entries_without_ids = deepcopy(list_of_job_entries)
list_of_job_ids = [job.pop('id') for job in list_of_job_entries_without_ids]
pickle.dump( list_of_job_entries_without_ids, open( "database.pickel", "wb" ) )
```

And read in the database using: 
```
import pickle
from pyiron.project import Project
pr = Project()
db_entry_lst = pickle.load( open( "database.pickel", "rb" ) )
for entry in db_entry_lst:
    if len(entry['project'].split(pr.project_path.split('project')[0])) == 1:
        entry['project'] += pr.project_path.split('project')[0]
new_ids = [pr.db.add_item_dict() for entry in db_entry_lst]
```

This code has to be adjusted to work with the new database ids but the general concept of storing the database and the HDF5 file separately should in principle still work. The more modern way would most likely be storing the job_table as a csv file in the archive with the HDF5 files, then we only need an import for this.

**Comment by jan-janssen** [comment]
As we discussed this topic again today I updated the example https://github.com/jan-janssen/pyiron-export-to-mybinder

**Comment by jan-janssen** [comment]
This is currently work in progress https://github.com/pyiron/pyiron_base/pull/77 so I would prefer to shift the discussion there.
