### ISSUE TITLE
Plotting repeats stops working

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron#1093]
If I look at the repeated structure manually, repeat seems to be working. But plot bombs and just shows the unit cell.

Joerg had the idea that maybe the cell was not getting done right and the atoms are being wrapped back into the unit cell, so I displaced the 0th atom (then you should see two atoms near each other), but this has no effect.

I'm on the current heads of pyiron and pyiron_base.

MWE:
```pyiron
struct = pr.create_ase_bulk('Al', cubic=True).repeat(2)
struct.positions[0, 0] += 0.6
struct.plot3d()
```

**Comment by jan-janssen** [comment]
Also when copying the structure certain things break. This does not work:
```
from pyiron import Project
pr = Project(".")
structure = pr.create_ase_bulk("Al", cubic=True)
structure_copy = structure.copy()
structure_copy[0] = "Ni"
structure_copy.plot3d()
```

While this does: 
```
from pyiron import Project
pr = Project(".")
structure = pr.create_ase_bulk("Al", cubic=True)
structure[0] = "Ni"
structure.plot3d()
```
