### ISSUE TITLE
scipy Volume relaxation

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1094]
I tried to couple the minimisation with GPAW and noticed the force criterion is rather high for volume relaxations: 
```
minm = job.create_job(pr.job_type.ScipyMinimizer, "test_rel")
minm.input.ionic_force_tolerance = 0.001
minm.calc_minimize(pressure=0, volume_only=True)
minm.input.ionic_force_tolerance
```
returns `0.01`

This is caused by:
```
def calc_minimize(
        self,
        max_iter=100,
        pressure=None,
        algorithm='CG',
        ionic_energy_tolerance=0,
        ionic_force_tolerance=1.0e-2,
        volume_only=False,
    ):
```

**Comment by jan-janssen** [comment]
As discussed in the pyiron meeting we should maybe add a separate parameter for the pressure relaxation. @samwaseda Can you take a look at this?

**Comment by samwaseda** [comment]
> As discussed in the pyiron meeting we should maybe add a separate parameter for the pressure relaxation. @samwaseda Can you take a look at this?

Sure
