### ISSUE TITLE
Trying to delete jobs from remote queue causes data loss

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1097]
Some of my remote jobs had convergence problems so I tried to find a way to cancel them within pyiron. The Project class has a queue_delete_job function which I would expect to use the queue_delete_job function from pyiron_base.server.queuestatus, which deletes Jobs from the queuing system so I tried to use it.
It did not cancel the jobs on the remote cluster but instead deleted them completely locally. So I looked it up and indeed the function simply calls the remove functions of the given item. I am not really sure why this is done, but imo this is a critical bug. It already caused data loss for me and I actually think it would be the best to delete it completely until there is another implementation since I don't see why there is a function with a misleading name that does nothing else than calling another function internally. Since I am not sure if this function is used somewhere or fulfills a purpose when using pyiron on the cluster itself I would appreciate if someone involved into core development could have a look at it.
On the long run I actually think it would be a good idea to implement some fallback mechanism for everything that permanently deletes data. Maybe requiring a confirmation similar to project.remove_jobs() or even an option to undo deletes done in the last 24 hours since it has the potential to wipe millions of core hours of calculations in a matter of seconds.

**Comment by jan-janssen** [comment]
When pyiron is installed on the login node, then the `remove_job()` function checks if the job exists on the queuing system and deletes it if it does. So for an installation on the login node the `queue_delete_job()` function is a backwards compatible interface for removing jobs combining the deleting from the queuing system and the deleting from the pyiron database in the same function. This been said, I understand that you want to delete the job from the queuing system, but I am not sure why you want to keep the job in the pyiron database after you removed it from the queuing system.

**Comment by pmrv** [comment]
> an option to undo deletes done in the last 24 hours since it has the potential to wipe millions of core hours of calculations in a matter of seconds.

I don't think it's a bad idea.  A cheap way would be to create a "trash-bin" project in the user's base project folder and move a job there when calling a delete-type function with the existing `Project.move_to()`.  This project could be emptied every so often with a cronjob and the pyiron CLI.  I don't have time right now to volunteer an implementation, but if more people want this I could add  it to the backlog.

**Comment by Leimeroth** [comment]
> This been said, I understand that you want to delete the job from the queuing system, but I am not sure why you want to keep the job in the pyiron database after you removed it from the queuing system.

The job was running but had problems with electronic convergence, so I wanted to cancel it, change some inputs and see if that would fix the problem.

**Comment by Leimeroth** [comment]
> I don't think it's a bad idea. A cheap way would be to create a "trash-bin" project in the user's base project folder and move a job there when calling a delete-type function with the existing `Project.move_to()`. This project could be emptied every so often with a cronjob and the pyiron CLI. I don't have time right now to volunteer an implementation, but if more people want this I could add it to the backlog.

To me this sound exactly like what I would have needed here.

**Comment by jan-janssen** [comment]
Have you tried: 
```
job = pr.load(...)
job.input = ....
job.run(delete_existing=True)
```
If you load the job, overwrite the input and then submit it again, pyiron automatically deletes the existing job by removing the input files and deleting the job from the queuing system and afterwards submits a new job with the update settings.

**Comment by samwaseda** [comment]
One thing maybe we should then do (if we have the fallback functionality) is also to check whether the job was submitted to the queue, because otherwise if we're simply testing a new class with quick local LAMMPS jobs, it might have an impact on the disk space.

**Comment by Leimeroth** [comment]
> Have you tried:
> 
> ```
> job = pr.load(...)
> job.input = ....
> job.run(delete_existing=True)
> ```
> 
> If you load the job, overwrite the input and then submit it again, pyiron automatically deletes the existing job by removing the input files and deleting the job from the queuing system and afterwards submits a new job with the update settings.

If I try that I actually have 2 jobs in the queue on the cluster that attempt to run in the same directory and therefore crash or result in a total mess up

**Comment by jan-janssen** [comment]
> If I try that I actually have 2 jobs in the queue on the cluster that attempt to run in the same directory and therefore crash or result in a total mess up

But then that sounds like the true bug to me, because this works fine for installations on the local cluster and it is definitely possible that this feature does not yet work with remote clusters.

**Comment by Leimeroth** [comment]
> One thing maybe we should then do (if we have the fallback functionality) is also to check whether the job was submitted to the queue, because otherwise if we're simply testing a new class with quick local LAMMPS jobs, it might have an impact on the disk space.

I would suggest 2 functions similar to remove_jobs() and remove_jobs_silently() for cases like that.

**Comment by jan-janssen** [comment]
@samwaseda As you liked the primary post, I was wondering if you experienced a similar bug on our system, because that should not be the case for my understanding.

**Comment by Leimeroth** [comment]
> But then that sounds like the true bug to me, because this works fine for installations on the local cluster and it is definitely possible that this feature does not yet work with remote clusters.

I agree if it works like that with your local installation, but I still think queue_delete_job is a very misleading name for a function that completely removes the job from pyiron and I do not see why it exists if it internally just calls job.remove()

**Comment by jan-janssen** [comment]
Can you try deleting the job directly using: 
```
from pyiron_base.server.queuestatus import queue_delete_job
queue_delete_job(job.server.queue_id) 
```

**Comment by Leimeroth** [comment]
> Can you try deleting the job directly using:
> 
> ```
> from pyiron_base.server.queuestatus import queue_delete_job
> queue_delete_job(job.server.queue_id) 
> ```

This does not delete it from the queuing system and returns none and I as understand it it is has no way to find out which queue adapter to use.

**Comment by jan-janssen** [comment]
Or even more simple: 
https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/project/generic.py#L1445
```
pr._queue_delete_job(item=job)
```

**Comment by pmrv** [comment]
> Or even more simple:
> https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/project/generic.py#L1445
> 
> ```
> pr._queue_delete_job(item=job)
> ```

To be fair, this is marked as an internal method, so even if you found it, you wouldn't want to use it.

**Comment by Leimeroth** [comment]
> > Or even more simple:
> > https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/project/generic.py#L1445
> > ```
> > pr._queue_delete_job(item=job)
> > ```
> 
> To be fair, this is marked as an internal method, so even if you found it, you wouldn't want to use it.

It also doesn't work, I guess the problem is again that it doesn't know which queue_
adapter to use

**Comment by jan-janssen** [comment]
> This does not delete it from the queuing system and returns none and I as understand it it is has no way to find out which queue adapter to use.

But the queue id is set correctly: 
```
job.server.queue_id
```

Because in general the `delete_job()` function is implemented for the remote queue adapter: 
https://github.com/pyiron/pysqa/blob/master/pysqa/utils/remote.py#L70

**Comment by Leimeroth** [comment]
I think the problem is in the queue_delete_job function itself

if s.queue_adapter is not None:
        return s.queue_adapter.delete_job(process_id=que_id)
else:
        return None

The queue adapter is not set at any point, so it just returns None

**Comment by jan-janssen** [comment]
But that is very strange because the queue adapter should be initialised when the `.pyiron` config is parsed.

**Comment by samwaseda** [comment]
> @samwaseda As you liked the primary post, I was wondering if you experienced a similar bug on our system, because that should not be the case for my understanding.

I liked the suggestion in the last part. But to be honest, deleting jobs has always been somewhat buggy, but since I was never able to identify the cause, I also never reported it.

**Comment by Leimeroth** [comment]
> But that is very strange because the queue adapter should be initialised when the `.pyiron` config is parsed.
> https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/settings/generic.py#L122

Then I don't understand what is happening.

**Comment by jan-janssen** [comment]
Can you test the notebook that you used to submit the jobs: 
```
from pyiron_base import Settings
s = Setting()
s.queue_adapter
```
And then check if this is different from the notebook you used to delete the jobs.

**Comment by Leimeroth** [comment]
> Can you test the notebook that you used to submit the jobs:
> 
> ```
> from pyiron_base import Settings
> s = Setting()
> s.queue_adapter
> ```
> 
> And then check if this is different from the notebook you used to delete the jobs.

This was all done in the same notebook. It doesn't work even if I i do job.run() in one cell and try to delete it in the next one

**Comment by jan-janssen** [comment]
But if there is no queue adapter I do not understand how the job is submitted to the remote cluster in the first place.

**Comment by Leimeroth** [comment]
Can I implement some debugging comments similar to the logger.warning/debug/whatever style used in pyiron in pysqa somehow?

**Comment by jan-janssen** [comment]
Sure, even though I am still not sure pysqa is the issue here as the queue adapter is defined inside pyiron and I do not understand how it can be None once and you are still able to submit jobs.

**Comment by Leimeroth** [comment]
So I did some more testing and I think I found the issue with the s.queue_adapter.delete_job(process_id=que_id), but I am not sure where it exactly comes from. The command that is finally executed on the cluster is  "scancel None" because the job id gets lost at some point. It is still there in the initial python command, so I am rather confused about what happens inbetween.

**Comment by jan-janssen** [comment]
Can you test with: https://github.com/pyiron/pysqa/pull/41 ? We were missing a single character `=` ...

**Comment by Leimeroth** [comment]
> Can you test with: [pyiron/pysqa#41](https://github.com/pyiron/pysqa/pull/41) ? We were missing a single character `=` ...

This cancels the job correctly.

**Comment by Leimeroth** [comment]
Can I additionally replace the project.queue_delete_job  method with project._queue_delete_job or can I delete the queue_delete_job method completely to stop people from deleting jobs by accident like I did or would that break something? 
I think that is still the most important point with this issue

**Comment by jan-janssen** [comment]
Sure, replace it with `project._queue_delete_job` and then we can discuss it in the pull request.

**Comment by Leimeroth** [comment]
Should be fixed now
