### ISSUE TITLE
Get info of jobs for a pyiron table

### ISSUE THREAD

**Issue by yuyuanjingxuan** [pyiron/pyiron#1106]
I am trying to collect all information of my job based on PyironTable according to the tutorial [link](https://pyiron.readthedocs.io/en/latest/source/notebooks/data_mining.html). <br/>
First step is to creating a pyiron table: <br/>
```python
table = Proj.create_table("table")
```
As it writes, to obtain a specific property I am interested in, a function should be defined:
```python
def myfunc(job):
    return job["..."]
```
To add the functions using the labels: 
```python
table.add["myprop"] = myfunc
```
Here, the type of job is `pyiron_base.job.path.JobPath`. To get more information about the results, it is necessary to convert `job` to `pyiron.vasp.vasp.Vasp`. <br/>
I know how to do it via `Proj.load(job_specifier='...', convert_to_object=True)`, while I have no idea how to convert it when adding the functions to a PyironTable. 

In addition, to load massive data with `convert_to_object=True` is greatly time-consuming. Could you give me a few suggestions how to accelerate it?

**Comment by jan-janssen** [comment]
The pyiron table also has an `convert_to_object` property: 
```
table.convert_to_object = True
```
This converts all jobs in the beginning. You can also do it inside the function but that might be duplicated work, if you need the full job object in more than one function: 
```
def myfunc(job):
      job_full = job.to_object()
      return type(job_full)
```
Finally @pmrv is looking into the option the option of loading only some parts of the full job but that is not yet fully implemented. Here is an example only loading the input structure https://github.com/pyiron/pyiron/blob/master/pyiron/table/funct.py#L129

**Comment by pmrv** [comment]
If you just need numeric data from the jobs (energies, positions, etc.), you can already access them right now from the `JobPath` object.  To find out under which HDF5 path you can access them, you can manually with a test job look at `job['output']` the groups and nodes in there you can use to navigate the output data, e.g. `job['output/generic/energy_pot']` gives the potential energy on most atomistic jobs. There's also a lot of function predefined [here](https://pyiron.readthedocs.io/en/latest/apidoc/pyiron.table.funct.html?highlight=funct#module-pyiron.table.funct), I think the way to access them is 
```python
table.add.get_encut
```
(this adds the function to the table directly).  If you need other values, feel free to mention them here and try to write a simple function for it, then we can see if it is easily added to the predefined list.

**Comment by jan-janssen** [comment]
@yuyuanjingxuan Can you give us some feedback if your issue is solved? In case it is solved feel free to close the issue.

**Comment by yuyuanjingxuan** [comment]
Thank you very much @jan-janssen and @pmrv. My issue is solved perfectly.
