### ISSUE TITLE
periodic boundary conditions and Lammps

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1109]
When setting periodic boundary conditions of a structure to False this does not change lammps input. The control file still states
`boundary p p p ` where I would expect `boundary f f f`.

Example:
```
from pyiron import Project
pr = Project("test_pbc")
pr.remove_jobs_silently()
job = pr.create_job("Lammps", "TestPBC")
job.structure = pr.create_ase_bulk("Cu", cubic=True)
print(job.structure.pbc)
job.structure.set_pbc(pbc=False)
job.run()
print(job.get_structure(iteration_step=-1).pbc)
job.input.control
```

**Comment by jan-janssen** [comment]
I have to admit we never really did calculations without periodic boundaries. But you should be able to change the periodic boundaries with the LAMMPS specific syntax:
```
job_md.input.control["boundary"] = "f f f"
```

**Comment by jan-janssen** [comment]
I looked at the code and found it is already implemented: 
```
        if not all(self.structure.pbc):
            self.input.control["boundary"] = " ".join(
                ["p" if coord else "f" for coord in self.structure.pbc]
            )
```
https://github.com/pyiron/pyiron/blob/master/pyiron/lammps/base.py#L333
So there seems to be a bug with the current implementation.

**Comment by jan-janssen** [comment]
Ok, actually it works, it is just not stored correctly: 
```
job.decompress()
job["log.lammps"]
```
This gives me: 
```
['LAMMPS (3 Mar 2020)\n',
 'units metal\n',
 'dimension 3\n',
 'boundary f f f\n',
 'atom_style atomic\n',
 ...]
```

**Comment by Leimeroth** [comment]
I only found this because I had wrong energies in gamma surface calculations, which could only be fixed by setting the periodic boundary conditions manually. So it can't only be a problem of storing it.

**Comment by jan-janssen** [comment]
@Leimeroth That is definitely possible, but the bug described above is fixed by the pull request I opened. Can you provide an example which still fails with these new fixes?

**Comment by jan-janssen** [comment]
In addition we had a critical issue with interactive Lammps calculation, which lead to very wired results https://github.com/pyiron/pyiron/issues/1145 so in case you might used interactive Lammps jobs this could also correct your energies.

**Comment by Leimeroth** [comment]
Ok, the issue is acutally fixed and the problem was in the underlying GammaSurface class from the workshop in which the periodic boundary condition in z direction was set to true.

**Comment by jan-janssen** [comment]
Great, by the way we have an updated version of the gamma surface script available at https://github.com/pyiron/pyiron/blob/master/notebooks/gamma_surface_parallel_master.ipynb So if you want to modify it we could also add it as an official class.

**Comment by Leimeroth** [comment]
I changed some parts of it, but it is still missing a quite a bit of funcitonality to be added to pyiron imo. But maybe it would be a good idea to put it into pyiron contribution so that it is easier to find? I copied some of the classes like the old version of elastic and the GammaSurface into a python script to use it myself, but I would assume that this is exactly what contribution is for.

**Comment by jan-janssen** [comment]
Yes, feel free to open a pull request on pyiron contrib - unfortunately the elastic matrix code is using code licensed under the GPL license while pyiron is licensed under the BSD license so we can not include it currently, you can find more information on this issue here https://github.com/pyiron/pyiron/issues/1025
