### ISSUE TITLE
Lammps not working

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#1117]
I trying to run a Lammps job, but I am getting this unusual error.
```python
2020-10-29 14:36:49,993 - pyiron_log - WARNING - Job aborted
2020-10-29 14:36:49,995 - pyiron_log - WARNING - /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/lammps/bin/run_lammps_2019.06.05_default.sh: line 2: exec: lmp_serial: not found

The job md_basic was saved and received the ID: 9994265

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in run_static(self)
    745                     stderr=subprocess.STDOUT,
--> 746                     universal_newlines=True,
    747                 )

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    410     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 411                **kwargs).stdout
    412 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    511             raise CalledProcessError(retcode, process.args,
--> 512                                      output=stdout, stderr=stderr)
    513     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/lammps/bin/run_lammps_2019.06.05_default.sh' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-61-dc1af6e70e0a> in <module>
      4 job_unit.structure = basis
      5 job_unit.calc_minimize(pressure=0.0)
----> 6 job_unit.run()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    682                 status = "created"
    683             if status == "initialized":
--> 684                 self._run_if_new(debug=debug)
    685             elif status == "created":
    686                 que_id = self._run_if_created()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1392         else:
   1393             self.save()
-> 1394             self.run()
   1395 
   1396     def _run_if_created(self):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    684                 self._run_if_new(debug=debug)
    685             elif status == "created":
--> 686                 que_id = self._run_if_created()
    687                 if que_id:
    688                     self._logger.info(

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in _run_if_created(self)
   1409             self.run_if_manually()
   1410         elif self.server.run_mode.modal:
-> 1411             self.run_static()
   1412         elif self.server.run_mode.non_modal or self.server.run_mode.thread:
   1413             self.run_if_non_modal()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in run_static(self)
    777                 if self.server.run_mode.non_modal:
    778                     s.close_connection()
--> 779                 raise RuntimeError("Job aborted")
    780             else:
    781                 job_crashed = True

RuntimeError: Job aborted
```

**Comment by samwaseda** [comment]
Post the lines you used which caused this error.

**Comment by ibrsam** [comment]
basis = pr.create_structure("Al", "fcc", 4.04)
job_unit = pr.create_job(pr.job_type.Lammps, "UnitCell")
job_unit.potential = 'Al_H_Ni_Angelo_eam'
job_unit.structure = basis
job_unit.calc_minimize(pressure=0.0)
job_unit.run()

**Comment by samwaseda** [comment]
Do you have `module load pyiron/dev` in your `.bashrc`?

**Comment by ibrsam** [comment]
I have this line
`#module load pyiron/dev`

**Comment by samwaseda** [comment]
Remove the hash and reload the notebook. If the problem persists, restart your kernel.

**Comment by ibrsam** [comment]
I did so and still have this problem. Also, I used to run the same code before, and I never got this error. Now even, I notice that it takes more time for `job` to be aborted since I am now loading a module and not executing the program directly which is added to my `$PYTHONPATH`. 

I do not know why it does not find the executable `lmp_serial`

**Comment by samwaseda** [comment]
> I did so and still have this problem. Also, I used to run the same code before, and I never got this error. Now even, I notice that it takes more time for `job` to be aborted since I am now loading a module and not executing the program directly which is added to my `$PYTHONPATH`.
> 
> I do not know why it does not find the executable `lmp_serial`

Loading the module does not take place locally. If it takes more time, it comes from elsewhere. Can you put `! which lmp_serial` in your notebook and see what it returns?

**Comment by pmrv** [comment]
> Remove the hash and reload the notebook. If the problem persists, restart your kernel.

Might actually need to restart your jupyter server (File -> Hub Control Panel -> restart).

**Comment by ibrsam** [comment]
`which: no lmp_serial in (/u/ibrsam/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/afs/ipp/amd64_sles15/bin:/mpcdf/soft/SLE_15/packages/x86_64/find-module/1.0/bin)`

**Comment by samwaseda** [comment]
> which: no lmp_serial in (/u/ibrsam/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/afs/ipp/amd64_sles15/bin:/mpcdf/soft/SLE_15/packages/x86_64/find-module/1.0/bin)

Did you really restart your kernel?

**Comment by samwaseda** [comment]
Oh I see that @pmrv pointed it out as well.

**Comment by ibrsam** [comment]
Yes, I did so.

**Comment by samwaseda** [comment]
> Yes, I did so.

ok now put `! module load pyiron/dev && which lmp_serial` and see what it returns.

**Comment by ibrsam** [comment]
`/u/system/SLES12/soft/pyiron/dev/anaconda3/bin/lmp_serial`

**Comment by samwaseda** [comment]
> /u/system/SLES12/soft/pyiron/dev/anaconda3/bin/lmp_serial

ok then `.bashrc` was not loaded. Go to the front page of jupyter->Control Panel->Stop My Server (as @pmrv pointed out). Otherwise you can also wait for @jan-janssen to merge his commit.

**Comment by ibrsam** [comment]
The point is that it was working with me perfectly without having ` module load pyiron/dev` in my `bashrc` file, and I want to use it as before. Sure, I can wait, if this helps the problem.

**Comment by samwaseda** [comment]
Oh wait if the essence of what you want is not loading `pyiron/dev`, then what @jan-janssen is doing is exactly the opposite, because it will be loaded automatically. Can you elaborate on your point maybe a bit for us to understand why you don't want to load it?

**Comment by jan-janssen** [comment]
@ibrsam This is the same issue that @zendegani posted here https://github.com/pyiron/pyiron_mpie/issues/37 this was never intended to work and the clear recommendation is to leave the line:
```
module load pyiron/dev
```
in your `.bashrc` at any time, never comment it out. Otherwise we would have multiple people with this issue once the login node has to be rebooted. Currently we see this issue coming up from time to time when the sessions of certain users are rebooted, but I really start to wonder why people remove the module load part. 

In the mean time I updated the resources to at least fix the lammps issue. Still you should do the following steps: 
* Shutdown your jupyter server 
* logout of the jupyterhub 
* disconnect the ssh connection
* reconnect with ssh 
* confirm the .bashrc is setup correctly 
* access the jupyterhub again 
Afterwards you should be able to execute Lammps calculations as expected and you can confirm the module is loaded correctly by:
```
import os
os.environ["CONDA_PREFIX"]
``` 
This should return: 
```
/u/system/SLES12/soft/pyiron/dev/anaconda3
```

**Comment by ibrsam** [comment]
Thanks for resolving the issue!
