### ISSUE TITLE
Updating master jobs after fetching from remote

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1124]
I ran a few Murnaghan jobs on a remote cluster and noticed that there status does not get updated when the child jobs are finished and downloaded. I tried to fix it by manually calling a few functions like run(), collect_output(), refresh_job_status() one the master job, but this didn't help. This is not super critical since it is still possible to call f.e. fit_polynomial() and retrieve results, but it is quite irritating when looking at the job_table()

**Comment by jan-janssen** [comment]
Just for me to understand this, the individual jobs are submitted to the cluster while the murnaghan remains locally right? What is the status of the murnaghan job afterwards? Can you try: 
```
murn.status.collect = True 
murn.run()
```
I assume the status of the Murnaghan is suspended, after the jobs are submitted and it does not recognise when they are transferred back, but at least the collect should work afterwards.

**Comment by Leimeroth** [comment]
> Just for me to understand this, the individual jobs are submitted to the cluster while the murnaghan remains locally right?

Yes when I do murn.run() the child jobs are submitted.

> What is the status of the murnaghan job afterwards?

suspended

>Can you try:
> 
> ```
> murn.status.collect = True 
> murn.run()
> ```
> 
> I assume the status of the Murnaghan is suspended, after the jobs are submitted and it does not recognise when they are transferred back, but at least the collect should work afterwards.

Yes doing this correctly sets the status to True

**Comment by jan-janssen** [comment]
> Yes doing this correctly sets the status to True

Afterwards the job status should be `finished`.

**Comment by Leimeroth** [comment]
Sorry thats what I meant

**Comment by jan-janssen** [comment]
@Leimeroth Can you check if https://github.com/pyiron/pyiron_base/pull/66 solves your issue?

**Comment by Leimeroth** [comment]
Fixed in pyiro
