### ISSUE TITLE
Importing calculated VASP one passes wrong structure

### ISSUE THREAD

**Issue by suhyunyoo** [pyiron/pyiron#1126]
While I'm trying to import already calculated VASP jobs and analyze them,
I found that the structure info is wrongly imported.
Anyone experiences the same thing or am I using wrong function?

Firstly, when I imported just structure file, using
`imp_str = ase_to_pyiron(ase.io.read(filename='CONTCAR', format='vasp'))`
`print(imp_str)`

It gives:

> Pd: [3.04219737e-03 1.75641347e-03 8.97991190e+00]
Pd: [5.59618928e+00 1.54183239e-03 8.97993715e+00]
Pd: [5.59948449 4.84896223 8.9911827 ]
Pd: [8.39860061 4.84893432 8.99084229]
Pd: [6.99906672 2.42481471 8.9911827 ]
...
Pd: [-1.02721015e-02 -5.93060057e-03  3.64066279e+01]
Pd: [ 2.80998072e+00 -6.00835372e-03  3.64070757e+01]
Pd: [ 2.79925365  4.84906523 36.43898164]
Pd: [ 8.39887568  4.84909314 36.43932205]
K: [2.79940901 1.61623945 6.30553079]
K: [ 1.39996002  0.80826734 39.12462921]

You may see adsorped K on the bottom and the top of the Pd slab, which is correct.

But when I import the whole calculation, using

`path = ['/u/suhyun/PyIron_data/tests/K_011/fcc']`
`pr.import_from_path(path[0])`
`job = pr.load(pr.get_job_ids()[0])`
`structure = job.get_structure()`
`print(structure)`

> Pd: [5.59948454 4.84896225 8.99118286]
Pd: [8.39860062 4.84893432 8.99084214]
Pd: [6.99906677 2.42481473 8.99118286]
...
Pd: [ 7.00934976  7.26751223 36.40707587]
Pd: [ 2.79925369  4.84906525 36.43898148]
Pd: [ 8.39887563  4.84909311 36.4393222 ]
Pd: [2.79940907 1.61623948 6.305531  ]
Pd: [ 1.39996005  0.80826736 39.12462926]
K: [3.04219093e-03 1.75640975e-03 8.97991209e+00]
K: [5.59618925e+00 1.54184089e-03 8.97993708e+00]

You can see the order of elements and coordinates is mixed.

Did I something wrong with commands?

**Comment by suhyunyoo** [comment]
It gives me the correct structure

**Comment by sudarsan-surendralal** [comment]
Can you post the contents of the POSCAR file here!

**Comment by suhyunyoo** [comment]
This is the imported file

Pd                                      
   1.00000000000000     
     8.3987381457000012    0.0000000000000000    0.0000000000000000
     4.1993690729999997    7.2735205941000007    0.0000000000000000
     0.0000000000000000    0.0000000000000000   45.4301643371999972
   Pd   K 
   117     2
Selective dynamics
Direct
  0.0002414805113928  0.0002414805113928  0.1976640856881171   T   T   T
  0.6662071142926336  0.0002119788307690  0.1976646415902823   T   T   T
  0.3333756569515607  0.6666595857596536  0.1979121763537010   T   T   T
  0.6666557495260214  0.6666557495260214  0.1979046833804923   T   T   T
  0.6666595857596536  0.3333756569515607  0.1979121763537010   T   T   T
 -0.0016514698069566  0.3341593918612925  0.1986144833863455   T   T   T
  0.0002119788307690  0.6662071142926336  0.1976646415902823   T   T   T
  0.3341487019692383  0.3341487019692383  0.1986243407920742   T   T   T
  0.3341593918612925 -0.0016514698069566  0.1986144833863455   T   T   T
  0.7778027319519315  0.1110509682508621  0.2483927562387874   T   T   T
  0.4449002905060225  0.7768751624793496  0.2487646019687189   T   T   T
  0.7778049234481729  0.7778049334150411  0.2484003673408643   T   T   T
  0.7768751525124814  0.4449003004728836  0.2487646019687189   T   T   T
  0.1107928802776730  0.4450743163972709  0.2487345540941599   T   T   T
  0.1108019253037293  0.1108019352705975  0.2487310456310999   T   T   T
  0.1110509582839939  0.7778027419187997  0.2483927562387874   T   T   T
  0.4448940462299912  0.4448940561968523  0.2487623736515899   T   T   T
  0.4450743064304097  0.1107928902445412  0.2487345540941599   T   T   T
  0.8887618403136361  0.2221602240767529  0.2988253471289343   T   T   T
  0.5557486267866041  0.8887564464284698  0.2988225884619786   T   T   T
  0.8888890392171722  0.8888890192464165  0.2986584309563379   T   T   T
  0.8887564663992256  0.5557486068158413  0.2988225884619786   T   T   T
  0.2221614040665777  0.5557487753566170  0.2988237337978324   T   T   T
  0.2222202716367885  0.2222202516660257  0.2988339316477141   T   T   T
  0.2221602440475157  0.8887618203428804  0.2988253471289343   T   T   T
  0.5555550488270136  0.5555550288562507  0.2989994915482929   T   T   T
  0.5557487953273799  0.2221613840958149  0.2988237337978324   T   T   T
  0.6666666666666643  0.0000000000000000  0.3490530549768494   F   F   F
  0.3333333333333357  0.6666666666666643  0.3490530549768494   F   F   F
  0.6666666666666643  0.6666666666666643  0.3490530549768494   F   F   F
  0.6666666666666643  0.3333333333333357  0.3490530549768494   F   F   F
  0.0000000000000000  0.3333333333333357  0.3490530549768494   F   F   F
  0.0000000000000000  0.0000000000000000  0.3490530549768494   F   F   F
  0.0000000000000000  0.6666666666666643  0.3490530549768494   F   F   F
  0.3333333333333357  0.3333333333333357  0.3490530549768494   F   F   F
  0.3333333333333357  0.0000000000000000  0.3490530549768494   F   F   F
  0.7777777711242990  0.1111111144245029  0.3993687032548010   F   F   F
  0.4444444377909704  0.7777777810911672  0.3993687032548010   F   F   F
  0.7777777711242990  0.7777777810911672  0.3993687032548010   F   F   F
  0.7777777711242990  0.4444444477578315  0.3993687032548010   F   F   F
  0.4444444377909704  0.4444444477578315  0.3993687032548010   F   F   F
  0.1111111044576347  0.4444444477578315  0.3993687032548010   F   F   F
  0.1111111044576347  0.1111111144245029  0.3993687032548010   F   F   F
  0.4444444377909704  0.1111111144245029  0.3993687032548010   F   F   F
  0.1111111044576347  0.7777777810911672  0.3993687032548010   F   F   F
  0.8888888955510978  0.2222222089136707  0.4496843517528646   F   F   F
  0.5555555622177692  0.8888888755803421  0.4496843517528646   F   F   F
  0.8888888955510978  0.8888888755803421  0.4496843517528646   F   F   F
  0.8888888955510978  0.5555555422470064  0.4496843517528646   F   F   F
  0.2222222288844335  0.5555555422470064  0.4496843517528646   F   F   F
  0.2222222288844335  0.2222222089136707  0.4496843517528646   F   F   F
  0.5555555622177692  0.2222222089136707  0.4496843517528646   F   F   F
  0.5555555622177692  0.5555555422470064  0.4496843517528646   F   F   F
  0.2222222288844335  0.8888888755803421  0.4496843517528646   F   F   F
  0.6666666666666643  0.0000000000000000  0.5000000000308162   F   F   F
  0.3333333333333357  0.6666666666666643  0.5000000000308162   F   F   F
  0.6666666666666643  0.6666666666666643  0.5000000000308162   F   F   F
  0.6666666666666643  0.3333333333333357  0.5000000000308162   F   F   F
  0.3333333333333357  0.3333333333333357  0.5000000000308162   F   F   F
  0.0000000000000000  0.3333333333333357  0.5000000000308162   F   F   F
  0.0000000000000000  0.0000000000000000  0.5000000000308162   F   F   F
  0.3333333333333357  0.0000000000000000  0.5000000000308162   F   F   F
  0.0000000000000000  0.6666666666666643  0.5000000000308162   F   F   F
  0.4444444377909704  0.7777777810911672  0.5503156483087679   F   F   F
  0.7777777711242990  0.1111111144245029  0.5503156483087679   F   F   F
  0.7777777711242990  0.7777777810911672  0.5503156483087679   F   F   F
  0.4444444377909704  0.4444444477578315  0.5503156483087679   F   F   F
  0.7777777711242990  0.4444444477578315  0.5503156483087679   F   F   F
  0.1111111044576347  0.4444444477578315  0.5503156483087679   F   F   F
  0.1111111044576347  0.1111111144245029  0.5503156483087679   F   F   F
  0.4444444377909704  0.1111111144245029  0.5503156483087679   F   F   F
  0.1111111044576347  0.7777777810911672  0.5503156483087679   F   F   F
  0.5555555622177692  0.8888888755803421  0.6006312965867124   F   F   F
  0.5555555622177692  0.5555555422470064  0.6006312965867124   F   F   F
  0.8888888955510978  0.2222222089136707  0.6006312965867124   F   F   F
  0.8888888955510978  0.8888888755803421  0.6006312965867124   F   F   F
  0.8888888955510978  0.5555555422470064  0.6006312965867124   F   F   F
  0.2222222288844335  0.5555555422470064  0.6006312965867124   F   F   F
  0.2222222288844335  0.2222222089136707  0.6006312965867124   F   F   F
  0.5555555622177692  0.2222222089136707  0.6006312965867124   F   F   F
  0.2222222288844335  0.8888888755803421  0.6006312965867124   F   F   F
  0.3333333333333357  0.6666666666666643  0.6509469448646641   F   F   F
  0.3333333333333357  0.3333333333333357  0.6509469448646641   F   F   F
  0.6666666666666643  0.0000000000000000  0.6509469448646641   F   F   F
  0.6666666666666643  0.6666666666666643  0.6509469448646641   F   F   F
  0.6666666666666643  0.3333333333333357  0.6509469448646641   F   F   F
  0.0000000000000000  0.3333333333333357  0.6509469448646641   F   F   F
  0.0000000000000000  0.0000000000000000  0.6509469448646641   F   F   F
  0.3333333333333357  0.0000000000000000  0.6509469448646641   F   F   F
  0.0000000000000000  0.6666666666666643  0.6509469448646641   F   F   F
  0.4445768669428426  0.7775847165223324  0.7011774115996539   T   T   T
  0.4444442941248959  0.4444443040917570  0.7013415691052944   T   T   T
  0.7775845380146884  0.1111719392423588  0.7011762662637999   T   T   T
  0.7777782845150547  0.7777782944819229  0.7010005085133397   T   T   T
  0.7775847065554642  0.4445768769097037  0.7011774115996539   T   T   T
  0.1111730892945526  0.4445715029952932  0.7011746529326981   T   T   T
  0.1111130617052797  0.1111130716721479  0.7011660684139184   T   T   T
  0.4445714930284321  0.1111730992614208  0.7011746529326981   T   T   T
  0.1111719292754905  0.7775845479815566  0.7011762662637999   T   T   T
  0.5564581808295869  0.8884330228652899  0.7512353980929136   T   T   T
  0.5555284098938954  0.5555283899231326  0.7515996327207682   T   T   T
  0.8884330428360456  0.5564581608588240  0.7512353980929136   T   T   T
  0.8882590269116584  0.2225404330936324  0.7512654459674727   T   T   T
  0.8884392871120773  0.8884392671413216  0.7512376264100427   T   T   T
  0.2222823750580744  0.5555305814193739  0.7516072438228451   T   T   T
  0.2225314080383390  0.2225313880675761  0.7512689544305325   T   T   T
  0.5555306013901368  0.2222823550873116  0.7516072438228451   T   T   T
  0.2225404530643953  0.8882590069409027  0.7512654459674727   T   T   T
  0.3331213545025667  0.6671262190406950  0.8023353584053123   T   T   T
  0.3330918528219430  0.3330918528219430  0.8023359143074775   T   T   T
  0.6671262190406950  0.3331213545025667  0.8023353584053123   T   T   T
  0.6666737475736750 -0.0000423236182250  0.8020878236418937   T   T   T
 -0.0008260585279568  0.3349848031402923  0.8013855166092489   T   T   T
 -0.0008153686359026 -0.0008153686359026  0.8013756592035205   T   T   T
  0.3349848031402923 -0.0008260585279568  0.8013855166092489   T   T   T
 -0.0000423236182250  0.6666737475736750  0.8020878236418937   T   T   T
  0.6666775838073072  0.6666775838073072  0.8020953166151025   T   T   T
  0.2222087051846052  0.2222086852138423  0.1387961255725706   T   T   T
  0.1111246281574631  0.1111246381243313  0.8612037789578203   T   T   T

**Comment by sudarsan-surendralal** [comment]
@suhyunyoo Can you also send me the vasprun.xml file? I think the issue is that the ordering of atoms is different in the vasprun.xml and POSCAR files.

**Comment by suhyunyoo** [comment]
@sudarsan-surendralal You can find the vasprun.xml and the POSCAR file in the link below:
[https://www.dropbox.com/t/b00n9LezXa4xG7J7](url)

**Comment by Leimeroth** [comment]
Are there any updates? I want to import a bunch of calculations with large amorphous structures and now I am not sure if it is actually a good idea to do this or will end up in a total mess.
Did someone already start working on this or figured out when exactly this is happening to give me a hint how to fix it?

**Comment by sudarsan-surendralal** [comment]
I'm working on this currently. To me, it looks like the sorting of the positions goes wrong somehow in this case. I'll update once I have the complete picture soon!

**Comment by sudarsan-surendralal** [comment]
@suhyunyoo I tried importing everything and it works perfectly well for me. Can you verify that you're not on a very old version of pyiron? You can do so by:
```
import pyiron
print(pyiron.__file__)
```
Can you verify that you're on the latest branch on the cluster?  Once you are, can you please re-import the jobs?

**Comment by suhyunyoo** [comment]
@sudarsan-surendralal 
I think my pyiron version is not up-to-date
`import pyiron
print(pyiron.__file__)`
Gives me that

> /cmmc/u/suhyun/prgm/pyiron/pyiron/__init__.py

In this case, how can I update it to the latest branch or use the one on the cluster?

**Comment by sudarsan-surendralal** [comment]
Go to your `.bashrc` file and uncomment the line where you overwrite `$PYTHONPATH` with your local folder. THen restart your Jupyter server (go to control panel and do this). After this re-import your jobs!

**Comment by suhyunyoo** [comment]
With the latest branch, the structure is correctly imported.
It seems the problem of the old pyiron version.
Thanks for your help!
I'll close it now

**Comment by sudarsan-surendralal** [comment]
Ok great! @Leimeroth you can confidently import your jobs now! :)
