### ISSUE TITLE
Appending an atom to structure

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#1131]
I am creating a  set of structures to descibe the decossion zone in the presence of hydrogen as shown in the following function:

```python
def create_decohesion(struct, d=0, n_H=0):
    struct_new = struct.copy()
    struct_new.cell[0][0] += d
    a = struct_new.cell[0][0]
    b = struct_new.cell[1][1]
    c = struct_new.cell[2][2]
    for i in range(len(struct.positions)):
        if (struct_new.positions[i][0] > a/2.):
            struct_new.positions[i][0] = struct_new.positions[i][0] + d
    for i in range(n_H):
        struct_new.append('H')
        struct_new.positions[-1]=[np.random.uniform(a/2.,a/2.+d),np.random.uniform(0,b),
                                  np.random.uniform(0,c)]
    return struct_new
```
Then, I define lists for hydrogen concentraions and different decohession zone sizes and run simple lammps jobs as follows,

```python
d_list = np.arange(-1,5,1)
H_list = np.arange(50,101,50)
energy_mat = np.zeros((H_list.size, d_list.size))

for i, c in enumerate(H_list):
    for j, d in enumerate(d_list):
        name_tail = "d_{}_".format(np.round(d,3)).replace('.','c').replace('-','m')+"H_{}".format(c)
        job_sc_d = pr.create_job(pr.job_type.Lammps, "decohesion_" + name_tail, True)
        job_sc_d.potential = 'Al_lammps_eam' 
        job_sc_d.structure = create_decohesion(basis_sc,d,c)
        job_sc_d.calc_static()
        job_sc_d.run()
        energy_mat[i][j] = job_sc_d['output/generic/energy_tot'][-1]
```
But, I get this error, 
```python
KeyError: <pyiron.atomistics.structure.periodic_table.ChemicalElement object at 0x2ba321c99b50>
```
After many trials, I am quite sure that this error arises becuase I am using the function `structure.append(Atom)`. Is there any solution to this problem?

**Comment by samwaseda** [comment]
That's because you cannot append a string to a structure.

**Comment by ibrsam** [comment]
I used this code, 
```python
from pyiron.atomistics.structure.atom import Atom
d = 2
n_H = 10
struct_new = basis_sc.copy()
struct_new.cell[0][0] += d
a = struct_new.cell[0][0]
b = struct_new.cell[1][1]
c = struct_new.cell[2][2]
for i in range(len(struct_new.positions)):
    if (struct_new.positions[i][0] > a/2.):
        struct_new.positions[i][0] +=  d
for i in range(n_H):
    positions = np.array([np.random.uniform(a/2.,a/2.+d),np.random.uniform(0,b),np.random.uniform(0,c)])
    atom = Atom(element='H', position=positions)
    struct_new.append(atom)
```
But, I still get this `UserWarning`,
```python
/cmmc/u/ibrsam/programs/pyiron/pyiron/atomistics/structure/atoms.py:2626: UserWarning: You are adding structures with different cell shapes. Taking the cell and pbc of the first structure:Cell([[42.18195398137459, -7.57945289248969e-32, -7.57945289248969e-32], [0.0, 8.036390796274919, -1.515890578497938e-32], [0.0, 0.0, 8.036390796274919]])
  "Taking the cell and pbc of the first structure:{}".format(self.cell))
```

**Comment by samwaseda** [comment]
Did it work or it didn't?

**Comment by ibrsam** [comment]
No, 
```python
KeyError: <pyiron.atomistics.structure.periodic_table.ChemicalElement object at 0x2ba3234504d0>
```

**Comment by samwaseda** [comment]
That's weird, because the following lines work perfectly fine for me:

```
from pyiron.atomistics.structure.atom import Atom
basis = pr.create_structure('Al', 'fcc', 4).repeat(5)
random_position = np.diagonal(basis.cell)*np.random.random(3)
basis.append(Atom(element='H', position=random_position))
```

**Comment by ibrsam** [comment]
Not working for the same error.

**Comment by samwaseda** [comment]
Do you have your own branch on GitHub?

**Comment by ibrsam** [comment]
No

**Comment by samwaseda** [comment]
> 
> But, I still get this `UserWarning`,
> 
> ```python
> /cmmc/u/ibrsam/programs/pyiron/pyiron/atomistics/structure/atoms.py:2626: UserWarning: You are adding structures with different cell shapes. Taking the cell and pbc of the first structure:Cell([[42.18195398137459, -7.57945289248969e-32, -7.57945289248969e-32], [0.0, 8.036390796274919, -1.515890578497938e-32], [0.0, 0.0, 8.036390796274919]])
>   "Taking the cell and pbc of the first structure:{}".format(self.cell))
> ```

But here you said you were getting a warning. Did you want to say you not only got a warning but also an error at the same time?

**Comment by ibrsam** [comment]
I create the structure, then I visualize it to make sure it delivers what I want. In this case, I get a warning. When I run the job, I get the key error.

**Comment by samwaseda** [comment]
Because your potential doesn't support hydrogen.

**Comment by samwaseda** [comment]
> I create the structure, then I visualize it to make sure it delivers what I want. In this case, I get a warning. When I run the job, I get the key error.

Look, your original error was because of `append`, and now you are talking about a different error and apparently you knew it. It would have been helpful if you had stated this earlier and not just *Not working for the same error*, which was also not true.

**Comment by ibrsam** [comment]
Yes, I see thanks!

**Comment by samwaseda** [comment]
And we'd love to see some effort to make an issue easier to understand from the beginning. You pasted your code (which is good), but you could have also created a shorter code to more easily pinpoint the error. In your case, it would have been enough to have something like:

```
basis = pr.create_structure('Al', 'fcc', 4)
basis.append('H')
```

to reproduce your error, which would spare everyone the time to read and understand a long code.

**Comment by ibrsam** [comment]
Yes, that is better. I will do this.
