### ISSUE TITLE
KeyError difficult to understand when potential doesn't support chemical elements present

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1132]
In [a recent issue](https://github.com/pyiron/pyiron/issues/1131), I realized that it's difficult to understand where the problem comes from when we use a potential in LAMMPS, which doesn't support the chemical composition in the system. Here's namely what I got in an Al-H system where I used an Al-potential:

```
~/dev_sam/pyiron/pyiron/lammps/structure.py in structure_atomic(self)
    627         el_lst = self._structure.get_chemical_elements()
    628         for id_atom, (el, coord) in enumerate(zip(el_lst, coords)):
--> 629             id_el = el_dict[el]
    630             dim = self._structure.dimension
    631             c = np.zeros(3)

KeyError: <pyiron.atomistics.structure.periodic_table.ChemicalElement object at 0x2b6c19230550>
```

It would be nice to have a message like `ValueError: selected potential does not support the existing chemical composition`.

**Comment by samwaseda** [comment]
Low priority but I don't know whether it's an easy fix for beginners.

**Comment by ibrsam** [comment]
Yes, that is a very tricky error, as it states `pyiron.atomistics.structure`, so one can think about the structure rather than the potential.
