### ISSUE TITLE
When the clouds come down  - Travis CI disabled 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1138]
As some of you might have noticed we lost the travis continuous integration and therefore the testing of the jupyter notebooks and the test builds for the documentation. 

**The background:** 

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Unfortunately in the current configuration when each commit uses 50 minutes to build the jupyter notebooks, 5 minutes for the python 3.7 and python 3.8 tests and double the amount once the pull request is open. As a result 120 minutes CI time per commit means 1000 minutes in Credits gives us room for less than 10 commits per month. 

As usual the situation could not be worse with one workshop running currently and another just coming up. Other projects like https://conda-forge.org are switching to Azure so we should also extend the tests on Azure, in addition we should make sure we decrease the time the notebooks in our repositories can be executed faster. Here are the run time statistics: 

- Input Notebook:  notebooks/bandstructure.ipynb [00:39<00:00,  1.43cell/s]
- Input Notebook:  notebooks/data_mining.ipynb [00:57<00:00,  2.63s/cell]
- **Input Notebook:  notebooks/energy_volume_curve.ipynb [10:53<00:00, 10.37s/cell]**
- Input Notebook:  notebooks/first_steps.ipynb  [01:35<00:00,  1.71s/cell]
- Input Notebook:  notebooks/gamma_surface_parallel_master.ipynb [00:47<00:00,  3.36s/cell]
- Input Notebook:  notebooks/lammps-fe-c-example.ipynb [00:04<00:00,  4.28cell/s]
- **Input Notebook:  notebooks/phonopy_example.ipynb [11:30<00:00, 11.90s/cell]**
- Input Notebook:  notebooks/pipeline.ipynb [00:52<00:00,  4.80s/cell]
- Input Notebook:  notebooks/sqs.ipynb [00:06<00:00,  1.49cell/s]
- Input Notebook:  notebooks/structures.ipynb [00:14<00:00,  5.05cell/s]
- Input Notebook:  notebooks/test_pyiron_installation.ipynb [00:37<00:00,  1.35s/cell]
- **Input Notebook:  notebooks/tests_sphinx_sphinx_check_all.ipynb  [04:08<00:00,  7.52s/cell]**
- Input Notebook:  notebooks/Thermodynamics_QHA.ipynb [00:18<00:00,  1.13cell/s]
- Input Notebook:  notebooks/water_MD.ipynb  [00:26<00:00,  1.34cell/s]

**Comment by samwaseda** [comment]
There's no way to run them on our own cluster? Switching to Azure doesn't sound to me like a solution to the fundamental problem (that we're running jobs on platforms which have no interest to allow us to do so).

By the way I found your title above super poetic XD

**Comment by jan-janssen** [comment]
There is a similar service in Garching, but that is currently limited to Gitlab and only provides Linux based testing. 

So insteadI first migrated to Azure from Microsoft and now even further to use just the Microsoft Github service. The advantage of this is that we have just a single service for continuous integration now, rather than three Travis CI, AppVeyor and Azure before. So now my hope is that we survive with this solution, still we should make sure that we decrease the CPU time we use for our testing.

**Comment by jan-janssen** [comment]
I migrated all our codes to the GIthub continuous integration: 
- https://github.com/pyiron/pyiron/pull/1139 
- https://github.com/pyiron/pyiron_contrib/pull/30
- https://github.com/pyiron/pyiron_base/pull/68
- https://github.com/pyiron/pysqa/pull/43
- https://github.com/pyiron/pyfileindex/pull/16
- https://github.com/pyiron/pylammpsmpi/pull/49

Still we should make sure to reduce the CPU time required to execute the example notebooks.
