### ISSUE TITLE
Misleading Error Message when setting Non-existing Lammps Potential

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#1144]
When you set a potential name that doesn't exist (e.g. a typo), the error that gets thrown is related to some IndexError because a non-existing potential has an empty list of elements it supports.  Since this is user-facing, I'd think there should be a nice "you set an invalid potential" error.  

I'll look into it after ADIS.

**Comment by liamhuber** [comment]
Good call. Probably a one-liner fix in the exception test anyhow :)
