### ISSUE TITLE
Weird behaviour of interactive job without interactive_enforce_structure_reset

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1145]
For the following lines:

```
lmp = pr.create_job('Lammps', 'lmp')
structure = pr.create_ase_bulk('Al', cubic=True).repeat([2, 2, 6])
lmp.potential = 'Al_lammps_eam'
lmp.interactive_open()
for strain in np.linspace(-0.1, 0.1, 11):
    lmp.structure = structure.apply_strain([0, 0, strain], return_box=True)
    lmp.interactive_enforce_structure_reset = True
    lmp.run()
lmp.interactive_close()
```

I get this very nice curve:

<img width="397" alt="Unknown" src="https://user-images.githubusercontent.com/37879103/98092757-54f9b000-1e87-11eb-9e19-fe8003b0995e.png">

But when `interactive_enforce_structure_reset` is not set, I get the following figure:

<img width="397" alt="Unknown" src="https://user-images.githubusercontent.com/37879103/98093007-aa35c180-1e87-11eb-87a8-3babf3182552.png">

Another weird thing is, when the `repeat` is not called, it works also fine again. I'm going to look into it myself after the ADIS workshop myself but if you can, that would be also great.

**Comment by jan-janssen** [comment]
Looks like a DFT curve - so I am not sure if it is a bug or a feature - just joking.
