### ISSUE TITLE
PhonopyJob taking unusually long to run on the queue

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron#1147]
I noticed today that `PhonopyJob`s are taking far too long to run on the queue. Here is my input code:

```
# setup phonopy job

pr_phon = pr.create_group('phonons')
phon_ref_job = pr_phon.create_job(pr.job_type.Lammps, 'phon_ref')
phon_ref_job.structure = pr.create_ase_bulk(name='Al', cubic=True).repeat(4)
phon_ref_job.potential = '2008--Mendelev-M-I--Al--LAMMPS--ipr1'

phonopy_job = phon_ref_job.create_job(pr.job_type.PhonopyJob, 'phonopy_job')
phonopy_job.server.cores = 4
phonopy_job.server.queue = 'cmti'
phonopy_job.server.run_time = 3600

phonopy_job.run()
```

In my case, it ran into the wall time limit. The above snippet normally took around 6-8 minutes to run on 4 cores.

Edit: I must add that it works fine on my local system, and on the head node.

**Comment by samwaseda** [comment]
Is there a particular reason to submit phonopy? I rather submitted LAMMPS and it worked well, i.e.

```
phon_ref_job = pr_phon.create_job('Lammps', 'phon_ref')
phon_ref_job.structure = pr_phon.create_ase_bulk(name='Al', cubic=True).repeat(4)
phon_ref_job.potential = '2008--Mendelev-M-I--Al--LAMMPS--ipr1'
phon_ref_job.server.cores = 4
phon_ref_job.server.queue = 'cmti'
phon_ref_job.server.run_time = 3600

phonopy_job = phon_ref_job.create_job('PhonopyJob', 'phonopy_job')

phonopy_job.run()
```

**Comment by raynol-dsouza** [comment]
Nice! It works this way. But it also worked when I submitted the job using the code in my first comment. 

Isn't the code in the first comment also used to submit other jobs that need a reference job? Personally, I'd prefer if it worked both ways (that way, I don't have to modify all my other notebooks that use Phonopy :P)

**Comment by samwaseda** [comment]
Hmmm, actually I just checked and your first version worked as well for me. Or is that what you are saying with *But it also worked when I submitted the job using the code in my first comment.*?

**Comment by raynol-dsouza** [comment]
Yes. The snippet in my first comment worked for me up until yesterday morning. It suddenly stopped working after that.

I have restarted my cluster server and I'm trying again...

**Comment by samwaseda** [comment]
ok since it worked for me now and I don't think there was an important change related to this, I don't think there's a systematic problem that we have to solve here.

**Comment by raynol-dsouza** [comment]
I agree. Unfortunately, it still doesn't work for me. But your method of submitting it to the queue works, and I will stick to it for the time being. Shall I close this issue for now?

**Comment by samwaseda** [comment]
As you like. From my side there's very little I can do.
