### ISSUE TITLE
VASP RPA calculation

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#1148]
When preparing for an RPA calculation, using NELM=1, the following line will always result in a not_converged status:

https://github.com/pyiron/pyiron/blob/c17d4f3628f2ad5c3d5f8485d367e835c8361ebb/pyiron/vasp/base.py#L425

I noticed this when trying to make a FlexibleMaster job which executes a series of VASP calculations, which halts when encountering this not_converged job. Is there some way to circumvent this?

**Comment by sudarsan-surendralal** [comment]
I guess this is a special case where you just need the eigenvalues from one electronic step without the need for self-consistency? Then I guess it's best to modify the `convergence_check()` function and add an exception for the special algorithm tags in the incar file where it returns `True` always.  Something like:

```
if self.input.incar["ALGO"] == "EIGENVAL" and self.input.incar["NELM"] == 1:
    return True
```
As far as I know, the pyiron developers have not done RPA calculations in VASP. So could you modify this and see if it works? We can then merge it through a pull request.

**Comment by SanderBorgmans** [comment]
@sudarsan-surendralal Thanks for the reply. I'll implement this, test it, and make a pull request.
