### ISSUE TITLE
SQS job fails 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1156]
Example: 
```
structure_lattice = pr.create_ase_bulk(name="Al", cubic=True)
structure_lattice.set_repeat(3)
job_sqs = pr.create_job(job_type=pr.job_type.SQSJob, job_name="sqs")
job_sqs.structure = structure_lattice
job_sqs.input
job_sqs.input.iterations = 1000
job_sqs.input.mole_fractions = {"Al": 0.5, "Ni": 0.5}
job_sqs.run()
job_sqs_reload = pr.load(job_sqs.job_name)
job_sqs_reload.run(delete_existing_job=True)
```

Error 
```
TypeError: Argument 'mole_fractions' has incorrect type (expected dict, got InputList)
```

**Comment by jan-janssen** [comment]
@pmrv Is there a simple way to convert input lists back to dictionaries?

**Comment by liamhuber** [comment]
> @pmrv Is there a simple way to convert input lists back to dictionaries?

This is a generic problem that InputList wraps some complex data types (at least dict and list) as InputLists and then at load time doesn't know whether they were *originally* InputLists and should be left that way or should be converted back.

I guess I've complained to @pmrv about this before ;)  I thought there was an issue for this already, but can't find it atm.

Definitely this is something that should be fixed directly in InputList so they load properly and not patched over here or in `.run`. I'm not sure from your wording if that was your intent, but in case it was I wanted to throw a warning.

**Comment by niklassiemer** [comment]
InputLists have a method to_buildin() which converty them to a dict or list, depending if it has keys or not
