### ISSUE TITLE
color scale for periodic_plot

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#1166]
I from Mendeleev I use peridic_plot as below: 
-from mendeleev import get_table
-from mendeleev.plotting import periodic_plot
I get a nice periodic table and fill it out with my calculation result. And as a representative, I wanted to know if we have any future in pyiron to color scale it or do it myself?  
<img width="555" alt="Screenshot 2020-11-10 at 11 19 12" src="https://user-images.githubusercontent.com/62750893/98645047-a225c800-2346-11eb-9026-b374102bf5b2.png">

**Comment by samwaseda** [comment]
I have no specific suggestion, but I absolutely love the figure you shared and if you want to raise this point at the next pyiron meeting, I'd be certainly interested in the discussion.

**Comment by liamhuber** [comment]
I want to echo Sam's assessment that this plot is totally rad.

I'm not sure I understand the question itself though -- isn't this just a matter of changing the `cmap='viridis'` flag to something else? More generally, I don't anticipate that we'll have some pyironic 'colour scale' we expect to use, i.e. `cmap=pr.colorscale` is not something to expect. (With `pr` here being our canonical instance of the `Project` class.)

**Comment by jan-janssen** [comment]
I close this question. Currently we do not have an integrated tool inside pyiron to plot periodic tables - the only way to plot the periodic table is using `mendeleev` as you do it already.
