### ISSUE TITLE
Structure checmial formula stored in database for sqs jobs

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1168]
**Summary**

sqs jobs store the chemical formula of the structure initally given in the job table. Imo it would make more sense to store the chemical formula of the final sqs structures.

**Steps to Reproduce**

create a sqsjob and run it, then look at Project.job_table()

**Comment by jan-janssen** [comment]
I agree - this can be achieved by implementing a custom function for the database entry https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/job/atomistic.py#L385 do you want to give it a try? Basically taking the input mole fraction to update the chemical formula in the database.

**Comment by Leimeroth** [comment]
Ok
