### ISSUE TITLE
Error in get_broyden_mixing()

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#117]
So, I had a calculation which ran successfully but the parsing failed because the OUTCAR parser could not get the broyden mixing mesh

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-340-2919e271a3c5> in <module>()
----> 1 oc.get_broyden_mixing_mesh(ham_repair.working_directory+"/OUTCAR")

/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/outcar.py in get_broyden_mixing_mesh(filename)
    562             for line in f.readlines():
    563                 if trigger in line:
--> 564                     return int(line.split()[4])
    565 
    566     @staticmethod

ValueError: invalid literal for int() with base 10: '******'
```
I checked the line and of course it gives out garbage although the calculation is fine
```

Broyden mixing: mesh for mixing (old mesh)
   NGX =123   NGY =103   NGZ = 81
  (NGX  =500   NGY  =420   NGZ  =320)
  gives a total of ****** points

```
Currently we try to parse the line `gives a total of ****** points`. But I realized from other calculations that this is the same as `NGX*NGY*NGZ` where `NGX =123   NGY =103   NGZ = 81`. Is this always the case? Then I can simply parse this line instead.

@jan-janssen I think you need this for your analysis right? Can you comment on this? Have you ever encountered this error?

**Comment by jan-janssen** [comment]
Maybe you can check if it is  '******' and then return 0 ? That should fix the issue. Or maybe even return None that would be more correct.
