### ISSUE TITLE
Lammps **langevin** MD -- interactive differs from regular

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron#1173]
**Summary**

If you set up a Lammps MD job, you get different physics depending whether or not you run the job interactively when using the Langevin thermostat.

Since it still works OK with the Nose-Hoover thermostat I think this is low-priority, but we should at least get a warning/error added when `langevin=True` pretty quickly.

**Steps to Reproduce**

```python
from pyiron import Project
import matplotlib.pyplot as plt

pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)

regular = pr.create_job(pr.job_type.Lammps, 'regular')
regular.structure = pr.create_ase_bulk('Al', cubic=True).repeat(3)
regular.potential = job.list_potentials()[0]
regular.calc_md(temperature=300, n_ionic_steps=1000, n_print=1, langevin=True)

interactive = regular.copy_to(new_job_name='interactive', new_database_entry=False)

regular.run()

interactive.interactive_open()
interactive.run()
interactive.interactive_close()

plt.plot(regular.output.temperature, label='regular')
plt.plot(interactive.output.temperature, label='interactive', linestyle='-.')
plt.legend()
plt.xlabel('Frame')
plt.ylabel('Temerpature [K]')

equil_frames = 100
print(
    regular.output.temperature[equil_frames:].mean(), 
    interactive.output.temperature[equil_frames:].mean()
)
```

**Expected Behavior**

The same statisical behaviour for both run styles.

**Actual Behavior**

Interactive lammps gives half the temperature that the regular job does. 

Note that as you increase `n_print`, the two results begin to converge. I guess this has to do with the fact that we really set the lammps number of steps to the print value [here](https://github.com/pyiron/pyiron/blob/7e48f661656b894b04a792e2c9be64ad0be220bb/pyiron/lammps/interactive.py#L314), so the lammps library is somehow starting a new calculation at each frame or something? 

I find the *exact* behaviour hard to understand, but the fact that they differ is really unsurprising given how `LammpsInteractive.run_if_interactive` reads. What is really blowing my mind right now is that with the Nose-Hoover thermostat it works fine, it's just Langevin that kills it.

**Further Information, Files, and Links**

With `langevin=True`:
![langevin](https://user-images.githubusercontent.com/20283329/98928017-8bfc4100-24d9-11eb-808c-39df3cffc030.png)

With `langevin=False`:
![nose_hoover](https://user-images.githubusercontent.com/20283329/98928039-91598b80-24d9-11eb-9189-eaf50edd4830.png)

I also looked at the input.control tables, and didn't see anything that stuck out to me. Something a little weird is that both styles use the same random seed, but with the langevin thermostat you anyhow get big divergence. This isn't a huge deal though, and might be a side effect of whatever is the main problem, so let's leave it for now.

**Comment by samwaseda** [comment]
I just looked into it and I have to admit I couldn't come farther than what you have already mentioned. I also looked into [`fix langevin` in LAMMPS](https://github.com/lammps/lammps/blob/master/src/fix_langevin.cpp), but I cannot really see which line could be causing the problem either.

> so the lammps library is somehow starting a new calculation at each frame or something?

I agree that this is most likely the point. But on the other hand it's also weird that it does not even follow the equipartition theorem, i.e. the initial kinetic energy should be at least equally distributed between the potential energy and the kinetic energy if Langevin is not doing anything. As a matter of fact, when you change `temperature_damping_timescale` to something very small, the system decisively converges towards a lower temperature, apparently 200 K in this case. So Langevin is somehow actively lowering the temperature, instead of doing nothing.

To be honest, I have the feeling that this is something we should report to the LAMMPS community, rather than issuing a warning or raising an error in pyiron, which I fear would give the impression that the user is doing something wrong.

**Comment by jan-janssen** [comment]
Can you check if the end points agree if you set `n_print=1000` ?

**Comment by liamhuber** [comment]
They won't. Nose-Hoover seems to use the same seed and differs only by a bit of numerical noise. With Langevin the input.control uses the same random seed in both run modes (for both random velocity generation and langevin command), but really clearly diverges quickly. If, indeed, the interactive run is doing some sort of restart then I guess it's using the same random seed again and again -- AND AHA! 

Thank you for asking this question, @jan-janssen! @samwaseda, that's probably it! Probably we're getting the *same* "random" kick at each step when we run the Langevin thermostat with `n_print=1`. In Nose-Hoover the random seed is applied only before we start running (to generate velocities), but with Langevin the seed appears in a command that's getting called again and again (the ensemble command?). It's a little weird to me that giving the same kick always drives us to T/2, but maybe it will make more sense once I digest it a bit more. Probably it's something to do with the drag still sucking energy out, but the kick adding less and less as it eventually never pushes people downhill?

Anyhow, to get back to your question, if you keep increasing `n_print`, you get different actual values, but the statistics (e.g. potential energy mean and std) converge between interactive and regular runs. For me this was sufficient, but as discussed in the last paragraph this was actually a super important clue. 🔍 

How to fix it is still not clear to me, but I am increasingly confident we know what's wrong.

**Comment by liamhuber** [comment]
> As a matter of fact, when you change `temperature_damping_timescale` to something very small, the system decisively converges towards a lower temperature, apparently 200 K in this case. So Langevin is somehow actively lowering the temperature, instead of doing nothing.

Low timescale = strong thermostat. It's only converging to 200K for the interactive job, right? If a very strong thermostat is converging to 200K in the traditional run, then there is something wrong with Lammps' numeric integrator for this ensemble/thermostat.

> To be honest, I have the feeling that this is something we should report to the LAMMPS community, rather than issuing a warning or raising an error in pyiron, which I fear would give the impression that the user is doing something wrong.

How the Lammps python bindings are used in the broader community is not clear to me. If other people are re-executing single Langevin N(P/V)T ensembles this way, then this may indeed be a bug they should be alerted to. On the other hand it might be an issue of how pyiron is talking to the lammps bindings. My expertise is too small here.

**Comment by samwaseda** [comment]
> Thank you for asking this question, @jan-janssen! @samwaseda, that's probably it! Probably we're getting the _same_ "random" kick at each step when we run the Langevin thermostat with `n_print=1`. In Nose-Hoover the random seed is applied only before we start running (to generate velocities), but with Langevin the seed appears in a command that's getting called again and again (the ensemble command?). It's a little weird to me that giving the same kick always drives us to T/2, but maybe it will make more sense once I digest it a bit more. Probably it's something to do with the drag still sucking energy out, but the kick adding less and less as it eventually never pushes people downhill?

I just checked `np.linalg.norm(np.mean(job.output.forces, axis=0))` (which essentially is the total magnitude of "mean forces over all steps" for all atoms) and in the case of interactive it doesn't disappear, meaning Langevin is indeedgiving always the same forces.

**Comment by samwaseda** [comment]
From the practical point of view, probably the most important reason to do `n_print=1` is to get better average values. For this, there is already `job.input.control.measure_mean_value` which is much more efficient. Maybe we should make this one more visible to common users, because when I implemented it it was just a quick fix for me, but I can see that it could be useful to many people.

**Comment by liamhuber** [comment]
> From the practical point of view, probably the most important reason to do `n_print=1` is to get better average values. For this, there is already `job.input.control.measure_mean_value` which is much more efficient. Maybe we should make this one more visible to common users, because when I implemented it it was just a quick fix for me, but I can see that it could be useful to many people.

I was also not aware of `measure_mean_value`, so increasing its visibility might be good!

I do have to disagree though, I think `n_print=1` does not help get better statistics; My understanding is that the snapshots need to be far enough apart to decorrelated to contribute meaningfully to calculating the average property.

The application I have in mind was rather to use interactive mode to cut in and manipulate an MD calculation. In this case I have a slab with some dislocations in it, use selective dynamics to freeze the surfaces of the slab in the `calc_md`, then break in at every step to manually shear those frozen atoms a little bit and watch for the dislocations to start moving. 
  We do things like this fine in protocols, but there we have our own Verlet integrator and just use `calc_static` in the interactive jobs, so I never ran into this problem until now.

**Comment by liamhuber** [comment]
> I just checked `np.linalg.norm(np.mean(job.output.forces, axis=0))` (which essentially is the total magnitude of "mean forces over all steps" for all atoms) and in the case of interactive it doesn't disappear, meaning Langevin is indeedgiving always the same forces.

Clever check! At least now we understand exactly what the problem is 😃

**Comment by samwaseda** [comment]
> The application I have in mind was rather to use interactive mode to cut in and manipulate an MD calculation. In this case I have a slab with some dislocations in it, use selective dynamics to freeze the surfaces of the slab in the `calc_md`, then break in at every step to manually shear those frozen atoms a little bit and watch for the dislocations to start moving.

But then I'd say there'd be also a bit of a similar kind of problem since the force+velocity field won't correspond to the actual positions, so I would rather put a few steps in between to allow the system to get accustomed to the given positions. Or you can also put external forces, in which case I would use the proper python callback function in LAMMPS (which is what I use for metadynamics etc.)

**Comment by liamhuber** [comment]
> But then I'd say there'd be also a bit of a similar kind of problem since the force+velocity field won't correspond to the actual positions, so I would rather put a few steps in between to allow the system to get accustomed to the given positions.

I don't exactly see what you're getting at here. In my case I don't care if the temperature is exactly right, I just want it to be pretty close -- it's a primitive way to set up a strain test to begin with. As long as the strain rate is not too high, I don't think it should mess with the thermodynamics too badly. 

> Or you can also put external forces, in which case I would use the proper python callback function in LAMMPS (which is what I use for metadynamics etc.)

I think I will stick with displacement controlled, but I am curious about this callback! Where is this? I don't see it in `control.LammpsControl`, and when I look for usages of "metadyn" in pyiron and pyiron_mpie all I find is the Vasp metadynamics.

**Comment by samwaseda** [comment]
> I don't exactly see what you're getting at here. In my case I don't care if the temperature is exactly right, I just want it to be pretty close -- it's a primitive way to set up a strain test to begin with. As long as the strain rate is not too high, I don't think it should mess with the thermodynamics too badly.

Oh sorry I just realized that you move only the slabs and not the dislocation itself (which makes sense). But if you are anyway using the LAMMPS integration, I would rather make LAMMPS displace the atoms as well, so that LAMMPS can do everything internally.

> I think I will stick with displacement controlled, but I am curious about this callback! Where is this? I don't see it in `control.LammpsControl`, and when I look for usages of "metadyn" in pyiron and pyiron_mpie all I find is the Vasp metadynamics.

yeah this callback is not something I made public. It's briefly explained [here](https://lammps.sandia.gov/doc/fix_external.html). I might present it at some point :D

**Comment by liamhuber** [comment]
> But if you are anyway using the LAMMPS integration, I would rather make LAMMPS displace the atoms as well, so that LAMMPS can do everything internally.

@samwaseda I feel like this betrays the promise of interactive jobs though 😿 Also, I would still classify the existing behaviour as a bug even if it's not how I'm "supposed" to do it. 

What I don't like about doing it in Lammps is then we're just writing special new parsers to the Lammps interface and the Lammps jobs further diverge from other job types. It's true that interactive jobs are currently slower, but I really like the idea that I can go to the head of my notebook, replace `job_type.Lammps` with `job_type.Vasp` (or any other code that has an interactive mode), and `potential` with some kpoint and energy cutoff settings, and the whole thing still does the same physics.

**Comment by samwaseda** [comment]
> @samwaseda I feel like this betrays the promise of interactive jobs though 😿 Also, I would still classify the existing behaviour as a bug even if it's not how I'm "supposed" to do it.

Well in my opinion the question is either you do everything interactively, or nothing. LAMMPS integration + external slab displacement is somewhere in between, that's not quite what we should be doing anyway.

> 
> What I don't like about doing it in Lammps is then we're just writing special new parsers to the Lammps interface and the Lammps jobs further diverge from other job types. It's true that interactive jobs are currently slower, but I really like the idea that I can go to the head of my notebook, replace `job_type.Lammps` with `job_type.Vasp` (or any other code that has an interactive mode), and `potential` with some kpoint and energy cutoff settings, and the whole thing still does the same physics.

The simple fact is that LAMMPS has an internal algorithm which knows how to update the neighbor lists, which we (most certainly - I'm not 100% sure) have to destroy if we displace the atoms ourselves. And the very reason that we use LAMMPS is because it's faster, which is also quite critical in your example because you want to keep the strain rate as low as possible. So I'd claim unfortunately there's no way around it.

**Comment by liamhuber** [comment]
> Well in my opinion the question is either you do everything interactively, or nothing. LAMMPS integration + external slab displacement is somewhere in between, that's not quite what we should be doing anyway.

That's a good perspective, I hadn't thought of it that way. I had thought that `calc_static`, `calc_md`, and `calc_minimize` are all "things you do" in interactive mode. You're right that there's no rule that this is the case!

I still do get a little uncomfortable that the job types diverge so much. I think I just need to accept this though 😉 

> The simple fact is that LAMMPS has an internal algorithm which knows how to update the neighbor lists, which we (most certainly - I'm not 100% sure) have to destroy if we displace the atoms ourselves. And the very reason that we use LAMMPS is because it's faster, which is also quite critical in your example because you want to keep the strain rate as low as possible. So I'd claim unfortunately there's no way around it.

You're 100% right, except about the criticality to my particular issue. I'm doing quasistatic (no real strain rate), and it's just for teaching with a toy example. So actually I'm not so concerned about speed ;) I mean, it might be nice if things ran in 20s instead of 5m, but 5m isn't killing me. But in general you are of course right that a native Lammps implementation is faster.

At the end of the day, the current behaviour is still a bug 😛

**Comment by samwaseda** [comment]
I see that I'm still assigned, but do you still think we're gonna do something about it?

**Comment by liamhuber** [comment]
> but do you still think we're gonna do something about it?

It is a legitimate bug: the physics of Lammps in interactive mode fails silently for one of our two thermostats by depending on `n_print`. I don't feel it's appropriate to just leave that there indefinitely. At a minimum this control setting needs to raise an error.

> I see that I'm still assigned, 

This is a good point. I somehow thought that you were the maintainer of `lammps.interactive` and/or `lammps.control`, but these are @jan-janssen and @sudarsan-surendralal.

I do not understand how to fix this. If no one understands/is willing to fix it, I will force it to throw an error and close the issue, but this is obviously not my favourite solution.

**Comment by samwaseda** [comment]
`fix langevin` and then `unfix langevin` at each step with different random numbers? Frankly, I would claim it's always wrong since whether it's every step or every 100 steps, you get anyway a periodic random force field, which is anyway not right. From my point of view, the only one way to solve this problem is to force LAMMPS to accept a new seed.

**Comment by jan-janssen** [comment]
Maybe this is my fault, I use the interactive MD mode for approximating the melting point. I run 100000 steps in LAMMPS look at the final structure, check if it is solid or liquid and then increase the temperature. I do not care about the 100000 steps in between. The reason why it fails is basically the `n_print=1` because it always resets the MD calculation after every step. The original interactive mode was only designed for run static requiring the user to implement everything else with interactive wrappers. So I am fine with adding a warning that calc_md is an experimental feature and should be used with special care, still I have calculation which use this feature so I am reluctant to remove it.

**Comment by samwaseda** [comment]
> Maybe this is my fault, I use the interactive MD mode for approximating the melting point. I run 100000 steps in LAMMPS look at the final structure, check if it is solid or liquid and then increase the temperature. I do not care about the 100000 steps in between. The reason why it fails is basically the `n_print=1` because it always resets the MD calculation after every step. The original interactive mode was only designed for run static requiring the user to implement everything else with interactive wrappers. So I am fine with adding a warning that calc_md is an experimental feature and should be used with special care, still I have calculation which use this feature so I am reluctant to remove it.

+1 for issuing a warning (rather than throwing an error), because it's not up to pyiron to decide whether `n_print=1` is wrong or `n_print=100`.

**Comment by liamhuber** [comment]
> +1 for issuing a warning (rather than throwing an error), because it's not up to pyiron to decide whether `n_print=1` is wrong or `n_print=100`.

Ok a warning it is.

But to re-emphasize, there is no deciding to be done in the example you gave -- `n_print=1` (with Langevin thermostat) is unambiguously wrong. Terribly wrong. This-parrot-is-dead-wrong. 

As we increase `n_print` it gets *less* wrong, and I see the merit in maintaining the feature without a full crash -- for Jan's case where `n_ionic_steps` >> `thermostat_timescale` the wrongness is no longer significant -- and we could actually use this as a metric for pyiron to give a better hint -- but for now I would rather just throw a flat warning that this is basically an experts-only thing to play with.

I want to leave the issue open until the warning there, but I should have time to get to it myself in the next week or two, so even in the worst case this issue won't be clogging the board forever ;)

**Comment by liamhuber** [comment]
Ok, in #1228 I just throw a warning as discussed. As soon as that's merged I'll add "unresolved" here and close.

**Comment by liamhuber** [comment]
As of #1228 this is still broken, but not silently 😉
