### ISSUE TITLE
VASP NEB calculation

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1176]
Is there some way to set up a VASP NEB calculation with pyiron? The documentation says it should be possible using flexible job, but I am a bit lost on how to do that. If someone already did this or could write me a short example that would be great.

**Comment by jan-janssen** [comment]
@liamhuber Once wrote a version based on the protocols defined in `pyiron_contrib` but I do not think we have support for the VASP build in NEB just yet. Still that would definitely be a nice addition.

**Comment by liamhuber** [comment]
Yes, there is an NEB protocol that is code agnostic (well, as long as that code has interactive mode 😝). It runs fine and you can see all the flags here, but it is not the most user friendly. Below is a minimum working example using Lammps as a reference, but you could just as easily (although slower) use Vasp.

The catch is that on the master branch I'm getting an HDF error and on @raynol-dsouza's branch (dev_raynol) I get a key error when trying to save. It will still run if you first checkout `dev_raynol`, and you can see from the plot that the correct data is tucked away in the job somewhere.
  Raynol, could you please resolve the data parsing error on your branch, and, if you have time, patch the main branch with whatever is already working from your branch such that the `to_hdf` call stops complaining?

```python
from pyiron import Project
import pyiron_contrib

structure = pr.create_ase_bulk('Al', cubic=True).repeat(3)
assert(1 in structure.get_neighbors().indices[0])  # Make sure 0 and 1 are neighbours
structure_init = structure.copy()
del structure_init[0]
structure_fin = structure.copy()
del structure_fin[1]

ref = pr.create_job(pr.job_type.Lammps, 'ref')
ref.structure = structure_init.copy()
ref.potential = ref.list_potentials()[0]
ref.save()  # Awkward necessity of protocols: references must be saved!

neb = pr.create_job(pr.job_type.ProtocolNEB, 'neb')
neb.input.ref_job_full_path = ref.path
neb.input.structure_initial = structure_init.copy()
neb.input.structure_final = structure_fin.copy()
neb.input.n_images = 10

neb.run()

neb.plot_elastic_band()
```

![neb](https://user-images.githubusercontent.com/20283329/98990524-dce85580-252a-11eb-819c-dad923516f47.png)

**Comment by raynol-dsouza** [comment]
@liamhuber @niklassiemer I can look into it. I will put this on priority.

**Comment by liamhuber** [comment]
> @liamhuber @niklassiemer I can look into it. I will put this on priority.

Thanks! I don't know how much of a headache patching the main branch will be, but patching yours to work with NEB should be super fast -- it looks like it's just trying to parse some force data that isn't there (or is there at a different address?)

**Comment by raynol-dsouza** [comment]
@Leimeroth the NEB code on my branch ('[dev_raynol](https://github.com/pyiron/pyiron_contrib/tree/dev_raynol/pyiron_contrib/protocol)') of 'pyiron_contrib' works now. I have a [demo notebook](https://github.com/pyiron/pyiron_contrib/tree/dev_raynol/pyiron_contrib/protocol/notebooks) here which may help you with understanding what inputs/outputs the NEB protocol takes. The demo notebook runs with Lammps. @liamhuber suggested that you test it with a VASP job (should be as easy as changing the 'job_type' from 'Lammps' to 'Vasp').

If you run into any issues with the NEB protocol itself, please do let me know.

**Comment by liamhuber** [comment]
@Leimeroth any update as to whether or not the NEB protocol solution works (a) with Lammps on your remote submission setup and (b) with Vasp?

**Comment by Leimeroth** [comment]
I had lots of jobs in the queue on the cluster and didn't want to mess with my pyiron installation while they were running, but they should be finished soon.

**Comment by Leimeroth** [comment]
I did some testing and get the following error when I try to run the example on remote:

/nfshome/leimeroth/git_projects/pysqa/pysqa/utils/remote.py:238: UserWarning: 
  warnings.warn(stderr.read().decode())
100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
0it [00:00, ?it/s]
/nfshome/leimeroth/git_projects/pysqa/pysqa/utils/remote.py:238: UserWarning: Traceback (most recent call last):
  File "/home/nl77pupy/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nl77pupy/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/cli/__main__.py", line 2, in <module>
    main()
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/cli/wrapper.py", line 39, in main
    submit_on_remote=args.submit
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/job/wrapper.py", line 145, in job_wrapper_function
    debug=debug
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/job/wrapper.py", line 48, in __init__
    pr = Project(path=os.path.join(working_directory, '..', '..'))
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/project/generic.py", line 145, in __init__
    self.db = FileTable(project=path)
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/generic/util.py", line 33, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/database/filetable.py", line 22, in __init__
    self.force_reset()
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/database/filetable.py", line 33, in force_reset
    df = pandas.DataFrame(self.init_table(fileindex=self._fileindex.dataframe))
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/database/filetable.py", line 47, in init_table
    job_dict = self.get_extract(path, mtime)
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/database/filetable.py", line 308, in get_extract
    'status': get_job_status_from_file(hdf5_file=path, job_name=job),
  File "/home/nl77pupy/git_projects/pyiron_base/pyiron_base/database/filetable.py", line 334, in get_job_status_from_file
    return h5io.read_hdf5(hdf5_file, job_name + '/status')
  File "/home/nl77pupy/miniconda3/lib/python3.7/site-packages/h5io/_h5io.py", line 265, in read_hdf5
    raise ValueError('no "%s" data found' % title)
ValueError: no "neb_job/status" data found

Also I noticed that the Project in which I run the script will throw errors if I try to submit other, completely unrelated jobs in it.

**Comment by raynol-dsouza** [comment]
This seems to me to be more of a pyiron_base issue than of the neb protocol itself. @jan-janssen any insights?

**Comment by jan-janssen** [comment]
@raynol-dsouza GenericJobs store the status in the HDF5 file https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/generic.py#L1161 I am not sure about the protocols.

**Comment by liamhuber** [comment]
The Protocols inherit from `GenericJob`, so I'm quite confused by this. I'm afraid I definitely won't be able to look into it this week; next week is only a maybe. 

@Leimeroth,  I'm happy to keep offering support but I'm afraid it will be pretty slow from my end, so if you feel there's a more effective way forward then I wish you the best -- I appreciate that you took the time to give this solution a try. Let us know if this still winds up being your best/only hope and we'll do our best to push it up the priority ladder. Otherwise we'll ping you if we manage to reproduce and squash the bug, and hopefully give you an additional weapon in the arsenal for the future.
