### ISSUE TITLE
VASP jobs showing "submitted" status, but aborted without starting the calculations

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1184]
All other similar jobs are running or finished. These jobs show "submitted" status, but not in the job waiting list.

The error.out is in the attachment. 

How to resubmit these jobs?

I am trying:

for jobname in df[df['status']=='submitted']['job'].values[0]:
    print(jobname)
    ham = pr.load(jobname)
    ham.status.created = True
    ham.run()

But it complains:
"2020-11-13 08:35:21,509 - pyiron_log - WARNING - Job 'h' does not exist and cannot be loaded"

Any suggestion? Thank you very much.

[error.out.gz](https://github.com/pyiron/pyiron/files/5535347/error.out.gz)

**Comment by lfzhu-phys** [comment]
I guess it's the cluster cmfe has an issue as all jobs run with cmti are ok. So, my only question is how to resubmit these jobs.

Thanks a lot.

**Comment by jan-janssen** [comment]
As discussed in the tutorial: https://pyiron.org/phasediagram-workshop-2020/Exercise1.html#modify-sqs-calculation-job 

Use: 
```
jo.run(delete_existing_job=True)
```

**Comment by lfzhu-phys** [comment]
@jan-janssen Thanks, Jan. Is that possible to do without deleting the jobs and just restart them?

**Comment by jan-janssen** [comment]
The only way to manually resubmit them would be to navigate to the folders and execute the `run_queue.sh`.

**Comment by lfzhu-phys** [comment]
@jan-janssen Thanks, Jan.

It is solved by doing:

for jobid in df[df['status']=='submitted']['id'].values:
    ham = pr.load(jobid)
    ham.status.created = True
    ham.run()

But I don't understand why it does not work by load job names.

**Comment by jan-janssen** [comment]
Right, I totally forgot about reseting the status and the job name can only be an issue if the same job name appears several times in the same project. Still I do not think the code you posted is causing this issue. So I would need more details to understand where it came from.

**Comment by lfzhu-phys** [comment]
Yes, by loading job names, it was complaining:

"2020-11-13 08:35:21,509 - pyiron_log - WARNING - Job 'h' does not exist and cannot be loaded"

As I just resubmitted them, I cannot reproduce this error this moment. If it comes up again, I will let you know.

Thank you very much.

**Comment by jan-janssen** [comment]
Then I guess you can close the issue now and once appears again we can have another look.
