### ISSUE TITLE
Git tests spamming

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1186]
It's been a few days since the unit tests became difficult to understand like [this one](https://github.com/pyiron/pyiron/pull/1185). Is there a possibility to deactivate them while the PR is a draft or something? Or I'd love to know why they are failing + even if they are failing I don't want to receive several emails for each commit.

**Comment by jan-janssen** [comment]
I have to admit I created an email filter to remove those emails automatically, it seems like Github is working on this https://github.community/t/disabling-notifications-for-a-given-workflow/17818

**Comment by liamhuber** [comment]
Yeah, I had an e-mail filter but somehow it wasn't sophisticated enough to catch new repositories so different things kept slipping through. TBH, I just disabled e-mail alerts entirely for everything except explicit @ mentions. I check my github feed manually, like, two to two-score times per day anyhow 😝

**Comment by samwaseda** [comment]
Hmmmm ok I just set a filter as well now. I'm not sure if this should be a solution though...
