### ISSUE TITLE
Implement calc_flexible

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1197]
After years of continuously hitting the wall for trying to calculate things for various temperatures with LAMMPS, only to find out that `calc_md` throws an error for T=0, I finally make this suggestion: How about creating `calc_flexible` (I don't like this name -> please help me come up with a better one), which essentially does:

- `n_ionic_steps = 0` -> `calc_static`, no matter what the rest of the arguments do (this is by the way the same as `run 0` in LAMMPS)
- `temperature = 0` -> `calc_minimize` for `n_ionic_steps` steps
- `temperature = None` -> `calc_md` in NVE for `n_ionic_steps` steps
- `temperature > 0` -> `calc_md` in NVT for `n_ionic_steps` steps
- NPT follows the same convention as `calc_md`

I'm gonna keep this one open for discussion and hopefully to wait for some newbies who wants to implement it, because this one shouldn't require a deep understanding of pyiron.

**Comment by liamhuber** [comment]
[Explcit is better than implicit.](https://www.python.org/dev/peps/pep-0020/) I don't really like this idea.

**Comment by samwaseda** [comment]
That's not quite a question of explicit or implicit, because the 0K MD must be conceptually the same thing as energy minimisation. And doing 0 steps is always a static calculation. If `calc_flexible` is the problem, I can actually also change `calc_md`, so that it does an energy minimisation for T=0 and a static calculation for `n_ionic_steps=0`. How about that?

**Comment by pmrv** [comment]
> That's not quite a question of explicit or implicit, because the 0K MD must be conceptually the same thing as energy minimisation. And doing 0 steps is always a static calculation. If `calc_flexible` is the problem, I can actually also change `calc_md`, so that it does an energy minimisation for T=0 and a static calculation for `n_ionic_steps=0`. How about that?

I feel strongly against that.  All three types of calculations are quite distinct.  E.g. even at `T=0` an md run simply has a different parameter set as a minimization run (a md run doesn't have any convergence criteria among others).  I'm also not convinced that there is a big practical benefit from breaking that clean distinction.  If there's a series of MD runs one naturally excludes `T=0` as well as `n_ionic_steps=0`.

**Comment by samwaseda** [comment]
ok if you guys are against it I can also live with the current situation, but I'm quite sure that this topic is going to come back at some point anyway, because in high throughput calculations there will be no distinction between 0K and finite temperatures.
