### ISSUE TITLE
VASP kpoints_per_reciprocal_angstrom not used in jobs with supercell

### ISSUE THREAD

**Issue by yury-lysogorskiy** [pyiron/pyiron#1198]
**Summary**

`VaspJob` *kpoints_per_reciprocal_angstrom* settings setup k-mesh only once when called, and not in master jobs with supercell, or if the structure is changed.

```
from pyiron import Project

pr=Project("test_vasp")
pr.job_table()
job = pr.create_job(pr.job_type.Vasp,"vasp_job")
job.structure = pr.create_ase_bulk("Cu","fcc", cubic=True, a=3.6)
job.set_kpoints(kpoints_per_reciprocal_angstrom=1/0.15)
```
results in [12,12,12] k-mesh (in `job.input.kpoints`)

1.  If structure is changed, i.e.:
```
job.structure = pr.create_ase_bulk("Cu","fcc", cubic=True, a=4.6)
```
k-mesh  remains [12,12,12] 

2. If job is used as `ref_job` for `PhonopyJob`,
```
ph=pr.create_job(pr.job_type.PhonopyJob,"phonopy")
ph.ref_job=job
```
k-mesh  remains the same [12,12,12] even for supercell.

**pyiron Version and Platform**

-0.3.12.post0.dev39-py3.7.egg

**Expected Behavior**
Once `kpoints_per_reciprocal_angstrom`  are setup, this parameter should became a part of the settings, not just part of the formula to compute k-mesh once.

**Actual Behavior**

k-mesh  remains the same [12,12,12] even for supercell.

**Steps to Reproduce**

```
from pyiron import Project

pr=Project("test_vasp")
pr.job_table()
job = pr.create_job(pr.job_type.Vasp,"vasp_job")
job.structure = pr.create_ase_bulk("Cu","fcc", cubic=True, a=3.6)
job.set_kpoints(kpoints_per_reciprocal_angstrom=1/0.15)
```
results in [12,12,12] k-mesh (in `job.input.kpoints`)

1.  If structure is changed, i.e.:
```
job.structure = pr.create_ase_bulk("Cu","fcc", cubic=True, a=4.6)
```
k-mesh  remains [12,12,12] 

2. If job is used as `ref_job` for `PhonopyJob`,
```
ph=pr.create_job(pr.job_type.PhonopyJob,"phonopy")
ph.ref_job=job
```
k-mesh  remains the same [12,12,12] even for supercell.

**Comment by jan-janssen** [comment]
I guess the only way to address this right now would be to already set the rescaled structure to the reference job before creating the phonopy job. Following the zen of python to be explicit rather than implicit I do not another solution which would be consistent with our definition. In this example defining the kpoint mesh explicitly in your case `[12, 12, 12]` rather implicitly: ```
job.structure = pr.create_ase_bulk("Cu","fcc", cubic=True, a=3.6)
job.set_kpoints(kpoints_per_reciprocal_angstrom=1/0.15)
job.structure.set_repeat(2)
```

@sudarsan-surendralal and @samwaseda Any other suggestions how to handle reciprocal kpoint mesh definition in particular in combination with the phonopy job?

**Comment by sudarsan-surendralal** [comment]
In my opinion, the best way to handle this is to create a property `k_mesh_per_reciprocal_angstrom` (default `None`) rather than a function. When the job is submitted after the final structure is set and the `write_input()` function is called, we then overwrite the existing kpoints based on the dimensions of the supercell. Is this an okay solution?

**Comment by samwaseda** [comment]
While I like @sudarsan-surendralal's suggestion, I also think `set_kpoints` sounds to me like "I'm setting them now" and I might not expect the values to change when I change the structure.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> While I like @sudarsan-surendralal's suggestion, I also think `set_kpoints` sounds to me like "I'm setting them now" and I might not expect the values to change when I change the structure.

Sure but the way @yury-lysogorskiy sets this is: `job.set_kpoints(kpoints_per_reciprocal_angstrom=1/0.15)` therefore not specifying the mesh explicitly. Then it should be fine right?

**Comment by samwaseda** [comment]
> 
> Sure but the way @yury-lysogorskiy sets this is: `job.set_kpoints(kpoints_per_reciprocal_angstrom=1/0.15)` therefore not specifying the mesh explicitly. Then it should be fine right?

Sounds great to me.

**Comment by yury-lysogorskiy** [comment]
In my previous implementation I did it in [`Kpoints.update_kmesh`](https://github.com/yury-lysogorskiy/pyiron/blob/icams/phonopy/pyiron/vasp/base.py#L2332)

**Comment by yury-lysogorskiy** [comment]
And also, one more thing:  calculation of k-mesh by given density should take into account the non-orthorombic cell,
I did it like [this](https://github.com/yury-lysogorskiy/pyiron/blob/8797bb0e93100515d6870770a539868f2a6459f3/pyiron/dft/job/generic.py#L291):
```python
def get_k_mesh_by_density(cell, kmesh_density_per_inverse_angstrom=1.0):
    """
    Args:
        cell:
        kmesh_density_per_inverse_angstrom:
    Returns:
    """
    omega = np.linalg.det(cell)
    l1, l2, l3 = cell
    g1 = 2 * np.pi / omega * np.cross(l2, l3)
    g2 = 2 * np.pi / omega * np.cross(l3, l1)
    g3 = 2 * np.pi / omega * np.cross(l1, l2)

    kmesh = np.rint(
        np.array([np.linalg.norm(g) for g in [g1, g2, g3]]) / kmesh_density_per_inverse_angstrom
    )
    kmesh[kmesh < 1] = 1
    return [int(k) for k in kmesh]
```

**Comment by samwaseda** [comment]
> ```python
> def get_k_mesh_by_density(cell, kmesh_density_per_inverse_angstrom=1.0):
>     """
>     Args:
>         cell:
>         kmesh_density_per_inverse_angstrom:
>     Returns:
>     """
>     omega = np.linalg.det(cell)
>     l1, l2, l3 = cell
>     g1 = 2 * np.pi / omega * np.cross(l2, l3)
>     g2 = 2 * np.pi / omega * np.cross(l3, l1)
>     g3 = 2 * np.pi / omega * np.cross(l1, l2)
> 
>     kmesh = np.rint(
>         np.array([np.linalg.norm(g) for g in [g1, g2, g3]]) / kmesh_density_per_inverse_angstrom
>     )
>     kmesh[kmesh < 1] = 1
>     return [int(k) for k in kmesh]
> ```

This is BRILLIANT! It's actually something I can use elsewhere for other purposes as well.
