### ISSUE TITLE
Is this distinction necessary?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#122]
I'm having a box which is orthogonal at the beginning of the simulation (interactive), which is sheared over the course of the calculation. Since `block` is set (which is due to the orthogonal box at the beginning of the simulation), I was not allowed to shear the box. But is this distinction anyway required?

https://github.com/pyiron/pyiron/blob/bf03c0e45db893881f33eac200c1f2bf87ffebc6/pyiron/lammps/interactive.py#L259

**Comment by jan-janssen** [comment]
Can not you just set `self.interactive_enforce_structure_reset = True` ?

**Comment by samwaseda** [comment]
That's also possible but is there anyway any reason to distinguish between `block` and `prism`?
