### ISSUE TITLE
`selective_dynamics=True` means atoms can move or can't move?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1224]
I never know which way around. Please someone give me the answer and I'll always remember that I asked this question here so that I can search for `selective_dynamics` in the search bar to find the answer.

**Comment by jan-janssen** [comment]
`True` means allowed to move.

**Comment by sudarsan-surendralal** [comment]
`True` means the atoms are allowed to move (dynamics is allowed). Btw this sort of way of defining constraints is kind of inherited from [VASP](https://cms.mpi.univie.ac.at/vasp/vasp/POSCAR_file.html)!

**Comment by samwaseda** [comment]
Thanks! I know it's inherited from VASP and I was aware of the link you shared, but it's still difficult to find the phrase, and from what I understand, it's also wrong:

*in our example the 1. coordinate of atom 1 and all coordinates of atom 2 are fixed*:

```
Cubic BN
   3.57
 0.0 0.5 0.5
 0.5 0.0 0.5
 0.5 0.5 0.0
   1 1
Selective dynamics
Cartesian
 0.00 0.00 0.00 T T F
 0.25 0.25 0.25 F F F
Cartesian
 0.01 0.01 0.01
 0.00 0.00 0.00
```

But ok you guys are my heroes. I can now happily close this issue.
