### ISSUE TITLE
pyiron.atomistics.structure.generator module is not available 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#1226]
I open one of my code and try to run it suddenly I get an error which "No module named 'pyiron.atomistics.structure.generator'" 
what is the problem 
see the attachment 
<img width="912" alt="Screenshot 2020-11-24 at 22 22 47" src="https://user-images.githubusercontent.com/62750893/100153082-ed41ee00-2ea3-11eb-99d0-79e02e82e0a5.png">

**Comment by liamhuber** [comment]
This is now directly available through 'pr.create.structure.surface_hkl'. (Use tab complete to double check the naming as I'm not at my machine right now.)

This is Ort idiot ongoing drive to make things more "pyironic ", ie only needing to import 'Project' and having everything tab completable 🙂
