### ISSUE TITLE
ImportError: SQSJob relies on sqsgenerator.core.sqs.ParallelSqsIterator, but this is unavailable

### ISSUE THREAD

**Issue by danjuzam** [pyiron/pyiron#1229]
When I tried to create an SQS job, an error occured:
> 
> from pyiron import Project
> pr = Project("sqs")
> job_sqs = pr.create_job(
...     job_type=pr.job_type.SQSJob, 
...     job_name="sqscalculation"
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/isi/w/mut/Programme/miniconda3/lib/python3.8/site-packages/pyiron/project.py", line 167, in create_job
    job = JobType(
  File "/isi/w/mut/Programme/miniconda3/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 92, in __new__
    job = job_class(project, job_name)
  File "/isi/w/mut/Programme/miniconda3/lib/python3.8/site-packages/pyiron/atomistics/job/sqs.py", line 144, in __init__
    _fail_if_imports_missing()
  File "/isi/w/mut/Programme/miniconda3/lib/python3.8/site-packages/pyiron/atomistics/job/sqs.py", line 64, in _fail_if_imports_missing
    raise ImportError("SQSJob relies on sqsgenerator.core.sqs.ParallelSqsIterator, but this is unavailable.")
ImportError: SQSJob relies on sqsgenerator.core.sqs.ParallelSqsIterator, but this is unavailable.

Any ideas what could be the reason for that?

**Comment by jan-janssen** [comment]
The SQS code is an external tool which can be installed as separate conda package: 
```
conda install -c conda-forge sqsgenerator 
```
https://anaconda.org/conda-forge/sqsgenerator
https://github.com/dgehringer/sqsgenerator

**Comment by danjuzam** [comment]
Ok, thank you. Is there a list where one can see which of the available job_types are included in the pyiron installation and which have to be installed separately (and then how)? That would be very helpful.

**Comment by jan-janssen** [comment]
@danjuzam That is a great idea, here is a first list of codes and how to install them, the rest of the job types are available out of the box, but many of them require a quantum engine to evaluate energies and forces for a given structure. These quantum engines are commonly external codes. Still at least the open source codes can all be installed using conda. 

| code | job_type | How to install ? |
|------|----------|----------------|
| sqsgenerator | SQSJob, ParallelSqsIterator | `conda install -c conda-forge sqsgenerator` | 
| S/PHI/nX | Sphinx | `conda install -c conda-forge sphinxdft` | 
| Gpaw | Gpaw | `conda install -c conda-forge gpaw` | 
| LAMMPS | Lammps | `conda install -c conda-forge lammps` | 
| VASP | Vasp | Compile on your own (commercial code) | 
| GAUSSIAN | Gaussian | Compile on your own (commercial code) |

**Comment by danjuzam** [comment]
@jan-janssen Thanks a lot

**Comment by jan-janssen** [comment]
@danjuzam Thank you for bringing this up, I opened a pull request to include it in the FAQ https://github.com/pyiron/pyiron/pull/1231 so if you have more questions do not hesitate to open issues here. We are happy to welcome new users to the pyiron community.
