### ISSUE TITLE
How to get per atom result of CNA

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1234]
I can see that `analyse_pyscal_cna_adaptive` returns the total number of atoms belonging to each crystal structure, but it doesn't tell me which atom is what. So I would love to have an array/list of length `n_atoms` which contains something like `['fcc', 'bcc', 'bcc', 'other', ... ]`

**Comment by jan-janssen** [comment]
`mode` - it is documented in the docstring - 'total' is default, 'numeric' and 'str' are other options.

**Comment by samwaseda** [comment]
oh ok I saw that one but I misunderstood the content. Did ovito have the same interface?

**Comment by jan-janssen** [comment]
Yes, and there is even an ovito compatibility mode.

**Comment by samwaseda** [comment]
ok I had the feeling that ovito worked differently for `mode` but I'm probably wrong. Thanks anyway!
