### ISSUE TITLE
Structure issues when using ASE functions

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#1241]
**Summary**

When creating a pyiron structure, and attempting to use an ASE function such as structure.set_dihedral(), an error occurs due to the structure.indices becoming floats. I have already pinpointed the problem I think (see below).

**pyiron Version and Platform**

HPC version of pyiron (should not significantly differ in atoms.py)

**Expected Behavior**

The ASE function should just return the adapted structure object without throwing an error due to float structure indices.

**Actual Behavior**

The execution of for instance structure.get_dihedral() throws the following error:
`TypeError: list indices must be integers or slices, not numpy.float64`

**Steps to Reproduce**

```
from pyiron import  ase_to_pyiron
from ase.build import  molecule

structure = ase_to_pyiron(molecule('H2COH'))
structure.set_dihedral(4,0,1,2,angle=90)
```

**Further Information, Files, and Links**

The issue happens in the function  `_masked_rotate` where a new class instance is made, without any atom inside resulting in an empty structure.indices array, which defaults to dtype=float. As a solution I propose changing the following line https://github.com/pyiron/pyiron/blob/832194ef1332b209378496ebb101a5ac1d1324a2/pyiron/atomistics/structure/atoms.py#L172 

to 

`self.indices = np.array(el_index_lst, dtype=np.int)`

```
def _masked_rotate(self, center, axis, diff, mask):
        # do rotation of subgroup by copying it to temporary atoms object
        # and then rotating that
        #
        # recursive object definition might not be the most elegant thing,
        # more generally useful might be a rotation function with a mask?
        group = self.__class__()
        for i in range(len(self)):
            if mask[i]:
                group += self[i]
        group.translate(-center)
        group.rotate(diff * 180 / pi, axis)
        group.translate(center)
        # set positions in original atoms object
        j = 0
        for i in range(len(self)):
            if mask[i]:
                self.positions[i] = group[j].position
                j += 1

```

**Comment by sudarsan-surendralal** [comment]
Sorry for the late response! Please see the linked pull request!
