### ISSUE TITLE
`set_initial_magnetic_moments` not working after deleting atoms

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1242]
This one works:

```
structure = pr.create_structure('Ni', 'fcc', 3.5)
del structure[0]
structure.set_initial_magnetic_moments(len(structure)*[2])
```

while this one doesn't:

```
structure = pr.create_structure('Ni', 'fcc', 3.5)
del structure[np.array([True, False, False, False])]
structure.set_initial_magnetic_moments(len(structure)*[2])
```

I put `bug` but if this is something that I shouldn't have done, I'm also okay to accept it.

**Comment by sudarsan-surendralal** [comment]
> I put `bug` but if this is something that I shouldn't have done, I'm also okay to accept it.

This is definitely a bug! See the linked pull request!
