### ISSUE TITLE
job run required Max?

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#1246]
I do some calculations with SPHInX and using the Pyiron interface, and when I want to submit my job,
 I get such an Error "'max' is undefined". I don't know whether in related to the new update pyiron or something else. (see attachment ) would it be possible for someone to tell me how to fix it?

<img width="959" alt="Screenshot 2020-12-04 at 01 22 52" src="https://user-images.githubusercontent.com/62750893/101105990-4a8a1d80-35cf-11eb-929d-510467bfb586.png">

**Comment by samwaseda** [comment]
I don’t know the problem in detail but it sounds to me like it’s related to @jan-janssen ’s update of the executables from yesterday.

**Comment by pmrv** [comment]
This is due to me updating the queue config file yesterday, @jan-janssen copied it from there.  Seems like I misunderstood the Jinja docs. I'll look into a solution right away.

**Comment by pmrv** [comment]
I provided the fix [here](https://github.com/pyiron/pyiron-resources-mpie/pull/11) and [here](https://github.com/pyiron/pysqa/pull/48), but I think only @jan-janssen can deploy new configuration.  Until then no calculations can be started from pyiron in the usual way.  If you need to run something *right now*, set the job run mode to `manual` and run 
```
python -m pyiron_base.cli wrapper -p {project_name_absolute} -j {job_id}"
```
from the directory where the job files are saved.  When you call `job.run()` after you set `manual` run mode, this command line will also be printed to you, so you can just copy that.

**Comment by jan-janssen** [comment]
Should be fixed now
