### ISSUE TITLE
What's standard procedure if terminal commands required

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1247]
I got a few feature requests from @yuyuanjingxuan which would require a few SPHInX commands. I could call them via `subprocess` but is it the right way to do so?

**Comment by jan-janssen** [comment]
Is it pre- or postprrocessing? or an independent sphincter command?

**Comment by samwaseda** [comment]
For the ones I have right now it's only post processing.

**Comment by jan-janssen** [comment]
Then I would try to included it at the end of the `run_` shell script - maybe check if a certain flag is set.

**Comment by samwaseda** [comment]
For the problem I'm having right now (parsing DOS), that would be a good solution, but then we would have to load the executable with a lot of commands, most of which are not going to be used in the majority of the cases. Making the user set the flags before running the simulation is also quite counter intuitive, because DOS is an ordinary output just like everything else.

**Comment by jan-janssen** [comment]
You can also add a secondary run script, but I think we should use the executables, as different versions of Sphinx might change the behavior of the dos parsing.

**Comment by samwaseda** [comment]
In the end I appended it to the current executables, but I'm not really fond of this solution...
