### ISSUE TITLE
Submit jobs using "s_cmfe" with 40 cores, but jobs run with "p_cmfe"

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1253]
Does anyone experience this? Or, it's the default that it automatically changes from "s_cmfe" to "p_cmfe" if using 40 core.

**Comment by pmrv** [comment]
The `s_cmfe` queue in pyiron only accepts jobs with < 40.  Larger jobs are automatically sent to `p_cmfe`.  So as long as it doesn't break anything, this is intended behavior.

**Comment by samwaseda** [comment]
@lfzhu-phys Is there a particular reason that there's should be a distinction between `s_cmfe` and `p_cmfe` for 40 cores?

**Comment by lfzhu-phys** [comment]
@pmrv @samwaseda Ok, understand, thanks a lot:) I am asking because s_cmfe with 40 cores were working well before for my jobs. Now it automatically switches to p_cmfe. I am worrying I occupy more resources which is not necessary:)
