### ISSUE TITLE
Load Jobs 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#1254]
I had a job which was done about a year ago, and new I wanted to load the job via job ID: 
pr.load(id of the job)
and then I get such an error : "Objects can be only recovered from hdf5 if TYPE is given."
does anyone knows how to solve the problem and why this error arise 
<img width="561" alt="Screenshot 2020-12-09 at 10 05 46" src="https://user-images.githubusercontent.com/62750893/101608691-55491600-3a06-11eb-8df1-4687e6c676e3.png">

**Comment by jan-janssen** [comment]
@mostafajoulaian nobody has the chance to help you unless you provide some more information about what kind of job you try to load. The job id `2980314` does not help. In addition we introduced issue templates to help the users provide the required information - I do not understand why you ignore those:  https://github.com/pyiron/pyiron/blob/master/.github/ISSUE_TEMPLATE/bug_report.md 

**Please provide more details**

**Comment by jan-janssen** [comment]
@samwaseda and @ashtonmv I assume this is related to backwards compatibility of the Sphinx Job class.

**Comment by samwaseda** [comment]
@mostafajoulaian I encounter this regularly and I have to admit I have never really been able to say when and why it happens. I have never posted this issue mainly because it was impossible to me to describe the issue properly and I was too fearful of someone telling me that I should provide more information that I wasn't really able to (which is exactly what happened here). My practical solution so far: load the input via `inspect` and copy the content.

**Comment by samwaseda** [comment]
> @samwaseda and @ashtonmv I assume this is related to backwards compatibility of the Sphinx Job class.

Maybe yes, maybe not. Frankly I have no idea. At least I can say it's not a general problem (i.e. in general it's backward compatible).

**Comment by jan-janssen** [comment]
What is the type of the job you try to reload? 
```
pr.inspect(2980314)["TYPE"]
```
All the above command says it is not able to reload that job type because pyiron does not know what kind of object it is.

**Comment by mostafajoulaian** [comment]
If I get information correctly  the file it hdf5 and job type ""<class 'pyiron.sphinx.sphinx.Sphinx'>""

**Comment by jan-janssen** [comment]
And what do you get for a more recent job?

**Comment by mostafajoulaian** [comment]
when I use recent job ID, no error will pup up

**Comment by samwaseda** [comment]
> when I use recent job ID, no error will pup up

I guess @jan-janssen 's question is what's written in `TYPE` for a more recent job.

**Comment by mostafajoulaian** [comment]
<img width="924" alt="Screenshot 2020-12-09 at 10 48 31" src="https://user-images.githubusercontent.com/62750893/101613498-1e75fe80-3a0c-11eb-89b7-079acd772c69.png">
@samwaseda when I use recent job ID it will loaded without any issue and job type is <class 'pyiron.sphinx.sphinx.Sphinx'>

**Comment by jan-janssen** [comment]
So to summarise: 
```
pr.inspect(2980314)["TYPE"] == pr.inspect(10617305)["TYPE"]
```
And what is the output of: 
```
```
pr.inspect(2980314).list_nodes()
```

**Comment by mostafajoulaian** [comment]
No
pr.inspect(10617305)["TYPE"] = <class 'pyiron.sphinx.sphinx.Sphinx'> !this is the new job
pr.inspect(2980314)["TYPE"] = nothing   !this is the old job
pr.inspect(2980314).list_nodes() = []  ! it is empty 
<img width="602" alt="Screenshot 2020-12-09 at 11 11 14" src="https://user-images.githubusercontent.com/62750893/101616142-49ae1d00-3a0f-11eb-8f10-24a046a47418.png">

**Comment by jan-janssen** [comment]
> If I get information correctly the file it hdf5 and job type ""<class 'pyiron.sphinx.sphinx.Sphinx'>""

But this is in contrast to what you posted before.

**Comment by jan-janssen** [comment]
> No
> pr.inspect(10617305)["TYPE"] = <class 'pyiron.sphinx.sphinx.Sphinx'> !this is the new job
> pr.inspect(2980314)["TYPE"] = nothing !this is the old job
> pr.inspect(2980314).list_nodes() = [] ! it is empty
> <img alt="Screenshot 2020-12-09 at 11 11 14" width="602" src="https://user-images.githubusercontent.com/62750893/101616142-49ae1d00-3a0f-11eb-8f10-24a046a47418.png">

To me this looks like the job does not exist or you do not have access - at least the HDF5 file is empty.

**Comment by jan-janssen** [comment]
**Summary**: 
The HDF5 file is empty - and I implemented an error message to be more explicit about empty HDF5 files. 

@mostafajoulaian Is there anything else we can do? Otherwise I guess you can close this issue.

**Comment by mostafajoulaian** [comment]
When you said what is the job type I got it as sam said {TYPE for a more recent job}. However
I bit confused; let me explain more in detail. This calculation belongs to the old Delta project, and now I have to re-run the codes. it is two separate notebooks:
1- the old version of the calculation, for instance (aluminum)
2- the second notebook is the one I am currently working on, and I want to load an old job in this notebook.
I load project as pr = Project('deltasphinxkjxc-Aluminium')! this is how it job named and stored 
I got a table of jobs and want to load one which, as you said, "job does not exist, or you do not have access - at least the HDF5 file is empty."
I open an old jupyter notebook restart the notebook (without removing the job) (jobs get new ID).
Surprisingly, when I load the project in the new notebook, the new notebook job has a different ID, which does not make sense at all?
look at the attachment (did I do something wrong to load the project)
<img width="1440" alt="Screenshot 2020-12-09 at 11 40 09" src="https://user-images.githubusercontent.com/62750893/101619896-246fdd80-3a14-11eb-8543-3244dae895ea.png">
<img width="1062" alt="Screenshot 2020-12-09 at 11 46 05" src="https://user-images.githubusercontent.com/62750893/101620106-6ef15a00-3a14-11eb-8d00-655614dd68f2.png">

**Comment by jan-janssen** [comment]
Great the I guess this issue is solved, as you said you once used the project: 
```
joulamps/pyiron_data/Detla_projects/deltasphinxkjxc-Aluminium/
```
and once the project:
```
joulamps/pyiron_data/Detla_projects/Aluminium/deltasphinxkjxc-Aluminium/
```
which are obviously different and in one the HDF5 file exists while in the other it does not.

**Comment by mostafajoulaian** [comment]
for Aluminum the problem was solved ( I guess because I run the cell again) but If I take another element such as Niobium
(the order is the same as Aluminium)
pr = Project('Niobium\deltasphinxkjxc_Niobium') dose not contain any job 


<img width="578" alt="Screenshot 2020-12-09 at 12 41 12" src="https://user-images.githubusercontent.com/62750893/101625547-d8c13200-3a1b-11eb-9633-59d8a2f98a8c.png">

**Comment by jan-janssen** [comment]
I can not even see the project column on the screenshot above, please post: 
```
pr.job_table().project.values
```

**Comment by jan-janssen** [comment]
@mostafajoulaian I have the feeling you moved around the HDF5 file outside of pyiron rather than using `pr.move_to()` and now you have an inconsistent database where the HDF5 files no longer exist in the paths which are stored in the pyiron database. So please very carefully check that your file system and your pyiron database is consistent. I do not see a bug here and we already extended the error message to make it more clear the HDF5 file is empty.
