### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#126]
I just noticed that our code quality went down from 'B' to a 'D'  :(. Any idea what happened?

https://app.codacy.com/project/pyiron-runner/pyiron/dashboard

**Comment by jan-janssen** [comment]
Somehow the Lines of code changed from 22000 to 9600 - I always thought we have over 50000 - at least that is what PyCharm said.

**Comment by sudarsan-surendralal** [comment]
Ok. In any case, I created a merge request https://github.com/pyiron/pyiron/pull/127 where I make some pep8 corrections whenever I come across it.

**Comment by jan-janssen** [comment]
Maybe they just decided to no longer count empty lines, because currently in all coverage statistics empty lines are still included, which does not make any sense. Anyway I guess we can close this issue. 

@sudarsan-surendralal can you close the issue?

**Comment by jan-janssen** [comment]
It again went up to A
