### ISSUE TITLE
Is there a particular reason to set `cell` actively to `None`?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1264]
https://github.com/pyiron/pyiron/blob/da28459af5070c8496e6faf8b17466183329c1d0/pyiron/atomistics/job/atomistic.py#L644

I see that in `get_structure`, `cell` is actively set to `None` if there's no output cell information. Is there a reason to do so? I don't see an immediate problem with the current implementation, but if for example in the case of SPHInX, the cell size doesn't change and for some reason there could be a parsing problem (after all `get_structure` is used inside `restart`, which in turn is used for not converged calculations), so I might prefer that `get_structure` still returns a structure with a valid cell size.

**Comment by sudarsan-surendralal** [comment]
> but if for example in the case of SPHInX, the cell size doesn't change and for some reason there could be a parsing problem (after all get_structure is used inside restart, which in turn is used for not converged calculations), 

Wouldn't it be better to rather fix the parser then? Even for non-converged calculations (that have not crashed), there should be reasonable output right?

>so I might prefer that get_structure still returns a structure with a valid cell size.

But at what step? This only works if the cell size doesn't change

**Comment by samwaseda** [comment]
> But at what step? This only works if the cell size doesn't change

My short summary:

Acceptable:

- Structure gets the initial cell size and the rest is updated
- It raises an Error

Not acceptable (and is the current implementation)

- Structure gets `None` for the cell and the rest is updated

**Comment by samwaseda** [comment]
And in [this PR](https://github.com/pyiron/pyiron/pull/1265) I return the structure with whatever can be updated. I was thinking about raising an error, but it turned out that the `get_structure` in `interactive.py` does virtually the same thing, and since I abolished the one in `interactive.py` and created a unified version in `atomistic.py` (frankly I don't really understand why there were two versions), I kind of had to take the version in `interactive.py` which doesn't break anything in the tests.

**Comment by liamhuber** [comment]
`cell = None` is perfectly reasonable for many molecular calculations. I suggest keeping it.

**Comment by samwaseda** [comment]
> `cell = None` is perfectly reasonable for many molecular calculations. I suggest keeping it.

Is it the convention for not having a cell? I thought it was just having no cell size and no PBC.

**Comment by liamhuber** [comment]
> > `cell = None` is perfectly reasonable for many molecular calculations. I suggest keeping it.
> 
> Is it the convention for not having a cell? I thought it was just having no cell size and no PBC.

I'm not sure. How do you have a cell without having a cell size though?

**Comment by samwaseda** [comment]
> > > `cell = None` is perfectly reasonable for many molecular calculations. I suggest keeping it.
> > 
> > 
> > Is it the convention for not having a cell? I thought it was just having no cell size and no PBC.
> 
> I'm not sure. How do you have a cell without having a cell size though?

As far as I remember ASE simply gives [0, 0, 0].

**Comment by liamhuber** [comment]
> > > > `cell = None` is perfectly reasonable for many molecular calculations. I suggest keeping it.
> > > 
> > > 
> > > Is it the convention for not having a cell? I thought it was just having no cell size and no PBC.
> > 
> > 
> > I'm not sure. How do you have a cell without having a cell size though?
> 
> As far as I remember ASE simply gives [0, 0, 0].

*grunt*, sounds like a kind of lazy workaround for not accounting for the true value of not having a cell. Anyhow, it's nothing I feel super strongly about one way or the other, but to answer your original question I still come down on the side that molecular calculations are a good reason to set the cell to `None` :p

**Comment by samwaseda** [comment]
Since I merged the changes [here](https://github.com/pyiron/pyiron/pull/1265), I'm not particularly interested in this topic anymore, so I'm gonna close this issue, but this is probably something we should keep in mind.
