### ISSUE TITLE
Changing atomic species ridiculously slow

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1272]
The following lines took nearly 5 min.

```
structure = Project('.').create_structure('Ni', 'fcc', 3.52).repeat(10)
for i in range(len(structure)):
    structure[i] = 'Al'
```

And since I'm running MC calculations with LAMMPS, where I switch species, it is actually quite critical that the simulation runs faster. Is there a way to make it maybe faster?

**Comment by samwaseda** [comment]
Ok I realised that using `Atoms.indices` makes it WAY faster, but is it safe? I'm gonna assign @sudarsan-surendralal because I have the feeling he knows it the best.

**Comment by sudarsan-surendralal** [comment]
For the snippet you show probably `structure[:] = "Al"` is the fastest way to do it.

If your structure already has all elements that you possibly want to switch to, using `indices` is definitely faster. But, it's only safe if you don't get rid of all atoms of a particular element or add new elements.

**Comment by samwaseda** [comment]
Okay brilliant. Thank you for your answer.
