### ISSUE TITLE
New pyiron release

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1275]
Joerg just informed me that the QuasiHarmonic Master does not work https://github.com/pyiron/phasediagram-workshop-2020/blob/master/Exercise4.ipynb

The issue was fixed in https://github.com/pyiron/pyiron/pull/1268 

So we just need to create a new pyiron release and afterwards update the pyiron version on cmti. 

@muh-hassani , @niklassiemer  and @pmrv Can one of you create a new release for pyiron?

**Comment by muh-hassani** [comment]
Hello @jan-janssen, I can do this.

**Comment by jan-janssen** [comment]
With the recent changes in https://github.com/pyiron/pyiron/pull/1278 and https://github.com/pyiron/pyiron/pull/1277 it makes sense to release a pyiron `0.4.0` version.

**Comment by jan-janssen** [comment]
The focus of the pyiron `0.4.0` release is going to be the modularisation, this includes the activities of positioning pyiron as a tool beyond computational materials science and at the same time inside the atomistic part we can continue to separate the structure creation and the structure analysis in stand-alone toolboxes which could even be used without pyiron.
