### ISSUE TITLE
Plot3d mirrors cluster structures

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#1281]
**Summary**

The plot3d() function appears to mirror cluster structures (no cell property), which is problematic for stereoisomers.

**pyiron Version and Platform**

HPC UGhent version of pyiron (should not significantly differ in atoms.py)

**Expected Behavior**

Using the plot3d_ase() function actually gives the correct structure (see attached xyz structure). The OH functionality should lie at the left side, pointing backwards, when the CH3 group lies on top.

**Actual Behavior**

plot3d() mirrors the structure such that when the CH3 group lies on top, the OH functionality lies at the **right** side when pointing backwards. Similarly, the handedness of the functional group at the bottom is reversed.

**Steps to Reproduce**

```
from pyiron import ase_to_pyiron
from ase.io import read

test = ase_to_pyiron(read('rrsr.xyz'))
test.plot3d_ase(spacefill=False,show_axes=False)
test.plot3d(spacefill=False,show_axes=False) # this mirrors the handedness
```

[rrsr.zip](https://github.com/pyiron/pyiron/files/5786386/rrsr.zip)

**Comment by samwaseda** [comment]
Ok I can see that it's mirrored on the yz plane. Let me see if I can fix it.
