### ISSUE TITLE
pyiron 0.4.0 - modular release

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1290]
As discussed in the last pyiron meeting @niklassiemer and I moved the traditional pyiron package to https://github.com/pyiron/pyiron_atomistics . This migration enables us to extend pyiron beyond atomistic simulation and continue working on the inclusion of continuum simulation https://github.com/pyiron/pyiron_contrib/pull/35 and the post processing of experimental datasets https://github.com/pyiron/pyiron_experimental . This extension of pyiron beyond atomistic simulation is part of https://materialdigital.de and @muh-hassani and @Ahmed-Aslam can tell you more about the Material Digital Project. 

**For the users:**
At the current stage the `pyiron` package can still be used as regularly:
```
from pyiron import Project
```
But the recommended way to import pyiron for atomistic simulation is:
```
from pyiron_atomistics import Project
```
All the rest stays the same. So the current switch is primarily for developers. 

**For the developers:**
As a developer, please do not open any more pull requests on this repository, but instead open pull requests on:
https://github.com/pyiron/pyiron_atomistics

**Bugs:**
- Comparing with `isinstance()` fails when comparing to an object imported from `pyiron` rather than `pyiron_atomistics`. 

If you identify more bugs please report them.

**Comment by liamhuber** [comment]
Nit: Do we want `pyiron_atomistics` or `pyiron_atomistic`? Compared to `pyrion_base`, `pyiron_continuum`, `pyiron_experiment`, I think the later actually fits better. I don't feel super strongly about it, but now is pretty much the only opportunity we'll have to make the choice 😛
