### ISSUE TITLE
ValueError: Was not able to locate the potential files

### ISSUE THREAD

**Issue by ycc252** [pyiron/pyiron#1292]
Hi all,

I have used Pyiron as a first try after successfully installation and configuration,

from pyiron import Project
pr = Project('test')
structure = pr.create_structure('Fe', 'bcc', 2.78)
job = pr.create_job(job_type=pr.job_type.Lammps, job_name='lammpstestjob')
job.structure = structure
job.potential = job.list_potentials()[0]
job.run()

But got below issue:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-d49bbc19900c> in <module>
      1 job = pr.create_job(job_type=pr.job_type.Lammps, job_name='lammpstestjob')
      2 job.structure = structure
----> 3 job.potential = job.list_potentials()#[0]
      4 job.run()

/mnt/c/Anaconda_linux/[/mnt/c/Anaconda_linux/anaconda3]/lib/python3.7/site-packages/pyiron/lammps/base.py in list_potentials(self)
    275             list: potential names
    276         """
--> 277         return list(self.view_potentials()["Name"].values)
    278 
    279     def enable_h5md(self):

/mnt/c/Anaconda_linux/[/mnt/c/Anaconda_linux/anaconda3]/lib/python3.7/site-packages/pyiron/lammps/base.py in view_potentials(self)
    257             raise ValueError("No structure set.")
    258         list_of_elements = set(self.structure.get_chemical_symbols())
--> 259         list_of_potentials = LammpsPotentialFile().find(list_of_elements)
    260         if list_of_potentials is not None:
    261             return list_of_potentials

/mnt/c/Anaconda_linux/[/mnt/c/Anaconda_linux/anaconda3]/lib/python3.7/site-packages/pyiron/lammps/potential.py in __init__(self, potential_df, default_df, selected_atoms)
    224                 plugin_name="lammps",
    225                 file_name_lst={"potentials_lammps.csv"},
--> 226                 backward_compatibility_name="lammpspotentials",
    227             )
    228         super(LammpsPotentialFile, self).__init__(

/mnt/c/Anaconda_linux/[/mnt/c/Anaconda_linux/anaconda3]/lib/python3.7/site-packages/pyiron/atomistics/job/potentials.py in _get_potential_df(plugin_name, file_name_lst, backward_compatibility_name)
    143                                 os.path.join(path, periodic_table_file_name), mode="r"
    144                             )
--> 145         raise ValueError("Was not able to locate the potential files.")
    146 
    147     @staticmethod

ValueError: Was not able to locate the potential files

**Comment by ycc252** [comment]
the topic is wrong, which should be ValueError: Was not able to locate the potential files

**Comment by jan-janssen** [comment]
Can you post your `~/.pyiron` config file? It seems like the resource directory is not configured correctly. pyiron requires your conda environment to be activated, e.g. the `CONDA_PREFIX` variable to be set to use the interatomic potentials from `pyiron-data`.
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment 
In case you installed pyiron from source please or via pip please follow the installation tutorial to download the parameter files:
https://pyiron.readthedocs.io/en/latest/source/installation.html#download-pyiron-parameter-files

If this does not help, please post your pyiron version
```
import pyiron
pyiron.__version__
```
how you installed pyiron and your `~/.pyiron` file.

**Comment by ycc252** [comment]
it works out. Thanks!

**Comment by ycc252** [comment]
but actually, I notice another problem. after using conda update pyiron(it says I need to restart, which I have done),but the pyiron version doesn't change.

**Comment by jan-janssen** [comment]
Can you post the output of:
```
import pyiron
print(pyiron.__version__)
print(pyiron.__file__)
```

**Comment by ycc252** [comment]
0.2.11
/mnt/c/Anaconda_linux/Anaconda3/lib/python3.7/site-packages/pyiron/__init__.py

**Comment by jan-janssen** [comment]
That is a bit strange, can you try to update pyiron to either 0.4.0 or 0.3.23. You can do this with conda using: 
```
conda install pyiron=0.4.0
```
Version 0.2.11 was released in April last year and we fixed quite a few bugs since then.

**Comment by ycc252** [comment]
conda install pyiron=0.4.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyiron=0.4.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.
pyiron.__version__
'0.2.11'

**Comment by jan-janssen** [comment]
Sorry I thought you have added the conda-forge channel: 
```
conda install -c conda-forge pyiron=0.4.0
```
Alternatively you can add the conda-forge channel using:
```
conda config --add channels conda-forge 
```

**Comment by ycc252** [comment]
it was installed but still not working.

**Comment by jan-janssen** [comment]
Can you post your pyiron config file `~/.pyiron` ?

**Comment by ycc252** [comment]
Hi, it is as follows
[DEFAULT]
PROJECT_PATHS = ~/pyiron/projects
RESOURCE_PATHS = ~/pyiron/resources

**Comment by ycc252** [comment]
Thanks so much,
I have tried to rerun everything, it works out

**Comment by jan-janssen** [comment]
Perfect

**Comment by Zephyrainzjl** [comment]
Well, I also encountered this issue, but I resolved it by running the following command:

conda install -c conda-forge iprpy-data.

I believe this is because the potential files were not installed when installing LAMMPS and other executables.
