### ISSUE TITLE
Lammps Potential Error

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1293]
**Summary**

Pyiron can't load the EMT_Asap_MetalGlass_PaduraruKenoufiBailey_2007_CuZr__MO_987541074959_001 potential, probably because it is not in the resources directory.

**pyiron Version and Platform**

recent git versions on ubuntu

**Expected Behavior**

Pyiron loads the potential and runs the job

**Actual Behavior**

Throws this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-033c8cd0fecd> in <module>
      8     j = pr.create_job("Lammps", f"potential_{i}") # Use the potential index within the jobname
      9     j.structure = structure
---> 10     j.potential = potentials[i]
     11     j.calc_minimize(pressure=0.0)
     12 

~/git_projects/pyiron_atomistics/pyiron_atomistics/lammps/base.py in potential(self, potential_filename)
    172         if "Citations" in potential.columns.values:
    173             pot_pub_dict = {}
--> 174             for p in ast.literal_eval(potential["Citations"].values[0]):
    175                 for k in p.keys():
    176                     pot_pub_dict[k] = p[k]

~/anaconda3/lib/python3.8/ast.py in literal_eval(node_or_string)
     97                     return left - right
     98         return _convert_signed_num(node)
---> 99     return _convert(node_or_string)
    100 
    101 

~/anaconda3/lib/python3.8/ast.py in _convert(node)
     96                 else:
     97                     return left - right
---> 98         return _convert_signed_num(node)
     99     return _convert(node_or_string)
    100 

~/anaconda3/lib/python3.8/ast.py in _convert_signed_num(node)
     73             else:
     74                 return - operand
---> 75         return _convert_num(node)
     76     def _convert(node):
     77         if isinstance(node, Constant):

~/anaconda3/lib/python3.8/ast.py in _convert_num(node)
     64     def _convert_num(node):
     65         if not isinstance(node, Constant) or type(node.value) not in (int, float, complex):
---> 66             _raise_malformed_node(node)
     67         return node.value
     68     def _convert_signed_num(node):

~/anaconda3/lib/python3.8/ast.py in _raise_malformed_node(node)
     61         node_or_string = node_or_string.body
     62     def _raise_malformed_node(node):
---> 63         raise ValueError(f'malformed node or string: {node!r}')
     64     def _convert_num(node):
     65         if not isinstance(node, Constant) or type(node.value) not in (int, float, complex):

ValueError: malformed node or string: nan
```

**Steps to Reproduce**

Try to create a job with the name potential

**Further Information, Files, and Links**

I tried to iterate over all available Cu potentials and compare their lattice constants. Jobs using openkim potentials failed when lammps was called, but using the potential above it actually fails when trying to assign it. I think the reason may be that the potentials does not have a directory in pyiron/ressources/lammps/potentials/potentials_LAMMPS and therefore can't be loaded. but the same jupyter notebook worked before I had to reinstall my system.

**Comment by niklassiemer** [comment]
What are the steps to reproduce this error? I.e. where do you get the names of the Potentials from? We had some changes in the potentials to get rid of duplicated entries #1181 and this seems to be related, since the potential name does not look like a NIST one.

**Comment by Leimeroth** [comment]
I just looped over all available potentials and did a simple relaxation to compare the lattice constants. This is the code:

# Create a template job with the fcc Cu structure to list available potentials
structure = pr.create_ase_bulk("Cu", "fcc", a=3.6, cubic=True)
job = pr.create_job("Lammps", "Template")
job.structure = structure
potentials = job.list_potentials()

# Get the number of available potentials
num_potentials = len(potentials)

import numpy as np

## Use numpy arrays because we will need them for plotting anyway
potential_indices = np.linspace(0, num_potentials-1, num_potentials)
lattice_constant = np.zeros(num_potentials)

for i in range(num_potentials):
    j = pr.create_job("Lammps", f"potential_{i}") # Use the potential index within the jobname
    j.structure = structure
    ## Catch eventual errors and skip them
    try:
        j.potential = potentials[i]
        j.calc_minimize(pressure=0.0)
        j.run()
    except:
        continue
    
    try:
        final_structure = j.get_structure()
    except IndexError:
        continue
    a = np.linalg.norm(final_structure.cell[0]) # calculate the lattice constant
    lattice_constant[i] = a

**Comment by jan-janssen** [comment]
Which version of pyiron data/ pyiron do you have? 
```
conda list pyiron
```
How is the resource directory configured?
```
cat ~/.pyiron
```
In the current implementation pyiron downloads a conda package we developed in collaboration with the NIST which includes all the recent potentials. You can find those in:
```
~/anaconda3/share/pyiron
```
This requires the conda environment to be activated, so the `CONDA_PREFIX` variable is set.

**Comment by Leimeroth** [comment]
pyiron                    0.3.8              pyh9f0ad1d_0    conda-forge
pyiron-data               0.0.5                hd8ed1ab_1    conda-forge
pyiron_base               0.1.44             pyhd8ed1ab_0    conda-forge

but with current git master branches of pyiron, pyiron_atomistics, pyiron_base, pyiron_contrib, pysqa

resources is default via pyiron.install(): 
RESOURCE_PATHS = ~/pyiron/resources

~/anaconda3/share/pyiron only contains the bin folder in the lammps subdirectory and no potentials

**Comment by jan-janssen** [comment]
Can you check `~/anaconda3/share/iprpy` ?

**Comment by Leimeroth** [comment]
That contains subdirectories with json potential files. Should I add it to the resources path or copy the data from there to my resources?

**Comment by Leimeroth** [comment]
I deleted the potentials directory in  pyiron/ressources/lammps/ and it seems to find the potentials in ~/anaconda3/share/iprpy, but it still throws the error, So I assume something is wrong in the formatting of the potential file.

Also if I execute pyiron.install() it still downloads potentials into the resources, but the Parudaru directory that is present in the iprpy directory is missing, i.e. they are not the same, which is probably unintended?

**Comment by jan-janssen** [comment]
`pyiron.install()` is only necessary if you install pyiron from source or pip 
https://pyiron.readthedocs.io/en/latest/source/installation.html#download-pyiron-parameter-files

**Comment by Leimeroth** [comment]
I was just confused why the resources version downloaded with pyiron.install() differs from the one coming with the conda installation

**Comment by jan-janssen** [comment]
This should not be the case because the resources are basically copied from the conda package. But maybe try updating pyiron to 0.4.0 - I am not sure if this change was already included in 0.3.8 . Alternatively you can download 0.3.23 which was the last 0.3.X release. More details on 0.4.X can be found https://github.com/pyiron/pyiron/issues/1290

**Comment by Leimeroth** [comment]
I am using the current git master branch, maybe the potential is a duplicate and was removed in the potential_lammps directory  but forgotten in the potentials_lammps.csv file?

**Comment by jan-janssen** [comment]
Ok, I guess we were on the wrong track, as the error message already says, the citation is `np.nan` which can not be parsed. The code did not expect a potential without a citation and therefore fails, if a citation exists which is not a string. This issue is fixed in https://github.com/pyiron/pyiron_atomistics/pull/22

I created an example repository on mybinder to demonstrate this functionality: 
https://github.com/jan-janssen/pyiron_test_potentials/blob/master/test_openkim.ipynb 

It is important to mention that all the potentials provided by NIST start with the year of publication. The potentials which do not start with a year are provided by openkim, these require an additional conda package to be installed: 
https://anaconda.org/conda-forge/openkim-models 

All these requirements are installed in the mybinder environment in:
https://github.com/jan-janssen/pyiron_test_potentials/

**Comment by Leimeroth** [comment]
Fixed
