### ISSUE TITLE
ConnectionError : cannot open pyiron account

### ISSUE THREAD

**Issue by Ahmed-Aslam** [pyiron/pyiron#1294]
Hi all,
I am unable to open my pyiron account (https://localhost:8000/user/aaslam/) via chrome. 

To connect to pyiron, first I login at gatezero (ssh -x -L 8000:localhost:30000 aaslam@gatezero.rzg.mpg.de) and then at cmti (ssh -x -L 30000:localhost:30000 aaslam@cmti001.bc.rzg.mpg.de). There is no issue for these steps. However, the connection to pyiron account via browser cannot be established. 

Is anyone else facing the same issue?

**Comment by jan-janssen** [comment]
The cluster is working fine, so it seems to be a client side issue. Maybe try a different browser or restart your computer in case the port is already used by another connection. 

@muh-hassani Any further suggestions?

**Comment by muh-hassani** [comment]
@Ahmed-Aslam I am currently outside. In half an hour, I will contact you and check the log of the jupyterhub to see what the problem is.

**Comment by pmrv** [comment]
It might be possible that this double forwarding has some problems, since you are connecting the tunnel at gatezero:30000 and only then opening the other tunnel.  Did that use to work?

Try cutting out one tunnel by using the `-J` flag of `ssh` like this
```
ssh -J gatezero.rzg.mpg.de -x -L 30000:localhost:30000 aaslam@cmti001.bc.rzg.mpg.de
```

**Comment by Ahmed-Aslam** [comment]
@jan-janssen I have tried both but still not working.

**Comment by Ahmed-Aslam** [comment]
> It might be possible that this double forwarding has some problems, since you are connecting the tunnel at gatezero:30000 and only then opening the other tunnel. Did that use to work?
Yes I always connect it like this. It was working for me today in the morning as well. 
> 
> Try cutting out one tunnel by using the `-J` flag of `ssh` like this
> 
> ```
> ssh -J gatezero.rzg.mpg.de -x -L 30000:localhost:30000 aaslam@cmti001.bc.rzg.mpg.de
> ```
This gives me an error " Permission denied"
> Also check that you don't have any other forwardings still running that might block your new connections, e.g. does
> 
> ```
> pgrep -a ssh
> ```
> 
> give any ssh processes you don't recognize?
No, there is no such process.

**Comment by sudarsan-surendralal** [comment]
It could be that you are out of memory/have exceeded your file quota. Can you login through the terminal and check this?

**Comment by muh-hassani** [comment]
> 
> 
> It could be that you are out of memory/have exceeded your file quota. Can you login through the terminal and check this?

In that case, normally there will be a failed spawn message.
I guess there is an issue with Ahmed's network.

**Comment by Ahmed-Aslam** [comment]
Thank you all. It seems there was some problem with my local network. Its working now.
