### ISSUE TITLE
The old way for modification of ZVAL in the POTCAR is unavailable 

### ISSUE THREAD

**Issue by yuyuanjingxuan** [pyiron/pyiron#1295]
Hi all,

I am carrying out a vasp calculation with potentiostat method. Thus, I use `potential_file_creator` to modify the `ZVAL` of one element of a structure provided. Take an example which add 0.01e to the 1st Ne atom of `struc`. What I used to do is 

```python
from pyiron_mpie.electrochemistry.potential_ramp import potential_file_creator
Ne_new= potential_file_creator(element="Ne", charge=0.01)
struct[0] = Ne_new
```
The type of `struc` here is `pyiron_atomistics.atomistics.structure.atoms.Atoms`, while the type of `Ne_new` is `pyiron.atomistics.structure.periodic_table.ChemicalElement`.

I am confused that the code above works one month ago. However, when I run the same code today, it is unavailable.  

**pyiron Version and Platform**
python 3.7.9
pyiron 0.4.0

**What I expect**
0.01e was successfully added to the 1st Ne atom of `struc`.

**Actual Behavior**
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/atomistics/structure/atoms.py in __setitem__(self, key, value)
   2205                 el = value
   2206             else:
-> 2207                 raise TypeError("value should either be a string or a ChemicalElement.")
   2208             if el != old_el:
   2209                 new_species = np.array(self.species).copy()

TypeError: value should either be a string or a ChemicalElement.
```
Could you please tell me how to avoid the issue here? Many thanks.

**Comment by sudarsan-surendralal** [comment]
This is very strange. Can you check if

```
from pyiron_atomistics.atomistics.structure.periodic_table import ChemicalElement

print(isinstance(Ne_new, ChemicalElement)
```

returns `True`?

**Comment by yuyuanjingxuan** [comment]
Unfortunately, it returns `False` here. 
Does that means `pyiron_atomistics.atomistics.structure.periodic_table.ChemicalElement` and `pyiron.atomistics.structure.periodic_table.ChemicalElement` are not the same object?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Unfortunately, it returns `False` here.
> Does that means `pyiron_atomistics.atomistics.structure.periodic_table.ChemicalElement` and `pyiron.atomistics.structure.periodic_table.ChemicalElement` are not the same object?

Yes you are right! We have updated `pyiron.atomistics` to `pyiron_atomistics.atomistics` but unfortunately, these changes are not made in the `pyiron_mpie` repository which you use.  I've opened a pull request for this (https://github.com/pyiron/pyiron_mpie/pull/39). Can you try using this branch?

**Comment by yuyuanjingxuan** [comment]
Thanks Sudarsan. It works when I load the `refactor` branch from `pyiron_mpie`.
