### ISSUE TITLE
Conda tries to install version 0.3.8

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#1303]
**Summary**
When installing pyiron via conda version 0.3.8 is installed as default instead of version 0.4.0 or another more recent version. I am not sure if this is intended behavior to not break stuff?

**pyiron Version and Platform**

Different Ubuntu versions and derivatives

**Comment by jan-janssen** [comment]
I can not reproduce this, when I use: 
```
conda create -n mynewpyironenv pyiron
```
I get version `0.4.0`.

**Comment by Leimeroth** [comment]
Does it make a difference when using conda install -c conda-forge pyiron in the base environment?

**Comment by jan-janssen** [comment]
It is using the dependencies which already exist in the base environment, like the python version and so on. If your base environment is up to date then it should be the same.

**Comment by Leimeroth** [comment]
It's a clean installation without any packages installed yet

**Comment by jan-janssen** [comment]
After installing it is always reasonable to update the installation, as the installers usually do not include the latest versions.

**Comment by Leimeroth** [comment]
This didn't solve the issue. I also have limited information, because the problem occurred for one of our students and not me.
We also use pyiron in a lecture and it didn't automatically update past version 0.3.8 for the students when running conda update --all, but for them it helped to run conda install -c conda-forge "pyiron>=0.4.0" so we didn't look into it further.

**Comment by jan-janssen** [comment]
It would be interesting to see which other packages were updated when you installed pyiron.

**Comment by Leimeroth** [comment]
conda install -c conda-forge pyiron
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done
## Package Plan ##
  environment location: /home/marie/anaconda3
  added / updated specs:
    - pyiron
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    bcrypt-3.2.0               |   py38h497a2fe_1          44 KB  conda-forge
    dill-0.3.3                 |     pyhd8ed1ab_0          60 KB  conda-forge
    git-2.30.0                 | pl5320h014a29a_0        12.5 MB  conda-forge
    gitdb-4.0.5                |     pyhd8ed1ab_1          46 KB  conda-forge
    gitpython-3.1.12           |     pyhd8ed1ab_0         110 KB  conda-forge
    h5io-0.1.2                 |     pyh95af2a2_0          16 KB  conda-forge
    importlib_resources-5.1.0  |   py38h578d9bd_0          36 KB  conda-forge
    iprpy-data-2020.11.20      |     pyhd3deb0d_0        71.9 MB  conda-forge
    libiconv-1.16              |       h516909a_0         1.4 MB  conda-forge
    mendeleev-0.6.1            |     pyh050c7b8_0         152 KB  conda-forge
    molmod-1.4.8               |   py38h25fe258_2         1.4 MB  conda-forge
    paramiko-2.7.2             |     pyh9f0ad1d_0         135 KB  conda-forge
    perl-5.32.0                |       h36c2ea0_0        16.8 MB  conda-forge
    phonopy-2.8.1              |   py38h0b5ebd8_1         940 KB  conda-forge
    pyfiglet-0.8.post1         |             py_0         514 KB  conda-forge
    pyfileindex-0.0.5          |     pyhd8ed1ab_0           9 KB  conda-forge
    pyiron-0.3.8               |     pyh9f0ad1d_0         213 KB  conda-forge
    pyiron-data-0.0.6          |       hd8ed1ab_0          13 KB  conda-forge
    pyiron_base-0.1.45         |     pyhd8ed1ab_0         106 KB  conda-forge
    pynacl-1.4.0               |   py38h497a2fe_2         1.3 MB  conda-forge
    pysqa-0.0.14               |     pyhd8ed1ab_0          17 KB  conda-forge
    quickff-2.2.4              |     pyh9f0ad1d_3         520 KB  conda-forge
    scandir-1.10.0             |   py38h497a2fe_3          29 KB  conda-forge
    seekpath-2.0.1             |     pyh44b312d_1          51 KB  conda-forge
    smmap-3.0.5                |     pyh44b312d_0          22 KB  conda-forge
    spglib-1.16.1              |   py38h5c078b8_0         604 KB  conda-forge
    sphinxdft-data-0.0.1       |       hd8ed1ab_2        29.4 MB  conda-forge
    tamkin-1.2.6               |             py_2         3.5 MB  conda-forge
    yaff-1.4.2                 |   py38h25fe258_4         910 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       142.7 MB
The following NEW packages will be INSTALLED:
  bcrypt             conda-forge/linux-64::bcrypt-3.2.0-py38h497a2fe_1
  dill               conda-forge/noarch::dill-0.3.3-pyhd8ed1ab_0
  git                conda-forge/linux-64::git-2.30.0-pl5320h014a29a_0
  gitdb              conda-forge/noarch::gitdb-4.0.5-pyhd8ed1ab_1
  gitpython          conda-forge/noarch::gitpython-3.1.12-pyhd8ed1ab_0
  h5io               conda-forge/noarch::h5io-0.1.2-pyh95af2a2_0
  importlib_resourc~ conda-forge/linux-64::importlib_resources-5.1.0-py38h578d9bd_0
  iprpy-data         conda-forge/noarch::iprpy-data-2020.11.20-pyhd3deb0d_0
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  mendeleev          conda-forge/noarch::mendeleev-0.6.1-pyh050c7b8_0
  molmod             conda-forge/linux-64::molmod-1.4.8-py38h25fe258_2
  paramiko           conda-forge/noarch::paramiko-2.7.2-pyh9f0ad1d_0
  perl               conda-forge/linux-64::perl-5.32.0-h36c2ea0_0
  phonopy            conda-forge/linux-64::phonopy-2.8.1-py38h0b5ebd8_1
  pyfiglet           conda-forge/noarch::pyfiglet-0.8.post1-py_0
  pyfileindex        conda-forge/noarch::pyfileindex-0.0.5-pyhd8ed1ab_0
  pyiron             conda-forge/noarch::pyiron-0.3.8-pyh9f0ad1d_0
  pyiron-data        conda-forge/noarch::pyiron-data-0.0.6-hd8ed1ab_0
  pyiron_base        conda-forge/noarch::pyiron_base-0.1.45-pyhd8ed1ab_0
  pynacl             conda-forge/linux-64::pynacl-1.4.0-py38h497a2fe_2
  pysqa              conda-forge/noarch::pysqa-0.0.14-pyhd8ed1ab_0
  quickff            conda-forge/noarch::quickff-2.2.4-pyh9f0ad1d_3
  scandir            conda-forge/linux-64::scandir-1.10.0-py38h497a2fe_3
  seekpath           conda-forge/noarch::seekpath-2.0.1-pyh44b312d_1
  smmap              conda-forge/noarch::smmap-3.0.5-pyh44b312d_0
  spglib             conda-forge/linux-64::spglib-1.16.1-py38h5c078b8_0
  sphinxdft-data     conda-forge/noarch::sphinxdft-data-0.0.1-hd8ed1ab_2
  tamkin             conda-forge/noarch::tamkin-1.2.6-py_2
  yaff               conda-forge/linux-64::yaff-1.4.2-py38h25fe258_4
Proceed ([y]/n)?

**Comment by Leimeroth** [comment]
This is after installing a few dependencies like ase manually

**Comment by jan-janssen** [comment]
Ok and what do you get if you enforce `pyiron>=0.4` ?

**Comment by Leimeroth** [comment]
conda install -c conda-forge "pyiron>=0.4.0"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/linux-64::apscheduler-3.6.3-py38h578d9bd_3, conda-forge/noarch::tzlocal-2.1-pyh9f0ad1d_0
  - conda-forge/linux-64::apscheduler-3.7.0-py38h578d9bd_0, conda-forge/noarch::tzlocal-2.0.0-pydone
## Package Plan ##
  environment location: /home/marie/anaconda3
  added / updated specs:
    - pyiron[version='>=0.4.0']
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    apscheduler-3.6.3          |   py38h578d9bd_3          81 KB  conda-forge
    cftime-1.4.1               |   py38h5c078b8_0         325 KB  conda-forge
    hdf4-4.2.13                |    h10796ff_1004         951 KB  conda-forge
    jpeg-9d                    |       h36c2ea0_0         264 KB  conda-forge
    jsoncpp-1.8.4              |    hc9558a2_1002         162 KB  conda-forge
    latexcodec-2.0.1           |     pyh9f0ad1d_0          18 KB  conda-forge
    libnetcdf-4.7.4            |nompi_h56d31a8_107         1.3 MB  conda-forge
    monty-4.0.2                |     pyh9f0ad1d_0          36 KB  conda-forge
    netcdf4-1.5.5.1            |nompi_py38h1cdf482_101         559 KB  conda-forge
    palettable-3.3.0           |             py_0          86 KB  conda-forge
    plotly-4.14.3              |     pyh44b312d_0         5.9 MB  conda-forge
    pybtex-0.24.0              |   py38h578d9bd_0         309 KB  conda-forge
    pyiron-0.4.0               |     pyhd8ed1ab_0           8 KB  conda-forge
    pyiron_atomistics-0.2.2    |     pyhd8ed1ab_0         227 KB  conda-forge
    pymatgen-2020.10.20        |   py38h82cb98a_0         3.4 MB  conda-forge
    pyscal-2.10.9              |   py38hc10631b_0         263 KB  conda-forge
    retrying-1.3.3             |             py_2          11 KB  conda-forge
    ruamel.yaml-0.16.12        |   py38h497a2fe_2         167 KB  conda-forge
    ruamel.yaml.clib-0.2.2     |   py38h497a2fe_2         174 KB  conda-forge
    tabulate-0.8.7             |     pyh9f0ad1d_0          24 KB  conda-forge
    tzlocal-2.1                |     pyh9f0ad1d_0          18 KB  conda-forge
    uncertainties-3.1.5        |     pyhd8ed1ab_0          75 KB  conda-forge
    vtk-8.2.0                  | py38hf2e56f5_218        39.3 MB  conda-forge
    xorg-kbproto-1.0.7         |    h7f98852_1002          27 KB  conda-forge
    xorg-libice-1.0.10         |       h516909a_0          57 KB  conda-forge
    xorg-libsm-1.2.2           |       h470a237_5          24 KB  conda-forge
    xorg-libx11-1.6.12         |       h516909a_0         917 KB  conda-forge
    xorg-libxt-1.2.1           |       h7f98852_0         371 KB  conda-forge
    xorg-xproto-7.0.31         |    h7f98852_1007          73 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        55.1 MB
The following NEW packages will be INSTALLED:
  apscheduler        conda-forge/linux-64::apscheduler-3.6.3-py38h578d9bd_3
  cftime             conda-forge/linux-64::cftime-1.4.1-py38h5c078b8_0
  hdf4               conda-forge/linux-64::hdf4-4.2.13-h10796ff_1004
  jsoncpp            conda-forge/linux-64::jsoncpp-1.8.4-hc9558a2_1002
  latexcodec         conda-forge/noarch::latexcodec-2.0.1-pyh9f0ad1d_0
  libnetcdf          conda-forge/linux-64::libnetcdf-4.7.4-nompi_h56d31a8_107
  monty              conda-forge/noarch::monty-4.0.2-pyh9f0ad1d_0
  netcdf4            conda-forge/linux-64::netcdf4-1.5.5.1-nompi_py38h1cdf482_101
  palettable         conda-forge/noarch::palettable-3.3.0-py_0
  plotly             conda-forge/noarch::plotly-4.14.3-pyh44b312d_0
  pybtex             conda-forge/linux-64::pybtex-0.24.0-py38h578d9bd_0
  pyiron_atomistics  conda-forge/noarch::pyiron_atomistics-0.2.2-pyhd8ed1ab_0
  pymatgen           conda-forge/linux-64::pymatgen-2020.10.20-py38h82cb98a_0
  pyscal             conda-forge/linux-64::pyscal-2.10.9-py38hc10631b_0
  retrying           conda-forge/noarch::retrying-1.3.3-py_2
  ruamel.yaml        conda-forge/linux-64::ruamel.yaml-0.16.12-py38h497a2fe_2
  ruamel.yaml.clib   conda-forge/linux-64::ruamel.yaml.clib-0.2.2-py38h497a2fe_2
  tabulate           conda-forge/noarch::tabulate-0.8.7-pyh9f0ad1d_0
  tzlocal            conda-forge/noarch::tzlocal-2.1-pyh9f0ad1d_0
  uncertainties      conda-forge/noarch::uncertainties-3.1.5-pyhd8ed1ab_0
  vtk                conda-forge/linux-64::vtk-8.2.0-py38hf2e56f5_218
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.2-h470a237_5
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.12-h516909a_0
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.2.1-h7f98852_0
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007
The following packages will be UPDATED:
  jpeg                        pkgs/main::jpeg-9b-h024ee3a_2 --> conda-forge::jpeg-9d-h36c2ea0_0
  pyiron                                 0.3.8-pyh9f0ad1d_0 --> 0.4.0-pyhd8ed1ab_0
Proceed ([y]/n)?

**Comment by jan-janssen** [comment]
So what changed in `0.3.9` and later is that we were adding `pymatgen` as additional dependency. https://github.com/conda-forge/pyiron-feedstock/commit/3af3f90990c32a473907256b001d2cfb67bec8cd - which is most likely also the reason for the increasing number of dependencies in particular `apscheduler` from abinit seems to be causing an issue:

```
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/linux-64::apscheduler-3.6.3-py38h578d9bd_3, conda-forge/noarch::tzlocal-2.1-pyh9f0ad1d_0
  - conda-forge/linux-64::apscheduler-3.7.0-py38h578d9bd_0, conda-forge/noarch::tzlocal-2.0.0-pydone
```

We could remove `pymatgen` again from the list of dependencies but as they are related to one of the larger projects in our community I assume we are going to have an even tighter integration with them in the future.

**Comment by jan-janssen** [comment]
@Leimeroth I released a new build of 0.4.0 which does not require `pymatgen` can you check if this resolves the dependency issue with the conda package?

**Comment by Leimeroth** [comment]
How is that done? If I run conda install -c conda-forge "pyiron>=0.4.0" again it does not show any conflicts anymore, but I am not sure if that is the case because you fixed it or because it is installed already

**Comment by jan-janssen** [comment]
No I guess we can only see it if somebody does another fresh install.
