### ISSUE TITLE
invalid __array_struct__ when structure.plot3d() for simple bccFe

### ISSUE THREAD

**Issue by edmen-dev** [pyiron/pyiron#1305]
**Summary**
After creating a trivial bcc structure, suddenly now I get an invalid __array_struct__ error when I try to run structure.plot3d(). The same problem appears when I run Vasp with this structure.

**pyiron Version and Platform**
My pyiron_atomistics.__version__ is
'0.2.3'

**Steps to Reproduce**
This is a simple cell to reproduce this problem:
import pyiron
from pyiron import Project
pr = Project('bccFe')
structure = pr.create_structure('Fe', 'bcc', 2.77)
structure.plot3d()

**Comment by jan-janssen** [comment]
That seems to be related to the numpy update, which numpy version do you use? 
```
conda list numpy
```
For me the example works fine with the latest numpy version.

**Comment by edmen-dev** [comment]
My numpy version is:
# packages in environment at /u/system/SLES12/soft/pyiron/dev/anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.20.0           py37haa41c4c_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge

Note: you may need to restart the kernel to use updated packages.

Is not the most recent one?

**Comment by jan-janssen** [comment]
I can confirm it is broken on the cluster while it seems to be working locally. @muh-hassani Can you take a look at this?

**Comment by jan-janssen** [comment]
I have to correct myself, my pyiron branch on cmti was not up to date. @edmen-dev Can you make sure you are on the latest master branch of pyiron_atomistics in case you use your own branch. You can test it with: 
```
import pyiron_atomistics
pyiron_atomistics.__file__
```

**Comment by jan-janssen** [comment]
I can confirm that also the central version is working fine, so I assume it is related to a custom `pyiron_atomistics` version.

**Comment by edmen-dev** [comment]
I see, thanks, I'll try to look at it properly later. Just FYI, what I get from your command lines is:
'/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/__init__.py'

**Comment by jan-janssen** [comment]
@edmen-dev Can you try restarting your jupyter notebook server?

**Comment by edmen-dev** [comment]
I did and that did not fix the problem. Now I am using the central version and so everything is working again, so your confirmations was right. Working with the central version nowadays is also good enough for me.
Thanks.
