### ISSUE TITLE
Creating structures using space_group, cut, and stack

### ISSUE THREAD

**Issue by zendegani** [pyiron/pyiron#1307]
Following today pyiron meeting, I've attached a simple code to create [Confined Basal Defect](https://www.sciencedirect.com/science/article/abs/pii/S135964541930727X) in C14 Laves phase.
Construction of the Laves and Mu phases requires a package that supports `spacegroup`, e.g. `ASE`.
Also cutting and stacking the atomic layers are required.
Eventually, I convert the structure with `ase_to_pyiron` to a pyiron object.
It would be nice to have these features directly within pyiron. 

```python
from pyiron import ase_to_pyiron
from ase.spacegroup import crystal
from ase.build import cut, stack


el1, el2 = 'Fe', 'Nb'

a_c14, c_c14 = 4.77, 7.78
ase_c14 = crystal(2*[el1]+[el2], basis=[(0,0,0),(0.1697,0.3394,.25),(1/3.,2/3.,.5629)], 
                  spacegroup=194, cellpar=[a_c14, a_c14, c_c14, 90., 90., 120.])

a_mu, c_mu =  a_c14, 26.78
ase_mu = crystal(2*[el1]+3*[el2], 
                 basis=[(0,0,0.5),(0.5,0.5,0.09),(0.,0.,0.05),(0.,0.,0.154),(0.,0.,1/3.)],
                 spacegroup=166, cellpar=[a_mu, a_mu, c_mu, 90., 90., 120.])

# cut out the required layers
ase_mu_cross = cut(ase_mu, (1, 0, 0), (0, 1, 0), origo=(0, 0, .29), nlayers=3)
ase_lower = cut(ase_c14, (1, 0, 0), (0, 1, 0), nlayers=7)
ase_upper = cut(ase_c14.repeat((1,1,2)), (1, 0, 0), (0, 1, 0), origo=(0, 0, .1), nlayers=13)

#stacking the layers
ase_stack_low_mid = stack(ase_lower,ase_mu_cross, distance=2.5)
ase_stack_whole = stack(ase_stack_low_mid,ase_upper, distance=2.5)
cbd = ase_to_pyiron(ase_stack_whole).repeat((3,3,2))
cbd.plot3d()
```

**Comment by pmrv** [comment]
From my side, all we really want to do is add `crystal`, `cut`, and `stack` to the [StructureFactory](https://github.com/pyiron/pyiron_atomistics/blob/859dec1f2d027b51676726c8670e599c5a81b487/pyiron_atomistics/atomistics/structure/factory.py#L50), otherwise this looks good enough, imo.

**Comment by zendegani** [comment]
Ok, I'll add three methods to wrap `crystal`, `cut`, and `stack`. I'll probably name them as `ase_crystal`, `ase_cut`, and `ase_stack`.

**Comment by niklassiemer** [comment]
You can also already convert `ase_c14` and `ase_mu` to pyiron with `ase_to_pyiron` before using  `cut` and `stack`, however, this is an additional line at the moment (as long as we do not have the changes in pyiron). Since `cut` and `stack` are working for our atoms class, `ase_crystal` should return a pyiron atoms object like we do it for the other functions.

**Comment by liamhuber** [comment]
I am not yet convinced, but I want to throw the idea out there: perhaps we should have an `ase` subdomain for the factory. ie

```python
pr.create.structure.ase.bulk(...)
pr.create.structure.ase.crystal(...)
pr.create.structure.ase.cut(...)
pr.create.structure.ase.read(...)
```

this would then be in contrast to something like 

```python
pr.create.structure.aimsgb.gb(...)
```

**Comment by pmrv** [comment]
Not sure if we want to make our dependencies that explicit?  I'd just call them

```python
pr.create.structure.bulk(...)
pr.create.structure.crystal(...)
pr.create.structure.cut(...)
pr.create.structure.read(...)
```

and pretend their ours, since they work with pyiron `Atoms`.

**Comment by samwaseda** [comment]
I would side with @pmrv. If there's an explicit ase dependency, I think it should behave like ase, i.e. `ase.build.bulk` and not `ase.bulk`.

**Comment by niklassiemer** [comment]
I like the idea of just using `cut` and `stack` as the names (stating this is the same as `ase.build.cut` in the Docstring similar to our `ase_read`). However, for `crystal` we already have an internal version. Do we plan to replace that?

**Comment by zendegani** [comment]
@niklassiemer  The current [crystal](https://github.com/pyiron/pyiron_atomistics/blob/859dec1f2d027b51676726c8670e599c5a81b487/pyiron_atomistics/atomistics/structure/factory.py#L155) method is the one that is used as `pr.create_structure()`. 
Not easy to replace and not necessary to do so. That is the reason I wanted to name the wrapper method as `ase_crystal` similar to what you mentioned about `ase_read`.

**Comment by zendegani** [comment]
I myself prefer a subdomain for `ase` as @liamhuber suggested rather than wrapping `ase` methods.
So far there are three suggestions about how the subdomain should look like:
@liamhuber 
```python
pr.create.structure.ase.bulk(...)
```
@pmrv 
```python
pr.create.structure.bulk(...)
```
@samwaseda 
```python
pr.create.structure.ase.build.bulk(...)
```
I think each of these has its own cons and pros. 
For example, `pr.create.structure.bulk(...)` does not make it clear what is behind the hood. 
As long as it depends on `ase`, I think it should express it explicitly similar to either of the other choices.
I am not sure if it is necessary to have a full domain as `pr.create.structure.ase.build.bulk(...)`, because for example, the user should not look for a DFT calculator of `ase` under `pr.create.structure.ase.`.
If only the structure related methods of `ase` should be available under `pr.create.structure.ase.` then there is no harm to have it as `pr.create.structure.ase.bulk(...)` rather than `pr.create.structure.ase.build.bulk(...)`, because it is shorter and more practical.

**Comment by samwaseda** [comment]
> @samwaseda
> 
> ```python
> pr.create.structure.ase.build.bulk(...)
> ```

No, I'm not pushing for this. I'm saying I prefer `pr.create.structure.ase.build.bulk` to `pr.create.structure.ase.bulk`, but my first choice would be what @pmrv suggests.

**Comment by liamhuber** [comment]
So from the isolated perspective of a user, I am totally on board that `pr.create.structure.bulk` is the nicest. However, from a wider dev perspective I have an ethical concern about properly attributing credit. The closer our method is to a straight port of their function (and `ase_bulk` is literally just `ase_to_pyiron(ase.bulk.build)`!!!) the less comfortable I am excluding the ASE name.

I would suggest then that we be intentional and consistent in including the source package (either `...structure.ase.bulk` or `...structure.ase_bulk`). We might also consider whether we want to group first by function or first by source, i.e. `ase_bulk` vs `bulk_ase`. But here I lean to the existing form of grouping first by source. 

This PR doesn't need to go back and re-name things it wouldn't otherwise touch, but it would be stellar to decide a format here and have this PR be the first that official adheres to it. (And maybe include the format in the factory module-level docstring for future devs to read!)

**Comment by pmrv** [comment]
From the meeting we want two functions

```
pr.create.structure.bulk
pr.create.structure.ase.bulk
```

where former just calls the later and says so in its docstring.  If we ever want to change bulk generation the `bulk` function will stay compatible and remap the arguments to whatever replacement we decide on.  `ase.bulk` should then be the exact ASE interface.

So the `ase.build` would live in a class like this

```python
class ASE:
  def bulk(*args, **kwargs):
    ase.build.bulk(*args, **kwargs)
```
