### ISSUE TITLE
from pyiron_atomistics.project import Project does not work

### ISSUE THREAD

**Issue by Alaukiksaxena** [pyiron/pyiron#1329]
When importing pyiron the following error shows up:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

The error can be traced back to `from pyiron_atomistics.project import Project `

Pyiron version is 0.1

**Comment by jan-janssen** [comment]
Does this happen on your local computer or the cmti cluster?

**Comment by Alaukiksaxena** [comment]
on cmti cluster

**Comment by jan-janssen** [comment]
@muh-hassani Can you take a look at this? It seems the current numpy version on cmti is broken.

**Comment by jan-janssen** [comment]
@Alaukiksaxena I tired to reproduce the error and for me everything worked fine. Can you check if the error remain?

**Comment by muh-hassani** [comment]
I can not also reproduce the error. Nevertheless, I updated numpy.

**Comment by Alaukiksaxena** [comment]
![image](https://user-images.githubusercontent.com/48807758/112769110-a6b1fb00-901f-11eb-9638-498518bc280b.png)
**Yes**  I still get the error.

**Comment by Alaukiksaxena** [comment]
Today, at noon I installed Keras and tensor flow.  Can that be the reason? 
Then, I uninstalled these packages, but I still get this error.

**Comment by Alaukiksaxena** [comment]
My numpy version was 1.19.5

Now, I upgraded it to 1.20.2
Now, Everything works fine.

Thank you @jan-janssen  and @muh-hassani

**Comment by jan-janssen** [comment]
> Today, at noon I installed Keras and tensor flow. Can that be the reason?
> Then, I uninstalled these packages, but I still get this error.

What do you mean by ` I installed Keras and tensor flow` ? via pip to your home directory? If you need a package to be installed on the cluster please contact @muh-hassani . Installing to your home directory is highly error-prone. But I would like to understand how exactly you installed the package because it should basically be disabled by default.

**Comment by Alaukiksaxena** [comment]
Yes, I installed them using pip to my home directory.
pip install Keras
pip install tensorflow
(It was not disabled, I was able to install these packages.)

In the future, I will contact @muh-hassani  to install any new packages.

**Comment by jan-janssen** [comment]
@muh-hassani previously we had the scripts in:
```
/u/system/SLES12/soft/pyiron/dev/anaconda3/bin/pip
/u/system/SLES12/soft/pyiron/dev/anaconda3/bin/pip3
``` 
overwritten with a print statement to contact the administrator to prevent this kind of issues. It seems those files were removed during an update.

**Comment by muh-hassani** [comment]
> 
> 
> @muh-hassani previously we had the scripts in:
> 
> ```
> /u/system/SLES12/soft/pyiron/dev/anaconda3/bin/pip
> /u/system/SLES12/soft/pyiron/dev/anaconda3/bin/pip3
> ```
> 
> overwritten with a print statement to contact the administrator to prevent this kind of issues. It seems those files were removed during an update.
I will try to fix it.

**Comment by muh-hassani** [comment]
> overwritten with a print statement to contact the administrator to prevent this kind of issues. It seems those files were removed during an update.

I can still find `pip` and `pip3` in `/u/system/soft/pyiron/dev/anaconda3/bin`. 
```
-rwxr-xr-x 1 smrhassani mpd 264 Feb  2 21:03 pip
-rwxr-xr-x 1 smrhassani mpd 264 Feb  2 21:03 pip3
```
I think a possible solution would be to remove the execute right for others, using:
```
chmod 754 pip
chmod 754 pip3
```
