### ISSUE TITLE
using Mendeleev module 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#1330]
**Summary**

perviously I used Mendeleev module to plot periodic table as color code but new I can not import `get_table`
**pyiron Version and Platform**
 latest version on cluster

**Expected Behavior**
my code is like below:
```
from mendeleev import get_table
from mendeleev.plotting import periodic_plot
ptable = get_table('elements')
periodic_plot(ptable)
```
I expecting to plot color code periodic table 

**Actual Behavior**

it is said:
cannot import name 'get_table' from 'mendeleev'

I was wondering to know this class get changed? or there is bug inside ?

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by jan-janssen** [comment]
I do not see that this is a `pyiron` related issue. Still the solution is: 

```
from mendeleev.fetch import fetch_table
from mendeleev.plotting import periodic_plot
ptable = fetch_table('elements')
periodic_plot(ptable)
```

**Comment by jan-janssen** [comment]
You can find an example notebook here https://github.com/lmmentel/mendeleev/blob/master/docs/source/notebooks/plotting.ipynb
