### ISSUE TITLE
ValueError: Was not able to locate a periodic table.while running notebook on jupyter server.  it is running smoothly on my local machine.

### ISSUE THREAD

**Issue by vijjubhuva** [pyiron/pyiron#1331]
Hello everyone!

i have found this error, when i run my jupyter notebook on jupyter server. Everything is running smooth on my local machine, but this only trouble, when i run my notebook on jupyter server.
is there any different path, i need to set up on jupyter server's ./bashrc and ~./pyiron? 

*/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/atomistics/structure/periodic_table.py in _get_periodic_table_df(file_name)
    389                                 os.path.join(path, periodic_table_file_name), mode="r"
    390                             )
--> 391             raise ValueError("Was not able to locate a periodic table. ")
    392         else:
    393             if file_name.endswith(".h5"):

ValueError: Was not able to locate a periodic table.

**Comment by liamhuber** [comment]
Hi Vijay,

> is there any different path, i need to set up on jupyter server's ./bashrc and ~./pyiron?

Yep, you need to set your `RESOURCE_PATHS` variable in `~/.pyiron`.

I'm super happy to see this question asked on github, but I'm actually going to answer it by e-mail 😝 It is CMTI-specific path information. Ideally this question would get asked over at eisenforschung/pyiron-resources-mpie, or eisenforschung/pyiron-config-mpie. But *a priori* it's very fair that you asked it here instead, and unfortunately I can't simply transfer issues between organizations. 

I'll send the path privately, but let me know here if that worked for you and hopefully we can close the issue.

**Comment by vijjubhuva** [comment]
Thank you dear Liam!
