### ISSUE TITLE
What is the best way to update a VASP calculation result which is already imported via import_from_path?

### ISSUE THREAD

**Issue by gongyilun** [pyiron/pyiron#1338]
What is the best way to update a VASP calculation result which is already imported via import_from_path?

**Comment by sudarsan-surendralal** [comment]
If there are no other jobs (apart from the ones you've imported) in your project, you can use `pr.remove_jobs(recursive=True)`. The re-import them.

**Comment by jan-janssen** [comment]
I close this issue as it is not updated for more than three month.
