### ISSUE TITLE
Still cannot access JupyterHub

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1351]
**Summary**
I still cannot access JupyterHub. It always shows as the following two pictures. Can anyone who has solved this problem give me some suggestions? Thanks a lot in advance.

<img width="1440" alt="Screen Shot 2021-07-07 at 08 29 29" src="https://user-images.githubusercontent.com/57641389/124712298-6f48c980-deff-11eb-82ae-86537cbd7458.png">
<img width="1440" alt="Screen Shot 2021-07-07 at 08 29 08" src="https://user-images.githubusercontent.com/57641389/124712304-71128d00-deff-11eb-838d-d89e868d75f4.png">

**pyiron Version and Platform**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by muh-hassani** [comment]
@lfzhu-phys, many other users do not have any issues. I have stopped your server. Can you please once again connect to the server?

**Comment by lfzhu-phys** [comment]
@muh-hassani Thanks. I just tried. It repeats the two pictures I attached. I also tried to quit the terminal and log in again. It still says "503: service unavailable."

**Comment by muh-hassani** [comment]
@lfzhu-phys can you retry now?

**Comment by lfzhu-phys** [comment]
@muh-hassani Great, it works now. Thank you very much.

**Comment by muh-hassani** [comment]
@lfzhu-phys, for my curiosity, did you kill any python processes as was suggested in my email yesterday?

**Comment by lfzhu-phys** [comment]
@muh-hassani  Yes, yesterday I killed all process by top. How did you fix this?

**Comment by muh-hassani** [comment]
Instead of you starting your server. I killed it and started it as the admin.
