### ISSUE TITLE
Request setting the working directory of job

### ISSUE THREAD

**Issue by yuyuanjingxuan** [pyiron/pyiron#1362]
**Summary** and **Detailed Description**
Hi all,

I am performing a series of long-trajectory MD simulations. Generally, each of the calculation includes over 100,000 snapshots. So the output file is huge (~20-30GB). Due to the limited quota of home directory, once they are over the budget, all my jobs will crash. To avoid the issue, I was wondering if it is possible that when I submit the job, I could set the working directory to `/ptmp` and keep the input file in the home directory. 

If pyiron does not support it yet, would it be considered as a new feature for a future version?

**Further Information, Files, and Links**
None

**pyiron Version and Platform**
python 3.7.9
pyiron 0.4.4

**Comment by jan-janssen** [comment]
You can create a symbolic link from your home directory to `ptmp` and then run your simulation there.

**Comment by pmrv** [comment]
But be aware this likely means you projects won't be backed up anymore, right?  You could always run on ptmp and then move the project back to a normal folder, but there's currently bugs that might make this a bit tricky, [here](https://github.com/pyiron/pyiron_base/issues/348) and [here](https://github.com/pyiron/pyiron_base/issues/350).

**Comment by yuyuanjingxuan** [comment]
@jan-janssen and @pmrv Thank you for your suggestions and it works for me.  But actually I just want to put big calculations to /ptmp instead of all my calculations. What I did currently is to created the job first. Then move the hdf5 directory to /ptmp and leave a symbolic link to the home directory. Do you know if there is an easy way to realise it?
