### ISSUE TITLE
Job type without `run`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1364]
It's about a job type that I'm developing in `pyiron_continuum`, but since it could apply to other jobs, I wanted to ask this question here.

I have a job type which should work as follows:

```python
job = pr.create.job.Elasticity('elast')
job.input.elastic_tensor = elastic_tensor
job.get_strain_field(positions)
```

As you can see in the lines above, there's no `run`. Of course I could create a `run`, which could look like this:

```python
job = pr.create.job.Elasticity('elast')
job.input.elastic_tensor = elastic_tensor
job.input.positions = positions
job.run()
job.output.strain_field
```

This, however, not only makes the code longer, but it will store data that I don't need, especially regarding the fact that it's not just `strain_field` that I might need, but I might need things like `greens_function` (the function itself and maybe also the second derivative), `displacement_field`, the Fourier transforms of these ones, maybe for isotropic and anisotropic cases separately etc. For all this, I would rather have a function each time, so that rather than calling `run` and storing useless data, I'd do a simple single step such as `job.get_greens_function(positions, second_derivative=True, fourier_transform=False, anisotropic=True)` etc., which is probably anyway nearly as fast as having it from `job.output`.

Suggestions?

P.S.
In my specific case I can also imagine something like `ElasticMedium`, which would be equivalent to `Atoms`, which takes elastic constants as an input instead of positions, i.e.:

```python
medium = pr.create.ElasticMedium(elastic_tensor=elastic_tensor)
medium.get_strain(positions)
```

but I don't know how generally used such a structure would be.

**Comment by niklassiemer** [comment]
The nice thing about the `run` is that is integrated in our normal setup of saving the job in the database, checking if the job is running, reloading the job if it already has been run, etc. However, I do well understand why one would like to get rid of the `run` method in user interactions. E.g. in https://github.com/pyiron/pyiron_contrib/pull/205 I try to have an 'always running' storage site where I use the interactive mode and, thus, implement `_run_if_interactive()` to write interesting things to the hdf. 
If your Job is only a python object, which does not store e.g. the positions (and does not need a db connection) and just provides methods to compute some properties given some positions this would not be a JobType within the pyiron framework imho.

**Comment by pmrv** [comment]
Agree with the direction of @niklassiemer, maybe the best would be something like `pr.create.continuum.elastic_medium()` that just returns a plain python object.

**Comment by samwaseda** [comment]
ok what @pmrv says is probably 100% equivalent to what I wrote in P.S. and hopefully it satisfies what @niklassiemer says. I guess then I'm gonna go indeed for `pr.create.continuum`.

Shouldn't we actually then have `pr.create.atoms` instead of `pr.create.structure`?

**Comment by pmrv** [comment]
> Shouldn't we actually then have `pr.create.atoms` instead of `pr.create.structure`?

I'd like that but we also have `pr.create.structure.atoms`, so `pr.create.atoms.atoms` is maybe a bit weird.

**Comment by samwaseda** [comment]
Hmmm ok. I'm personally okay with `pr.create.atoms.atoms` since I also get the impression that it emphasises the fact that it creates individual atoms, but anyway since my problem has been solved I close this issue for now.
