### ISSUE TITLE
Can't establish a secure connection to the server "localhost"  for Jupyterhub

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1372]
I try to log in the cluster using:
ssh -x -L 30000:localhost:30000 username@cmti001.bc.rzg.mpg.de

The error message is:
-------------------------
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 30000
Could not request local forwarding.
--------------------------

Therefore, I cannot create a connection to the JupyterHub. 

It happens quite often. Sometimes it just automatically works again.

Can anyone give me some suggestions to solve this?

Thank you very much in advance.

**Comment by raynol-dsouza** [comment]
Hi Lifang,

Can you try:

`ssh -x -L 8000:localhost:30000 <username>@cmti001.bc.rzg.mpg.de`

This works for me.

**Comment by lfzhu-phys** [comment]
Hi Raynol,

Thanks. As I am connecting from home, I normally do the following:
ssh -x -L 8000:localhost:30000 user@gatezero.rzg.mpg.de
ssh -x -L 30000:localhost:30000 use@cmti001.bc.rzg.mpg.de

The problem appears when I do the second connecting. Do you have any experience for this?

**Comment by raynol-dsouza** [comment]
> ssh -x -L 8000:localhost:30000 user@gatezero.rzg.mpg.de

I usually login to the institute VPN and then use `ssh -x -L 8000:localhost:30000 user@cmti001.bc.rzg.mpg.de`

Does using `ssh -x -L 8000:localhost:30000 user@gatezero.rzg.mpg.de` first and then `ssh -x -L 8000:localhost:30000 user@cmti001.bc.rzg.mpg.de` work?

**Comment by lfzhu-phys** [comment]
Hi Raynol,

Thanks a lot for your suggestion:)

It works:
Login to VPN and then use ssh -x -L 8000:localhost:30000 user@cmti001.bc.rzg.mpg.de

But it doesn't work using:
ssh -x -L 8000:localhost:30000 user@gatezero.rzg.mpg.de, then
ssh -x -L 8000:localhost:30000 user@cmti001.bc.rzg.mpg.de.

Thanks again:)

**Comment by pmrv** [comment]
When trying to bridge over the gate machine of mpcdf, I'd recommend letting ssh do all the work for you, like this
```bash
ssh -J user@gatezero.rzg.mpg.de -f -N  -L 8000:127.0.0.1:30000 user@cmti001.bc.rzg.mpg.de
```
`-J` tells ssh to connect the specified host first and only from there to the final destination.

The error message says that the port you're requesting is already in use, so I guess you already have a port forwarding running on either your local machine or the gate machine (probably from the last time you ran these commands).  You can check with 
```bash
netstat | grep ssh
```
or
```
ssh -O check user@host
```
whether you have an existing ssh connection running.  (No output or error means no, otherwise it's already running).

**Comment by raynol-dsouza** [comment]
@lfzhu-phys glad that it works! There are instructions [here](https://github.com/eisenforschung/cm-onboarding/blob/master/Cluster.md#connect-to-the-cluster), but the links there seem to be outdated.

@pmrv Nice! I did not know this. gatezero often connected first and kicked me out at a random time, and so I switched to using the institute VPN.

**Comment by lfzhu-phys** [comment]
@pmrv Yes, this is the problem I am aware of, but don't have a clear solution for a long time (even I have tried a few commands from the online suggestions, but a little bit worried that they will mess up the cluster:))

Thanks a lot for the clear solution.

**Comment by lfzhu-phys** [comment]
@raynol-dsouza Thanks Raynol for the information. I will look into the instructions.
