### ISSUE TITLE
VASP Queue Configuration 

### ISSUE THREAD

**Issue by sinazadeh** [pyiron/pyiron#1379]
**Problem:**
The submitted jobs will abort a few seconds after submitting in the queue using pyiron.

**Steps:**
In the server that our institute uses, we use following .sh file to submit job in the queue:

```
#!/bin/bash
#SBATCH -J JobName               #Job Name (JobName)
#SBATCH -t 1:00:00               #Wall time h:m:s (1 hour)
#SBATCH -N 2                     #Number of nodes (2 nodes)
#SBATCH --ntasks-per-node=48     #Cores per node (48 cores per node)
#SBATCH --mem=324G               #Memory per node (324 GB of memory per node)
#SBATCH -o JobName.o%j           #standard output file (JobName.ojobnumber)
#SBATCH -e JobName.e%j           #standard error file (JobName.ejobnumber)

ml purge                         # purge all modules to start with a clean environment
# load the appropriate vasp module with the dependencies listed first (ie intel/2020a)
ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
ml list                          # list the modules currently loaded to have a record of the loaded modules
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun vasp_std                       # run the standard version of vasp (vasp_std)
```
In order to configure pyiron to use vasp, I created a .sh files in the following path:
pyiron/resources/vasp/bin/
run_vasp_5.4.4_default.sh:
```
#!/bin/bash
srun vasp_std
```
After that, I created two files in the following path:
pyiron/resources/queues/
queue.yaml
```
queue_type: SLURM
queue_primary: slurm
queues:
  slurm: {script: slurm.sh}

```
slurm.sh
```
#!/bin/bash
#SBATCH -J JobName               #Job Name (JobName)
#SBATCH -t 1:00:00               #Wall time h:m:s (1 hour)
#SBATCH -N 2                     #Number of nodes (2 nodes)
#SBATCH --ntasks-per-node=48     #Cores per node (48 cores per node)
#SBATCH --mem=324G               #Memory per node (324 GB of memory per node)
#SBATCH -o time.o%j           #standard output file (JobName.ojobnumber)
#SBATCH -e time.e%j           #standard error file (JobName.ejobnumber)

{{command}}

```
After running the following code, the status of job changes from submitted to aborted
```
pr = Project(path="prj")
basis = pr.create_ase_bulk('Fe', cubic=True)
job = pr.create_job(
        job_type=pr.job_type.Vasp,
        job_name='Element')
job.structure = basis
job.server.queue = job.server.list_queues()[-1]
job.executable.version =job.executable.available_versions[0]
job.run()
```

**Comment by pmrv** [comment]
I think you just forgot to load the appropriate `ml` commands to configure the environment in your `pyiron/resources/vasp/bin/
run_vasp_5.4.4_default.sh`. 

Pyiron basically just runs the code specific shell script from within `queue.sh` script, so if your codes needs additional cluster modules (like your version of VASP), you'll need to enable them somewhere and the run script is the best location for that.

Please also post the stdout/stderr you get from the aborted jobs, if any.

**Comment by sinazadeh** [comment]
> I think you just forgot to load the appropriate `ml` commands to configure the environment in your `pyiron/resources/vasp/bin/ run_vasp_5.4.4_default.sh`.
> 
> Pyiron basically just runs the code specific shell script from within `queue.sh` script, so if your codes needs additional cluster modules (like your version of VASP), you'll need to enable them somewhere and the run script is the best location for that.
> 
> Please also post the stdout/stderr you get from the aborted jobs, if any.

Thank you for your comment. I changed run_vasp_5.4.4_default.sh file to this:
```
#!/bin/bash
ml purge
ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
srun vasp_std
```
But still the same problem. The only way that I can run VASP through pyiron is by changing slurm.sh to:

```
#!/bin/bash
#SBATCH -J JobName               #Job Name (JobName)
#SBATCH -t 1:00:00               #Wall time h:m:s (1 hour)
#SBATCH -N 2                     #Number of nodes (2 nodes)
#SBATCH --ntasks-per-node=48     #Cores per node (48 cores per node)
#SBATCH --mem=324G               #Memory per node (324 GB of memory per node)
#SBATCH -o JobName.o%j           #standard output file (JobName.ojobnumber)
#SBATCH -e JobName.e%j           #standard error file (JobName.ejobnumber)

ml purge                         # purge all modules to start with a clean environment
# load the appropriate vasp module with the dependencies listed first (ie intel/2020a)
ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
ml list                          # list the modules currently loaded to have a record of the loaded modules
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun vasp_std                
```
The problem is if I do so, job status in VASP wont update and always says submitted.
The aborted job:
```
     id   status chemicalformula      job    subjob          projectpath  \
0  6293  aborted             Fe2  Element  /Element  /scratch/user/sina/   

            project                  timestart                   timestop  \
0  phononpy_proj38/ 2021-11-01 08:18:44.306796 2021-11-01 08:18:44.340935   

   totalcputime                     computer hamilton     hamversion parentid  \
0           0.0  pyiron@c501.cluster#1#slurm     Vasp  5.4.4_default     None   

  masterid  
0     None  
```
I ran test_pyiron_installation.ipynb and here is the results:
```
import sys
sys.platform
'linux'
```
```
from pyiron_base import Settings
s = Settings()
s._configuration
{'user': 'pyiron',
 'resource_paths': ['/home/sina/pyiron/resources',
  '/scratch/user/sina/.conda/envs/pyironenv/share/pyiron',
  '/scratch/user/sina/.conda/envs/pyironenv/share/iprpy'],
 'project_paths': ['/scratch/user/sina/'],
 'connection_timeout': 60,
 'sql_connection_string': 'sqlite:////home/sina/pyiron/resources/pyiron.db',
 'sql_table_name': 'jobs_pyiron',
 'sql_view_connection_string': None,
 'sql_view_table_name': None,
 'sql_view_user': None,
 'sql_view_user_key': None,
 'sql_file': '/home/sina/pyiron/resources/pyiron.db',
 'sql_host': None,
 'sql_type': 'SQLite',
 'sql_user_key': None,
 'sql_database': None,
 'project_check_enabled': True,
 'disable_database': False}
```
```
! conda list pyiron

# packages in environment at /scratch/user/sina/.conda/envs/pyironenv:
#
# Name                    Version                   Build  Channel
pyiron                    0.4.5              pyhd8ed1ab_0    conda-forge
pyiron-data               0.0.17               hd8ed1ab_0    conda-forge
pyiron_atomistics         0.2.26             pyhd8ed1ab_0    conda-forge
pyiron_base               0.3.6              pyhd8ed1ab_0    conda-forge
pyiron_contrib            0.1.0              pyhd8ed1ab_0    conda-forge
```

**Comment by sinazadeh** [comment]
I also changed the permissions of all three files (run_vasp_5.4.4_default.sh / queue.yaml
 / slurm.sh  ) from 644 to 777 but it didn't solve the problem.

**Comment by sinazadeh** [comment]
@jan-janssen If you have any thoughts on this I would appreciate it.

**Comment by pmrv** [comment]
> > I think you just forgot to load the appropriate `ml` commands to configure the environment in your `pyiron/resources/vasp/bin/ run_vasp_5.4.4_default.sh`.
> > Pyiron basically just runs the code specific shell script from within `queue.sh` script, so if your codes needs additional cluster modules (like your version of VASP), you'll need to enable them somewhere and the run script is the best location for that.
> > Please also post the stdout/stderr you get from the aborted jobs, if any.
> 
> Thank you for your comment. I changed run_vasp_5.4.4_default.sh file to this:
> 
> ```
> #!/bin/bash
> ml purge
> ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
> srun vasp_std
> ```
> 
> OR
> 
> ```
> #!/bin/bash
> ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
> srun vasp_std
> ```

From you working script below, it seems you also need `export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so` inside the run script.

> 
> But still the same problem. The only way that I can run VASP through pyiron is by changing slurm.sh to:
> 
> ```
> #!/bin/bash
> #SBATCH -J JobName               #Job Name (JobName)
> #SBATCH -t 1:00:00               #Wall time h:m:s (1 hour)
> #SBATCH -N 2                     #Number of nodes (2 nodes)
> #SBATCH --ntasks-per-node=48     #Cores per node (48 cores per node)
> #SBATCH --mem=324G               #Memory per node (324 GB of memory per node)
> #SBATCH -o JobName.o%j           #standard output file (JobName.ojobnumber)
> #SBATCH -e JobName.e%j           #standard error file (JobName.ejobnumber)
> 
> ml purge                         # purge all modules to start with a clean environment
> # load the appropriate vasp module with the dependencies listed first (ie intel/2020a)
> ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
> ml list                          # list the modules currently loaded to have a record of the loaded modules
> export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
> srun vasp_std                
> ```
> 
> The problem is if I do so, job status in VASP wont update and always says submitted.

I assume you made sure that the job is also listed by SLURM as submitted and eventually run.  If so, it sounds like pyiron is encountering an error as it starts executing the run script, just before it can update the job status.  This error should end up in `pyiron.log` (in the folder from where you run your pyiron notebook/script) or in the redirected output files from SLURM, `JobName.e%j`/ `JobName.o%j`.  Can you post the contents of these files?


> I ran test_pyiron_installation.ipynb and here is the results:
> 
> ```
> import sys
> sys.platform
> 'linux'
> ```
> 
> ```
> from pyiron_base import Settings
> s = Settings()
> s._configuration
> {'user': 'pyiron',
>  'resource_paths': ['/home/sina/pyiron/resources',
>   '/scratch/user/sina/.conda/envs/pyironenv/share/pyiron',
>   '/scratch/user/sina/.conda/envs/pyironenv/share/iprpy'],
>  'project_paths': ['/scratch/user/sina/'],
>  'connection_timeout': 60,
>  'sql_connection_string': 'sqlite:////home/sina/pyiron/resources/pyiron.db',
>  'sql_table_name': 'jobs_pyiron',
>  'sql_view_connection_string': None,
>  'sql_view_table_name': None,
>  'sql_view_user': None,
>  'sql_view_user_key': None,
>  'sql_file': '/home/sina/pyiron/resources/pyiron.db',
>  'sql_host': None,
>  'sql_type': 'SQLite',
>  'sql_user_key': None,
>  'sql_database': None,
>  'project_check_enabled': True,
>  'disable_database': False}
> ```
> 
> ```
> ! conda list pyiron
> 
> # packages in environment at /scratch/user/sina/.conda/envs/pyironenv:
> #
> # Name                    Version                   Build  Channel
> pyiron                    0.4.5              pyhd8ed1ab_0    conda-forge
> pyiron-data               0.0.17               hd8ed1ab_0    conda-forge
> pyiron_atomistics         0.2.26             pyhd8ed1ab_0    conda-forge
> pyiron_base               0.3.6              pyhd8ed1ab_0    conda-forge
> pyiron_contrib            0.1.0              pyhd8ed1ab_0    conda-forge
> ```

Thanks for posting this, it seems the installation is fine.

**Comment by sinazadeh** [comment]
Thank you for your time. 
Outputs:
```
2021-11-02 10:03:18,784 - pyiron_log - INFO - run job: Element id: None, status: initialized
2021-11-02 10:03:18,784 - pyiron_log - INFO - run job: Element id: None, status: initialized
2021-11-02 10:03:19,560 - pyiron_log - INFO - run job: Element id: 6433, status: created
2021-11-02 10:03:19,560 - pyiron_log - INFO - run job: Element id: 6433, status: created
2021-11-02 10:03:20,157 - pyiron_log - INFO - job: Element id: 6433, status: submitted, submitted: queue id 1746979
2021-11-02 10:03:20,157 - pyiron_log - INFO - job: Element id: 6433, status: submitted, submitted: queue id 1746979

```
JobName.e1746979

```
Currently Loaded Modules:
  1) GCCcore/9.3.0         6) UCX/1.8.0
  2) zlib/1.2.11           7) intel/2020a
  3) binutils/2.34         8) impi/2019.7.217
  4) iccifort/2020.1.217   9) vasp/5.4.4.pl2-vtst-wannier-beef
  5) numactl/2.0.13       10) imkl/2020.1.217
```
JobName.o1746979
```
 running on   16 total cores
 distrk:  each k-point on   16 cores,    1 groups
 distr:  one band on    1 cores,   16 groups
 using from now: INCAR     
 vasp.5.4.4.18Apr17-6-g9f103f2a35 (build Jan 04 2021 18:32:27) complex          
  
 POSCAR found type information on POSCAR  Fe
 POSCAR found :  1 types and       2 ions
 scaLAPACK will be used

 ----------------------------------------------------------------------------- 
|                                                                             |
|           W    W    AA    RRRRR   N    N  II  N    N   GGGG   !!!           |
|           W    W   A  A   R    R  NN   N  II  NN   N  G    G  !!!           |
|           W    W  A    A  R    R  N N  N  II  N N  N  G       !!!           |
|           W WW W  AAAAAA  RRRRR   N  N N  II  N  N N  G  GGG   !            |
|           WW  WW  A    A  R   R   N   NN  II  N   NN  G    G                |
|           W    W  A    A  R    R  N    N  II  N    N   GGGG   !!!           |
|                                                                             |
|      For optimal performance we recommend to set                            |
|        NCORE= 4 - approx SQRT( number of cores)                             |
|      NCORE specifies how many cores store one orbital (NPAR=cpu/NCORE).     |
|      This setting can  greatly improve the performance of VASP for DFT.     |
|      The default,   NCORE=1            might be grossly inefficient         |
|      on modern multi-core architectures or massively parallel machines.     |
|      Do your own testing !!!!                                               |
|      Unfortunately you need to use the default for GW and RPA calculations. |
|      (for HF NCORE is supported but not extensively tested yet)             |
|                                                                             |
 ----------------------------------------------------------------------------- 

 LDA part: xc-table for Pade appr. of Perdew
 POSCAR found type information on POSCAR  Fe
 POSCAR found :  1 types and       2 ions
 POSCAR, INCAR and KPOINTS ok, starting setup
 FFT: planning ...
 WAVECAR not read
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1     0.949413626346E+01    0.94941E+01   -0.56278E+03   128   0.718E+02
DAV:   2    -0.183553449241E+02   -0.27849E+02   -0.27666E+02   128   0.107E+02
DAV:   3    -0.184945984443E+02   -0.13925E+00   -0.13924E+00   208   0.947E+00
DAV:   4    -0.184946106017E+02   -0.12157E-04   -0.12157E-04   128   0.871E-02
DAV:   5    -0.184946106427E+02   -0.40991E-07   -0.41585E-07   176   0.529E-03    0.124E+01
RMM:   6    -0.157806534676E+02    0.27140E+01   -0.11640E+01   140   0.389E+01    0.331E+00
RMM:   7    -0.155011354810E+02    0.27952E+00   -0.77796E-01   133   0.107E+01    0.107E+00
RMM:   8    -0.154720405971E+02    0.29095E-01   -0.19094E-02   137   0.120E+00    0.390E-01
RMM:   9    -0.154686973160E+02    0.33433E-02   -0.72404E-03   135   0.994E-01    0.329E-02
RMM:  10    -0.154687295723E+02   -0.32256E-04   -0.10192E-04    76   0.964E-02
   1 F= -.15468730E+02 E0= -.15461128E+02  d E =-.228044E-01

```

**Comment by sinazadeh** [comment]
Also, this is the completed job
![aUntitled](https://user-images.githubusercontent.com/63080674/139906470-549ab68b-384a-4bb0-9620-9c77538ce790.png)

**Comment by jan-janssen** [comment]
@sinazadeh Hi, I am sorry for the delay. There are two parts to the pyiron submission script: First the `slurm.sh` which calls the python process and then the `run_vasp_5.4.4_mpi.sh` script which calls the VASP executable. As discussed in https://pyiron.readthedocs.io/en/latest/source/installation.html#hpc-cluster-with-postgresql-database-and-jupyterhub 

The `slurm.sh` script should look something like this:
```
#!/bin/bash
#SBATCH --output=time.out
#SBATCH --job-name={{job_name}}
#SBATCH --workdir={{working_directory}}
#SBATCH --get-user-env=L
{%- if run_time_max %}
#SBATCH --time={{run_time_max // 60}}
{%- endif %}
{%- if memory_max %}
#SBATCH --mem={{memory_max}}
{%- endif %}
{%- if cores < 48 %}
#SBATCH --ntasks-per-node={{cores}}
{%- else %} 
#SBATCH --ntasks-per-node=48
{%- endif %}
#SBATCH --ntasks={{cores}}

{{command}}
``` 

The `run_vasp_5.4.4_mpi.sh` script: 
```
#!/bin/bash
ml purge
ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef

export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun -n $1 vasp_std    
```

**Comment by sinazadeh** [comment]
> @sinazadeh Hi, I am sorry for the delay. There are two parts to the pyiron submission script: First the `slurm.sh` which calls the python process and then the `run_vasp_5.4.4_mpi.sh` script which calls the VASP executable. As discussed in https://pyiron.readthedocs.io/en/latest/source/installation.html#hpc-cluster-with-postgresql-database-and-jupyterhub
> 
> The `slurm.sh` script should look something like this:
> 
> ```
> #!/bin/bash
> #SBATCH --output=time.out
> #SBATCH --job-name={{job_name}}
> #SBATCH --workdir={{working_directory}}
> #SBATCH --get-user-env=L
> {%- if run_time_max %}
> #SBATCH --time={{run_time_max // 60}}
> {%- endif %}
> {%- if memory_max %}
> #SBATCH --mem={{memory_max}}
> {%- endif %}
> {%- if cores < 48 %}
> #SBATCH --ntasks-per-node={{cores}}
> {%- else %} 
> #SBATCH --ntasks-per-node=48
> {%- endif %}
> #SBATCH --ntasks={{cores}}
> 
> {{command}}
> ```
> 
> The `run_vasp_5.4.4_mpi.sh` script:
> 
> ```
> #!/bin/bash
> ml purge
> ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
> 
> export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
> srun -n $1 vasp_std    
> ```

Thank you for your answer.
`#SBATCH --workdir={{working_directory}}`
It will crush the run_queue.
Without this line of code:
```
2021-11-03 11:56:27,854 - pyiron_log - INFO - job: vasp_0_95 id: 6471, status: submitted, run job (modal)
2021-11-03 11:56:27,903 - pyiron_log - WARNING - Job aborted
2021-11-03 11:56:27,903 - pyiron_log - WARNING - Job aborted
2021-11-03 11:56:27,903 - pyiron_log - WARNING - Job aborted
2021-11-03 11:56:27,904 - pyiron_log - WARNING - /bin/sh: /home/sina/pyiron/resources/vasp/bin/run_vasp_5.4.4_default.sh: /bin/bash^M: bad interpreter: No such file or directory

2021-11-03 11:56:27,904 - pyiron_log - WARNING - /bin/sh: /home/sina/pyiron/resources/vasp/bin/run_vasp_5.4.4_default.sh: /bin/bash^M: bad interpreter: No such file or directory
```
If I can handle this somehow, it will solve the problem.

**Comment by pmrv** [comment]
> > @sinazadeh Hi, I am sorry for the delay. There are two parts to the pyiron submission script: First the `slurm.sh` which calls the python process and then the `run_vasp_5.4.4_mpi.sh` script which calls the VASP executable. As discussed in https://pyiron.readthedocs.io/en/latest/source/installation.html#hpc-cluster-with-postgresql-database-and-jupyterhub
> > The `slurm.sh` script should look something like this:
> > ```
> > #!/bin/bash
> > #SBATCH --output=time.out
> > #SBATCH --job-name={{job_name}}
> > #SBATCH --workdir={{working_directory}}
> > #SBATCH --get-user-env=L
> > {%- if run_time_max %}
> > #SBATCH --time={{run_time_max // 60}}
> > {%- endif %}
> > {%- if memory_max %}
> > #SBATCH --mem={{memory_max}}
> > {%- endif %}
> > {%- if cores < 48 %}
> > #SBATCH --ntasks-per-node={{cores}}
> > {%- else %} 
> > #SBATCH --ntasks-per-node=48
> > {%- endif %}
> > #SBATCH --ntasks={{cores}}
> > 
> > {{command}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `run_vasp_5.4.4_mpi.sh` script:
> > ```
> > #!/bin/bash
> > ml purge
> > ml intel/2020a vasp/5.4.4.pl2-vtst-wannier-beef
> > 
> > export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
> > srun -n $1 vasp_std    
> > ```
> 
> Thank you for your answer. `#SBATCH --workdir={{working_directory}}` It will crush the run_queue.
> 
> ```
>   955             self._logger.warning("Job aborted")
>     956             self.status.aborted = True
> --> 957             raise ValueError("run_queue.sh crashed")
>     958         s.logger.debug("submitted %s", self.job_name)
>     959         self._logger.debug("job status: %s", self.status)
> ValueError: run_queue.sh crashed
> ```

Weird, that shouldn't happen, but it's also important that pyiron runs from the working directory.  Try to work around for now with `cd {{working_directory}}` after all the slurm commands.  We should check that crash though.

> 
> Without this line of code:
> 
> ```
> 2021-11-03 11:56:27,854 - pyiron_log - INFO - job: vasp_0_95 id: 6471, status: submitted, run job (modal)
> 2021-11-03 11:56:27,903 - pyiron_log - WARNING - Job aborted
> 2021-11-03 11:56:27,903 - pyiron_log - WARNING - Job aborted
> 2021-11-03 11:56:27,903 - pyiron_log - WARNING - Job aborted
> 2021-11-03 11:56:27,904 - pyiron_log - WARNING - /bin/sh: /home/sina/pyiron/resources/vasp/bin/run_vasp_5.4.4_default.sh: /bin/bash^M: bad interpreter: No such file or directory
> 
> 2021-11-03 11:56:27,904 - pyiron_log - WARNING - /bin/sh: /home/sina/pyiron/resources/vasp/bin/run_vasp_5.4.4_default.sh: /bin/bash^M: bad interpreter: No such file or directory
> ```
> 
> If I can handle this somehow, it will solve the problem.

Is it possible that your cluster doesn't have `bash` or in a non-standard location?  You can check the path with `which bash` from the command line.  If that shows nothing, you probably don't have bash (weird, though), but you could change the first line to `#!/bin/sh`, it it shows anything else than `/bin/bash` replace the first line with `#!/usr/bin/env bash`.

**Comment by sinazadeh** [comment]
Thank you all. I do not know how but the following code runs without any problem and I am happy with that. Thanks again.

```
#!/bin/bash
#SBATCH --output=time.out
#SBATCH --job-name={{working_directory}}
#SBATCH --get-user-env=L
#SBATCH -t 1:00:00
#SBATCH -N 2                     
#SBATCH --ntasks-per-node=8     
#SBATCH --mem=50G               

{{command}}
```
