### ISSUE TITLE
Kernel Restarting

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1386]
I am currently experiencing a strange problem. As long as I execute the block:

"solid = pr.create.structure.bulk('W', cubic=True)
solid.set_repeat([supercell,supercell,supercell])
natoms = len(solid)"

It shows the kernel has died and it will restart automatically. However, it was working well one hour ago. Does anyone have the same problem? Any suggestion would be highly appreciated. Thanks in advance.

<img width="1440" alt="Screen Shot 2021-12-06 at 17 37 58" src="https://user-images.githubusercontent.com/57641389/144887287-b28c8f8f-f675-44ee-b73a-ff239f04cf68.png">

**Comment by samwaseda** [comment]
`Kernel Restarting` occurs often when there is not enough memory. Can you check whether or not you have very large arrays or other variables?

**Comment by lfzhu-phys** [comment]
Thanks, Sam. No, I just start the notebook and didn't perform any calculations within this notebook yet. It's strange that only when executing this block.

"solid = pr.create.structure.bulk('W', cubic=True)
solid.set_repeat([supercell,supercell,supercell])
natoms = len(solid)"

**Comment by jan-janssen** [comment]
What is the value of `supercell` ?

**Comment by raynol-dsouza** [comment]
I also have the same issue.

**Comment by lfzhu-phys** [comment]
The supercell is 5*15*15.-------- Original message --------From: Jan Janssen ***@***.***>Date: Mon, 6 Dec 2021, 18:00To: pyiron/pyiron ***@***.***>Cc: lfzhu-phys ***@***.***>, Author ***@***.***>Subject: Re: [pyiron/pyiron] Kernel Restarting (Issue #1386)
What is the value of supercell ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.




-------------------------------------------------
Max-Planck-Institut für Eisenforschung GmbH
Max-Planck-Straße 1
D-40237 Düsseldorf
 
Handelsregister B 2533 
Amtsgericht Düsseldorf
 
Geschäftsführung
Prof. Dr. Gerhard Dehm
Prof. Dr. Jörg Neugebauer
Prof. Dr. Dierk Raabe
Dr. Kai de Weldige
 
Ust.-Id.-Nr.: DE 11 93 58 514 
Steuernummer: 105 5891 1000


Please consider that invitations and e-mails of our institute are 
***@***.*** 
***@***.***

Bitte beachten Sie, dass Einladungen zu Veranstaltungen und E-Mails
***@***.*** gültig sind. 
***@***.***
-------------------------------------------------

**Comment by liamhuber** [comment]
I hogged a gratuitous amount of memory, but Raynol pinged me on slack almost immediately after and I killed the processes. They no longer show up on htop but is there any way the memory has not been released?

**Comment by liamhuber** [comment]
Ok, nevermind...I thought it was gratuitous but apparently not. Looking at the memory columns of htop, I had O(10) processes with O(1GB) memory. I thought this was a lot, but apparently not. Most usage seems to be ipykernels. I could kill top users but am loath to do so without any warning, also there is some root process that appears to be quite brutal, but I don't recognize it or the user directory where it's running.

**Comment by jan-janssen** [comment]
Can it be related to people converting their HDF5 files?

**Comment by muh-hassani** [comment]
171/187 GB of memory is used. I am sending an email to the theory mailing list, so people kill unwanted processes.

**Comment by samwaseda** [comment]
By the way I still support the idea of restarting the server once a week, for example Sunday morning.

**Comment by muh-hassani** [comment]
> By the way I still support the idea of restarting the server once a week, for example Sunday morning.

It is not easy, since it must be done via MPCDF and not me. But if necessary, we can arrange it.

**Comment by jan-janssen** [comment]
@muh-hassani Can not you do it via the admin panel? I guess what sam means is primarily stopping all user servers once.

**Comment by muh-hassani** [comment]
> @muh-hassani Can not you do it via the admin panel? I guess what sam means is primarily stopping all user servers once.

Yes, I can stop servers. But I did not want to interrupt other's work. Unsaved notebooks might be lost. But if you recommend it, I can do it.

**Comment by jan-janssen** [comment]
But the interruption is the same when MPCDF does it, I just wanted to make sure that you have all the necessary permissions.

**Comment by muh-hassani** [comment]
Currently, @fldei101's processes are the most memory-hungry ones. I can kill his server.

**Comment by muh-hassani** [comment]
Now 30GB of memory is freed. I tried the @lfzhu-phys's code, it works fine.

**Comment by lfzhu-phys** [comment]
Great, just tried, it works now:) Thanks you all very much for the rapid responses:))

**Comment by lfzhu-phys** [comment]
Thanks, Muhammad:)

**Comment by samwaseda** [comment]
I have personally never heard of any place where it is allowed to keep programs running after logging out of the server on the login node (actually I even think usually it's not even allowed to run programs on the login node). So restarting the server only once a week is in my opinion still extremely generous.

**Comment by muh-hassani** [comment]
> I have personally never heard of any place where it is allowed to keep programs running after logging out of the server on the login node (actually I even think usually it's not even allowed to run programs on the login node). So restarting the server only once a week is in my opinion still extremely generous.

we can discuss it tomorrow in the meeting.
