### ISSUE TITLE
SQS+Phonopy for an alloy generates +300 VASP jobs

### ISSUE THREAD

**Issue by sinazadeh** [pyiron/pyiron#1389]
Hey,
I am trying to plot DOS chart for an alloy, for example, 0.2Fe-0.3Ni-0.4Cr-0.1Co. Running the following code generates 323 VASP jobs. Is it normal or I am doing something wrong?

```
from pyiron import Project

pr = Project(path="SQSpR16")
structure_lattice = pr.create_ase_bulk(name="Fe", cubic=True)
structure_lattice.set_repeat(3)
job_sqs = pr.create_job(job_type=pr.job_type.SQSJob, job_name="sqs")
job_sqs.structure = structure_lattice
job_sqs.input
job_sqs.input.iterations = 1000
job_sqs.input.mole_fractions = {"Fe": 0.2, "Ni": 0.3, "Cr": 0.4, "Co": 0.1}
job_sqs.run()
job = pr.create_job(
        job_type=pr.job_type.Vasp,
        job_name='VaspJob')
job.structure = job_sqs.list_structures()[0]
job.server.queue = job.server.list_queues()[-1]
phono = job.create_job(
        job_type=pr.job_type.PhonopyJob,
        job_name='phono_job')
phono.run()
phono.plot_dos()
```

![image](https://user-images.githubusercontent.com/63080674/147401174-2bc224be-8e72-46cb-8447-0ba5aaebe26f.png)

**Comment by samwaseda** [comment]
If it's an SQS (i.e. if there's no internal symmetry), there's a degree of freedom of `number of atoms x dimension`, meaning 162 in your case. In the case of phonopy, it looks at the displacement in both `+dx` and `-dx` (to be sure that it finds the correct energy minimum), which in total makes 324 configurations. From the output it indeed looks like there were 324 configurations, so everything seems to be correct.

**Comment by sinazadeh** [comment]
Thanks for your explanation. To plot dos, phono.plot_dos() is the correct command in this case?

**Comment by samwaseda** [comment]
yes

**Comment by sinazadeh** [comment]
@samwaseda 
Do you have any idea why the generated dos chart has negative values? Logically it shouldn't have

![image](https://user-images.githubusercontent.com/63080674/147450757-b2cf1210-4535-4a9f-afe4-ef6a57d3ac4d.png)

**Comment by samwaseda** [comment]
Because it has negative force constants, which comes from the fact that there was no structure optimisation beforehand.

**Comment by sinazadeh** [comment]
Does pyiron have commands for that (or documentation) or I should use manual vasp tags in incar file?

**Comment by samwaseda** [comment]
I find it great that you ask pertinent questions, but it looks like they are mostly physics related and less pyiron, so you might actually need to get a proper supervisor. You don't have one?

**Comment by sinazadeh** [comment]
> I find it great that you ask pertinent questions, but it looks like they are mostly physics related and less pyiron, so you might actually need to get a proper supervisor. You don't have one?

sadly not yet.

**Comment by samwaseda** [comment]
ok you need the following lines:

```python
job_minim = pr.create_job(job_type=pr.job_type.Vasp, job_name='minimization')
job_minim.structure = job_sqs.list_structures()[0]
job_minim.calc_minimize()
job_minim.run()
```

And what you get with `job_minim.get_structure()` is what should be inserted into your SQS job. If you have farther questions you can contact me directly (I hope you can find my address somewhere 😎).

**Comment by sinazadeh** [comment]
Thanks man.
