### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by sinazadeh** [pyiron/pyiron#1399]
**Error**
ResolvePackageNotFound:
  - python=3.1
 
**Steps to produce error**
module load Anaconda3/2021.11
conda create -n pyironenv
conda activate pyironenv
conda install -c conda-forge notebook
conda install -c conda-forge pyiron -y

**Temporary Solution**
conda create -n pyironenv python=3.9
OR Skipping 
conda install -c conda-forge notebook

**Comment by jan-janssen** [comment]
`Python 3.1` or `Python 3.10`? We run all the unit tests with `Python 3.10` https://github.com/pyiron/pyiron_atomistics/runs/5299894276?check_suite_focus=true so the environment usually works fine. Which operation system do you use?

**Comment by sinazadeh** [comment]
operation system: Linux (CentOS 7)
As I mentioned, the pyiron installation raises errors after installing the notebook conda package
`conda install -c conda-forge notebook`
![image](https://user-images.githubusercontent.com/63080674/155459587-4fa7cab7-64a9-40b1-a93a-f9e90f65ace4.png)
Currently, I installed pyiron on Python 3.9.7 without any problems

**Comment by jan-janssen** [comment]
Can you try? 
```
conda install -c conda-forge pyiron notebook "python=3.10"
```
There is an issue that `python=3.10` is recognized as `python=3.1` .

**Comment by sinazadeh** [comment]
> Can you try?
> 
> ```
> conda install -c conda-forge pyiron notebook "python=3.10"
> ```
> 
> There is an issue that `python=3.10` is recognized as `python=3.1` .

Tried that but it installed Python 3.9.7!
Steps:
```
conda install -c conda-forge pyiron notebook "python=3.10"
conda install -c conda-forge pyiron -y
```
This is maybe because of the fact that the latest python version in Anaconda 2021.11 is 3.9.7 https://www.anaconda.com/blog/anaconda-individual-edition-2021-11

**Comment by jan-janssen** [comment]
But you should be able to create a new environment with Python `3.10`. As I said we use it for our tests and also my personal systems use `3.10` for quite some time.

**Comment by jan-janssen** [comment]
I used https://github.com/conda-forge/miniforge for the installation and `mamba install` rather than `conda install` that is a lot fast in resolving the dependencies.

**Comment by sinazadeh** [comment]
> I used https://github.com/conda-forge/miniforge for the installation and `mamba install` rather than `conda install` that is a lot fast in resolving the dependencies.

I will try that, thank you
