### ISSUE TITLE
SQSJob related questions

### ISSUE THREAD

**Issue by sinazadeh** [pyiron/pyiron#1400]
As described here (https://cniu.me/2017/08/05/SQS.html) one of the criteria for selecting the best SQS structure is Objective function.

> We can tell that a SQS with an objective function of -0.95 is better than one with that of -0.85. But it is possible the former takes 3 weeks to generate, while the latter takes only 5 days, and both turn out to be good enough. It would be great if there is a clear line, after which all SQS is good enough. But this line is dependent on the specific material and the properties of interest in each study.

I know we can define the objective function using job_sqs.input.objective but what if we don't know the objective function and want to search for it? The default value is 0.0 but it doesn't seem optimal when you are working with primitive structures.
I can write a bash code to run that c++ but I wanted to make sure if SQSJob is not usable in this case.

**Comment by jan-janssen** [comment]
From a theoretical perspective I would say you could use the best guess after certain time and calculate your final property of interest or an approximate for it to identify if your calculation are already converged. 

For the more technical answer you find the documentation for the SQS code we use at https://sqsgenerator.readthedocs.io/en/latest/ just like phonopy pyiron is primarily an interface to connect existing simulation codes to provide a framework to develop combined simulation protocols. Similar to the general idea I mentioned above.
