### ISSUE TITLE
error loading .pmgrc.yaml when importing pyiron

### ISSUE THREAD

**Issue by edmen-dev** [pyiron/pyiron#1401]
When I "import pyiron" in the cluster I get the following error:
```
"/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pymatgen/core/init.py:49: UserWarning: Error loading .pmgrc.yaml: [Errno 2] No such file or directory: '/u/edmen/.pmgrc.yaml'. You may need to reconfigure your yaml file.
  warnings.warn(f"Error loading .pmgrc.yaml: {ex}. You may need to reconfigure your yaml file.")"
```
Everything else seems to work fine.
My pyiron version is 0.4.6

Thanks for the help.

**Comment by jan-janssen** [comment]
It is an issue with Pymatgen - it is fixed in the next version https://github.com/materialsproject/pymatgen/issues/2444

**Comment by jan-janssen** [comment]
For me the issue is fixed by:
```
conda install pymatgen=2022.2.25 
```

@muh-hassani Can you update the version on the MPIE cluster?

**Comment by muh-hassani** [comment]
@jan-janssen Done!

**Comment by jan-janssen** [comment]
@edmen-dev Can you check if this resolves your issue?

**Comment by edmen-dev** [comment]
I tried now. I was getting the following problem:

"Solving environment: failed with initial frozen solve. Retrying with flexible solve."

at the end it did continue and solve the environment but I did not proceed with the installation just in case. Should I proceed or should I create my own environment and install there?

**Comment by jan-janssen** [comment]
@edmen-dev If you are on cmti001 @muh-hassani already fixed the issue, so the command above is not even necessary.

**Comment by edmen-dev** [comment]
Indeed, it is fixed for me too, thanks!
