### ISSUE TITLE
Restructure pyiron

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1403]
Following my suggestion of today, I write down items that I want to change in pyiron, which would require a major overhaul. Depending on the feedback I get from you, I'll talk to @JNmpi again to organise an intensive multiple-day session.

# `GenericParamters` vs. `DataContainer`

This is a classical problem, but it looks to me that the current `ParallelMaster` does not simply allow to switch from `GenericParameters` to `DataContainer`, because the HDF5 contains also info about the child jobs, which `DataContainer` is not expecting (I didn't dig much into it though).

# Redundant `TemplateJob`

Take LAMMPS and Murnaghan as example for the derivative structure:

- `JobCore` -> `GenericJob` -> `AtomisticGenericJob` -> `LammpsBase`
- `JobCore` -> `GenericJob` -> `GenericMaster` -> `ParallelMaster` -> `AtomisticParallelMaster` -> `Murnaghan`

For me, this totally makes sense. In particular, by looking at it I know where to branch if I need to create a new class. What doesn't make much sense for me is:

- `JobCore` -> `GenericJob` -> `TemplateJob` (-> `PythonTemplateJob`) -> `ABC` -> ...

If I'm a total new user and look at this, I wonder what `TemplateJob` is for. Even if I understand it, we might be encouraging new users to create a whole new branch starting from `TemplateJob`, which has no conceptual element in it.

# Conflict of `InteractiveWrapper` vs. `SerialMaster` and `ParallelMaster`

`Murnaghan` and `SxExtOpt` do very similar things: create a lot of child jobs and run them one after another. The main difference is the fact that `Murnaghan` can launch various jobs at the same time, while `SxExtOpt` conceptually cannot. However, `Murnaghan` is derived from `ParallelMaster` and `SxExtOpt` is derived from `InteractiveWrapper`, and they do really different things when static jobs are attached. Except for the job submission, they should be derived from the same class, especially regarding the fact that they are meant to do exactly the same when an interactive job is attached.

# (optional) Remove distinction between child and master

It's mostly about the interactive class, but currently a master job cannot become a child job, e.g. energy minimiser is a master to use something like LAMMPS. However, I can also totally imagine a MC simulation doing energy minimisation at each step, in which case it would be great if the energy minimiser can also be an interactive job.

**Comment by pmrv** [comment]
> # `GenericParamters` vs. `DataContainer`
> 
> This is a classical problem, but it looks to me that the current `ParallelMaster` does not simply allow to switch from `GenericParameters` to `DataContainer`, because the HDF5 contains also info about the child jobs, which `DataContainer` is not expecting (I didn't dig much into it though).

Generally I'd expect this to work, if not then most likely we'll just need to fine-tune the `to_hdf` implementation of the involved classes.

> # Redundant `TemplateJob`
> 
> Take LAMMPS and Murnaghan as example for the derivative structure:
> 
>     * `JobCore` -> `GenericJob` -> `AtomisticGenericJob` -> `LammpsBase`
> 
>     * `JobCore` -> `GenericJob` -> `GenericMaster` -> `ParallelMaster` -> `AtomisticParallelMaster` -> `Murnaghan`
> 
> 
> For me, this totally makes sense. In particular, by looking at it I know where to branch if I need to create a new class. What doesn't make much sense for me is:
> 
>     * `JobCore` -> `GenericJob` -> `TemplateJob` (-> `PythonTemplateJob`) -> `ABC` -> ...
> 
> 
> If I'm a total new user and look at this, I wonder what `TemplateJob` is for. Even if I understand it, we might be encouraging new users to create a whole new branch starting from `TemplateJob`, which has no conceptual element in it.
> # Conflict of `InteractiveWrapper` vs. `SerialMaster` and `ParallelMaster`

Imo the `TemplateJob` is simply what `GenericJob` really should be and we should integrate it into each other.
