### ISSUE TITLE
How to modify "run_thermointdfteam_0.01_mpi.sh" in pyiron

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1407]
After the cluster update, "pr.create.job.ThermoIntDftEam" doesn't work any more. The executable calls the modified VASP:

/u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018

The error message is: "error while loading shared libraries: libmpifort.so.12: cannot open shared object file: No such file or directory".

The problem can be solved by "module load intel/18.0.5  impi/2018.4". Then the executable works when I directly run it in the working directory, but does not work within pyiron. That means the file "run_thermointdfteam_0.01_mpi.sh" needs to be modified.

This file is under the path:
/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/

I don't have the permission to modify this file. Can anyone do the modification? Also, I am not totally sure how to modify this file. If I have the permission to modify it, I can try things out.

Thanks in advance.

**Comment by lfzhu-phys** [comment]
@jan-janssen Unfortunately, the error "error while loading shared libraries: libmpifort.so.12: cannot open shared object file: No such file or directory" remains.

I tried the following command in my working directory
srun -n 40 /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018

This command is working.

**Comment by jan-janssen** [comment]
@lfzhu-phys Does this mean you have to remove the line `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/afs/@cell/common/soft/intel/ics2019.4/compilers_and_libraries/linux/mkl/lib/intel64` ? Can you check in file where you fixed the issue if this line is removed?

**Comment by lfzhu-phys** [comment]
@jan-janssen I mean, I just run this command line in the terminal under the working directory and it works. 

I have a stupid question. I checked the file run_thermointdfteam_0.01_mpi.sh under the path: /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/run_thermointdfteam_0.01_mpi.sh.

It's still like the following:
---------------------------------------
#!/bin/bash
module load intel/19.0.5
module load impi/2019.5
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/afs/@cell/common/soft/intel/ics2019.4/compilers_and_libraries/linux/mkl/lib/intel64

if [ $(hostname) == 'cmti001' ];
then
        export I_MPI_HYDRA_BOOTSTRAP=fork;
        mpiexec -n $1 /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018
else
        srun -n $1 /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018
fi
--------------------------------------------

It seems nothing has been modified. Or, should I do something in order to see the changes?

**Comment by jan-janssen** [comment]
The modifications are currently only in https://github.com/eisenforschung/pyiron-resources-mpie/pull/33 - I am just wondering if we should remove the `export LD_LIBRARY_PATH` line as that seems to be causing the error.

**Comment by lfzhu-phys** [comment]
Maybe we make a try? Can you please remove it and then I can do a test?

Another question:
Is the 'afs' in 
"export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/**afs**/@cell/common/soft/intel/ics2019.4/compilers_and_libraries/linux/mkl/lib/intel64" 

has any relation with that mentioned by Christoph in his email:

"Please also don't complain about stuff in afs that is suddenly missing - 
I had asked for dependencies on AFS several weeks ago and got zero response! "

Thank you very much for your time.

**Comment by jan-janssen** [comment]
Ok, I removed all links to `afs` in https://github.com/eisenforschung/pyiron-resources-mpie/pull/33 but I am not able to test this.

**Comment by lfzhu-phys** [comment]
If I just execute my pyiron notebook to create and run the job, it will automatically call the modified file `run_thermointdfteam_0.01_mpi.sh in` https://github.com/eisenforschung/pyiron-resources-mpie/pull/33, right? I did this. The libmpifort.so.12 error is still there.

**Comment by jan-janssen** [comment]
@tnecnivkcots Can you merge the changes in https://github.com/eisenforschung/pyiron-resources-mpie/pull/33 and update the version on the cluster?

**Comment by tnecnivkcots** [comment]
I have updated the changed files of the pull request [Thermofix #33](https://github.com/eisenforschung/pyiron-resources-mpie/pull/33).
