### ISSUE TITLE
pyiron inside pycharm: ValueError: Was not able to locate a periodic table

### ISSUE THREAD

**Issue by ahmedabdelkawy** [pyiron/pyiron#1428]
I am not sure if this is the proper repo for this issue. Please move it if it is not

**Summary**
Pyiron is installed on my local machine WSL. 
I am trying to run pyiron workflow from Pycharm professional with python interpreter the same as the conda environment that has Pyiron. 
running pr.create.structure.bulk('any_element') result in: ValueError: Was not able to locate a periodic table. 

- import pyiron works fine 

- .Pyiron configuration:
```
[DEFAULT]
PROJECT_CHECK_ENABLED = False
FILE = ~/pyiron.db
RESOURCE_PATHS = ${CONDA_PREFIX}/share/pyiron
```

- periodic_table.csv file is located in /home/abdelkawy/anaconda3/share/pyiron/atomistics

- conda list pyiron:
pyiron                    0.4.6              pyhd8ed1ab_0    conda-forge
pyiron-data               0.0.20               hd8ed1ab_0    conda-forge
pyiron_atomistics         0.2.25             pyhd8ed1ab_2    conda-forge
pyiron_base               0.4.5              pyhd8ed1ab_0    conda-forge

**Comment by jan-janssen** [comment]
@niklassiemer Are you also using pyiron with WSL on windows? It sounds to me like and issue with the WSL interpreter not finding the environment variable `${CONDA_PREFIX}` but I am not sure how to validate this: https://www.jetbrains.com/help/pycharm/using-wsl-as-a-remote-interpreter.html

@ahmedabdelkawy Can you try to print `${CONDA_PREFIX}` on the command line? or in python using `os.environ["CONDA_PREFIX"]` ? If these are not set then pyiron can not find the resources and consequently cannot find the `periodic table`.

**Comment by ahmedabdelkawy** [comment]
Thanks, Jan, for the fast reply.

In Pycharm using python interpreter, `os.environ["CONDA_PREFIX"]` gives:
File ~/anaconda3/lib/python3.9/os.py:679, in _Environ.__getitem__(self, key)
    676     value = self._data[self.encodekey(key)]
    677 except KeyError:
    678     # raise KeyError with the original key value
--> 679     raise KeyError(key) from None
    680 return self.decodevalue(value)

KeyError: 'CONDA_PREFIX'

In WSL terminal using python,  `os.environ["CONDA_PREFIX"]` gives: '/home/abdelkawy/anaconda3'


`${CONDA_PREFIX}` in WSL terminal  Gives:
-bash: /home/abdelkawy/anaconda3: Is a directory

**Comment by niklassiemer** [comment]
I am using pycharm with the windows python.

Could you try `import sys; print(sys.executable); print(sys.path)` from the wsl python and the pycharm python?

**Comment by ahmedabdelkawy** [comment]
Pyiron installed in base
base is activated in WSL and base interpreter is selected in pycharm

WSL python:
`print(sys.executable)`
/home/abdelkawy/anaconda3/bin/python
`print(sys.path)`
['', '/home/abdelkawy/anaconda3/lib/python39.zip', '/home/abdelkawy/anaconda3/lib/python3.9', '/home/abdelkawy/anaconda3/lib/python3.9/lib-dynload', '/home/abdelkawy/anaconda3/lib/python3.9/site-packages']


pycharm python:
`print(sys.executable)`
/home/abdelkawy/anaconda3/bin/python3
`print(sys.path)`
['/mnt/c/Users/abdelkawy/Desktop/new_project_7', '/mnt/c/Users/abdelkawy/Desktop/new_project_7', '/mnt/c/Program Files/JetBrains/PyCharm 2022.2/plugins/python/helpers/pycharm_display', '/home/abdelkawy/anaconda3/lib/python39.zip', '/home/abdelkawy/anaconda3/lib/python3.9', '/home/abdelkawy/anaconda3/lib/python3.9/lib-dynload', '/home/abdelkawy/anaconda3/lib/python3.9/site-packages', '/mnt/c/Program Files/JetBrains/PyCharm 2022.2/plugins/python/helpers/pycharm_matplotlib_backend']

**Comment by niklassiemer** [comment]
Ok, both ways use the same executables (ans similar python paths), however, the pycharm interpreter does not know about the conda environment it runs in. This can be fixed by providing environment variables to be set for a given interpreter in pycharm. I would have to look up the exact location, however, pycharm offers a possibility to add environment variables to the interpreter. I just wonder why the conda environment is not setting these...
