### ISSUE TITLE
working in view_mode

### ISSUE THREAD

**Issue by JNmpi** [pyiron/pyiron#1429]
**Summary**

When activating view_mode (pr.switch_to_viewer_mode()) several features that are possible in the non_viewer_mode are not working:

- creation of a pyiron table
- running a job (in my folder)
- creating a project in my folder once I have switched to viewing mode

**pyiron Version and Platform**

MPCDF cluster

**Expected Behavior**

To analyse and re-run jobs that are from somebody else and not in my directory it would be important to create a project in my workspace and be able to copy job(s) into this project and (re-)run them. 

Are there some workarounds?

**Comment by jan-janssen** [comment]
The difficulty is that the view mode internally uses a different database connection. We have one connection for read/write access to the database (normal mode) and one connection for read-only mode (view mode). With read-only mode we have access to the database entries from everybody while in read/write mode we only have access to the jobs we created. Based on this restriction we would need two database connections at the same time, which is currently not implemented in pyiron. So I am not exactly sure what is the easiest way to realize more access to shared data.

**Comment by pmrv** [comment]
The only technical problem I see right now, is that each project looks up the central database connection object from the settings.  I don't think it would be too hard to change it such that changing to viewer mode just instantiates a new object and doesn't close the global one.  As @jan-janssen said, that's not implemented that's not implemented right now.

**Comment by liamhuber** [comment]
@pmrv I like this, although then I think we should move away from the term "mode", which suggest an exclusive selection, and towards something like "pr.open_viewer()" which opens a new attribute "pr.viewer" or something like that.

**Comment by JNmpi** [comment]
Thanks for your prompt reply and thoughts. I very much like the idea that we could have two modes and each project can be linked to one or the other, i.e., to the view_mode link or the standard one. For many future applications and particularly in terms of collaborative projects such a feature would be highly appreciated.

**Comment by niklassiemer** [comment]
I also like the idea! However, I would rather have two different routes in one project like @liamhuber suggested (i.e. the `pr.viewer` property, which, however, should activate the corresponding viewer mode on the fly). Or by using `viewer_pr = pr._open_viewer()` to return a view project. 
Implementation wise we need then, of course, both ways to connect to the db simultateously.
