### ISSUE TITLE
docker command is not correct

### ISSUE THREAD

**Issue by jkitchin** [pyiron/pyiron#1444]
**Summary**

The command documented at https://pyiron.readthedocs.io/en/latest/source/installation.html#docker-container does not work.

Specifically,

`docker run -i -t -p 8888:8888 pyiron/pyiron /bin/bash -c "source /srv/conda/envs/notebook/bin/activate; jupyter lab --notebook-dir=/home/pyiron/ --ip='*' --port=8888"`

fails with this error:

```
/bin/bash: /srv/conda/envs/notebook/bin/activate: No such file or directory
[C 2022-12-21 14:49:16.949 ServerApp] Bad config encountered during initialization: No such directory: ''/home/pyiron''
```

The issues are:
1. There is no directory for /home/pyiron. It should be /home/jovyan I think.
2. /srv/conda/envs/notebook/bin/activate does not exist 

In the image:
```
(base) jovyan@0d53d6ea0639:~$ ls /home
jovyan
(base) jovyan@0d53d6ea0639:~$ ls /srv
(base) jovyan@0d53d6ea0639:~$ 
```

This command works for me:
`docker run -i -t -p 8888:8888 pyiron/pyiron /bin/bash -c "jupyter lab --notebook-dir=/home/jovyan/ --ip='*' --port=8888"`

**Comment by jan-janssen** [comment]
Hi @jkitchin , 

Thanks for pointing this out - it seems our documentation was not updated ... when the location of the conda environment changed. The right command should be: 
```
docker run -i -t -p 8888:8888 pyiron/pyiron /bin/bash -c "source /opt/conda/bin/activate; jupyter notebook --notebook-dir=/home/pyiron/ --ip='*' --port=8888"
```
As explained in the docker-stacks repository https://github.com/pyiron/docker-stacks 

I am going to open a pull request to fix this. 

Best, 

Jan
