### ISSUE TITLE
Installation is  confusing 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1477]
Hi @ligerzero-ai , 

With the three different submenus for installation on the pyiron read the docs package users do not know where to find the right instructions: 
https://pyiron.readthedocs.io/en/latest/index.html

Can you merge them into one installation document? 

Best, 

Jan

**Comment by niklassiemer** [comment]
One alternative could be one installation landing page with different installation scenarios outlined.

**Comment by ligerzero-ai** [comment]
I'll get around to fixing it some time later this week - sorry!

**Comment by samwaseda** [comment]
> One alternative could be one installation landing page with different installation scenarios outlined.

I follow this one, and it appears to me like we need a  one landing page with steps better sectioned, for the people to know which ones are relevant in their environment. Maybe I'm gonna make a better suggestion in a different PR.

**Comment by jan-janssen** [comment]
To prevent redundant work, I also today finished the documentation for the `pysqa` package to hopefully move at least this core part to a more stable basis. It is now available at https://pysqa.readthedocs.io/
