### ISSUE TITLE
Is 'set_kmesh_density' necessary?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#213]
I understand that [`set_kmesh_density`](https://github.com/pyiron/pyiron/blob/master/pyiron/dft/job/generic.py#L110) sets automatically the kmesh density according to the box size, but:

- I find it very difficult to know whether it's `set_kpoints` or `set_kmesh_density`, which allows me to set specific k points.
- There is no argument, except for `kspace_per_in_ang`.
- `kspace_per_in_ang` is also not quite easy to understand

My suggestion would be to erase the function altogether and make `_get_k_mesh_by_cell` a public function. What do you think?

**Comment by jan-janssen** [comment]
The function was originally introduced for high throughput computing. But I thought @sudarsan-surendralal was working on rewriting it. So maybe he can comment on this issue.

**Comment by sudarsan-surendralal** [comment]
The reason why we left this is that people in ICAMS apparently still use this function. So is it okay if we erase this function?

**Comment by jan-janssen** [comment]
I thought we planned to extend the functionality, did not we?

**Comment by samwaseda** [comment]
Pull request opened [here](https://github.com/pyiron/pyiron/pull/214)


I attach the [notebook](https://github.com/pyiron/pyiron/files/3148940/kpoint.txt) (you have to replace .txt by .ipynb)

**Comment by jan-janssen** [comment]
The pull request is merged. Can you close the issue @samwaseda ?

**Comment by samwaseda** [comment]
Bien!
