### ISSUE TITLE
LAMMPS: Shoud get_structure() return centered coordinates?

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#228]
In LAMMPS calculations, the atoms often leave the unit cell during the simulation. To visualize this properly, we need to fold them back into the unit cell

```
final_struct = job_lammps.get_structure(iteration_step=-1).center_coordinates_in_unit_cell()
```
Is it okay if I call `center_coordinates_in_unit_cell()` inside `get_structure()`? Or are there cases where the unwrapped structure is needed? Also can I implement this at a generic level?

 @jan-janssen @samwaseda @liamhuber

**Comment by jan-janssen** [comment]
I guess both information are interesting, maybe we could add a flag in get structure? like `center_coordinates_in_unit_cell`

**Comment by liamhuber** [comment]
There are cases where the unwrapped coordinates are necessary (e.g. direct-MD calculations of diffusion), but in fact LAMMPS *does* wrap them back in...it just only does so intermittently. Thus, if unwrapped coordinates are *needed* one has to ask for them specifically (ask @rads if you need any more details on that). As such, I see no problem having the default behaviour be to return wrapped coordinates.

**Comment by samwaseda** [comment]
I'm fine with both options as default behaviour, as long as they both remain available.

**Comment by sudarsan-surendralal** [comment]
Thanks for the input! I've made the changes to the base classes here by adding a new `wrap_atoms` parameter. See [here](https://github.com/pyiron/pyiron/pull/230)
