### ISSUE TITLE
Why does the job have to have finished?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#229]
I'm having a complicated structure optimisation, which I wanted to visualise with `animate_structure()`, but apparently it works only if the status is `finished`. Why? Cf. [this page](https://github.com/pyiron/pyiron/blob/4b8cc8cbcf0797ac466fdacb3f3f32c3c7080656/pyiron/atomistics/job/atomistic.py#L266)

**Comment by sudarsan-surendralal** [comment]
This was written before interactive jobs were available in pyiron. The positions are written only if the job is finished. We can make an exception for interactive jobs if you want

**Comment by jan-janssen** [comment]
Fixed in https://github.com/pyiron/pyiron/pull/338

**Comment by jan-janssen** [comment]
@samwaseda Is it working for you? Can you close this issue?

**Comment by samwaseda** [comment]
Yes it works. Thanks!
