### ISSUE TITLE
LAMMPS: temperature vs temperatures

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#236]
I noticed the in LAMMPS output, the temperatures are stored as `"temperatures"` but according to what we decided [here](https://pyiron.github.io/source/faq.html#which-output-quantities-are-stored-in-pyiron) it should be `"temperature"`.  This is how it is in VASP. Shall I correct this? Otherwise `job.output.temperature` won't work.

**Comment by liamhuber** [comment]
Yes, please fix it. It seems to me that the underlying rational for plural vs singular is whether it's a box property (e.g. energy_tot, volume, temperature...), or a per-atom property (positions, forces...), in this case the singular is definitely better for temperature.

**Comment by sudarsan-surendralal** [comment]
Fixed [here](https://github.com/pyiron/pyiron/pull/237)
