### ISSUE TITLE
Problem in DocString

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#238]
I just saw on [this page](https://pyiron.github.io/apidoc/pyiron.vasp.base.html#pyiron.vasp.base.VaspBase) the example

```
ham.input.incar[IBRION=-1]
```

But this doesn't work, right?

**Comment by sudarsan-surendralal** [comment]
Oops! Fixed [here](https://github.com/pyiron/pyiron/pull/239)!
