### ISSUE TITLE
Shouldn't this be optional?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#322]
https://github.com/pyiron/pyiron/blob/974d9108d43b28f533969e147499f2dcdcfd3f9b/pyiron/atomistics/job/interactivewrapper.py#L105

Shouldn't this line be an option?

**Comment by jan-janssen** [comment]
The interactive wrappers wrap around one code, therefore the underlying code uses all the available cores. This was designed for minimisers.
