### ISSUE TITLE
Errors by rewriting hdf5 files in one project simultaneously

### ISSUE THREAD

**Issue by FeLoch** [pyiron/pyiron#370]
The function [rewrite_hdf5](https://github.com/pyiron/pyiron/blob/b03cb5600e667d2ad05f36b04496a94045a479e9/pyiron/base/generic/hdfio.py#L631) creates always the new file '5_rewrite.h5', which causes read/write errors by rewriting files in the same project at the same time.

**Comment by FeLoch** [comment]
pull request open #371

**Comment by jan-janssen** [comment]
Thanks a lot.
