### ISSUE TITLE
Memory_limit

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#379]
Currently in line https://github.com/pyiron/pyiron/blob/master/pyiron/base/server/generic.py#L291 the memory `limit` is not passed to the `check_queue_parameters` function.

**Comment by jan-janssen** [comment]
You are right, it should be https://github.com/pyiron/pyiron/pull/380

**Comment by jan-janssen** [comment]
@SanderBorgmans Does this solve your issue?

**Comment by SanderBorgmans** [comment]
Yes, sorry, I forgot to close the issue!
