### ISSUE TITLE
What is this good for?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#410]
So it took me some time to understand that this function killed my custom potential class. (Despite the missing docstrings) I understand what it does, but I don't understand what it is good for. Why shouldn't we simply pass the original lines from the static version?

https://github.com/pyiron/pyiron/blob/01afd5d72c761644bf759ddbaba01e09a6c313f9/pyiron/lammps/interactive.py#L201

**Comment by jan-janssen** [comment]
Because we do not copy the file, but rather link to the file in the resource directory, simply because the interactive job doesn't need a working directory.

**Comment by samwaseda** [comment]
Ok but according to this implementation, the potential is never set if it doesn't require a file, like parameter-based potentials, right?

**Comment by jan-janssen** [comment]
The potential is set in https://github.com/pyiron/pyiron/blob/01afd5d72c761644bf759ddbaba01e09a6c313f9/pyiron/lammps/interactive.py#L209

**Comment by samwaseda** [comment]
But most of the time `atom_style` isn't `full`

**Comment by jan-janssen** [comment]
But the lines below are executed no matter what the atom_style is : 
https://github.com/pyiron/pyiron/blob/01afd5d72c761644bf759ddbaba01e09a6c313f9/pyiron/lammps/interactive.py#L210

**Comment by samwaseda** [comment]
No they aren't, if `potential_lst` has no file (i.e. if `self.input.potential.files` has no file), because the for loop two lines below (L212) has nothing to loop over.

**Comment by jan-janssen** [comment]
Either the potential requires a file, like EAM, MEAM, MTP and so on or if it does not, then a water potential is handled separately. What kind of potentials do you plan to use?

**Comment by samwaseda** [comment]
Morse, Lennard Jones etc.?

**Comment by jan-janssen** [comment]
I guess those are currently not supported by this setter.

**Comment by samwaseda** [comment]
But I don't understand why this setter has been changed. We could have very well changed the static version to never copy the potential file and instead point to the file, in which case there won't be a discrepancy between the static and interactive version.

**Comment by jan-janssen** [comment]
Feel free to modify it.

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron/pull/412
