### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#44]
https://github.com/pyiron/pyiron/blob/40fe661e44c9a7ab08df3a3d92de90fab4b4c8b5/pyiron/base/job/generic.py#L872

Does this mean "if self.job_id is None:"?

**Comment by jan-janssen** [comment]
yes, that is the case if you want to restart from a job which was not executed yet - it was more of an experimental feature and I am not sure if it is working at the moment.

**Comment by samwaseda** [comment]
but isn't it better to write `if self.job_id is None`?

**Comment by jan-janssen** [comment]
Feel free to improve the code ... it is not perfect ;-)

**Comment by jan-janssen** [comment]
@samwaseda Can we close this issue?
