### ISSUE TITLE
tags not updated in get_structure

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#443]
I noticed that the spins are not updated when I get the final structures via `get_structure`, which is not difficult to understand since the tags were historically used for initial structures, but I still find it quite confusing that I see the initial magnetic moments in the final structure. Shall we apply individual updates (i.e. `spin` is updated while `selective_dynamics` isn't etc.)?

https://github.com/pyiron/pyiron/blob/29441c4cfd78c889e781801e2043994fdfc2c8a6/pyiron/atomistics/job/atomistic.py#L630

**Comment by jan-janssen** [comment]
We should also consider keeping the consistency with ASE, the have: 
`get_initial_magnetic_moments` and `get_magnetic_moments`
https://gitlab.com/ase/ase/blob/master/ase/atoms.py#L606

**Comment by samwaseda** [comment]
Okay but then shall we implement `get_magnetic_moments` in `pyiron.atomistics.job.atomistic`? Or should `dft.job.generic` rather be extended?

**Comment by jan-janssen** [comment]
I just noticed that I missed this issue - my suggestion would be to implement it in `dft.job.generic` for now. Still I am not sure if this issue is still active.

**Comment by jan-janssen** [comment]
@samwaseda Was this fixed by https://github.com/pyiron/pyiron/pull/670 ? If it is fixed, can you close the issue?
