### ISSUE TITLE
Lammps structures can be read wrong

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron#449]
Beyond some level of cell shape complexity, there is a breakdown in communication between pyiron and Lammps. For a concrete example, Al run with a cubic or orthogonal cell is fine, but with the primitive structure pyiron reads the structure wrong. 

MWE:
```python
job = pr.create_job(pr.job_type.Lammps, 'primitive_trouble')
job.structure = pr.create_ase_bulk('Al').repeat(3)
job.potential = job.list_potentials()[0]
job.run()

job.structure.plot3d()  # Fine
job.get_final_structure().plot3d()  # Uh-oh
```

The average energies under a simple MD run are fine regardless of whether I use the primitive, orthorhombic, or cubic cells, so things are getting passed to Lammps fine, but when we try to read the Lammps output we're misinterpreting it.

**Comment by jan-janssen** [comment]
Can you test this with interactive mode?

**Comment by liamhuber** [comment]
```python
job = pr.create_job(pr.job_type.Lammps, 'primitive_trouble')
job.structure = pr.create_ase_bulk('Al').repeat(5)
job.potential = job.list_potentials()[0]
job.interactive_open()
job.run()
job.interactive_close()

job.structure.plot3d()  # Fine
job.get_final_structure().plot3d()  # Still a problem
```

There is still some order in the final structure, but there are large voids in the cell and other places with overlapping atoms -- it looks like a wrapping problem. pyiron is changing the cell to something with zeros above the diagonal. This probably gives a pretty good hint where things are going wrong.

I can probably look at this later today or this evening, but I ran into it working something else (where I can get away with an orthogonal cell just fine) and I'd like to finish that first.

**Comment by liamhuber** [comment]
indeed, using `get_structure(iteration_step=-1, wrap_atoms=False)` shows that the atoms still have very reasonable positions relative to each other, it's just when they get wrapped back into the cell that things go wrong. I bet we're just converting the Lammps triclinic cell wrong...

**Comment by liamhuber** [comment]
Fixed in [this pull request](https://github.com/pyiron/pyiron/pull/463).
