### ISSUE TITLE
deactivate library

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#45]
https://github.com/pyiron/pyiron/blob/40fe661e44c9a7ab08df3a3d92de90fab4b4c8b5/pyiron/base/job/interactive.py#L50

Is it okay if I put `self._interactive_library = None` in `interactive_close()`?

**Comment by jan-janssen** [comment]
Yes

**Comment by jan-janssen** [comment]
@samwaseda Can we close this issue?
