### ISSUE TITLE
snapshot defined but not used

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#473]
I see the option `snapshot` in `def restart` but I don't see it inside the function. It's probably not used, is it? I guess it's better to say in the Doc string that it won't be reflected or simply remove it altogether.

https://github.com/pyiron/pyiron/blob/42c5825cdfbc21a1b3a124fb87d59fa15c66196c/pyiron/base/job/generic.py#L1181

**Comment by sudarsan-surendralal** [comment]
Earlier we had the option of choosing which snapshot from the simulation to return. Later we realized that it does not make sense to restart from a snapshot that is not the last one. So yeah you can remove it if you want but make sure you fix this line too

https://github.com/pyiron/pyiron/blob/42c5825cdfbc21a1b3a124fb87d59fa15c66196c/pyiron/vasp/base.py#L507

**Comment by jan-janssen** [comment]
@sudarsan-surendralal or @samwaseda Can one of you fix this and open a pull request?

**Comment by samwaseda** [comment]
Sure. I'll (probably) do it later today

**Comment by samwaseda** [comment]
Does [this function](https://github.com/pyiron/pyiron/blob/dd89ac141562e5c61d6574c7c8b681e1ab60a0f4/pyiron/vasp/base.py#L490) still have utility?

**Comment by samwaseda** [comment]
It's done [here](https://github.com/pyiron/pyiron/pull/566)

**Comment by jan-janssen** [comment]
> Does [this function](https://github.com/pyiron/pyiron/blob/dd89ac141562e5c61d6574c7c8b681e1ab60a0f4/pyiron/vasp/base.py#L490) still have utility?

In https://github.com/pyiron/pyiron/blob/master/pyiron/vasp/base.py#L484 ? @sudarsan-surendralal Can you comment on this?
