### ISSUE TITLE
interactive VASP gives an error

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#487]
Following code gives an index error with `interactive_energy_pot_getter`

```
vasp = pr.create_job('Vasp', 'vasp')
vasp.structure = pr.create_structure('Fe', 'bcc', 2.83)
vasp.interactive_open()
vasp.run()
vasp.interactive_close()
```

**Comment by jan-janssen** [comment]
https://gitlab.mpcdf.mpg.de/pyiron/pyiron-support/issues/244

**Comment by jan-janssen** [comment]
For all the external users - Vasp 5.4.4 requires a patch for interactive mode to be enabled again - for Vasp 5.4.1 it worked out of the box.

**Comment by samwaseda** [comment]
> https://gitlab.mpcdf.mpg.de/pyiron/pyiron-support/issues/244

My branch is and has been up to date if that's what you're telling me

**Comment by jan-janssen** [comment]
Please try` job.executable.version = "5.4.4_int"`
https://gitlab.mpcdf.mpg.de/pyiron/pyiron-support/issues/244#note_48666

**Comment by samwaseda** [comment]
XD sorry that was a super foolish mistake
