### ISSUE TITLE
Pressure not properly rotated

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#491]
https://github.com/pyiron/pyiron/blob/77053fa5b0bddcc1f6f0e3c7a15b234985a165ba/pyiron/lammps/base.py#L544

If the upper triangle matrix is defined for Lammps, the pressure coordinates will be wrong -> it has to be rotated just in the same way as positions or velocities

**Comment by jan-janssen** [comment]
@samwaseda As far as I understand @liamhuber has been working on this.
