### ISSUE TITLE
ValueError: Was not able to locate a periodic table. 

### ISSUE THREAD

**Issue by chrinide** [pyiron/pyiron#495]
Hi all,

I have used Pyiron as a first try after successfully installation and configuration,

```
from pyiron import Project
pr = Project('test')
basis = pr.create_structure(element='Fe', bravais_basis='bcc', lattice_constant=2.75)
```

But got below issue:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-8f2356a42527> in <module>
      1 from pyiron import Project
      2 pr = Project('test')
----> 3 basis = pr.create_structure(element='Fe', bravais_basis='bcc', lattice_constant=2.75)

~/miniconda3/envs/psi4/lib/python3.7/site-packages/pyiron/project.py in create_structure(element, bravais_basis, lattice_constant)
    473             element=element,
    474             bravais_basis=bravais_basis,
--> 475             lattice_constants=[lattice_constant],
    476         )
    477 

~/miniconda3/envs/psi4/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in __new__(cls, *args, **kwargs)
   4021 class CrystalStructure(object):
   4022     def __new__(cls, *args, **kwargs):
-> 4023         basis = _CrystalStructure(*args, **kwargs).atoms()
   4024         return basis
   4025 

~/miniconda3/envs/psi4/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in __init__(self, element, bravais_lattice, bravais_basis, lattice_constants, dimension, rel_coords, pse, **kwargs)
   3591             scaled_positions=self.coordinates,
   3592             cell=self.amat,  # tag = "Crystal",
-> 3593             pbc=[True, True, True][0 : self.dimension],
   3594         )
   3595 

~/miniconda3/envs/psi4/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in __init__(self, symbols, positions, numbers, tags, momenta, masses, magmoms, charges, scaled_positions, cell, pbc, celldisp, constraint, calculator, info, indices, elements, dimension, species, high_symmetry_points, **qwargs)
    127         self._species = list()
    128         self.positions = None
--> 129         self._pse = PeriodicTable()
    130         self._tag_list = SparseArray()
    131         self.indices = np.array([])

~/miniconda3/envs/psi4/lib/python3.7/site-packages/pyiron/atomistics/structure/periodic_table.py in __init__(self, file_name)
    193             file_name (str): Possibility to choose an source hdf5 file
    194         """
--> 195         self.dataframe = self._get_periodic_table_df(file_name)
    196         if "Abbreviation" not in self.dataframe.columns.values:
    197             self.dataframe["Abbreviation"] = None

~/miniconda3/envs/psi4/lib/python3.7/site-packages/pyiron/atomistics/structure/periodic_table.py in _get_periodic_table_df(file_name)
    388                                 os.path.join(path, periodic_table_file_name), mode="r"
    389                             )
--> 390             raise ValueError("Was not able to locate a periodic table. ")
    391         else:
    392             if file_name.endswith(".h5"):

ValueError: Was not able to locate a periodic table. 
```

Any suggestion?

**Comment by jan-janssen** [comment]
Hi @chrinide, 

Can you post your `.pyiron` configuration - commonly in your user directory `~/.pyiron`? If it does not exist you might have to configure pyiron again https://pyiron.github.io/source/installation.html#configuration .

Best, 

Jan

**Comment by chrinide** [comment]
Hi, 

This is:

```
[DEFAULT]
PROJECT_PATHS = ~/pyiron/projects
RESOURCE_PATHS = ~/pyiron/resources
```

**Comment by jan-janssen** [comment]
Ok, can you show me the content of `~/pyiron/resources`, simply `ls ~/pyiron/resources`. This should be the same like: https://github.com/pyiron/pyiron-resources and in particular there should be https://github.com/pyiron/pyiron-resources/blob/master/atomistics/periodic_table.csv in `ls ~/pyiron/resources/atomistics/periodic_table.csv`. These files are downloaded during the configuration step of `pyiron.install()` if the files are not there you can simply download them from the repository and place them in the folder.

**Comment by Vadym-ko** [comment]
Thank you, @jan-janssen! 
Direct downloading from the [github folder](https://github.com/pyiron/pyiron-resources) helped. 
For some reason after installation there was no _periodic_table.csv_ file in the _resources_ folder. 
I have reinstalled, but it didn't work. Perhaps there are some problems with _pyiron.install()_ script.

**Comment by jan-janssen** [comment]
Can you tell me which version of pyiron you are using? `conda list pyiron`

**Comment by Vadym-ko** [comment]
Version 0.2.10

**Comment by jan-janssen** [comment]
I tried to reproduce the issue on mybinder https://github.com/jan-janssen/debug-pyiron-install/tree/master but somehow I was not able to.

**Comment by jan-janssen** [comment]
@chrinide and @Vadym-ko Can I close this issue? As far as I understand it works when you download the resources directly from GitHub.

**Comment by Vadym-ko** [comment]
As I have figured it out this issue happens if the _pyiron.install()_ command was terminated. In this case _pyiron.install()_ recall returns _"pyiron is already installed"_, but there could be not all files in  the resources folder. Downloading directly from GitHub solves the problem. Consequently, I suggest to close the issue.
