### ISSUE TITLE
Phonopy master wrong run mode - modal instead of non_modal

### ISSUE THREAD

**Issue by yury-lysogorskiy** [pyiron/pyiron#503]
**pyiron version**: 0.2.10

`pr=Project("test-phonopy")`
`atoms = pr.create_ase_bulk("Mo")`
`job = pr.create_job(pr.job_type.PhonopyJob,"phonopy")`
`engine_job = pr.create_job(pr.job_type.Vasp,"vasp_engine")`
`engine_job.structure = atoms`
`engine_job.executable.mpi =True`
`engine_job.server.queue = "xxx"`
`engine_job.server.cores=4`
`job.ref_job = engine_job`
`job.server.run_mode = "non_modal"`
`job.run(run_mode="non_modal")`

expected behavior: run master job in non_modal mode in background
actual behavior: 

> The job phonopy was saved and received the ID: 9
> 2020-01-17 13:26:02,965 - pyiron_log - INFO - job: phonopy id: 9 run parallel master (modal)
> 2020-01-17 13:26:04,567 - pyiron_log - INFO - phonopy: run job supercell_phonon_0
> 2020-01-17 13:26:04,572 - pyiron_log - INFO - run job: supercell_phonon_0 id: None, status: initialized
> The job supercell_phonon_0 was saved and received the ID: 10
> 2020-01-17 13:26:05,112 - pyiron_log - INFO - run job: supercell_phonon_0 id: 10, status: created
> Queue system id:  2812640
> 2020-01-17 13:26:05,202 - pyiron_log - INFO - job: supercell_phonon_0 id: 10, status: submitted, submitted: queue id 2812640
> 2020-01-17 13:26:05,203 - pyiron_log - INFO - phonopy: submitted job supercell_phonon_0

**Comment by jan-janssen** [comment]
If you specify the queue the `run_mode` is `queue` rather than `non_modal`

**Comment by yury-lysogorskiy** [comment]
> If you specify the queue the `run_mode` is `queue` rather than `non_modal`

I specify _queue_ for **engine_job** and it goes to queue mode, that is correct, but
**job** is executed in _modal mode_, as I see from the on-screen log.

However,  **job** collected output and finished properly

**Comment by jan-janssen** [comment]
But that is only the submission https://github.com/pyiron/pyiron/blob/master/pyiron/base/master/parallel.py#L553 - the master is not waiting until the jobs are finished it just waits until the jobs are submitted.

**Comment by yury-lysogorskiy** [comment]
I assume, that if the number of _subjobs_ is too large, it is better to let user decide - submit them in main process (_modal_ mode)  or in background  (_non_modal_ mode)

**Comment by jan-janssen** [comment]
We removed this functionality to make it easier for the user to see what exactly is happening and to reduce conflicts with the queuing system when too many processes were submitting at the same time.

**Comment by yury-lysogorskiy** [comment]
Could this behavior be just the **default** option, but still providing the possibility to user to submit it in _non-modal_ mode with expected behavior?

**Comment by jan-janssen** [comment]
I won't have the time to implement it, but feel free to open a pull request.
