### ISSUE TITLE
Magnetic moments for ISPIN=2, LORBIT=10 Vasp calculations not read

### ISSUE THREAD

**Issue by yury-lysogorskiy** [pyiron/pyiron#504]
Per-atom magnetic moments not read.

**Input script:**
`from pyiron import Project`
`pr=Project("test-magmom")`
`atoms = pr.create_ase_bulk("Fe", cubic = True)`
`engine_job = pr.create_job(pr.job_type.Vasp,"vasp_engine")`
`engine_job.structure = atoms`
`engine_job.input.incar["LORBIT"]=10`
`engine_job.input.incar["ISPIN"]=2`
`engine_job.set_exchange_correlation_functional("PBE")`
`engine_job.executable.mpi =True`
`engine_job.server.queue = "XXX"`
`engine_job.server.cores=2`
`engine_job.run()`

**Output**
`engine_job["output"]`

> {'groups': ['charge_density', 'electronic_structure', 'generic', 'outcar', 'structure'], 'nodes': ['description']}

`engine_job["output/outcar"]`
>{'groups': [], 'nodes': ['broyden_mixing', 'irreducible_kpoints', 'kin_energy_error', 'stresses']}

`engine_job["output/electronic_structure"]`
>{'groups': ['dos'], 'nodes': ['TYPE', 'efermi', 'eig_matrix', 'k_points', 'k_weights', 'occ_matrix']}

`engine_job["output/generic"]`
>{'groups': ['dft'], 'nodes': ['cells', 'energy_pot', 'energy_tot', 'forces', 'positions', 'positions_unwrapped', 'pressures', 'steps', 'temperature', 'volume']}

No info about magnetic moments...
However this code works:
`from pyiron.vasp.outcar import  Outcar`
`outcar = Outcar()`
`outcar_file_name=".../pyiron/projects/test-magmom/vasp_engine_hdf5/vasp_engine/OUTCAR"`
`outcar.from_file(outcar_file_name)`
`outcar.get_magnetization(outcar_file_name)`
>([array([2.       , 2.       , 2.       , 2.       , 4.8420694, 3.8795071,
         3.9383515, 4.0114096, 3.9909919, 3.9988781, 3.9988781])],
 [[2.008, 2.008], [2.008, 2.008]])

**Comment by sudarsan-surendralal** [comment]
These values are stored in 

`engine_job["output/generic/dft/final_magmoms"]`

and 

`engine_job["output/generic/dft/magnetization"]`
