### ISSUE TITLE
First pyiron Workshop - http://potentials.rub.de - in Bochum - Germany - 31st of March to 2nd of April 2020

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#506]
WORKSHOP

"WORKFLOWS FOR ATOMISTIC SIMULATION"

SCOPE

It is increasingly common that atomistic simulations such as molecular
dynamics or structural relaxation are used as engines that drive more
complex simulation tasks, for example, the computation of phase diagrams
or the search for novel materials with specific properties, etc.

The workflow along the simulation chain then becomes an integral part of
research and for transparent and reproducible results or for
transferring to other materials systems it is essential that the
workflow along the simulation chain is well documented.

At this workshop leading international researchers will give an
introduction to simulations and workflows that they use in their
research. In the afternoons hands-on tutorials using pyiron will
enable the participants to set up their own simulation tasks and
workflows.

REGISTRATION

Participation is free of charge, limited to a maximum of 50
participants. We ask you to provide us with some information on your
background and your motivation for taking part in the workshop, which we
will use as the basis to select participants. For a binding registration
please send an email with your name, contact details and a few lines on
your background and motivation for attending the workshop to:
potentials@icams.rub.de We will then inform you regarding acceptance at
the workshop as soon as possible.

DATES AND PLACE

31 March-2 April 2020, Bochum, Germany

WEBSITE

http://potentials.rub.de

**Comment by FeLoch** [comment]
Since the workshop is cancelled due to COVID-19, should we close the issue?
