### ISSUE TITLE
what does this line do?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#515]
It looks extremely redundant. What does this line mean and the lines that follow?

https://github.com/pyiron/pyiron/blob/aeeb93fb826800e869fd52215b9696d11e61af7e/pyiron/base/job/generic.py#L1015

**Comment by jan-janssen** [comment]
If the master job is in `run_mode` `non_modal` also all his childs are set to run_mode `non_modal`.

**Comment by samwaseda** [comment]
ok sorry I didn't see the object part
