### ISSUE TITLE
Length of the job name 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#518]
@pmrv I just checked the code an the job names are limited to 50 characters: 
https://github.com/pyiron/pyiron/blob/master/pyiron/base/database/generic.py#L114

**Comment by pmrv** [comment]
Thanks for checking!  I found out how to use job groups today, which side steps this and is probably what I should have done anyway. I think I'll add this information to one of the intro notebooks though, once I've stepped through all of them.
