### ISSUE TITLE
bug in set_empty_states in sphinx

### ISSUE THREAD

**Issue by FeLoch** [pyiron/pyiron#520]
Empty states can never be set!

https://github.com/pyiron/pyiron/blob/010444ae03d099909a0ae94ddd5086d26ae6528e/pyiron/sphinx/base.py#L577

**Comment by FeLoch** [comment]
pull request open #521

**Comment by jan-janssen** [comment]
I do not get it, what was wrong with the previous code? if the number is smaller than `0` it raises and issue and if it is `None` nothing happens.

**Comment by FeLoch** [comment]
If `n_empty_states` is not None it raises an error, too. Therefore it always raises an error.

**Comment by jan-janssen** [comment]
Got it, it should have been is `not None and `instead of is `not None or `

**Comment by FeLoch** [comment]
Moreover, the user is never able to restore `"auto"` for the emtpy states.
