### ISSUE TITLE
Lammps Dies

### ISSUE THREAD

**Issue by vijjubhuva** [pyiron/pyiron#522]
I recently added pyiron in my computer. However,  I am getting following error about the LAMMPS.
I also tried manually but doesn't work as well.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/pyiron/base/job/generic.py in run_static(self)
    721                     stderr=subprocess.STDOUT,
--> 722                     universal_newlines=True,
    723                 )

/anaconda3/lib/python3.6/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 

/anaconda3/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    417             raise CalledProcessError(retcode, process.args,
--> 418                                      output=stdout, stderr=stderr)
    419     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command 'pyiron/resources/lammps/bin/run_lammps_2018.03.13.sh' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-22-547a87b2509b> in <module>()
----> 1 job.run()

/anaconda3/lib/python3.6/site-packages/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    658                 status = "created"
    659             if status == "initialized":
--> 660                 self._run_if_new(debug=debug)
    661             elif status == "created":
    662                 que_id = self._run_if_created()

/anaconda3/lib/python3.6/site-packages/pyiron/base/job/generic.py in _run_if_new(self, debug)
   1302         else:
   1303             self._create_job_structure(debug=debug)
-> 1304             self.run()
   1305 
   1306     def _run_if_created(self):

/anaconda3/lib/python3.6/site-packages/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    660                 self._run_if_new(debug=debug)
    661             elif status == "created":
--> 662                 que_id = self._run_if_created()
    663                 if que_id:
    664                     self._logger.info(

/anaconda3/lib/python3.6/site-packages/pyiron/base/job/generic.py in _run_if_created(self)
   1319             self.run_if_manually()
   1320         elif self.server.run_mode.modal:
-> 1321             self.run_static()
   1322         elif self.server.run_mode.non_modal or self.server.run_mode.thread:
   1323             self.run_if_non_modal()

/anaconda3/lib/python3.6/site-packages/pyiron/base/job/generic.py in run_static(self)
    751                 if self.server.run_mode.non_modal:
    752                     s.close_connection()
--> 753                 raise RuntimeError("Job aborted")
    754             else:
    755                 job_crashed = True

RuntimeError: Job aborted

**Comment by jan-janssen** [comment]
Hi @ vijjubhuva, thank you for giving pyiron a try. To me this looks like Lammps is not setup correctly. The easiest way to setup Lammps with pyiron is: 
`conda -c conda-forge install lammps`

**Comment by vijjubhuva** [comment]
Thank you so much for your reply. Now lammps work perfectly.
