### ISSUE TITLE
Does it make sense to multiply it by 2*pi?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#537]
The name `kpoints_per_angstrom` in `get_k_mesh_by_cell` makes me think that this is the number of k-points per angstrom, but in reality it is 1/angstrom and multiplied by 2*pi. Is it really intuitive? Besides, from my point of view it makes more sense to have `kpoints_per_angstrom` as the first argument and `cell` after that, since I'm usually interested to know how many points I need for the **current** cell and not what it looks like for an unrelated structure.

https://github.com/pyiron/pyiron/blob/7fc724ba91964323050a1d0c5603677df0a54801/pyiron/dft/job/generic.py#L83

P.S.
I just realised that I had changed `kpoints_per_in_angstrom` to `kpoints_per_angstrom` around a year ago without knowing that `in` stood for "inverse". I'd be very much interested to know whether anyone was actually using this command.

**Comment by samwaseda** [comment]
Maybe I should say clearly how I would use it: I'd like to get let's say something like 24 k-points per lattice in each direction. Then I'm fine with any of the following options:
```
job.get_k_mesh_by_cell(24)
job.get_k_mesh_by_cell(24/lattice_constant)
job.get_k_mesh_by_cell(24*lattice_constant)
```
But **NOT** with
```
get_k_mesh_by_cell(None, 24/lattice_constant/2/np.pi)
get_k_mesh_by_cell(None, 24*lattice_constant/2/np.pi)
```

**Comment by jan-janssen** [comment]
If I remember correctly @yury-lysogorskiy implemented this functionality for his high throughput calculation, so maybe he can explain the usage.

**Comment by liamhuber** [comment]
While we're talking about this, I'm pretty sure the variable name needs to be `kpoints_per_reciprocal_angstrom`

**Comment by jan-janssen** [comment]
I just had a quick call with @yury-lysogorskiy and we decided to open a pull request with his new changes https://github.com/pyiron/pyiron/pull/565 . @samwaseda Can you take a look at this?

**Comment by samwaseda** [comment]
So you decided to not reflect any of my suggestions above?

**Comment by jan-janssen** [comment]
No. Yury had already made the changes before, all I want is to merge both discussions.

**Comment by samwaseda** [comment]
Ok I submitted the comment

**Comment by jan-janssen** [comment]
@samwaseda I close the issue for now and we can continue the discussion in https://github.com/pyiron/pyiron/pull/565
