### ISSUE TITLE
Multi Word Keys in GenericParameters

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#540]
Right now keys into GenericParameters cannot have white space in them and instead have to have underscores `'___'` instead, which is a bit inconvenient and unintuitive. 

Our consensus from Friday was to change `GenericParameters.__getitem__` to
special case keys with white space and replace it with
`GenericParameters.multi_word_separator = '___'` transparently.  Looking into
it there are three methods involved in this

1. [`__getitem__`](https://github.com/pyiron/pyiron/blob/master/pyiron/base/generic/parameters.py#L652)
2. [`get`](https://github.com/pyiron/pyiron/blob/master/pyiron/base/generic/parameters.py#L357)
3. [`_find_line`](https://github.com/pyiron/pyiron/blob/master/pyiron/base/generic/parameters.py#L962)

and the only reason special casing white space is necessary in the first place
is that `_find_line` splits keys on white space to make handling *values* with
white space a bit simpler.  I think the intended use case is something like
this (it's broken in `__getitem__` because of a small bug)
```python
>>> p = GenericParameters()
>>> p['fix'] = '2 3 foo bar'
>>> p['fix']
'2 3 foo bar'
>>> p.get('fix 2')
'3 foo bar'
>>> p.get('fix 2 3')
'foo bar'
>>> p.get('fix 3')
```
Something similar for `__setitem__` is not implemented.  If we replace white
space with `'___'` in `__getitem___` or `get`, then this is broken, because
`_find_line` will never see keys with white space.  OTOH, I don't think this
functionality is worth having to manually do the replacement and a superficial
grep on our internal notebooks (with `"input(.control)?\[['\"].*['\"]\]"`)
seems to show that is never used anyway, but I don't know about your personal
or external code.  Still I would rather then remove the code that enables this
behavior and just allow keys with white space in the underlying
`OrderedDict()`.  With this the use case e.g. for multiple fixes in lammps
would be
```python
>>> p = GenericParameters()
>>> p['fix ensemble'] = 'nvt'
>>> p['fix 2'] = 'foo bar'
>>> p
 Parameter      Value   Comment
1  foo ensemble nvt
2  foo 2        foo bar
>>> p.get_string_lst()
['fix ensemble nvt\n', 'fix 2 foo bar\n']
```
The code in `get_string_lst` to write the input files would handle this
already, if it weren't the case now that `_find_list` is (more or less) broken
on keys with white space.  We can also continue to special case keys with
`'___'` in them while writing for backwards compatibility, but it wouldn't be
necessary anymore.

Since this is a slightly bigger change than we discussed I wanted to check back
with you before I create a pull request and break a lot of code.  The options
are basically

1.  Replace white space in keys as originally discussed, which breaks the first
    use case and creates dead code in `_find_line`,
2.  don't replace white space in keys and remove the code in `_find_line`, this
    just breaks use case one or
3.  same as 2. and save the first use case by adding code to enable something like
```python
>>> p = GenericParameters()
>>> p['fix'] = '2 3 foo bar'
>>> p['fix']
'2 3 foo bar'
>>> p['fix', '2']
'3 foo bar'
>>> p['fix', '2', '3']
'foo bar'
>>> p['fix', '3']
```
Naturally that only makes sense if this is actually used anywhere in the code
base.

**Comment by jan-janssen** [comment]
@pmrv Any progress with this? I started by simply removing the multi word part: https://github.com/pyiron/pyiron/pull/564

**Comment by pmrv** [comment]
Yeah, I have a branch (on my office computer..) where I removed the multi word part as well and fixed reading them from a file as well, that should work, but I got distracted testing it.

It gets tricky when reading GenericParameters from a file, because right now only the first word of a line is used as a key. So when querying for a key with white space (`'set group H charge'` for this error) the parameter is not found, because only the first word (`'set'`) was read as the key.  I will look into the error later today and get back.

**Comment by pmrv** [comment]
So, I think the problem with just removing multi word part on getting is, that then we need a unambiguous way to split a line in a parameter file into the key and the value on reading.  Errors come from the `LammpsStructure` trying to read the charges from the potential file with `GenericParameters.get('set group H charge')` where the full lines are
```
set group H charge 0.415
set group O charge -0.83
```
So in this case the fix would be to somehow have the keys be `'set group H charge'` and `'set group O charge'`, but I don't think there's an easy way to do it for all types of input lines in Lammps, because we don't know how many words we need for a key to be unique.

The real problem is that if we have to leave this in, then we can also not do the automatic translating 'a b' -> 'a___b' that we talked about, because that would turn the keys from above into 'set___group___H___charge' and those are also not there. Maybe a solution could be to remove the multi word part from the getters/setters and instead have a method like find_line() that handles the use case in the tests? That could mean fixing a lot of code however. What's your opinion on this?

**Comment by jan-janssen** [comment]
@sudarsan-surendralal Can you comment on this? 

From my perspective the reading of the charge within the Lammps structure class is a special case, therefore the simple recommendation would be to move the special `_find_line()` function to the `LammpsPotential` class. Following: 
```
Special cases aren't special enough to break the rules.
```
https://www.python.org/dev/peps/pep-0020/

**Comment by sudarsan-surendralal** [comment]
>@sudarsan-surendralal Can you comment on this?

This is an ancient piece of pyiron code and I agree that we have to change it. @pmrv, can you push your local branch? I can then change things after merging with your branch

**Comment by jan-janssen** [comment]
@sudarsan-surendralal I just started by moving the function to the Lammps potential class, to separate the functionality https://github.com/pyiron/pyiron/pull/564

**Comment by pmrv** [comment]
As far as I can tell even in the Lammps potential its only used to get the charges and the element id from the element names, so I would even only add special functions for this. I'll open a pull request with this before the meeting today.

@sudarsan-surendralal Have to get on the VPN first, but sure.

**Comment by jan-janssen** [comment]
We can continue the discussion in the pull request. So I close the issue for now.
