### ISSUE TITLE
No double-using status

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron#541]
`2020-03-06 20:54:19,896 - pyiron_log - WARNING - EDDRMM warning occurred 4 times first in ionic step 1. Status is switched to 'not_converged'.`

Since status `not_converged` already has a very specific meaning, we should not double-use it here. Something generic like `warning` or `finished_with_warning` would be nice, and I think it's probably fine to make it general enough to cover other cases.

Motivation: I'm doing VASP minimizations on a system that often experience this ZBRENT issue, but it does not seem to have any adverse effects on overall the energy minimization when it occurs, and the final relaxation steps always proceed fine with no warnings at all. However, when I get a `not_converged` status, I always need to manually check whether it was *actually* not converged (possible, these are large supercell minimizations!) or if it just had these ZBRENT problems.

**Comment by liamhuber** [comment]
[Here](https://github.com/pyiron/pyiron/blob/master/pyiron/vasp/base.py#L465) is the relevant VASP code.

I found the `status` property [here](https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/core.py#L175) in `JobCore` and can see from the docstring what the allowable values are, but I see a setter or where we actually control for these values...

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/jobstatus.py

**Comment by sudarsan-surendralal** [comment]
> Motivation: I'm doing VASP minimizations on a system that often experience this ZBRENT issue, but it does not seem to have any adverse effects on overall the energy minimization when it occurs, and the final relaxation steps always proceed fine with no warnings at all. However, when I get a not_converged status, I always need to manually check whether it was actually not converged (possible, these are large supercell minimizations!) or if it just had these ZBRENT problems.

If I understand correctly, while this warning/error is not a major issue for most of us, this is critical for some calculations with higher precision (@jan-janssen, perhaps yours?). So @FeLoch and I decided to create a function `set_eddrmm_handling` ([here](https://github.com/pyiron/pyiron/blob/ecf64369dde74305369146dcd2883a346277cf05/pyiron/vasp/base.py#L780)) to take care of this. You just have to set this function once before you run it (`job.set_eddrmm_handling('ignore')`) to ignore these warnings.

**Comment by liamhuber** [comment]
@sudarsan-surendralal True, when I looked in at the vasp interface code I saw that option. This resolves my particular issue, but it doesn't address the underlying problem that we're using a status flag to mean something other than its stated and intended meaning.

**Comment by liamhuber** [comment]
Fixing...

**Comment by liamhuber** [comment]
Patched [here](https://github.com/pyiron/pyiron/pull/543). I didn't run tests locally, so let's wait if the pipeline catches anything. It's a pretty small patch, so hopefully it will be fine.

I didn't make any effort for backwards compatibility here, since this is presumably still a super niche issue.
