### ISSUE TITLE
sphinx does not enter the main loop

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#582]
I managed to install sphinx on my local pc through conda and it seems to crash. I inspected the sphinx log file and found this error message

`This feature needs pcre2. Configure with --enable-pcre2`

However, I see that this is enabled in the conda forge recipe https://github.com/conda-forge/sphinxdft-feedstock/blob/master/recipe/build.sh

Any clues?

**Comment by jan-janssen** [comment]
Please download the latest version:
```
conda install -c conda-forge sphinxdft=2.6.1=h6ced99e_5
```

**Comment by sudarsan-surendralal** [comment]
Thanks! It works now.
