### ISSUE TITLE
Clean up Gaussian code

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#593]
@SanderBorgmans I just found the following module load command:
https://github.com/pyiron/pyiron/blob/178feb4a53a731adcccc85d57e00af79bb972a9b/pyiron/gaussian/gaussian.py#L226
This is very cluster specific and we should find a way to get remove it. Is `cubegen` part of gaussian?

**Comment by SanderBorgmans** [comment]
@jan-janssen cubegen is indeed a part of gaussian, and normally should only be run a single time to generate a cube file with the densities of all the orbitals. However, I could not get it to work with nglview that way, and so cubegen has to be run every time a different orbital needs to visualized. Initially I was thinking to create a separate job type to run this kind of calculation, but I lost track of this.

**Comment by jan-janssen** [comment]
Ok, I guess my issue is simply that it would not work on any other cluster the way it is currently implemented. But maybe we could do something like exporting the command to a shell variable. We do something similar here: 
https://github.com/pyiron/pyiron-resources/blob/master/thermodynamics/bin/run_sxuniqdispl_0.1.sh 
pyiron writes a script that requires `sxuniqdispl` but if it is not accessible, people can load a module in the script and so on. So my idea would be to have a `cubegen.sh` script in the resource folder. In the script you can place the lines: 

```
ml load Gaussian/g16_E.01-intel-2019a
module use /apps/gent/CO7/haswell-ib/modules/all
```

In the code you would then call: 
`cubegen.sh; cubegen 1 MO={} {}.fchk {}.cube".format(index+1,path,path)`

**Comment by SanderBorgmans** [comment]
Yes I knew it was problematic, but this snippet was written during the semester, so if it worked I was happy. 

The solution you propose sounds perfect.

**Comment by SanderBorgmans** [comment]
@jan-janssen I am looking into this at the moment. So for this to work, the cubegen.sh script should go into the resources folder, but how does bash know where to find the cubegen.sh?

**Comment by jan-janssen** [comment]
You can use the resource paths: 
```
import os
from pyiron_base import Settings
s = Settings()

def get_cubegen_path():
    for resource_path in s.resource_paths:
        p = os.path.join(resource_path, "gaussian", "bin", "cubegen.sh")
        if os.path.exists(p):
            return p
```
