### ISSUE TITLE
Testing Lammps Library 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#596]
@sudarsan-surendralal and @raynol-dsouza 

If you get the following error message: 
```
OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
```

Just add the following lines to your notebook: 
```
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
```

This should fix the bug with the lammps library.

**Comment by raynol-dsouza** [comment]
Hi @jan-janssen,

I updated my existing lammps build to `py37_openmpi_2`, added the above two lines, and still get this error:

`
NameError                                 Traceback (most recent call last)
<ipython-input-16-547a87b2509b> in <module>
----> 1 job.run()

~/pyiron/pyiron/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    662                 status = "created"
    663             if status == "initialized":
--> 664                 self._run_if_new(debug=debug)
    665             elif status == "created":
    666                 que_id = self._run_if_created()

~/pyiron/pyiron/pyiron/base/job/generic.py in _run_if_new(self, debug)
   1305         else:
   1306             self._create_job_structure(debug=debug)
-> 1307             self.run()
   1308 
   1309     def _run_if_created(self):

~/pyiron/pyiron/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    664                 self._run_if_new(debug=debug)
    665             elif status == "created":
--> 666                 que_id = self._run_if_created()
    667                 if que_id:
    668                     self._logger.info(

~/pyiron/pyiron/pyiron/base/job/generic.py in _run_if_created(self)
   1328             return self.run_if_scheduler()
   1329         elif self.server.run_mode.interactive:
-> 1330             self.run_if_interactive()
   1331         elif self.server.run_mode.interactive_non_modal:
   1332             self.run_if_interactive_non_modal()

~/pyiron/pyiron/pyiron/lammps/interactive.py in run_if_interactive(self)
    313 
    314         else:
--> 315             super(LammpsInteractive, self).run_if_interactive()
    316             self.interactive_execute()
    317             self.interactive_collect()

~/pyiron/pyiron/pyiron/atomistics/job/interactive.py in run_if_interactive(self)
    117             raise ValueError("Input structure not set. Use method set_structure()")
    118         if not self.interactive_is_activated():
--> 119             self.interactive_initialize_interface()
    120         pre_struct = self.get_structure(-1)
    121         if pre_struct is not None:

~/pyiron/pyiron/pyiron/lammps/interactive.py in interactive_initialize_interface(self)
    220         else:
    221             self._create_working_directory()
--> 222             self._interactive_library = LammpsLibrary(
    223                 cores=self.server.cores,
    224                 working_directory=self.working_directory

NameError: name 'LammpsLibrary' is not defined
`

**Comment by jan-janssen** [comment]
try: 
`conda install -c conda-forge pylammpsmpi `

**Comment by raynol-dsouza** [comment]
Now I run into a different error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-16-547a87b2509b> in <module>
----> 1 job.run()

~/pyiron/pyiron/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    662                 status = "created"
    663             if status == "initialized":
--> 664                 self._run_if_new(debug=debug)
    665             elif status == "created":
    666                 que_id = self._run_if_created()

~/pyiron/pyiron/pyiron/base/job/generic.py in _run_if_new(self, debug)
   1305         else:
   1306             self._create_job_structure(debug=debug)
-> 1307             self.run()
   1308 
   1309     def _run_if_created(self):

~/pyiron/pyiron/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    664                 self._run_if_new(debug=debug)
    665             elif status == "created":
--> 666                 que_id = self._run_if_created()
    667                 if que_id:
    668                     self._logger.info(

~/pyiron/pyiron/pyiron/base/job/generic.py in _run_if_created(self)
   1328             return self.run_if_scheduler()
   1329         elif self.server.run_mode.interactive:
-> 1330             self.run_if_interactive()
   1331         elif self.server.run_mode.interactive_non_modal:
   1332             self.run_if_interactive_non_modal()

~/pyiron/pyiron/pyiron/lammps/interactive.py in run_if_interactive(self)
    313 
    314         else:
--> 315             super(LammpsInteractive, self).run_if_interactive()
    316             self.interactive_execute()
    317             self.interactive_collect()

~/pyiron/pyiron/pyiron/atomistics/job/interactive.py in run_if_interactive(self)
    117             raise ValueError("Input structure not set. Use method set_structure()")
    118         if not self.interactive_is_activated():
--> 119             self.interactive_initialize_interface()
    120         pre_struct = self.get_structure(-1)
    121         if pre_struct is not None:

~/pyiron/pyiron/pyiron/lammps/interactive.py in interactive_initialize_interface(self)
    222             self._interactive_library = LammpsLibrary(
    223                 cores=self.server.cores,
--> 224                 working_directory=self.working_directory
    225             )
    226         if not all(self.structure.pbc):

~/anaconda3/lib/python3.7/site-packages/pylammpsmpi/lammps_wrapper.py in __init__(self, cores, working_directory, client, mode)
     28 
     29         else:
---> 30             raise ValueError("mode should be either dask or local")
     31 
     32 

ValueError: mode should be either dask or local
```

**Comment by jan-janssen** [comment]
I was not aware that you are using the latest master branch. This seems to be a bug with the new interface https://github.com/pyiron/pylammpsmpi/pull/36 

Either you can manually modify the file: 
`~/anaconda3/lib/python3.7/site-packages/pylammpsmpi/lammps_wrapper.py`

**Comment by sudarsan-surendralal** [comment]
Jan, interactive jobs with the lammps version on the latest conda forge actually works for me

```
conda list lammps
# packages in environment at /home/surendralal/miniconda3/envs/pyiron_workshop:
#
# Name                    Version                   Build  Channel
lammps                    2020.03.03         py37_mpich_2    conda-forge

```

**Comment by raynol-dsouza** [comment]
@sudarsan-surendralal are you using the latest master branch? 

@jan-janssen manually changed `lammps_wrapper.py`, and now a new error:

```
~/anaconda3/lib/python3.7/site-packages/pylammpsmpi/lammps.py in _receive(self)
     72             data from the command
     73         """
---> 74         output = pickle.load(self._process.stdout)
     75         return output
     76 

EOFError: Ran out of input
```

**Comment by jan-janssen** [comment]
@raynol-dsouza Do you run the example code above?

**Comment by raynol-dsouza** [comment]
The above code executes properly. I just found out that the cause for the error is setting `lmp.server.cores` to anything above 1. 

I also tried changing the default cores in `lammps_wrapper.py` to 2, and set `lmp.server.cores=2` but that didn't help.

I think this is now more of an issue with the openmpi build of the latest lammps version than the interactive jobs, as the mpich version that @sudarsan-surendralal is using runs interactive jobs properly.

**Comment by jan-janssen** [comment]
No - this only works with openmpi - mpich does not work. It is a bug in the new interface - most likely when scattering the positions. The new interface is only used when we run with more than one core.

**Comment by jan-janssen** [comment]
@raynol-dsouza I fixed it in https://github.com/pyiron/pyiron/pull/597

**Comment by jan-janssen** [comment]
@raynol-dsouza Can you pull the latest master branch from pyiron and update pylammpsmpi using `pip install --pre pylammpsmpi` this should update to the latest prerelease version. Once it is also working for you we should maybe release a new version.

**Comment by raynol-dsouza** [comment]
@jan-janssen I did as you asked, and got this message when I tried updating to the pre-release version:

```
(base) raynol025@raynol025-ThinkPad-E485:~$ pip install --pre pylammpsmpi
Requirement already satisfied: pylammpsmpi in ./anaconda3/lib/python3.7/site-packages (0.0.3)
Requirement already satisfied: mpi4py in ./anaconda3/lib/python3.7/site-packages (from pylammpsmpi) (3.0.3)
```

I ran the same code again with multiple cores. It ran perfectly this time, but ended with raising this error while calling `interactive_close()`:

```
~/anaconda3/lib/python3.7/site-packages/pylammpsmpi/lammps_wrapper.py in close(self)
     82     def close(self):
     83         fut = self.lmp.close()
---> 84         return fut.result()

AttributeError: 'NoneType' object has no attribute 'result'

```

**Comment by jan-janssen** [comment]
Can you try it again? 
```
pip install pylammpsmpi==0.0.3.post0.dev13
```

**Comment by raynol-dsouza** [comment]
@jan-janssen It works properly now without throwing any errors. :)

**Comment by jan-janssen** [comment]
Perfect, then we can include it in the next pyiron release.
