### ISSUE TITLE
Filtering Huge Data using pyiron_table 

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#600]
I am working on big data sets of VASP calculations. And, I want to know how I can filter them according to some parameters. For example, I want to know how to filter the jobs that have something in common in INCAR, let's say `AEXX = 0.47`. Or, I want to sort the data according to the trajectory length.

Till now I am using the conventional way of sorting in pandas as `df.loc[(df['job'].str.contains('Mg')),['job','subjob','project']]`. 

Please, let me know if you have a better way to do that

**Comment by jan-janssen** [comment]
You can define any kind of filter function: 
```
def incar_filter(job):
    data_dict = job['input/incar/data_dict']
    incar_key = 'AEXX'
    incar_value = '0.47'
    if incar_key in data_dict['Parameter'] and data_dict['Value'][data_dict['Parameter'].index(incar_key)] == incar_value and len(job['output/generic/positions']) > 100:
        return True
    else: 
        return False
```

And then attach it to the pyiron table object: 
```
table = pr.create_job(pr.job_type.TableJob, 'table')
table.filter_function = incar_filter
```

**Comment by sudarsan-surendralal** [comment]
Related to this, can we have a higher level filter function that filters at the database level itself? This would make things even faster since we can apply the job-based filter function to a limited set.

**Comment by jan-janssen** [comment]
Sounds like a good idea to me. At the moment it is using `get_job_ids()` from the project:

https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L276 and https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L303

So if you add a `database_filter_function` property and implement a database filter at the two lines above, it should be fine.

**Comment by jan-janssen** [comment]
I created a corresponding function in https://github.com/pyiron/pyiron/pull/601
