### ISSUE TITLE
Creating a project from Filtered Data

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#604]
Usually, I load a project and filter data, but, can I do the opposite? For example, I want to get output from the sub-project according to my filtration. Let's say that `df = pr.job_table()` is a kind of `pandas.core.frame.DataFrame
` which is created from a `pyiron.project.Project`. So, I am asking if I can get `pyiron.project.Project` from `pandas.core.frame.DataFrame` which will save me a lot of time.

**Comment by jan-janssen** [comment]
Do you mean in relation to `iterjobs()`? You can always iterate over a list of `job_ids` using the `inspect()` function and this is what you get from the Dataframe. The project is for file based access and the `job_table()` with the resulting Dataframe is for database based access. Therefore they always exist together. For the pyiron table object @sudarsan-surendralal is currently working on implementing a database based filter, but that is what we already discussed in your previous issue https://github.com/pyiron/pyiron/issues/600 .

**Comment by ibrsam** [comment]
I mean firstly I load the entire data which I am going to filter later. Then, after filtration let's say using `df_new = df.loc[df['job'].str.contains('anything')]`. Then, after defining my filter or `get_something functions`, I want to access only a project of the filtered data. So, let's say a project of `df_new`. Currently, I am using `pr.inspect(job_id)` but with looping over the whole data which I do not need.

**Comment by jan-janssen** [comment]
No, if you loop over the job_ids in your reduced data frame, there is no overhead:
```
for job_id in df_new['id'].values:
    pr.inspect(job_id)
```
