### ISSUE TITLE
write method does not work

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pyiron#606]
If a structure is created in pyiron using `create_ase_bulk`, and try to write it to a file using `structure.write`, the following error is generated-
```
AttributeError: 'Atoms' object has no attribute 'get_cell_lengths_and_angles'
```
However if method `write_poscar` is imported from `pyiron.vasp.structure`, it works.

**Comment by jan-janssen** [comment]
`from pyiron import pyiron_to_ase`

https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L4287

**Comment by srmnitc** [comment]
Thanks! But I think the write function should be handled somehow. Either raise a warning or convert it internally. It is a little bit confusing when the API documentation lists the method, and it does not work.

**Comment by jan-janssen** [comment]
@sudarsan-surendralal or @samwaseda  Can one of you take a look at this?
