### ISSUE TITLE
Update Structure Notebook

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#609]
@sudarsan-surendralal Can you update the structure example notebook? 
https://github.com/pyiron/pyiron/blob/master/notebooks/structures.ipynb 
After the recent changes in https://github.com/pyiron/pyiron/pull/603 and https://github.com/pyiron/pyiron/pull/607 it should no longer be necessary to create a pyiron project.

**Comment by sudarsan-surendralal** [comment]
But isn't the idea of creating these objects from the project class "pyironic"? I mean didn't we do this to reduce the number of imports?

**Comment by jan-janssen** [comment]
Originally yes, but if I remember correctly @liamhuber and @samwaseda explicitly asked for this feature to be able to create structures without the need to create a project.

**Comment by jan-janssen** [comment]
Done in https://github.com/pyiron/pyiron/pull/617 - so I close this issue.
