### ISSUE TITLE
Learning about decorators in Python 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#610]
For those of you who always wondered what the `@property` command does: 
https://realpython.com/primer-on-python-decorators/#simple-decorators
It is basically a function to modify functions defined in Python. The discussion recently came up in a pull request https://github.com/pyiron/pyiron/pull/592#pullrequestreview-398797489 therefore we should think about implementing a corresponding decorator in pyiron. 

For if anybody is interested to work on this issue feel free to assign yourself and open a pull request. I am looking forward for active discussions.

**Comment by jan-janssen** [comment]
I just noticed that Aiida is already using decorators in their code: 
https://github.com/aiidateam/aiida-tutorials/blob/master/docs/pages/2019_IIT_Mandi_India/sections/workflows.rst

**Comment by sudarsan-surendralal** [comment]
Apart from the basic `@property` decorator, I'm not too familiar with the advanced usage of decorators. Maybe we can discuss this in our pyiron meetings?

**Comment by jan-janssen** [comment]
The idea would be to define our own decorators like: `@calc_md` this would allow us to modify the function the user is accessing beyond the code the developer writes when implementing the module. Basically it would solve the issue with `set_kpoints` and `_set_kpoints` we would simply write:
```
@set_kpoints 
def set_kopints(self):
      <code specific function>     
```
