### ISSUE TITLE
Unable to read the CONTCAR file to Atoms object

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pyiron#613]
After running a vasp calculation, when  trying to extract the CONTCAR to atoms object using `job.get_final_structure_from_file()`, the following error is generated-
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-e4f3739894f0> in <module>
----> 1 job_vasp.get_final_structure_from_file()

~/miniconda3/envs/pyiron_workshop/lib/python3.7/site-packages/pyiron/vasp/base.py in get_final_structure_from_file(self, filename)
    701                 output_structure = read_atoms(
    702                     filename=filename,
--> 703                     species_list=input_structure.get_parent_elements(),
    704                 )
    705                 input_structure.cell = output_structure.cell.copy()

~/miniconda3/envs/pyiron_workshop/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in __getattr__(self, item)
   2876         if item in self._tag_list.keys():
   2877             return self._tag_list._lists[item]
-> 2878         return object.__getattribute__(self, item)
   2879 
   2880     def __len__(self):

AttributeError: 'Atoms' object has no attribute 'get_parent_elements'
```
Is there some other way to visualise the OUTCAR file?

**Comment by sudarsan-surendralal** [comment]
Yeah, that seems to be a bug. Simply use `job.get_structure(-1)` to get the final structure

**Comment by jan-janssen** [comment]
The `-1` is optional and an alternative function which internally calls the same command would be `job.get_final_structure()`. In pyiron the output files are parsed directly after the calculation and the results are stored in the HDF5 file. You can access also it using `job['output/generic/positions']` or alternatively `job.output.positions` and respectively `job.output.cell` . To see a list of all generic properties type `job['output/generic']`.

**Comment by sudarsan-surendralal** [comment]
Fixed and merged here https://github.com/pyiron/pyiron/pull/614. @srmnitc, feel free to close this if you are satisfied!

**Comment by srmnitc** [comment]
Great @sudarsan-surendralal thanks a lot for the quick bug fix!
