### ISSUE TITLE
git installation instructions

### ISSUE THREAD

**Issue by ashtonmv** [pyiron/pyiron#643]
Would it make sense to add something like this to the README below the conda installation instructions, to help people who want to develop their own pyiron features? Right now I'm afraid it's somewhat difficult for an outsider to know where pyiron's dependencies are (at least for us old-fashioned requirements.txt people). Unless there's a good reason to keep it there, we might also consider moving environment.yml to the main folder instead of .ci_support.

**git (developmental) install**
Alternatively, the developmental version can be installed from this repository:

    git clone https://github.com/pyiron/pyiron.git

Then install all dependencies (we recommend managing these with conda):

    conda install -f pyiron/.ci_support/environment.yml

**Comment by jan-janssen** [comment]
I am open to adding it to the readme, I guess we should just discuss some more alternatives: 

We could use: 
```
pip install git+https://github.com/pyiron/pyiron.git
```
or: 
```
git clone https://github.com/pyiron/pyiron.git
pip install . 
```

The same master branch version is available via: 
```
pip install --pre pyiron 
```

Finally if we first install pyiron via conda then all the dependencies are installed via conda and only the pyiron package is installed via pip. This would be my recommendation: 
```
conda install -c conda-forge pyiron
pip install --pre pyiron 
```

**Comment by ashtonmv** [comment]
I like it! I figured you would have some more elegant recommendation. I'm happy with whatever you want, but if I install with pip it's not really a git version, just a frozen copy of the branch, right? So for a git installation I personally like your second recommendation

    git clone https://github.com/pyiron/pyiron.git
    pip install .

because I think most people who would want a pre-released version will be developers/hopeful contributors, and imo git is cleaner for developing than pip or conda.

**Comment by jan-janssen** [comment]
In pyiron every commit to the master branch results in a new pip pre release: 
https://pypi.org/project/pyiron/#history

**Comment by ashtonmv** [comment]
Yes pip is definitely good for pulling our latest changes, but anyone trying to contribute will also want a route to save/share their own changes. Now that I think of it, maybe git installation instructions don't belong in the README, but rather in a CONTRIBUTING.md ([like this excessively detailed one](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)), which could also contain some guidelines for creating pull requests, issues, etc. I think something like that would lower the bar for new/external contributors to join the development, if that's what we want.

**Comment by jan-janssen** [comment]
@ashtonmv Sounds like a great idea to me. Maybe you can open up a pull request with a first draft and then we can continue from there.
