### ISSUE TITLE
VASP job .calc_static() non-complete settings

### ISSUE THREAD

**Issue by yury-lysogorskiy** [pyiron/pyiron#648]
### Workflow to reproduce the error
Step 1. Run minimization
```
vasp_opt_job = ... setup full relaxation job ... 
vasp_opt_job.calc_minimize(pressure=0.0)
```

Step 2. Run phonopy on optimized structure
```
vasp_engine = subpr.create_job(pr.job_type.Vasp, "vasp_engine")
vasp_engine.input = deepcopy(vasp_opt_job.input)
vasp_engine.structure =vasp_opt_job.get_final_structure()
vasp_engine.calc_static()
phonopy_job = ...setup phonopy job...
phonopy_job.ref_job = vasp_engine
phonopy_job.run() # on cluster
```

ends up with 100x **useless** VASP ionic iterations  for each of phonopy subjob on the cluster

### Explanation
[vasp_engine.calc_static()](https://github.com/pyiron/pyiron/blob/master/pyiron/vasp/base.py#L942) setup
incar["IBRION"] = -1
incar["NELM"] = electronic_steps (or default)

However NSW=100 remains from the previous copied input.
As stated in [official VASP documentation](https://cms.mpi.univie.ac.at/vasp/vasp/IBRION_1.html)
> IBRION=-1
> No update; ions are not moved, but NSW outer loops are performed. In each outer loop the electronic degrees of freedom are re-optimized (for NSW$ >$0 this obviously does not make much sense, except for test purposes). If no ionic update is required use NSW=0 instead.

So, the incar["NSW"] = 0 should be also setup in the calc_static()

**Comment by sudarsan-surendralal** [comment]
Thanks for pointing this out. Have opened a pull request for this: https://github.com/pyiron/pyiron/pull/650
