### ISSUE TITLE
calc_minimize within LAMMPS is not working

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#665]
It complains as following:
```
-----------------------------------------------------------------------------------
/u/system/SLES12/soft/pyiron/dev/pyiron_mpie/pyiron/pyiron/lammps/base.py in calc_minimize(self, e_tol, f_tol, max_iter, pressure, n_print, style)
    597             n_print=n_print,
    598             style=style,
--> 599             rotation_matrix=self._prism.R
    600         )
    601     calc_minimize.__doc__ = LammpsControl.calc_minimize.__doc__

AttributeError: 'NoneType' object has no attribute 'R'
--------------------------------------------------------------------------------------
```
Any suggestion for this? Many thanks in advance.

**Comment by jan-janssen** [comment]
Please first assign a structure before calling `calc_minimize()`: 

This works: 

```
job = pr.create_job(pr.job_type.Lammps, 'lmp')
job.structure = pr.create_structure('Fe', 'bcc', 2.78)
job.calc_minimize()
```

This gives the error message above: 

```
job = pr.create_job(pr.job_type.Lammps, 'lmp')
job.calc_minimize()
```

Still I guess it would be nice to raise a warning that no structure is set.

**Comment by lfzhu-phys** [comment]
Thanks, Jan. I am using machine learning potential with our automated interface method.
The error occurs even when the structure is assigned. Is that mean pr.job_type.LammpsMlip not working?

**Comment by jan-janssen** [comment]
I have not worked with the Mlip potentials for quite some time but they were working for me. @pmrv recently looked into the Mlip potentials, maybe he can comment on this. But in general the error message you posted above simply says no structure is set, that is the only reason why `self._prism` can be `None`. So it seems the error is somewhere else.

**Comment by pmrv** [comment]
Iirc the error was MlipLammps deriving from LammpsBase not from LammpsInteractive and that messed with the `self._prism`.  I have a fix for this on my fork, will open a PR after ADIS. ;)

**Comment by lfzhu-phys** [comment]
Thanks, Jan. I will check it again and keep you posted about this issue.

**Comment by lfzhu-phys** [comment]
> Iirc the error was MlipLammps deriving from LammpsBase not from LammpsInteractive and that messed with the `self._prism`. I have a fix for this on my fork, will open a PR after ADIS. ;)

That's great. Thanks a lot:)

**Comment by lfzhu-phys** [comment]
Jan has solved this issue. It's working now:)

Thanks a lot:)
