### ISSUE TITLE
VASP: "ZBRENT: fatal error: bracketing interval incorrect" not captured

### ISSUE THREAD

**Issue by FeLoch** [pyiron/pyiron#668]
If you run a calculation using` IBRION = 2`, the calculation can stop and you will get the following error:

> ZBRENT: fatal error: bracketing interval incorrect
> please rerun with smaller EDIFF, or copy CONTCAR
> to POSCAR and continue

So far pyrion ignores it and sets the status to `"finished"`. The user will never know, that the calculation has not converged. Look at [this page](https://www.vasp.at/forum/viewtopic.php?t=7415) for details.

**Comment by jan-janssen** [comment]
I guess we discussed this before in https://github.com/pyiron/pyiron/pull/356 and https://github.com/pyiron/pyiron/pull/356 @sudarsan-surendralal Can you comment on this?

**Comment by sudarsan-surendralal** [comment]
Can we reopen merge requests? There seems to be two of them doing the same thing

**Comment by FeLoch** [comment]
I used #356, because it is the first request for this issue.
