### ISSUE TITLE
new flexible input handling

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#674]
We had already discussed (in #592 and off Github) that we'd like to have a new data structure to handle the various input files in pyiron.  

I made a [prototype binder](https://mybinder.org/v2/gist/pmrv/48b55796e266b2d49aa78e0a7601fa91/master?filepath=proplist.ipynb) so we can discuss whether that solves all our use cases.  I decided against subclassing [Box](https://github.com/cdgriffith/Box), because they don't preserve order (which we wanted to have for sphinx) and it seemed more complex than what we need.  Whereas box is more of an extensive dictionary, I tried more to make a list that you can also access with keys. 

There's a bunch of examples in the binder, if you think something is missing let me know or we can discuss the details tomorrow.  My next idea would be that I have @ashtonmv 's `Group` subclass from this, because it has the sphinx logic already and then work on switching Lammps input over to this.

**Comment by ashtonmv** [comment]
@pmrv this looks awesome! I'm still playing with it, but it seems to work very well.

Could we create a to_dict() method to represent it as a true dict object when needed? Within that method I guess we could just assign `None` or `True` as the value for non-key/value items. If we can get it to be a clean, serializable object then it should be easy to implement `Ipython.display.JSON` within __repr__ or __str__. That would be my favorite way to "print" the input as a collapsible nested object in Jupyter, although it looks like [it might not be supported everywhere](https://stackoverflow.com/questions/18873066/pretty-json-formatting-in-ipython-notebook).

**Comment by pmrv** [comment]
Sure that would be easy.  I really like the idea of the collapsible output and will look into the details for tomorrow.  For now I added a custom json encoder to the gist, so you can serialize to json with
```python
>>> p = proplist.PropList({'foo': [1,2,3], 'bar': {'next': 42}})
>>> json.dumps(p, cls = proplist.PropListJSONEncoder)
'{"foo": [1, 2, 3], "bar": {"next": 42}}'
```

**Comment by pmrv** [comment]
I added `_repr_json_` which allows jupyter to render the lists as json.  If I understand this right [this](https://jupyterlab.github.io/jupyterlab/json-extension/index.html) extension must be enabled for it to work.  On my machine that worked out of the box, for mybinder I had to activate the extension manager (Commands [Ctrl-C] -> Extensions -> Enable Extension Manager) after spinning up the instance.
