### ISSUE TITLE
Inconsistencies between pyiron `Atoms` and ase `Atoms`

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#677]
## Problem

Consider the following snippet:
```
from ase.atoms import Atoms as ASEAtoms
from pyiron import Atoms
struct = Atoms()
print(isinstance(struct, ASEAtoms))
```
If you run this for the first time, the output is `False`. But if you execute this in a jupyter notebook cell for the second time, the output is `True`.

## Reason

When you import the `ASEAtoms` class for the first time, it points to the ase `Atoms` class. However, once we import pyiron's atoms class, the `ase.atoms` class is forced to point to pyiron's atoms class

https://github.com/pyiron/pyiron/blob/62929d56046d480179a9f14fb4a72b5fde441820/pyiron/atomistics/structure/pyironase.py#L25-L26

## Why this is dangerous
 
This leads to issues with using ase writers https://github.com/pyiron/pyiron/issues/663 (ASE checks if the structure is an ase `Atoms` instance before writing them), and inconsistencies with the testing for this pull request https://github.com/pyiron/pyiron/pull/664 (they pass/fail depending on when the class is executed). 

## What should be done (IMO)

I think the above lines should be removed because it was intended to be a temporary hack. Since we now have the `ase_to_pyiron` function, we could use that to convert ase generated structures to pyiron structures.

**Comment by jan-janssen** [comment]
But then we break the old behaviour, because ASE and all classes which rely on ASE atoms returns ASE atoms rather than pyiron atoms. If we do this step would not it be more consistent to derive our atoms class from the ASE atoms class?
