### ISSUE TITLE
sphinx test want odd version

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#685]
I was trying to run the sphinx tests locally and the two lines below gave me some problems.  As the pyiron resources ship scripts for 2.6.1 (not 2.6 or 2.6.2) this throws exceptions on my machine.  I guess I messed up my setup somehow and I fixed it locally for my version now (so it's not critical), but still I was wondering what's the motivation in not using the default version or one we don't "officially" depend on.  

https://github.com/pyiron/pyiron/blob/31e12d80a36223a159af3dcadce848df13e09c11/tests/sphinx/test_base.py#L71-L73****

**Comment by jan-janssen** [comment]
Instead of requiring the full pyiron resources https://github.com/pyiron/pyiron-resources  we use a reduced set of resources in https://github.com/pyiron/pyiron/tree/master/tests/static/ . Still I agree the version should be 2.6.1 instead of 2.6 .

**Comment by pmrv** [comment]
Ah, I didn't see those.  I'll just update it here then, if nobody has other reasons.
