### ISSUE TITLE
make error.msg readable

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#702]
I find it often very difficult to understand the content of `error.msg`, because it's apparently written in jupyter format, but not formatted properly. Is there a way to make it more readable?

**Comment by jan-janssen** [comment]
`cat error.msg` works while `vim error.msg` if I remember correctly

**Comment by samwaseda** [comment]
Thanks! `cat error.msg` indeed worked (and `vim error.msg` didn't). I'm gonna close this issue, but I guess people would appreciate it more if there was a way to do it in the browser.

**Comment by jan-janssen** [comment]
I found the following example:
https://www.tutorialspoint.com/How-can-I-remove-the-ANSI-escape-sequences-from-a-string-in-python
```
import re
def escape_ansi(line):
    ansi_escape =re.compile(r'(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]')
    return ansi_escape.sub('', line)
print(escape_ansi(line = '\t\u001b[0;35mSomeText\u001b[0m\u001b[0;36m172.18.0.2\u001b[0m'))
```
Can you try if it works with: 
```
job.decompress()
job["error.msg"]
```
 It would be good if pyiron was able to remove the colouring for internal error storage.

**Comment by samwaseda** [comment]
Actually I just realised that with no further extension `print(''.join(job['error.msg']))` does exactly what it needs, even with colouring.

**Comment by jan-janssen** [comment]
@samwaseda Can you add this to https://github.com/pyiron/pyiron/pull/646 ? - under additional information. I can imagine multiple please struggling with this.

**Comment by samwaseda** [comment]
I'm not sure if this should be the standard way or seeing the error messages. I have the feeling that there should be a generic function that looks for/shows potential errors.

**Comment by jan-janssen** [comment]
I guess all I want is some benefit from this discussion. So either we implement a quick `job.show_error()` function which executes these lines automatically - or at least have a `show_error(job)` function in the developers documentation, that everybody can copy and paste. Most likely it is even possible to extract just this single file from the tar and read it, but that would already be the next level.

**Comment by samwaseda** [comment]
Ok I can talk about this one at the next pyiron meeting.

**Comment by jan-janssen** [comment]
Thx - so let me reopen the issue that we have it on the agenda for the next meeting.

**Comment by samwaseda** [comment]
I guess the best would be to have something like `job['file'].print()`, which does `print(''.join(job['file']))`. Even better would be to pass the argument for the print string in `print()`, which means it's gonna be more like `print(string.join(job['file']))`. I wanted to implement this myself, but didn't know how to do it, because this would be a function on the return value of `__getitem__`...

**Comment by jan-janssen** [comment]
The ugly way would be to have a separate `if` for `error.msg` files inside the `__getitem___` function.

**Comment by samwaseda** [comment]
> The ugly way would be to have a separate `if` for `error.msg` files inside the `__getitem___` function.

Maybe we should extend `class Output` or create a similar one, because we are now talking about individual cases as we did for output values (like `total_displacements`, which behaves like an output tag but in reality pyiron calculates the values internally).
