### ISSUE TITLE
Protocol jobs not running on the queue

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron#703]
Since last week, all protocol jobs submitted to the queuing system return this error immediately after creating the sub jobs within the protocol:

```
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/rads/pyiron_repos/pyiron/pyiron/base/job/wrappercmd.py", line 52, in <module>
    command_line(sys.argv[1:])
  File "/u/rads/pyiron_repos/pyiron/pyiron/base/job/wrappercmd.py", line 46, in command_line
    submit_on_remote=submit_on_remote
  File "/u/rads/pyiron_repos/pyiron/pyiron/base/job/wrapper.py", line 147, in job_wrapper_function
    job.run()
  File "/u/rads/pyiron_repos/pyiron/pyiron/base/job/wrapper.py", line 113, in run
    self.job.run_static()
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py", line 642, in run_static
    self.execute()
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py", line 636, in execute
    super(Protocol, self).execute()
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py", line 437, in execute
    self.update_and_archive(self.get_output())
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/compound/neb.py", line 163, in get_output
    'energy_pot': ~gp.calc_static.output.energy_pot[-1],
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/utils/pointer.py", line 279, in __invert__
    return self.resolve()
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/utils/pointer.py", line 282, in resolve
    return self._resolve_function(self._resolve_path())
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/utils/pointer.py", line 237, in _resolve_path
    result = getattr(result, crumb_name)
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/utils/dictionaries.py", line 53, in __getattr__
    return self.__getitem__(item)
  File "/u/rads/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/utils/dictionaries.py", line 65, in __getitem__
    return super(IODictionary, self).__getitem__(item)
KeyError: 'energy_pot'
```
Usually, we run into this error only when a particular vertex has not run, and hence has no output (here, `'energy_pot'`) in its output dictionary. @jan-janssen, @liamhuber, have any recent changes been made that could be causing this behavior with protocol jobs?

**Comment by raynol-dsouza** [comment]
Just to clarify though, the jobs run perfectly fine on the head node.

**Comment by jan-janssen** [comment]
I guess this is related to https://github.com/pyiron/pyiron/pull/678 and https://github.com/pyiron/pyiron/pull/676 - you can always go back to https://github.com/pyiron/pyiron/tree/pyiron-0.2.14 to revert these changes. Basically what changed is that we no longer index all classes automatically but instead only index them when we import the module or are able to reload the class when the module is stored in the TYPE.

**Comment by raynol-dsouza** [comment]
I modified already the `__init__.py` of `pyiron_conrib` to a similar format as `pyiron_mpie` (as you had suggested after the pyiron meeting yesterday). I think that is what  [#678](https://github.com/pyiron/pyiron/pull/678) and [#676](https://github.com/pyiron/pyiron/pull/676) refer to. The issue still persists.

Will reverting back to [pyiron-0.2.14 ](https://github.com/pyiron/pyiron/tree/pyiron-0.2.14) still make sense if the above commits were the only things modified?

**Comment by jan-janssen** [comment]
Can you check that after importing your class the classes become available in: 
```
import pyiron_contrib
dir(pr.job_type)
```

In addition can you show me what is inside:
```
job["TYPE"]
```

**Comment by raynol-dsouza** [comment]
Yes. The classes are available in `dir(pr.job_type)` after importing `pyiron_contrib`.

`job["TYPE"]` however is None.

**Comment by jan-janssen** [comment]
First - this means the new `__init__.py` file is working correctly. 

Second - In a new notebook, please try creating the same job and instead of calling `job.run()` call `job.save()` and afterwards look into `job["TYPE"]` - at least this should not return `None`.

**Comment by raynol-dsouza** [comment]
Second - Checked this. It does not return `None`.

It returns `"<class 'pyiron_contrib.protocol.compound.md.ProtoMD'>"`

**Comment by jan-janssen** [comment]
And you can import it like: 
```
from pyiron_contrib.protocol.compound.md import ProtoMD
```
Right? 

Can you try? 
```
type(job.project_hdf.create_object(class_name=job["TYPE"]))
``` 

That is what is happening in https://github.com/pyiron/pyiron/pull/676

**Comment by raynol-dsouza** [comment]
First: Yes.

Second: I get the following error message:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-6-1b93df85cf17> in <module>
----> 1 type(md.project_hdf.create_object(class_name=md["TYPE"]))

AttributeError: 'ProtoMD' object has no attribute 'project_hdf'
```

**Comment by jan-janssen** [comment]
Sorry my mistake it is `project_hdf5` rather than `project_hdf`

**Comment by raynol-dsouza** [comment]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-752e4ac3a1f9> in <module>
----> 1 type(md.project_hdf5.create_object(class_name=md["TYPE"]))

~/pyiron_repos/pyiron/pyiron/base/generic/hdfio.py in create_object(self, class_name, **qwargs)
   1243             pyiron object: defined by the pyiron class in class_name with the input from **qwargs
   1244         """
-> 1245         internal_class_name = class_name.split(".")[-1][:-2]
   1246         if internal_class_name in self._project.job_type.job_class_dict.keys():
   1247             module_path = self._project.job_type.job_class_dict[internal_class_name]

AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jan-janssen** [comment]
It seems like `md["TYPE"]` is `None` again. 

Please try: 
```
type(job.project_hdf5.create_object(class_name="<class 'pyiron_contrib.protocol.compound.md.ProtoMD'>"))
```

**Comment by raynol-dsouza** [comment]
Sorry, I had not executed `md.save()`.

After running the above command, I get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py in __init__(self, **kwargs)
     63         try:  # Super magic when the inheritance path is just vertices
---> 64             super(Vertex, self).__init__()
     65         except TypeError:  # Super magic when the inheritance path includes GenericJob (i.e. for a Protocol)

TypeError: __init__() missing 2 required positional arguments: 'project' and 'job_name'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-10-a1a8b20ce3ab> in <module>
----> 1 type(md.project_hdf5.create_object(class_name="<class 'pyiron_contrib.protocol.compound.md.ProtoMD'>"))

~/pyiron_repos/pyiron/pyiron/base/generic/hdfio.py in create_object(self, class_name, **qwargs)
   1253             importlib.import_module(module_path),
   1254             internal_class_name,
-> 1255         )(**qwargs)
   1256 
   1257     def to_object(self, object_type=None, **qwargs):

~/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py in __init__(self, project, job_name)
    630 
    631     def __init__(self, project=None, job_name=None):
--> 632         super(Protocol, self).__init__(project=project, job_name=job_name)
    633         self.vertex_name = job_name
    634 

~/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/compound/md.py in __init__(self, **kwargs)
     71 
     72     def __init__(self, **kwargs):
---> 73         super(MolecularDynamics, self).__init__(**kwargs)
     74 
     75         # Protocol defaults

~/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py in __init__(self, **kwargs)
    354     """
    355     def __init__(self, **kwargs):
--> 356         super(CompoundVertex, self).__init__(**kwargs)
    357 
    358         self.graph = Graph()

~/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py in __init__(self, **kwargs)
     64             super(Vertex, self).__init__()
     65         except TypeError:  # Super magic when the inheritance path includes GenericJob (i.e. for a Protocol)
---> 66             super(Vertex, self).__init__(**kwargs)
     67         self.input = InputDictionary()
     68         self.output = IODictionary()

~/pyiron_repos/pyiron/pyiron/base/job/generic.py in __init__(self, project, job_name)
    152 
    153     def __init__(self, project, job_name):
--> 154         super(GenericJob, self).__init__(project, job_name)
    155         self.__name__ = "GenericJob"
    156         self.__version__ = "0.4"

~/pyiron_repos/pyiron/pyiron/base/job/core.py in __init__(self, project, job_name)
     95         self._is_valid_job_name(job_name)
     96         self._name = job_name
---> 97         self._hdf5 = project.open(self._name)
     98         self._job_id = None
     99         self._parent_id = None

AttributeError: 'NoneType' object has no attribute 'open'
```

**Comment by jan-janssen** [comment]
That looks good, we did not provide the project and job name, but it seems to be able to resolve the class. Can you try? 

```
job_core = pr.inspect(job.job_id)
type(job_core.to_object())
```

Again make sure `job['TYPE']` is not `None` - this should provide the right arguments.

**Comment by raynol-dsouza** [comment]
It returns: `pyiron_contrib.protocol.compound.md.ProtoMD`

**Comment by jan-janssen** [comment]
Now I am confused, because this means also: 

```
job_new = pr.load(job.job_id)
type(job_new)
```

Works right? And that is basically what pyiron is doing. 

Can you please try to create the job in one notebook and then open a new notebook and basically only import the project from pyiron and try to reload the job using its `job_id` ?

**Comment by raynol-dsouza** [comment]
Yes, it does load the same old `ProtoMD` job in a different notebook, which does not import `pyiron_contrib`.

**Comment by jan-janssen** [comment]
Then I do not see why it should not work with the queuing system.

**Comment by jan-janssen** [comment]
Can you try creating a small job, saving it in one notebook and then reload it in another notebook and try to execute it there? That is basically exactly what we do when we submit a Job to the queue.

**Comment by raynol-dsouza** [comment]
Did that. Unfortunately end up getting the same error that I got initially.

**Comment by jan-janssen** [comment]
Then it seems to be specific to the protocols, you should now be able to compare both objects, the one in the original notebook and the one in the reloaded notebook to identify which part is broken. The big advantage is that you can now interactively debug the behavior of what happens when your job is executed in the queue.

**Comment by raynol-dsouza** [comment]
I know this isn't the ideal way of resolving bugs, but doing this worked:

It was indeed a problem concerning protocols and to be specific, my branch. I switched to the master branch which is several commits behind, and found out that the protocol jobs didn't throw any errors. 

While trying to get protocols to run parallelly in the last two weeks, I may have modified some part of the code (or put an unnecessary comma) in my branch. I could not isolate where the problem was coming from, so I cloned the master branch, and replaced only the code that set up parallel protocols. The jobs are now running properly on the queue.

**Comment by jan-janssen** [comment]
Congrats, I am happy it helped. Maybe you can add a few lines about how to debug jobs that fail when submitting to the queue to https://github.com/pyiron/pyiron/blob/master/CONTRIBUTING.rst - basically a short summary of what we discussed here, as a future reference for others.

**Comment by raynol-dsouza** [comment]
Will do. Thanks for the help! :)
