### ISSUE TITLE
pyiron on iOS / Apple iPad 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#707]
With more and more students using their iPads during lectures to write down their notes, we should make sure to provide access to pyiron for iOS devices. 

Currently I mainly use pyiron with mybinder: 
![out](https://user-images.githubusercontent.com/3854739/83399096-e5c3ef80-a400-11ea-9e08-8cd4679817f1.gif)

The apps I use: 

- https://termius.com - for ssh tunnels 
- https://workingcopyapp.com - for accessing the git repository and making changes 
- https://juno.sh/junoconnect/ - for accessing mybinder - **demonstrated above** - it can also be used to access our cluster, but the notebooks can not be executed on the cluster as we use https (to prevent other users of the cluster from accessing our sessions) and port forwarding (to prevent public access).  

Maybe others could share their experience as well.

**Comment by jan-janssen** [comment]
@SanderBorgmans If I remember correctly you also use iPads for lectures at UGent, maybe you have a few more suggestions for us.

**Comment by jan-janssen** [comment]
Joerg suggested https://apps.apple.com/us/app/carnets-jupyter/id1450994949 to open notebooks locally on iOS devices.

**Comment by SanderBorgmans** [comment]
> @SanderBorgmans If I remember correctly you also use iPads for lectures at UGent, maybe you have a few more suggestions for us.

Hi Jan, thanks for the update. I'm afraid I won't be able to give many suggestions, as my current use for lectures is limited to preparing notes using the notability app. But I am surely open to new uses!
