### ISSUE TITLE
creating slab and visualisation 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#708]
<img width="913" alt="Screenshot 2020-06-03 at 23 13 14" src="https://user-images.githubusercontent.com/62750893/83689825-fedec300-a5ef-11ea-9aee-9125a51a0220.png">

I wanted to create a slab and visualized it via pyiron.
I already tried two different way of the way as attachment picture anyone had the idea why it does not view the slab?

**Comment by mostafajoulaian** [comment]
<img width="945" alt="Screenshot 2020-06-03 at 23 17 36" src="https://user-images.githubusercontent.com/62750893/83690125-7280d000-a5f0-11ea-83b3-2dcbb17bde1d.png">
as below picture, the code is superfine, and it works very well, but I want to see my structure in each step of calculation I know it is possible via a separate tool like VESTA. I am just wondering to know do we have any helpful feature in pyiron to do it interactively in the notebook

**Comment by jan-janssen** [comment]
You need to import the cut function:
https://wiki.fysik.dtu.dk/ase/ase/build/tools.html

```
from ase.build import cut
```

**Comment by mostafajoulaian** [comment]
Thank you for your response but my question is actually related to viewing the slab.
it seems:
"ase.visualize.view" term does not work 
<img width="958" alt="Screenshot 2020-06-04 at 09 43 55" src="https://user-images.githubusercontent.com/62750893/83729901-9a038700-a648-11ea-883e-8b2053fa808b.png">


how about my second question? 
dose pyiron has a possibility to visualize POSCAR file directly ? or I should use another program like VESTA

**Comment by jan-janssen** [comment]
At the moment you are using ASE rather than pyiron. To convert an ASE structure you can use: 

```
from pyiron import ase_to_pyiron
ase_to_pyiron(slab).plot3d()
```
