### ISSUE TITLE
Job status not refreshing

### ISSUE THREAD

**Issue by FeLoch** [pyiron/pyiron#714]
If you create job and submit it to a queueing system, the status of the job won't update automatically.

To get the correct status you have to run `job.refresh_job_status()` before.

**Comment by jan-janssen** [comment]
How do you check the status? `job.status.finished` should work. We had a similar discussion in https://github.com/pyiron/pyiron/pull/426

**Comment by FeLoch** [comment]
I just used `job.status`. For me this should always return the correct status of the job.

**Comment by jan-janssen** [comment]
The issue is the communication over the database is a bottleneck, in particular for people who do not have access to an postgresql database. So at the moment the attributes are updated from the database but the string is not. Though that is not very consistent.

**Comment by FeLoch** [comment]
Sure, I uderstand, but still `job.status` should return the correct status, what it doesn't. Since this function is not called frequently, wouldn't it be fine to use the database? Otherwise we can update the string when updating the attributes.

**Comment by jan-janssen** [comment]
I agree but we have to keep track of the number of database requests, so I would recommend checking the previous job status and only update it if it is running, collect or submitted.

**Comment by FeLoch** [comment]
I like this!

**Comment by jan-janssen** [comment]
Maybe you can add such a check to https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/jobstatus.py#L181
