### ISSUE TITLE
Deprecation warning not shown

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#718]
I was creating a new deprecation warning in `atoms.py` and realized that it was not shown when used in the notebook. I can see the same problem e.g. for `structure.get_voronoi_volume()`. Am I missing something?

**Comment by jan-janssen** [comment]
Maybe it is related to the warning filters: 
https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L1255

**Comment by jan-janssen** [comment]
Can you share an example?

**Comment by samwaseda** [comment]
```
from pyiron import Project
Project('.').create_structure('Fe', 'bcc', 2.8).get_voronoi_volume()
```

**Comment by samwaseda** [comment]
I put `warnings.filterwarnings("default")` right before `class Atoms(object)` and now it worked. So I guess it's changed somewhere inside pyiron. Is it the right way to change it inside pyiron anyway?

**Comment by samwaseda** [comment]
Sorry my statement above seems to be wrong - I removed all `simplefilter` and `filterwarnings`, but it still doesn't show the warnings. I guess I'm simply going to put `warnings.filterwarnings("default")` in `atoms.py`.

**Comment by jan-janssen** [comment]
I do not think pyiron should change the the warnings filter, because then the user can no longer change it from the outside.

**Comment by samwaseda** [comment]
ok then what's the default procedure if I want to show the warning?

**Comment by jan-janssen** [comment]
This is very interesting, when I execute your example I do not get a warning either, but when I run: 

```
pr = Project('.')
struct = pr.create_structure('Fe', 'bcc', 2.8)
struct.get_voronoi_volume()
```
I get the warning. So there seems to be an issue with Jupyter.

**Comment by jan-janssen** [comment]
@samwaseda Can you close this issue? I guess we can not solve it at the moment as it is related to jupyter rather than pyiron.

**Comment by samwaseda** [comment]
Ok

**Comment by jan-janssen** [comment]
I tested it again on mybinder:
```
from pyiron import Project
Project('.').create_structure('Fe', 'bcc', 2.8).get_voronoi_volume()
```
gives no error message. But executing the command again: 
```
Project('.').create_structure('Fe', 'bcc', 2.8).get_voronoi_volume()
```
We get the error message.
