### ISSUE TITLE
503 : Service Unavailable Your server appears to be down. Try restarting it from the hub

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#722]
Does anyone have the same problem? I can not start my server. I have tried a few times to restart it from the hub, but it doesn't work.
Appreciate any suggestion:)

**Comment by FeLoch** [comment]
@jan-janssen : Do you know more about it?

**Comment by lfzhu-phys** [comment]
Problem solved:) That is because I reached the file number limit on the cluster.
@FeLoch Thanks:)

**Comment by jan-janssen** [comment]
To debug this kind of issues you can take a look at: 
```
tail -f /u/system/SLES12/soft/pyiron/dev/jupyterhub.cmti001.log
```

**Comment by jan-janssen** [comment]
And maybe we should add the quota command for future reference: 
```
/usr/lpp/mmfs/bin/mmlsquota --block-size auto
```

**Comment by lfzhu-phys** [comment]
@jan-janssen Thanks, Jan. I will record the debug command line:)

**Comment by jan-janssen** [comment]
Maybe we should even add these to the CM internal documentation as Mira suggested.
