### ISSUE TITLE
Error when executing jupyter notebooks 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#732]
During the automated tests of the jupyter notebook, we get the following error message: 
```
Traceback (most recent call last):
2489  File "/home/travis/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 693, in _finalize_fairy
2490    fairy._reset(pool)
2491  File "/home/travis/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 880, in _reset
2492    pool._dialect.do_rollback(self)
2493  File "/home/travis/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 538, in do_rollback
2494    dbapi_connection.rollback()
```
The tests finish successful, still it is confusing for new users so we should figure out what is causing this error. To me it seems to be related to the way we use SQLalchemy in combination with SQLite.

**Comment by pmrv** [comment]
It seems the error only appears when running the test via `python -m unittest ..`.  If you just run `python ..` it's not triggered.   Also when running a test under pdb you can run the full script multiple times and the errors is only triggered once you quit pdb.  My guess is that SQLalchemy install some weird atexit handlers or something similar and tries to clean up the connection even after we closed it from the pyiron side.

**Comment by jan-janssen** [comment]
Removing the` __del__` function in the settings object solved the issue, most likely it is anyway better to use the default garbage collection.
