### ISSUE TITLE
Structure species get mixed up when creating the lammps structure.inp file

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron#736]
If I assign the following structure to a job:

```
O: [1.9526 0.     0.    ]
O: [0.     1.9526 0.    ]
O: [0.     0.     1.9526]
Ti: [0. 0. 0.]
Sr: [1.9526 1.9526 1.9526]
pbc: [ True  True  True]
cell: 
[[3.90528 0.      0.     ]
 [0.      3.90528 0.     ]
 [0.      0.      3.90528]]
```
the `structure.inp` file created by pyrion before running the lammps job is written as:

```
Sr: [1.95260000e+00 1.19562267e-16 1.19562267e-16]
Sr: [0.00000000e+00 1.95260000e+00 1.19562267e-16]
Sr: [0.     0.     1.9526]
Ti: [0. 0. 0.]
O: [1.9526 1.9526 1.9526]
pbc: [ True  True  True]
cell: 
[[3.90528000e+00 2.39129433e-16 2.39129433e-16]
 [0.00000000e+00 3.90528000e+00 2.39129433e-16]
 [0.00000000e+00 0.00000000e+00 3.90528000e+00]]
```

Note: I am running a custom hybrid potential, which looks like this:

```
## create groups ##
group O type 1
group Ti type 2
group Sr type 3
 
## set charges - beside manually ##
set group O charge -1.2000
set group Ti charge 2.4000
set group Sr charge 1.2000
 
pair_style hybrid/overlay morse 15.0 mie/cut 15.0 coul/long 15.0 beck 15.0
pair_coeff * * coul/long
pair_coeff 1 3 beck 3.0 0 0 0 0
pair_coeff 1 2 beck 1.0 0 0 0 0
pair_coeff 1 1 beck 22.0 0 0 0 0
pair_coeff 1 3 mie/cut 3.0 1.0 12.0 0
pair_coeff 1 2 mie/cut 1.0 1.0 12.0 0
pair_coeff 1 1 mie/cut 22.0 1.0 12.0 0
pair_coeff 1 3 morse 0.019623 1.8860 3.32833
pair_coeff 1 2 morse 0.024235 2.2547 2.708943
pair_coeff 1 1 morse 0.042395 1.3793 3.618701
kspace_style ewald 1.0e-8.0
```

**Comment by jan-janssen** [comment]
Can you post your code? Either as inline example or simply attach the notebook? In addition please try it once with a three element potential provided with pyiron, so we are sure it works for the regular potentials. My assumption is it works if you use alphabetical ordering, meaning: 

```
group O type 1
group Ti type 3
group Sr type 2
```

**Comment by raynol-dsouza** [comment]
For this potential, there is no change if I use alphabetical ordering.

Attached is the notebook. [SrTiO3.zip](https://github.com/pyiron/pyiron/files/4776536/SrTiO3.zip)

I will check if this issue exists for a regular three element potential.

**Comment by jan-janssen** [comment]
I tried it with `Ni` `Al` `H`, that works without an issue, so it seems to be related to your potential. Can you post `job.potential ` for `Sr` `Ti` `O` ?

**Comment by raynol-dsouza** [comment]
Okay, I figured it out: The interaction coefficients were setup wrongly in the potential file that I created. I changed it to this:
```

## create groups ##
group O type 3
group Sr type 1
group Ti type 2
 
## set charges - beside manually ##
set group O charge -1.2000
set group Ti charge 2.4000
set group Sr charge 1.2000
 
pair_style hybrid/overlay morse 15.0 mie/cut 15.0 coul/long 15.0 beck 15.0
pair_coeff * * coul/long
pair_coeff 1 3 beck 3.0 0 0 0 0
pair_coeff 2 3 beck 1.0 0 0 0 0
pair_coeff 3 3 beck 22.0 0 0 0 0
pair_coeff 1 3 mie/cut 3.0 1.0 12.0 0
pair_coeff 2 3 mie/cut 1.0 1.0 12.0 0
pair_coeff 3 3 mie/cut 22.0 1.0 12.0 0
pair_coeff 1 3 morse 0.019623 1.8860 3.32833
pair_coeff 2 3 morse 0.024235 2.2547 2.708943
pair_coeff 3 3 morse 0.042395 1.3793 3.618701
kspace_style ewald 1.0e-8.0
```
and it works fine now.

**Comment by jan-janssen** [comment]
Can you still post your`job.potential` ?

**Comment by raynol-dsouza** [comment]
The potential is the same as posted above. I put in a new entry in the `potential_lammps.csv` in `resources ` setting up this potential.

**Comment by raynol-dsouza** [comment]
That would be this:

```
Config  \
0  [atom_style full\n, ## create groups ###\n, group O type 3\n, group Sr type 1\n, group Ti type 2\n, \n, ## set charges - beside manually ###\n, set group O charge -1.2000\n, set group Ti charge 2....   

                               Filename              Name   Model      Species  
0  [ananya_potential/SrTiO3_Pedone.pot]  Ananya_potential  Custom  [Sr, Ti, O]  
```

**Comment by jan-janssen** [comment]
The important point is that the order in the Species column - here: `[Sr, Ti, O]` matches the order in your potential file - here:
```
## create groups ##
group O type 3
group Sr type 1
group Ti type 2
```
Second there is no need for a potential file - `[ananya_potential/SrTiO3_Pedone.pot]` should be `[]` because you anyway include all the potential parameter in the `Config`. Here is an updated example for water: https://github.com/pyiron/pyiron/blob/find_potential_file/notebooks/water_MD.ipynb

**Comment by jan-janssen** [comment]
Can you add a short explanation to https://github.com/pyiron/pyiron/blob/master/docs/source/faq.rst ? I guess this could be relevant for other users as well.

**Comment by raynol-dsouza** [comment]
I was unaware about the second method specifying an input potential. This saves me some trouble, as I wouldn't want to modify my `potential_lammps.csv` every time I need to use a new potential.

I shall update [https://github.com/pyiron/pyiron/blob/master/docs/source/faq.rst](https://github.com/pyiron/pyiron/blob/master/docs/source/faq.rst) to include this issue.

Shall I close this issue?

**Comment by jan-janssen** [comment]
Sure, you can close the issue. 

I guess I should add - the recommended order is alphabetically, but in principle you can use any order, you just have to be consistent, as you nicely showed above.

**Comment by raynol-dsouza** [comment]
Shall I just update this as an answer to 'How to use a custom potential in LAMMPS'?

**Comment by jan-janssen** [comment]
Yes, that would be great.

**Comment by jan-janssen** [comment]
@raynol-dsouza Can you open the pull request today? Then we can discuss it in tomorrows meeting.

**Comment by raynol-dsouza** [comment]
Yes, I can. Sorry for the delay.
