### ISSUE TITLE
How to save and launch job in different notebooks

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#738]
I have two notebooks which do (more or less) the following:

Notebook 1:
```
job = Project('SPX').create_job('Sphinx', 'spx')
... job creation ...
job.save()
```

Notebook 2:
```
job = Project('SPX').load('spx')
job.run()
```

When I run these notebooks, it shows `job exists already and therefore was not created!` in the second notebook and pyiron refuses to run the job. Did I do it wrong?

**Comment by jan-janssen** [comment]
The save function, should not be used by the user - it is mainly an internal function. What do you try to achieve? If you want to execute the job in the second notebook you can use `job.run(run_again=True)`

**Comment by samwaseda** [comment]
The second notebook is Steepest Descent. I'd like to have full flexibility in the first notebook, e.g. containing SSA, ART etc. and it would be nice if the second notebook can be submitted to the queue and simply does steepest descent.

**Comment by jan-janssen** [comment]
Then you need a scrip job

**Comment by jan-janssen** [comment]
I still struggle to understand what you try to achieve.

**Comment by samwaseda** [comment]
Instead of creating a new pyiron class, I'm trying to create a notebook which does just one thing - steepest descent in this case, but then nothing else, so that this notebook can be considered as a class on its own. Ideally, it's like this:

Notebook 1
```
spx = Project('SPX').create_job('Sphinx', 'spx')
... job creation ...
spx.save()

scr = Project('SPX').create_job('ScriptJob', 'submit_spx')
scr.script_path = 'steepest_descent.ipynb'
scr.input['job_name'] = 'spx'
scr.run()
```

Notebook 2:
```
spx = Project(path_to_spx+'SPX').load(Project(...).get_custom_dict()['job_name'])
spx.run()
for force>0:
    ... steepest descent algorithm ...
```

**Comment by jan-janssen** [comment]
Sphinx - `spx` - is an interactive job right?

**Comment by jan-janssen** [comment]
Can you try `job.run(repair=True)` ?

**Comment by samwaseda** [comment]
> Sphinx - `spx` - is an interactive job right?

Yes

> Can you try `job.run(repair=True)` ?

With `job.project_hdf5.create_working_directory()` in the first notebook it doesn't complain but the job doesn't seem to be starting (it just shows the execution star in the notebook cell and doesn't advance).

**Comment by jan-janssen** [comment]
Can we arrange some meeting? Screen sharing? I either need the notebooks to try it myself or at least look at your screen.

**Comment by jan-janssen** [comment]
The following worked for me: 

```
from pyiron import Project
pr = Project('save')
structure = pr.create_ase_bulk("Al")
job = pr.create_job(pr.job_type.Lammps, "lmp")
job.structure = structure
job.potential = 'Al_Mg_Mendelev_eam'
job.save()
```

And the in the next: 
```
from pyiron import Project
pr = Project('save')
job = pr.load("lmp")
if job._check_if_input_should_be_written():
    job.project_hdf5.create_working_directory()
    job.write_input()
    job._copy_restart_files()
job.status.created = True
job.run()
```

Just creating the working directory without the input files was not sufficient for me. Basically I copied the remaining steps from `_create_job_structure()`: https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/generic.py#L1587

**Comment by samwaseda** [comment]
So, if the following lines (of yours) from Notebook II are written before `job.save()` in Notebook I, it worked:

```
if job._check_if_input_should_be_written():
    job.project_hdf5.create_working_directory()
    job.write_input()
    job._copy_restart_files()
job.status.created = True
```

**Comment by jan-janssen** [comment]
Either before the `save()` or after the `load()`, both is fine. But you are right maybe instead you can call `job._create_job_structure()` rather than `job.save()` in the first notebook.

**Comment by samwaseda** [comment]
In the case of SPHInX, without `write_input` the information required is not stored in hdf.

**Comment by jan-janssen** [comment]
That sounds like a bug to me ...

**Comment by jan-janssen** [comment]
@samwaseda Can this issue be closed?
