### ISSUE TITLE
debye_temperature() in FitMurnaghan 

### ISSUE THREAD

**Issue by prince-mathews** [pyiron/pyiron#741]
Recently I was trying to calculate the Debye temperatures for aluminium and scandium. I came across `debye_temperature()` under FitMurnaghan class. 

`out = self._murnaghan['output']`
        `V0 = out['equilibrium_volume']`
        `B0 = out['equilibrium_bulk_modulus']`
        `Bp = out['equilibrium_b_prime']`

       vol = self.volume

        mass = set(self._murnaghan.structure.get_masses())
        if len(mass) > 1:
            raise NotImplementedError('Debye temperature only for single species systems!')
        mass = list(mass)[0]

        r0 = (3 * V0 * Ang3_to_Bohr3 / (4 * np.pi)) ** (1. / 3.)
        debye_zero = empirical * convert * np.sqrt(r0 * B0 * GPaTokBar / mass)

The equation for calculating `debye_zero` is the same as mentioned in the work by Moruzzi. However, the Wigner Seitz radius `r0` seems wrong. The equilibrium volume `V0` in `r0` should be the equilibrium volume per atom of the cell, therefore this equilibrium volume should divided by the number of atoms in the cell considered for the equilibrium energy - volume calculations.

**Comment by jan-janssen** [comment]
Yes, the Debye model is limited to primitive cells at the moment.
