### ISSUE TITLE
Errors not found when submitted script crashes

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#744]
I had a notebook with a small error inside, which I submitted to the queueing system. When the job crashed, I couldn't find out where the problem came from, because I couldn't find the error message anywhere. I presume that the converted notebook is not available when the job is aborted, right? But it would be helpful if the conversion is performed nevertheless.

**Comment by jan-janssen** [comment]
I guess this is nothing we can change. We use `jupyter nbconvert`: 
https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/script.py#L245

To find the error message, please try: 
```
find -name error.msg . 
```

**Comment by samwaseda** [comment]
> To find the error message, please try:
> 
> ```
> find -name error.msg . 
> ```

The problem is `error.msg` is apparently not created if there was a problem inside the notebook. I don't understand why though.

**Comment by jan-janssen** [comment]
Did you submit the job to the queue? Is there a `error.out` ?

**Comment by samwaseda** [comment]
Yes but there was nothing written there
