### ISSUE TITLE
Is there a way to make pr.inspect(job)['input/data_dict'] more readable?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#760]
Title essentially says everything. Basically, when `pr.inspect(job)['input/data_dict']` is executed, we'd see something like:

```
{'Parameter': ['EnCut',
  'KpointCoords',
  'KpointFolding',
  'EmptyStates',
  'Sigma',
  'Xcorr',
  'VaspPot',
  'Estep',
  'Ediff',
  'WriteWaves',
  'KJxc',
  'SaveMemory',
  'CoarseRun',
  'rhoMixing',
  'spinMixing',
  'CheckOverlap',
  'THREADS',
  'Istep',
  'dF'],
 'Value': ['550',
  '[0.5, 0.5, 0.5]',
  '[5, 11, 24]',
  '33',
  '0.07522641',
  'PBE',
  'True',
  '100',
  '0.0001',
  'True',
  'False',
  'True',
  'False',
  '0.5',
  '0.5',
  'True',
  '1',
  '100',
  0.01],
 'Comment': ['',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']}
```

And this is horrible.

**Comment by samwaseda** [comment]
Something like `pr.load(job_name).input` without loading the job.

**Comment by pmrv** [comment]
I don't think there is, since this is the pretty much tied to the internal representation of GenericParameters.  In #749 this will be much better since the hierarchical structure is properly reflected in the hdf5 serialization.

**Comment by jan-janssen** [comment]
I agree with @pmrv we should switch to the new input class in the mid-term. The `GenericParameters` class is one of the oldest, originally developed for key value based files like the VASP input and then iteratively extended to support more complicated input structures. Now we are at the point where we learned enough from the `GenericParameters` class and can replace it with the hierarchical `inputlist` class.

**Comment by samwaseda** [comment]
Ok that's also fine by me.
