### ISSUE TITLE
Number of electronic steps

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#777]
I know that I was the one who wanted to increase the number of electronic steps to 400, which in my opinion still makes sense for one-step static calculations. But I'm starting to realise that in structure optimisation and interactive calculations it's rather a waste of time. I'd therefore suggest we change the default number of electronic steps to something like 40 or 100 for structure optimisation. And at the same time, I'd also love to change it for the interactive case, although I'm not really sure if it's possible with the current framework. What do you think?

**Comment by jan-janssen** [comment]
The default in VASP is 60 https://www.vasp.at/wiki/index.php/NELM so we could even aim for consistency with VASP as I guess the majority of our current user base is using VASP primarily.
