### ISSUE TITLE
Consistency of project in submitted notebook

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#780]
I have a suggestion.

Currently when a notebook is submitted, two projects are created: one for the job submitter, one for the job running within the notebook. However, conceptually they usually belong to the same project. What I have been doing therefore is something like:

Submitter:
```
pr = Project('PROJECT')
```

Job notebook:
```
pr = Project('path_to_project/PROJECT')
```

which requires a long line for the project and if the path is not correct, a new project will be created in the given path. That's not so nice. My suggestion to solve this would be:

Submitter:
```
pr = Project('PROJECT')
```

Job notebook:
```
pr = Project() # This will simply take over the project of the submitter
```

This will not only create only one project, but also then we can compress the submitter (which has been a big problem for me since the number of files is exploding).

Usually I implement new stuff myself but since this requires a core knowledge of pyiron, I'll simply throw it to @jan-janssen and see what he says :)

**Comment by samwaseda** [comment]
Just to make sure: I'm not talking about `Project('.')`. I'm saying both the submitter and the notebook should share the same project and no further project should be created.

And I don't understand your example.

If you are saying something like this:

Submitter:
```
pr = Project('SUBMIT')
for i in range(2):
    job = pr.create_job('ScriptJob', 'script_{}'.format(i))
    job.script_path = 'job.ipynb'
    job.run()
```

Notebook to submit:
```
pr = Project('JOB')
job = pr.create_job('Vasp', 'vasp')
... job creation ...
job.run()
```

Then the user will still have a problem that `Project('SUBMIT').inspect('vasp')` doesn't work. In this case, it only works with `Project('SUBMIT/script_0_hdf5/script_0/JOB/')`, which is anyway impossible to understand because `Project('SUBMIT')` does not tell you how to access this job. So, in the current implementation I claim that the user must change the job name for each job anyway.

**Comment by jan-janssen** [comment]
I meant you can have multiple projects inside one script job, for example:
```
Project('SUBMIT/script_0_hdf5/script_0/step0/')
Project('SUBMIT/script_0_hdf5/script_0/step1/')
Project('SUBMIT/script_0_hdf5/script_0/step2/')
```
In my case I am commonly only interested in the last step of an algorithm. But I agree the `script_0_hdf5/script_0` part is annoying. The reason for this is that the root group of the HDF5 file behaves different compared to all other groups and pyiron has the flexibility to have multiple jobs in one HDF5 file even though we do not use it at the moment. So the HDF5 path looks something like this: 
```
script_0.h5: /script_0/output/generic
```
To keep the path for both the files and the HDF5 file consistent we introduced: 
```
script_0_hdf5/script_0
``` 
Again in principle there could be multiple jobs in the HDF5 file and then the working directory would otherwise be shared.

**Comment by samwaseda** [comment]
> ```
> Project('SUBMIT/script_0_hdf5/script_0/step0/')
> Project('SUBMIT/script_0_hdf5/script_0/step1/')
> Project('SUBMIT/script_0_hdf5/script_0/step2/')
> ```

This is fine, I'm not suggesting to change the current behaviour. I'm just suggesting to add the possibility that the submitted notebook chooses automatically the root project as well.

**Comment by jan-janssen** [comment]
Can we do something like?
```
from pyiron import working_directory
pr = Project(working_directory)
```
By default this would be `.` and for the script job it could be something different.

**Comment by samwaseda** [comment]
That would be already very good! Even better would be if we wouldn't have to import anything, e.g. `Project(default_working_directory=True)`?

**Comment by jan-janssen** [comment]
So then 
```
Project(default_working_directory=True)
```
would be the same as 
```
Project(".")
```
For a regular project. I like this option. By default 
```
default_working_directory=False
```
ok ?

**Comment by samwaseda** [comment]
Brilliant!
