### ISSUE TITLE
Softlinks in HDF5

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#789]
Different codes store the same data under different paths, e.g. electronic structure information in vasp vs. sphinx.  Since HDF offers [soft links](https://h5py.readthedocs.io/en/stable/high/group.html#dict-interface-and-links), the idea would be to let every code store under what ever HDF5 paths they want but create generic links to the tags described in the [FAQ](https://pyiron.github.io/source/faq.html#which-output-quantities-are-stored-in-pyiron).

I'll hack together a demo for next meeting, but in case of the electronic structure I'm not sure what are all the code-specific differences.

**Comment by jan-janssen** [comment]
This issues is now open for more than three months, so I would prefer to close them to keep track of the topics we actually have time to work on right now. If we want to have a continuous discussion on this topic we could also open such a discussion in https://github.com/orgs/pyiron/teams/pyiron
