### ISSUE TITLE
add more tests

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#792]
A few modules have no or not a lot coverage from the unit test.  Low hanging fruits include
- [ ] `pyiron.gaussian`
- [ ] `pyiron.gpaw`
- [ ] `pyiron.thermodynamics`
There's also
- [ ] `pyiron.base` (60%)
- [ ] `pyiron.project` (50%)
that have some good coverage, but functionality in there should be independent of external executables and so should be able to do better. 
We also discussed
- [ ] running notebooks under coverage, or
- [ ] extracting additional tests from handbooks/examples to test with "real" simulations.

**Comment by jan-janssen** [comment]
This issues is now open for more than three months, so I would prefer to close them to keep track of the topics we actually have time to work on right now. If we want to have a continuous discussion on this topic we could also open such a discussion in https://github.com/orgs/pyiron/teams/pyiron
