### ISSUE TITLE
replace GenericParameters with InputList

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#794]
Midterm `InputList` should replace `GenericParameters`.  I'll be working on the lammps jobs, but definitely new classes should only use `InputList` and if you touch a class for whatever reason, consider looking into it.  Big differences in usage are only where the `GenericParameters` object is written to a file as `InputList` doesn't have a method to do this.

**Comment by samwaseda** [comment]
Can you also tell me how to visualize `InputList` properly?

**Comment by pmrv** [comment]
You mean to get the tree view in a notebook? It should be automatically as that, otherwise try `display(InputList(...))`.  The method `_repr_json_` turns the list into a nested dictionary and is called automatically whenever jupyter tries to display an InputList.

**Comment by jan-janssen** [comment]
This issues is now open for more than three months, so I would prefer to close them to keep track of the topics we actually have time to work on right now. If we want to have a continuous discussion on this topic we could also open such a discussion in https://github.com/orgs/pyiron/teams/pyiron
