### ISSUE TITLE
open version 1.0.0 issues

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#795]
We discussed some issues we want to have, but are not mature yet for their own issues or not actively worked on yet

- [ ] ground work for pyiron/experimental (vs. making a separate module); what classes would be needed?
- [ ] pyiron GUI via [ipytree](https://github.com/QuantStack/ipytree)
- [x] remote SQL database access, HDF-only installations?
- [ ] dynamic object loading from hdf (automatic from object metadata?)
- [x] identify parts that can be split into separate repositories
  - `pyiron.base` is essentially standalone, everything else could be `atomistic`

**Comment by jan-janssen** [comment]
Another point that came up in a discussion today, is to support scratch directories which are only available on a given compute node. In principle it would be good if pyiron could copy the HDF5 file to the scratch directory, execute it there (write input files, run executable, collect output files) and finally copy the executed HDF5 file back to the working directory. This workflow is similar to working on a remote host.

**Comment by samwaseda** [comment]
@Ahmed-Aslam is now working on the potential class for LAMMPS and I think his class should be extended to other codes as well. I'm not sure how important compared to other issues named above, but since it's rather likely that there'll be limited backward compatibility, I think the changes should take place at the same time as pyiron 1.0.0

**Comment by jan-janssen** [comment]
I guess we should discuss this again in the next pyiron meeting as I have a few more collaborators who want to use the latest features for remote jobs and I would like to give them the option install via conda directly. So I would suggest to release a 0.3.0 version now with all the changes in the master branch and continue working towards 1.0

**Comment by jan-janssen** [comment]
I released 3.0 - announcement https://github.com/pyiron/pyiron/issues/939 - it includes all the changes of the current master branch.

**Comment by jan-janssen** [comment]
I moved ahead and split pyiron and pyiron_base - https://github.com/pyiron/pyiron/pull/952

**Comment by jan-janssen** [comment]
This issues is now open for more than three months, so I would prefer to close them to keep track of the topics we actually have time to work on right now. If we want to have a continuous discussion on this topic we could also open such a discussion in https://github.com/orgs/pyiron/teams/pyiron
