### ISSUE TITLE
force_reset in job creation?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#802]
I very often write lines like:

```
lmp = pr.create_job('Lammps', 'test')
lmp.remove()
lmp = pr.create_job('Lammps', 'test')
```

or

```
pr.remove_jobs(recursive=True)
lmp = pr.create_job('Lammps', 'test')
```

pyiron complains with the first option (and also it looks ugly) and the second option is anyway not recommended. I'd like to have something like `pr.create_job(..., force_rerun=True)`. What do you think?

**Comment by jan-janssen** [comment]
I like the idea, I am just not sure if `force_rerun` is clear to everybody. What about `delete_existing_job` ?

**Comment by samwaseda** [comment]
I'm fine with anything, but I think it's important that `run(run_again=True)` gets a similar name (or this new argument gets a similar name), since it does essentially the same thing (even though `run(run_again=True)` doesn't work for all job types),

**Comment by jan-janssen** [comment]
Ok, we can also update `run(run_again=True)` to `run(delete_existing_job=True)`. Can you open the pull request?

**Comment by samwaseda** [comment]
Another consideration: since we set `job.set_input_to_read_only()` when the job finishes, isn't it better to drop `run(run_again=True)` (or `run(delete_existing_job=True)`) altogether?

**Comment by appassionate** [comment]
Hi, @jan-janssen, for the "backup job which condition is not converged"reason, I need to backup job using ".copy_to" but there seems have no method such as "reset_job".  In the "job.run" implement I followed the reset step to build a function as "reset" action.
Here wiil be a example If you are interested, Can it be a method in jobs? Thanks.

```python
def reset_job(job):
    
    if job.job_id:
        #self._logger.info("run repair " + str(self.job_id))
        
        master_id, parent_id = job.master_id, job.parent_id
        job.remove(_protect_childs=False)
        job.reset_job_id()
        job.project.set_job_status(job.job_id, "initialized")
        job.master_id, job.parent_id = master_id, parent_id
```
