### ISSUE TITLE
Better way to add structures

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#810]
We need to make sure that we raise errors/warnings when we add structures with different cells, pbc, etc, and go beyond the ase way of adding structures! Some possible examples where we encounter such issues are:

-  Adding an adsorbate structure with no pbc to a semi-infinite slab with pbc (how should the pbc commutation look like?)
-  Adding two structures with different cell values.

Suggestions are welcome!

**Comment by pmrv** [comment]
What happens if you add an ASE atoms and our subclass?  Can we somehow make sure, that always our subclass is returned not matter the order of addition?

**Comment by sudarsan-surendralal** [comment]
> What happens if you add an ASE atoms and our subclass? Can we somehow make sure, that always our subclass is returned not matter the order of addition?

The way I set it up currently,  we get a pyiron structure if we append an ase structure to a pyiron object and an ase structure if we try to append a pyiron structure to an ase object (both works well). The latter isn't what we really want but I think it is the correct way to handle this since the user still expects an ase object.

**Comment by sudarsan-surendralal** [comment]
Regarding incompatible cell sizes and pbcs, currently we just raise warnings (I don't want to break ase based workflows). https://github.com/pyiron/pyiron/pull/680/commits/fc7385c6b5a5585078fcf131614e2d365e2516e6.
