### ISSUE TITLE
How to make interactive LAMMPS occupy less memory

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#812]
I have a MC job in which I do something like 10,000 steps, where I essentially don't need anything other than `energy_pot` and `species`. So far, I know that I can get rid of some keys like `unwrapped_positions` by deleting them from `interactive_output_functions`, but as keys like `positions` are still needed to update the structure info, it requires quite some space. Is there a way to make pyiron store only `energy_pot` and `species`?

**Comment by jan-janssen** [comment]
You can try to set the flush frequency to a high value: 
```
job.interactive_flush_frequency = 100000
```
And before closing the job you could remove entries inside: 
```
job._interactive_cache["positions"] = []
```

**Comment by samwaseda** [comment]
I close this issue for now because I guess it's still a relatively special case, but I guess in the future we should think about deleting positions, cells etc. if we don't need them.

**Comment by jan-janssen** [comment]
Instead of closing, you could simply clean the memory at that point right? The flush frequency part still applies, because the `calc_minimize` happens inside lammps only and only the first and last step are stored in cache.
