### ISSUE TITLE
Import problem with Phonopy jobs

### ISSUE THREAD

**Issue by perez-danny** [pyiron/pyiron#816]
Hi,

I am going through the Phonopy tutorial at https://github.com/pyiron/pyiron/blob/master/notebooks/phonopy_example.ipynb using a fresh Conda install. When I try to execute a Phonopy job, as in box [17], I get the error:

    import phonopy.structure.spglib as spg 
    ModuleNotFoundError: No module named 'phonopy.structure.spglib'

That file is indeed absent from the master branch of Phonopy. It seems that it was removed about 14 days ago when this functionality was refactored in spglib. 

Replacing ` import phonopy.structure.spglib as spg ` by  `import spglib as spg` in pyiron/atomistics/structure/phonopy.py  seems to solve the issue, but further test might be warranted.

**Comment by jan-janssen** [comment]
Hi @perez-danny 

Phonopy changed the interface in version 2.7 so the easiest way to fix this is installing version 2.6 . We update the pyiron master branch, to import spglib directly:
https://github.com/pyiron/pyiron/pull/784
And I just opened a pull request to fix the conda package:
https://github.com/conda-forge/pyiron-feedstock/pull/31

Best, 

Jan

**Comment by jan-janssen** [comment]
Hi @perez-danny, 

I assume this issue is resoled and close it. If this is not the case feel free to reopen it at any time. 

Best, 

Jan
