### ISSUE TITLE
LAMMPS hdf5 takes very large space

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#818]
I have an issue here, which I don't understand. Look at the lines below:

```
lmp = pr.create_job('Lammps', 'lmp', delete_existing_job=True)
lmp.structure = pr.create_structure('Al', 'fcc', 4.).repeat(5)
lmp.potential = lmp.list_potentials()[0]
lmp.calc_md(temperature = 300)
lmp.interactive_open()
for _ in range(10):
    lmp.run()
# lmp.h5: 140 MB
lmp.interactive_close()
# lmp.h5: 5.8 MB
```

As I indicate in the comments, the hdf5-file becomes extremely large after several runs, for no obvious reason. Then when it's closed, it suddenly becomes 25-times smaller. Here, I'm talking about the size of the hdf5-file only and not the memory used by the system (i.e. I'm not counting cache).

Looking at the content of the hdf5-file, I couldn't pinpoint the problem, since there was no indication of what could be consuming so much space. I also added `lmp.project_hdf5.rewrite` after the run, but then there was no output anymore in the hdf5 file.

**Comment by jan-janssen** [comment]
The job is rewritten during the interactive close, that is why the file size is decreased: 
https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/interactive.py#L290

To maintain a low file size over the whole run you can simply set a flush frequency larger than the number of steps computed: 
```
lmp.interactive_flush_frequency = 10000
```

**Comment by samwaseda** [comment]
ok apparently I had understood the functionality of `interactive_flush_frequency` completely wrong. Sorry for posting nearly the same issue twice.

But then shouldn't it be large by default? Or even: do we ever have to flush in the first place?

**Comment by jan-janssen** [comment]
The issue with a high flush frequency is that you can loose all your results if something breaks. That is why we focused on having save default values rather than fast ones. But I am open to discuss this in the next pyiron meeting.
