### ISSUE TITLE
Error when submitting ScriptJob

### ISSUE THREAD

**Issue by edmen-dev** [pyiron/pyiron#819]
I am submitting a ScriptJob, but the job fails before the script starts and the error.out file shows the following error message:

`
/u/system/SLES12/soft/pyiron/dev/anaconda3//bin/python: No module named pyiron.base.job.wrappercmd`

**Comment by pmrv** [comment]
What pyiron version are you using? Can you also include a minimal example that triggers the bug?

In 0.2.17 `pyiron.base.job.wrappercmd` was already moved to `pyiron.base.job.wrapper` and `pyiron.cli`, so it sounds like there might be a mismatch between pyiron versions saving & running the job.

**Comment by jan-janssen** [comment]
I assume you have your own pyiron version. You can check this using: 
```
import pyiron
pyiron.__file__
```
I recently updated the central version to 0.2.17 so the easiest way is to update your installation as well.

**Comment by edmen-dev** [comment]
My pyiron version is:
'/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/__init__.py'

How can I update the pyiron version?

**Comment by edmen-dev** [comment]
After restarting my kernel, now it seems that the run_squeue script is correct and works... I will see if everything is fine now...
Sorry for this... Jan, this is perhaps because your update?

**Comment by jan-janssen** [comment]
Possibly, when did you submit the job? I did the update on Tuesday.

**Comment by edmen-dev** [comment]
I submitted the jobs that failed like this just today... and very possibly using a notebook that I opened before last Tuesday...

**Comment by jan-janssen** [comment]
Ok, that might be the reason then.
