### ISSUE TITLE
DFT related members in AtomisticGenericJob

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#820]
`AtomisticGenericJob` has `{set,get}_encut()` and `set_kpoints()` defined on it.  Since they only raise a `NotImplementedError` and not all subclasses use them (e.g. lammps), is there a specific reason to keep them? They also live on the generic DFT class, which is more appropriate anyways.

**Comment by jan-janssen** [comment]
I guess in principe it should be sufficient to have them implemented in https://github.com/pyiron/pyiron/blob/master/pyiron/dft/job/generic.py
So maybe just test removing them to see if anything breaks.
