### ISSUE TITLE
Auto-correction of user provided job_name

### ISSUE THREAD

**Issue by yury-lysogorskiy** [pyiron/pyiron#822]
Just an idea:

- once user provides the incorrect job_name for job, a warning should be thrown and job_name auto-correction should be done.

- provide a pyiron function to auto-correct given string, i.e. instead of:
` job_name = "s_"+str(strain).replace(".","")`
do something like:
` job_name = to_pyiron_job_name("s_"+str(strain))`

This option also could be switchable in config file

**Comment by pmrv** [comment]
Generally I'd like a more diverse character set, but I feel it should be transparent, i.e. translated/escaped when the name is put into the database and translated back when showing it to the user.  This way would avoid situations where a job pop ups under different name that you expect. 

I think the code internally checks that the job name is a valid python identifier.  What was the reason for that?  Does the database choke on some characters?

**Comment by samwaseda** [comment]
> * once user provides the incorrect job_name for job, a warning should be thrown and job_name auto-correction should be done.

I guess @jan-janssen had an example for this one, although it was a long time ago that he presented it. I remember that it was a quite good one so I can imagine we work on it again.

**Comment by yury-lysogorskiy** [comment]
This is not a bug, but a proposal. The only reason why I suggest this, is to make the code like this:
`job = pr.create_job(pr.job_type.Lammps, 'strain_'+str(eps).replace(".","_").replace("-","_"))`
more elegant, smth. like this:
```
job_name = function_to_create_valid_pyiron_job_name('strain_'+str(eps))
job = pr.create_job(pr.job_type.Lammps, job_name)
```
At least on the demos that would be more appealing...

**Comment by jan-janssen** [comment]
Currently we use https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/core.py#L891 

With this, the following line returns an error: 
```
job = pr.create_job(pr.job_type.Lammps, "job_" + str(3.4))
```
Result: 
```
ValueError: Invalid name for a PyIron object (no "." or "#") allowed
```

I guess what @yury-lysogorskiy is suggesting is replacing the ValueError with a warning an automatically replacing characters which are not compatible.

**Comment by pmrv** [comment]
Interestingly, it seems this was our intent already
https://github.com/pyiron/pyiron/blob/a9d05e10ef3d77ccb79505ab861d766b071d2306/pyiron/base/database/jobtable.py#L331
https://github.com/pyiron/pyiron/blob/a9d05e10ef3d77ccb79505ab861d766b071d2306/pyiron/base/database/filetable.py#L241
https://github.com/pyiron/pyiron/blob/a9d05e10ef3d77ccb79505ab861d766b071d2306/pyiron/base/job/core.py#L149

I'm in favor of translating, but if we can manage I'd also like to translate back.  If it turns out to be too hard, a warning works.

**Comment by jan-janssen** [comment]
I guess the translating back part is dangerous, but if I remember correctly we had the same discussion some time ago. At the time we decided to fail early rather than writing a lot of complicated code - following the zen of python.
