### ISSUE TITLE
Having trouble iterating over jobs in project object

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#825]
Hello, 
I am trying to run the following example.

https://github.com/pyiron/pyiron-meeting-mpie/blob/master/handbook/3-vasp/3-2-murnaghan/convergence_Encut%2B_and_KP.ipynb

I get the following error at cell [97]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-105-7f74a5f10ef9> in <module>
      5     #print(encut_str)
      6     pr0 = pr1[encut_str]
----> 7     for job in pr0.iter_jobs(path=pr0,convert_to_object=False):
      8         E.append(job["output/generic/total_energies"][-1])
      9         V.append(job["output/generic/volume"][-1])

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/project/generic.py in iter_jobs(self, path, recursive, convert_to_object, status)
    527         for job_id in job_id_lst:
    528             if path is not None:
--> 529                 yield self.load(job_id, convert_to_object=False)[path]
    530             else:  # Backwards compatibility - in future the option convert_to_object should be removed
    531                 yield self.load(job_id, convert_to_object=convert_to_object)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/job/path.py in __getitem__(self, item)
    376             with open(file_name) as f:
    377                 return f.readlines()
--> 378         return self.project_hdf5.__getitem__(item)
    379 
    380 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/generic/hdfio.py in __getitem__(self, item)
    792             raise NotImplementedError("Implement if needed, e.g. for [:]")
    793         else:
--> 794             item_lst = item.split("/")
    795             if len(item_lst) == 1 and item_lst[0] != "..":
    796                 if item in self.list_nodes():

AttributeError: 'Project' object has no attribute 'split'[](url)
```

**Comment by jan-janssen** [comment]
In the example it says:
```
for job in pr0.iter_jobs(convert_to_object=False):
```
In your code you have:
```
for job in pr0.iter_jobs(path=pr0,convert_to_object=False):
```

The path parameter should be a path inside the HDF5 file rather than the project object. The usage of iter_jobs is explained in section 5.1 of the pyiron Paper https://www.sciencedirect.com/science/article/pii/S0927025618304786

**Comment by sravankumarkb** [comment]
Thank you for taking a look. 

My code on cmti001: /u/skanchar/pyiron/projects/handbook/3-vasp/3-2-murnaghan/convergence_Encut+_and_KP.ipynb
I have a similar error even with

`for job in pr0.iter_jobs(convert_to_object=False):`

Below is the error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-137-618fba576714> in <module>
      7     for job in pr0.iter_jobs(convert_to_object=False):
      8         #print (job)
----> 9         E.append(job["output/generic/total_energies"][-1])
     10         V.append(job["output/generic/volume"][-1])
     11     para, para_error = murnaghanfit_leastsq(V, E, fittype='birchmurnaghan') # [e0, b0, bP, v0] [d_e0, d_b0, d_bP, d_v0]

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/job/path.py in __getitem__(self, item)
    376             with open(file_name) as f:
    377                 return f.readlines()
--> 378         return self.project_hdf5.__getitem__(item)
    379 
    380 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/generic/hdfio.py in __getitem__(self, item)
    822                     hdf_object = self.copy()
    823                     hdf_object.h5_path = "/".join(item_abs_lst[:-1])
--> 824                     return hdf_object[item_abs_lst[-1]]
    825 
    826     def _read(self, item):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/generic/hdfio.py in __getitem__(self, item)
    801                         obj = hdf_item.copy()
    802                         return obj
--> 803                 raise ValueError("Unknown item: {}".format(item))
    804             else:
    805                 if item_lst[0] == "":  # absoute HDF5 path

ValueError: Unknown item: total_energies

**Comment by sravankumarkb** [comment]
I have changed the variable from "total_energies" to "energy_tot" and it works okay now. This again comes back to my point that these examples have to be updated as some of the function names and variable names have changed.

`    for job in pr0.iter_jobs(convert_to_object=False):
        E.append(job["output/generic/total_energies"][-1])
        V.append(job["output/generic/volume"][-1])`

is changed to 

`    for job in pr0.iter_jobs(convert_to_object=False):
        E.append(job["output/generic/energy_tot"][-1])
        V.append(job["output/generic/volume"][-1])`

**Comment by sudarsan-surendralal** [comment]
Thanks for the changes @sravankumarkb. @jan-janssen should we move these issues to https://github.com/pyiron/pyiron-meeting-mpie/issues and link pull requests to fix them?

**Comment by jan-janssen** [comment]
I opened a pull request https://github.com/pyiron/pyiron-meeting-mpie/pull/3

**Comment by samwaseda** [comment]
Is `["output/generic/total_energies"]` still there by the way?

**Comment by jan-janssen** [comment]
@samwaseda Yes it was replaced, but the examples were not updated.

**Comment by samwaseda** [comment]
Sorry somehow all the replies were not shown when I loaded the page - now they suddenly appeared.

**Comment by jan-janssen** [comment]
I close this issue in favour of https://github.com/pyiron/pyiron-meeting-mpie/issues/1
