### ISSUE TITLE
run_time units

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#830]
In the current configuration the value set to `job.server.run_time` is put by pysqa directly into the SLURM submission script.  This means its in minutes, but documented by pyiron as seconds.  The question is now whether the pysqa template should convert to minutes or we should update the documentation.  Keeping the time consistently in seconds makes more sense to me, but what are your thoughts?

**Comment by jan-janssen** [comment]
I have it on the list https://github.com/pyiron/pysqa/issues/24 but did not find the time to fix it yet.

**Comment by pmrv** [comment]
So basically pysqa should accept seconds and do the conversion?  I'll have a look after ADIS then.
