### ISSUE TITLE
center_coordinates_in_unit_cell not working anymore

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#832]
Is there a replacement for `center_coordinates_in_unit_cell` in ASE?

**Comment by samwaseda** [comment]
I just realised that the problem is not `center_coordinates_in_unit_cell` is not working, but the box is not translated to a pyiron object when it's created with ASE anymore. Is the right way to do the translation with `ase_to_pyiron`?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> I just realised that the problem is not `center_coordinates_in_unit_cell` is not working, but the box is not translated to a pyiron object when it's created with ASE anymore. Is the right way to do the translation with `ase_to_pyiron`?

Yes an ASE object remains an ASE object now which does not have `center_coordinates_in_unit_cell`. You'd have to use `ase_to_pyiron` to convert to a pyiron object.

**Comment by samwaseda** [comment]
ok thanks!
