### ISSUE TITLE
Setting nbands tag in vasp calcs using the job object

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#834]
Hi

I am wondering if there is a way to set nbands using the jobs object. Thanks.

The only solution I came up with is 
`ham_vasp = pr.create_job(pr.job_type.Vasp, 'check_job')
ham_vasp.input.incar["NBANDS"] = 24`

Please let me know if there is a better way to do this. Thanks.

I came across the "set_empty_states" function which I think also sets the NBANDS tag. But I am not sure if the code is accurate.
I am pasting below the function from the documentation.

`    def set_empty_states(self, n_empty_states=None):
        """
        Sets the number of empty states in the calculation
        Args:
            n_empty_states (int): Required number of empty states

        """
        n_elect = self.get_nelect()
        if n_empty_states is not None:
            self.input.incar["NBANDS"] = int(round(n_elect / 2)) + int(n_empty_states)
`
It looks like it adds the n_empty_states to (n_elect / 2), should not it be (n_elect / 2) + (n_ions / 2) as the default nbands value vasp sets is (n_elect / 2) + (n_ions / 2)

[https://www.vasp.at/wiki/index.php/NBANDS](url)

PS: Please let me know if there is a function to get values like NIONS, NBANDS, etc.,. I can always unzip the files and look at the OUTCAR on the terminal. Just wondering if I can do this from the notebook as well. Thanks.

**Comment by sudarsan-surendralal** [comment]
If you need to control the VASP `NBANDS` tag directly, `ham_vasp.input.incar["NBANDS"] = 24` is the best way to go. `set_empty_states` is more generic and is used to exactly specify the number of states that will be empty (assuming each state has a maximum occupancy of 2 as in non-magnetic calculations). This is done to be compatible with other codes (like SPHINX) that don't follow VASP's default behaviour. 

> PS: Please let me know if there is a function to get values like NIONS, NBANDS, etc.,. I can always unzip the files and look at the OUTCAR on the terminal. Just wondering if I can do this from the notebook as well. Thanks.

It's not recommended to get such generic output using code specific tags. So, if you want to get the number of ions, simply type `len(ham.structure)` and to get the number of ions and for the number of bands, look at `ham["output/electronic_structure/eig_matrix"].shape` which gives the shape as `n_kpoints x n_bands`
```

**Comment by jan-janssen** [comment]
@sravankumarkb If the question is answered, please close the issue.
