### ISSUE TITLE
Pyiron table incompatible with numpy arrays

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#835]
When performing optimization jobs using the Gaussian plugin, the output of the frames is saved using numpy arrays.
This causes an issue with the JSON serialization, as I get the following error:

`TypeError: Object of type ndarray is not JSON serializable`

Perhaps the standard behavior of the pyiron table should be to convert everything to lists?

**Comment by SanderBorgmans** [comment]
As a quick fix, I introduced the following function:

```
    @staticmethod
    def convert_numpy_to_list(table_dict):
        for k,v in table_dict.items():
            for k1,v1 in v.items():
                if isinstance(v1,np.ndarray):
                    v[k1] = v1.tolist()
        return table_dict
```
which acts on `self.pyiron_table._df.to_dict()` in both the `to_hdf` and `update_table` methods from `datamining.py`.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> As a quick fix, I introduced the following function:
> 
> ```
>     @staticmethod
>     def convert_numpy_to_list(table_dict):
>         for k,v in table_dict.items():
>             for k1,v1 in v.items():
>                 if isinstance(v1,np.ndarray):
>                     v[k1] = v1.tolist()
>         return table_dict
> ```
> 
> which acts on `self.pyiron_table._df.to_dict()` in both the `to_hdf` and `update_table` methods from `datamining.py`.

Thanks for this! Can you open a pull request with these changes if you have them in a separate branch?
