### ISSUE TITLE
Possibly too easy to accidentally remove_jobs(recursive=True)?

### ISSUE THREAD

**Issue by ashtonmv** [pyiron/pyiron#843]
I might be the only one, but I very often have a `pr.remove_jobs(recursive=True)` statement in my notebooks that I forget to comment out, and sometimes I accidentally rerun it when I later revisit the notebook.

This is obviously a user error on my part, but I'm wondering if there's any argument against accomodating my stupidity with something like

```python
confirmed = input(f"Are you sure you want to delete all jobs from '{project_name}'? y/(n)")`
if confirmed.lower() == "y":
    # proceed to delete everything
else:
    # alert the user that nothing was deleted
```

so that the user has to confirm the deletion each time. For unit tests and users who are not as careless as I am, perhaps this safety could also be bypassed using an `enable` or `force_enable` keyword like we have in place for `pr.remove`?

Just a suggestion/question.

**Comment by pmrv** [comment]
I think the idea is ok, especially since we have it on `pr.remove` and that does essentially the same. My only worry is that we'd need to update a bunch of tests & example notebooks.  On the other hand those should probably use `pr.create_job(delete_existing=True)` anyway.

**Comment by jan-janssen** [comment]
I am a bit reluctant as I got used to using `pr.remove_jobs(recursive=True)` for the interactive development - basically running the the notebook with "Kernel Restart & Run All" until it produces the correct results. But once we have the ability to set the flag on a project level I am open to it. For example: 
```
pr.enable_remove_jobs = True
```
which then results in the current behaviour.

**Comment by ashtonmv** [comment]
Yeah I guess it mostly only matters for people running heavier DFT calculations. So I'm happy to leave it as-is.
