### ISSUE TITLE
Function for removing groups in a project?

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#845]
Hello,

Is there a function for removing groups in a project? 
`pr.list_groups()`
`['200_0']`
Let us say I want to remove the 200_0 group from the project. How would I do that?
I saw the "remove_group()" it in one of the previous issues. 
[https://github.com/pyiron/pyiron/issues/808](url)

But I am not able to understand how I can use it to remove the 200_0 group from my project.

Any help is appreciated. Thanks.

**Comment by jan-janssen** [comment]
```
pr["200_0"].remove(enable=True)
```
