### ISSUE TITLE
Job tables

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#856]
When loading a string into a job table through a property function, _e.g._:
```
def get_structure_name(job):
    return job.job_name.split('_')[-1]

table.add["lot"] = get_lot
```

and the string equals 't' or 'f' (or 'T', 'F'), it gets converted into 'True' or 'False' respectively. I suspect that this is not the expected behavior.

**Comment by jan-janssen** [comment]
I guess we did this by purpose to help the VASP users https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L447

**Comment by SanderBorgmans** [comment]
I see, if it is expected I will try to avoid this situation. I noticed this when I made a table with a column listing the element, and the fluor element (F) got changed to the 'False' string

**Comment by jan-janssen** [comment]
I commonly have one column per element and then only store the number of counts in the column to simplify the filtering. Still I agree that it should be more optimised, maybe having a flag to enable or disable this behaviour. So feel free to open a pull request for this.

**Comment by pmrv** [comment]
I'd like to document this, but am unsure where to place this. Maybe in a docstring [here](https://github.com/pyiron/pyiron/blob/cf4167002f745c69454a4fde6dc544c528952940/pyiron/table/datamining.py#L628)?

**Comment by jan-janssen** [comment]
@sudarsan-surendralal We discussed this in the pyiron meeting and identified that the VASP parser should make sure that the `True` and `False` values are stored as boolean in the generic parameters, even when importing the VASP calculation. Can you take a look at it?

**Comment by sudarsan-surendralal** [comment]
Thanks for pointing this out. The linked pull requests should fix this!
