### ISSUE TITLE
JobTable filters cannot be lambdas

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#857]
Setting `filter_function` on the pyiron table with a lambda gives an error when the job is read from HDF5.  This is because the filter is saved as source code and `inspect.getsource()` reports the full line the lambda is defined on instead of the function body.  I guess a fix is maybe too complicated, but we should update the docs as it is a bit surprising given that it _is_ possible to use lambda for the table values.

This is mainly a reminder to myself to update all the relevant docs & notebooks, unless somebody has an idea to improve the situation.

**Comment by jan-janssen** [comment]
Maybe it makes sense to add this to the FAQ

**Comment by jan-janssen** [comment]
In addition there is some lambda code still inside the pyiron table https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L143

**Comment by jan-janssen** [comment]
I looked it up again and we can use Lambda functions for properties https://github.com/pyiron/pyiron-meeting-mpie/blob/master/handbook/8-bigdata/8-2-pyiron-table/pyirontable-ham-class.ipynb so it should be able to extend the support for filter functions as well.

**Comment by pmrv** [comment]
Will have a look for Friday.

**Comment by jan-janssen** [comment]
The user functions we simply pickle rather than using `inspect`:
https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L129

**Comment by pmrv** [comment]
True, I still don't understand, because it's usually not possible to pickle free lambdas, maybe it has something to do with they way user functions are wrapped in an additional lambda down the line.

**Comment by jan-janssen** [comment]
`pickle` can not but `dill` can https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L8

**Comment by pmrv** [comment]
Ah, I stumbled on `dill`, but I hadn't checked the import.  Should be doable tomorrow then.

**Comment by pmrv** [comment]
I just realized that this will also have some backwards compatibility issues and I want solid tests and also de-cob some of the function serialization logic.  I'm sure it should just work same as the user function, but since I'm on vacation next week, I put this on my list and will close this until I'm back.
