### ISSUE TITLE
Trouble saving data into pyiron table

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#864]
Hello,

I have been trying to save the data from DFT calcs into a pyiron table (tot_DFT_data_table). I created the pyiron table using 

```
tot_DFT_data_table = pr.create_table("tot_DFT_data_table")
```
I get the following error at the end of the collection of my data into the table. I think that the error has to do with storing all the data into a h5 file with the table's name. I can see that all the data has been copied into the table when I print the dataframe using

```
tot_DFT_data_table.get_dataframe()
```
The status of the job is aborted. 
```
tot_DFT_data_table.status
```
I am not sure what to make of the error and if the data will load if I shutdown the notebook and open it back. Any help is greatly appreciated. Thank you.

Error
```
100%|██████████| 14784/14784 [15:09<00:00, 16.25it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-358-ddb08d961dc7> in <module>
     13 
     14 # Running the table to generate the data
---> 15 tot_DFT_data_table.run(run_again = True)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    673                 status = "created"
    674             if status == "initialized":
--> 675                 self._run_if_new(debug=debug)
    676             elif status == "created":
    677                 que_id = self._run_if_created()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/job/generic.py in _run_if_new(self, debug)
   1350         else:
   1351             self.save()
-> 1352             self.run()
   1353 
   1354     def _run_if_created(self):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/job/generic.py in run(self, run_again, repair, debug, run_mode)
    675                 self._run_if_new(debug=debug)
    676             elif status == "created":
--> 677                 que_id = self._run_if_created()
    678                 if que_id:
    679                     self._logger.info(

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/base/job/generic.py in _run_if_created(self)
   1367             self.run_if_manually()
   1368         elif self.server.run_mode.modal:
-> 1369             self.run_static()
   1370         elif self.server.run_mode.non_modal or self.server.run_mode.thread:
   1371             self.run_if_non_modal()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/table/datamining.py in run_static(self)
    752         self._create_working_directory()
    753         self.status.running = True
--> 754         self.update_table()
    755         self.status.finished = True
    756         self.run()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/table/datamining.py in update_table(self, job_status_list)
    773                 job_status_list=job_status_list,
    774             )
--> 775         self.to_hdf()
    776         self._pyiron_table._df.to_csv(
    777             os.path.join(self.working_directory, "pyirontable.csv"), index=False

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/table/datamining.py in to_hdf(self, hdf, group_name)
    695         if len(self.pyiron_table._df) != 0:
    696             with self.project_hdf5.open("output") as hdf5_output:
--> 697                 hdf5_output["table"] = json.dumps(self.pyiron_table._df.to_dict())
    698 
    699     def from_hdf(self, hdf=None, group_name=None):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type ndarray is not JSON serializable
```

**Comment by jan-janssen** [comment]
That is fixed in https://github.com/pyiron/pyiron/pull/836 - Can you try using the current master branch?

**Comment by sravankumarkb** [comment]
Thanks @jan-janssen 
How do I use the current master branch?
Do I change something in my .bashrc on cmti?

I have the following line in my .bashrc

```
module load pyiron/dev
```
Please let me know if I need to change this to something else. Thanks.

**Comment by pmrv** [comment]
The "dev setup" we usually run is to load the module (as you have) to get the dependencies, but then also check out the pyiron repo locally (mine lives in `~/software/pyiron`).
```bash
> mkdir -p ~/software
> cd ~/software
> git clone git@github.com:pyiron/pyiron.git
```
and then also modify the python module path, so that this local version is found before the system one.  This is done via setting `PYTHONPATH` in your `~/.profile`.  The quick version
```bash
echo "export PYTHONPATH=$HOME/software/pyiron:$PYTHONPATH" >> ~/.profile
```

This has the advantage that you can develop in your local check out and try dev versions their without having to manage the deps yourself.

**Comment by sravankumarkb** [comment]
Thanks @pmrv 

I get the following error when I try to clone the pyiron repository

```
Cloning into 'pyiron'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by pmrv** [comment]
You'll have to [add](https://docs.github.com/en/github/authenticating-to-github/updating-your-github-access-credentials#updating-your-ssh-keys) your public ssh key to you github account or use the https link. ;)

**Comment by sravankumarkb** [comment]
Thanks @pmrv 
My brain has stopped thinking  😆
I have added the following lines in my .bashrc. I hope this takes care of it. I have the "updatelocalpyiron" function. It would be great if you could take a look and let me know if I am doing it right.  Thanks a bunch.

```
module load pyiron/dev

#loading pyiron from local pyiron version, the local pyiron version has to be updated regularly

echo 'export PYTHONPATH="$HOME/software/pyiron:$PYTHONPATH"' >> ~/.profile

# function for updating the local pyiron

function updatelocalpyiron { cd $HOME/software; git clone https\://github.com/pyiron/pyiron.git temp; mv temp/.git pyiron/.git ; rm -rf temp; }

```

**Comment by jan-janssen** [comment]
@sravankumarkb If the question is answered, please close the issue.

**Comment by sravankumarkb** [comment]
I tried what @pmrv suggested, but for some reason, I am not being able to get rid of the error. I am sure it has to do with how I am loading pyiron. Should I open a separate issue to get my pyiron loading sorted out? (with the MPIE tag perhpas?) Thanks.

**Comment by jan-janssen** [comment]
No, I was just going through the issues and had the feeling that some of them were answered.

**Comment by jan-janssen** [comment]
Can you check? 
```
import pyiron
pyiron.__file__
```

When ever you change your `.bashrc` it is important to stop your jupyter server https://localhost:8000/hub/home and start a new server so it initialises your `.bashrc`. Jupyter does not initialise your `.bashrc` when you restart the kernel or open a new jupyter notebook.

**Comment by sravankumarkb** [comment]
Yes, I stopped the tunneling that I do with mobaxterm to connect to the jupyter lab, closed the window on my browser, and then started the tunnel again and opened jupyter lab. I got the following on running your script. Looks like it is loading pyiron from the dev version.
```
'/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/__init__.py'
```
I have the following lines in my .bashrc

```
module load pyiron/dev

#loading pyiron from local pyiron version, the local pyiron version has to be updated regularly

echo 'export PYTHONPATH="$HOME/software/pyiron:$PYTHONPATH"' >> ~/.profile

# function for updating the local pyiron

function updatelocalpyiron { cd $HOME/software; git clone https\://github.com/pyiron/pyiron.git temp; mv temp/.git pyiron/.git ; rm -rf temp; }

```

**Comment by sravankumarkb** [comment]
It finally worked!

Now I get the following upon running

```
import pyiron
pyiron.__file__
```

```
'/u/skanchar/software/pyiron/pyiron/__init__.py'
```
Looks like just stopping the tunneling in mobaxterm does not stop the server and I have to stop the server in the control panel on jupyter hub to actually stop the server. 
Sorry for the trouble @jan-janssen  and @pmrv 
I am closing this issue now. Thanks for your help.

**Comment by jan-janssen** [comment]
> 
> echo 'export PYTHONPATH="$HOME/software/pyiron:$PYTHONPATH"' >> ~/.profile
> 

I am a bit confused about this part. This adds the line:
```
export PYTHONPATH="$HOME/software/pyiron:$PYTHONPATH"
```
to your `.profile` file when you login. Resulting in multiple of those entries. Is there any specific reason why you do not add this line once to your `.bashrc` ?

**Comment by sravankumarkb** [comment]
Yeah, it does result in multiple entries. I have now changed it to 

```
export PYTHONPATH="$HOME/software/pyiron:$PYTHONPATH"
```
and I can also save the arrays in project tables. So, I think everything is okay now. Thanks again.
