### ISSUE TITLE
group_name not honored in GenericJob.from_hdf

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#866]
When opening the sub group in its given hdf file
https://github.com/pyiron/pyiron/blob/a9d05e10ef3d77ccb79505ab861d766b071d2306/pyiron/base/job/generic.py#L1199
the result is not reassigned to `self._hdf` and since `FileHDFio.open()` doesn't modify its argument, but provides a copy
https://github.com/pyiron/pyiron/blob/a9d05e10ef3d77ccb79505ab861d766b071d2306/pyiron/base/generic/hdfio.py#L365
this means `group_name` is effectively ignored.  I could fix this, but I'm a bit worried this might introduce weird bugs I won't directly catch. Am also unsure if this should be fixed in `open()` or on `from_hdf()`.  Anyone with more experience poking around the HDF5 has an opinion on this?

**Comment by jan-janssen** [comment]
but is not open typically used in combination with a "with statement: 
```
with self.project_hdf.open(group_name) as h5: 
    # do something with h5 
```

**Comment by jan-janssen** [comment]
So I believe the open function is correct - it is just that in the `from_hdf()` which is implemented in the GenericJob class the group_name variable is ignored. The work around is setting the `h5_path` manually: 
https://github.com/pyiron/pyiron/blob/master/pyiron/base/master/generic.py#L535

**Comment by pmrv** [comment]
> but is not open typically used in combination with a "with statement:
> 
> ```
> with self.project_hdf.open(group_name) as h5: 
>     # do something with h5 
> ```

It is, but I'm honestly not sure why.  The `__enter__()` is just returning `self` and `__exit__` does pop the current path from that objects history, but `open()` gave you a copy to begin with so from my reading doing
```python
with hdf.open(path) as hdf:
  do_something(hdf)
```
is the same as 
```python
do_something(hdf.create_group(path))
```

**Comment by jan-janssen** [comment]
I have to admit maybe it is also more historically. pyiron only opens the HDF5 file once you write to it - basically when h5io is called. All the rest just updates the h5path. I am open to changing the use of open and just give it a try if anything breaks.

**Comment by pmrv** [comment]
I modified `GenericJob.from_hdf()` to save the result of `open()`  and the `pyiron.base` tests still pass. It seems like the minimally invasive change, even though from a design perspective it feels like `open()` should modify the state of the object (to me, subjectively).  So unless someone else also has very strong feelings on this I'll just do the small change.  I'll open a PR later this week with changes to make `to_object()` work for all pyiron types.

**Comment by jan-janssen** [comment]
But is not this the default behaviour for python, like:
```
f = open("demofile.txt", "r")
print(f.read())
```

**Comment by pmrv** [comment]
> But is not this the default behaviour for python, like:
> 
> ```
> f = open("demofile.txt", "r")
> print(f.read())
> ```

Fair, as I said no hard opinions from my side.  More reason to move it to `from_hdf`.
