### ISSUE TITLE
passing project groups instead of jobs to the functions for project table

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#874]
Hi all,

I am trying to store my DFT data in a project table. My project has some groups which then have some jobs. All the jobs in the project are looped through when I run the following command.

```
tot_DFT_data_table = pr.create_table("tot_DFT_data_table")
tot_DFT_data_table.run()
```

Is there a way I only loop through the project groups instead of going through all the jobs in the project while adding the data to the project table. Currently I have been done the following to add data to the project table. So, instead of evaluating the function for every job in the project, can I only have it evaluated for pr_groups and add only the pr_group data to the table?

```
def get_blabla(job):
    return ('blabla')
tot_DFT_data_table.add["blabla"] = get_blabla
```

or an easier solution I think is to do something like below where I just manually add the data to the pandas data frame. But the key is I want the pandas data frame to be a project table so that it is stored on the cluster. Is that possible? Thanks for taking the time.

```
import pandas as pd

data = {'name': ['Somu', 'Kiku', 'Amol', 'Lini'],
	'physics': [68, 74, 77, 78],
	'chemistry': [84, 56, 73, 69],
	'algebra': [78, 88, 82, 87]}	
#create dataframe
df_marks = pd.DataFrame(data)
print('Original DataFrame\n------------------')
print(df_marks)

new_row = {'name':'Geo', 'physics':87, 'chemistry':92, 'algebra':97}
#append row to the dataframe
df_marks = df_marks.append(new_row, ignore_index=True)
```

**Comment by jan-janssen** [comment]
I am a bit confused, as typically there is no data inside the project, instead the data is only stored in the jobs. My suggestion would be to collect the fundamental properties you want to extract from the individual DFT calculation - energy and volume - and store those in the data frame. And then do all the post processing on top of the data frame. We should not use the data frame to store any fitted intermediate results, but instead only the "raw" results of the DFT calculations. If you take a look at my phase diagram calculations https://github.com/jan-janssen/NiCr-pyiron-example/blob/master/phasediagram_calculation.ipynb - I run the calculation in cell 60 and then I define the pyiron tables to store the results of the individual phonopy calculation over all concentrations and strains in one pyiron table and afterwards I filter the data for the fitting. 

By separating the data generation, data aggregation and the data analysis it is easier for an external person to understand how a specific result was calculated, which increases the reproducibility of our research.

**Comment by jan-janssen** [comment]
The separation of data generation, data aggregation and data analysis is also discussed in the pyiron paper in section 2.2 https://www.sciencedirect.com/science/article/pii/S0927025618304786

**Comment by pmrv** [comment]
I never tried this, but pyiron tables are also jobs, so it should be possible to aggregate in one table the results of a project full of tables, no?  It's tables all the way down in a sense.  This stays nicely reproducible as each table describes exactly how it computes its results and its all stored.

**Comment by jan-janssen** [comment]
@pmrv But as the pyiron tables copy the data it would be the same as just running the pyiron table on the top level directory. The pyiron tables can be update when more jobs are added or when additional parameters are required using `table.update()` so I am not sure if we really need two layers of data aggregation. All I care for is that the data is not modified but instead it is raw data extracted from the underlying calculations. All modifications should be applied on the data frame later on.

**Comment by sravankumarkb** [comment]
Yes, you are absolutely right. @jan-janssen  
I agree completely that the separation of data generation, data aggregation, and data analysis is good. But, let's say in the cases where data generation is dependent on data analysis and not the other way around. Then data analysis and data generation cannot be separated. 

Anyways, I do not want to get too much into the discussion. 

If I could just store the fitted parameters in a job table, I won't have to modify my analysis code a lot. I just want the code to be simple for now and don't want to get stuck on this problem forever!

**Comment by jan-janssen** [comment]
In the case where the data generation depends on the data analysis, that would be another iteration of the simulation lifecycle. Still you can store the data in the same pandas data frame and just add data in every iteration. Once you start storing only the fitted values we loose all the reproducibility. Therefore it is important to have the essential parameters - those which changed between the different calculations - as well as the output stored in the pyiron table.

**Comment by pmrv** [comment]
@jan-janssen My point is the 2nd level of tables would store both the jobs they get their data from and the fitting method, so it's still very reproducible, if I'm not missing anything.

**Comment by sravankumarkb** [comment]
Yes, I understand your point that it is important to store all the data used for the analysis so everything is reproducible. 

I am planning to have two job tables. One with all the DFT data from the main project and I just update the table whenever I am finished with pr_group. At the same time, I am going to add the fitted parameters to a different project table, so that the fitted parameters are also stored on the cluster. Once I save both these data in the two tables, I am going to just delete the pr_group so I don't reach my file limit and continue with the next pr_group. the project table with all the DFT data should enable anyone to do the analysis they want.

As of now, I am not so focused on other persons being able to follow my code independently without me guiding them. Anyways, the functions are going to be there in the code. So,...

**Comment by jan-janssen** [comment]
@pmrv I agree that it is technically possible, but I have the fear that people would start deleting the first level of tables. Therefore as the fits are commonly cheap I would not store them and instead maintain them in the jupyter notebook. One cloud also imagine the case where somebody reloads only the fitted table in a separate notebook and then nobody has the chance to see how the data was generated. 


> As of now, I am not so focused on other persons being able to follow my code independently without me guiding them. Anyways, the functions are going to be there in the code. So,...

@sravankumarkb For you personally the reproducibility might not be an issue, still I saw too many students starting projects like this and then moving on with something else and when the next student tries to pick up the work it is easier for him to start again from scratch rather than reusing the work of the previous student. pyiron is designed to address this loss of knowledge in the research process, that is why I am so strict about this part.

**Comment by sravankumarkb** [comment]
I understand your point @jan-janssen 

This basically means that I have to store all the DFT data in a project table for the three different interdependent levels in my system for which the code is already a mess.

And now I have to figure out how to analyse the results by digging through the three levels in the project table to do the analysis. I will try to rewrite my analysis code. Let's see how many issues I will come across while doing that with my lack of proper understanding of pandas data structures. 😓

Good luck to the person who will try to understand the analysis without comments! 😆

**Comment by pmrv** [comment]
> @pmrv I agree that it is technically possible, but I have the fear that people would start deleting the first level of tables. Therefore as the fits are commonly cheap I would not store them and instead maintain them in the jupyter notebook. One cloud also imagine the case where somebody reloads only the fitted table in a separate notebook and then nobody has the chance to see how the data was generated.

Fair, someone might actually delete part of their workflow accidentally or not.  My worry is more from the side that if we don't offer a solution to store things connected with how they are computed, people will rather start saving them to files outside pyiron (via pandas/numpy, e.g.), which would be somewhat of a Daten-GAU. ;)   I haven't urgently needed anything in this direction though, so no hard opinions.

**Comment by sravankumarkb** [comment]
> > @pmrv I agree that it is technically possible, but I have the fear that people would start deleting the first level of tables. Therefore as the fits are commonly cheap I would not store them and instead maintain them in the jupyter notebook. One cloud also imagine the case where somebody reloads only the fitted table in a separate notebook and then nobody has the chance to see how the data was generated.
> 
> Fair, someone might actually delete part of their workflow accidentally or not. My worry is more from the side that if we don't offer a solution to store things connected with how they are computed, people will rather start saving them to files outside pyiron (via pandas/numpy, e.g.), which would be somewhat of a Daten-GAU. ;) I haven't urgently needed anything in this direction though, so no hard opinions.

Yep, exactly! I am considering just storing them in text files so I can just load them whenever I want to plot them. Anyways, when someone new reruns the whole code those text files will show up with data.

**Comment by jan-janssen** [comment]
@pmrv I agree external text files are the worst as that breaks the reproducibility. The goal is that all information should be in the notebook + the HDF5 files otherwise we have no chance of sharing the data and so on. 

Regarding the fits, currently we address this by with the Murnaghan object, when the user is using the Murnaghan jobs to create the calculations then the fit is stored in the Murnaghan and if you run a table over all Murnaghan you have this kind of intermediate results. If the users do not use these predefined classes we have currently no chance to store what they did to the data other than storing the jupyter notebook. If the data was once manipulated outside pyiron for example by fitting storing it again in the HDF5 file does not help as we already have no idea where the data is coming from - we lost the provenance at that point. 

In the end it depends on the user. We can not force anybody to develop reproducible workflows, we can only make it as easy as possible. Still I am reluctant to store any data which was manipulated by the user again in a pyiron object as it would give the impression that it is possible to reproduce this data which is not the case.

**Comment by sravankumarkb** [comment]
@jan-janssen If I get the code together for the case where I get the Murnaghan parameters for different cases from just one table with all the DFT data. There is no point in doing the other strategy, as this is clearly better for reproducibility. It is just more work for me. But I think we are past that anyways.

The current Murnaghan object does not return the structure (or the a,c parameters). It returns the values it is supposed to return (E, V, B, B') which is fine for a cubic cell. But for more complicated cells, these outputs might not be sufficient. And there can always be cases where classes and source code get updated and variables get assigned different names, upon which the defined (Murnaghan/any other) objects might result in errors. To avoid those scenarios, it might be best to have user-defined functions that are hopefully self sufficient.

Please correct me if I am wrong. Thanks.
