### ISSUE TITLE
Are deleted jobs removed from the project table upon updating?

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#877]
Hi all,

Are deleted jobs removed from the project table upon updating?

For example

```
job_vasp = pr.create_job(pr.job_type.Vasp, 'junk_job_1')
job_vasp.structure = bulk_structure
job_vasp.calc_static()
job_vasp.run()

pr.job_table()
```
I get 

```
0 | 6333995 | finished | Mg2 | junk_job_1
```
I then add the data to a project table

```
DFT_data_table = pr.create_table("DFT_data_table")
# Specifiying the parameters to be stored
DFT_data_table.add["encut"] = get_job_encut
DFT_data_table.add["kpts"] = get_job_kpts
DFT_data_table.add["job_status"] = get_job_status

# running the table so that a folder is created
DFT_data_table.run()
DFT_data_table.get_dataframe()
```
I get 

```
0 | 6333995 | [4 4 4] | finished
```
Then I remove the first job and run a second job

```
pr.remove_job('junk_job_1')
job_vasp = pr.create_job(pr.job_type.Vasp, 'junk_job_2')
job_vasp.structure = bulk_structure
job_vasp.calc_static()
job_vasp.run()
pr.job_table()
```
I get 

```
0 | 6334011 | finished | None | DFT_data_table
1 | 6334012 | finished | Mg2 | junk_job_2
```
This makes sense with the first job removed and the second job added to the project table.
But when I update the project table and print the data frame, I still have the first job in the project table.
```
DFT_data_table.update_table()
DFT_data_table.get_dataframe()
```
I get 

```
0 | 6333995 | [4 4 4] | finished
6334011 | - | running
6334012 | [4, 4, 4] | finished
```
The first job is still there in the project table upon updating.
So, I am wondering if it is possible to remove the deleted jobs from the project table as well when I do update_table() by specifying some option or if there is a different function to update the table differently.

The running one in the above output is the job of the project table which is a secondary issue with update_table(). This appears with update_table() but not with run(). I guess it is not a big deal, but it would be nice to not have the data of the project table job itself in the table.

Thanks for taking the time. Any help is greatly appreciated. Thanks.

**Comment by jan-janssen** [comment]
I quick remark on adding functions, for the built in functions you can use:

```
DFT_data_table.add.get_job_encut
DFT_data_table.add.get_job_kpts
DFT_data_table.add.get_job_status
```

Rather than 

```
DFT_data_table.add["encut"] = get_job_encut
DFT_data_table.add["kpts"] = get_job_kpts
DFT_data_table.add["job_status"] = get_job_status
```

Like it is demonstrated in:
https://github.com/pyiron/pyiron-meeting-mpie/blob/master/handbook/8-bigdata/8-2-pyiron-table/pyirontable-ham-class.ipynb
Or:
https://github.com/jan-janssen/pyiron-nist-workshop/blob/master/quick_test.ipynb

Still to answer the question currently we keep all the calculation in the pyiron table and there is no way to remove the calculation from the dataframe. But feel free to add this feature, as it might also be interesting for others.

**Comment by jan-janssen** [comment]
I noticed you wrote your own functions, so the changes above do not work directly, they mainly work for the built in functions listed in:
https://github.com/pyiron/pyiron/blob/master/pyiron/table/datamining.py#L21

```
DFT_data_table.add.get_encut
DFT_data_table.add.get_n_kpts
```
