### ISSUE TITLE
Why does loading pyiron take so much time?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#907]
I noticed that it takes around 20 seconds to load pyiron now. It was slightly faster until a few days ago. What happened?

**Comment by jan-janssen** [comment]
I am not aware that anything essential changed in the core, so I would assume it is based on the high load on the database we have currently. Simply establishing the initial connection to the database seems to take quite some time.

**Comment by samwaseda** [comment]
Hm ok thanks!

**Comment by sudarsan-surendralal** [comment]
> 
> 
> I am not aware that anything essential changed in the core, so I would assume it is based on the high load on the database we have currently. Simply establishing the initial connection to the database seems to take quite some time.

I too am experiencing this today but not just at establishing the initial connection. It appears that reading from the HDF5 files is taking longer!

**Comment by jan-janssen** [comment]
It might also be related to a high load on the file system - maybe Christoph can give us more information on this.

**Comment by jan-janssen** [comment]
Can you check if it is better now?

**Comment by samwaseda** [comment]
Not really...

**Comment by samwaseda** [comment]
Although I realised yesterday that sometimes it takes 20 seconds, other times it takes 2 seconds and so on. It follows the same tendency right now as well.

**Comment by jan-janssen** [comment]
So to me it really seems to be storage related - I guess we should as Christoph in the CM meeting. Or did you contact him already?

**Comment by samwaseda** [comment]
ok if it's a cluster problem, I'm less concerned. I thought it was a more systematic problem inside pyiron that we should fix quickly before it gets entangled in the code. I'll write to him now anyway.

**Comment by jan-janssen** [comment]
Any update on this? @samwaseda @sudarsan-surendralal

**Comment by samwaseda** [comment]
I guess we can close this one. I don't think there's something systematic going on inside pyiron.
