### ISSUE TITLE
What if I want to change the folder name or move the notebook to a different folder

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#913]
Hi all,

I have been wondering about this for a while and don't know how to do this yet.
What if I want to change the folder name or move the notebook to a different folder?
I looked into previous issues but could not find anything that directly answers this. 

Any help is greatly appreciated. Thanks.

I tried this by copying a notebook folder into a different folder and tried running it, but when I do 

```
pr = Project(path='Encut_variation')
pr.job_table()
```
I get the following output in the notebook in it's original folder

```
id | status | chemicalformula | job | subjob | projectpath | project | timestart | timestop | totalcputime | computer | hamilton | hamversion | parentid | masterid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8488631 | finished | None | tot_DFT_data_table | /tot_DFT_data_table | /cmmc/u/ | skanchar/pyiron/p
```
Whereas in the copied folder, I get nothing

```
__
```

**Comment by jan-janssen** [comment]
For pyiron to be able to track your changes it is important that you do not manipulate the filesystem outside of pyiron. For moving and copying we have https://github.com/pyiron/pyiron-meeting-mpie/blob/master/handbook/6-file-and-job-management/6-3-rename-move-copy/project.ipynb but I have to admit I have not tested those for a while. The majority of the current user base is involved in method development so we are more focused on keeping the method - in this case the notebook - rather than the data. Still this is definitely an option to extend pyiron.

**Comment by sravankumarkb** [comment]
Thanks Jan. I will try it out and get back to you if there are any issues.

I think changing the folder names and moving the folders would be somewhat common especially in the beginning of a project. Because I realize whatever I have been doing should be a sub-folder in a major folder. As I keep doing more calcs and get more into the project the file structure will become more clear. 

Moving the minor calcs/notebooks into a major folder makes it easier to keep track of what I have been doing, rather than having everything on the main directory and me assigning weird and long names to the new folders. 😆

**Comment by sravankumarkb** [comment]
So, I fiddled around with the pr.copy_to() function in a sample notebook a little.
I came across a couple of issues. I have added a notebook demonstrating these issues to the meeting folder. It would be great if you can have a look. Thanks.

[https://github.com/pyiron/pyiron-meeting/blob/master/2020-09-04/original.ipynb](url)

**Comment by jan-janssen** [comment]
Please start by executing the example I send above and confirm it is working or not.

**Comment by sravankumarkb** [comment]
So, I executed the example you sent above. The job_table command after the 

```
pr.move_to(pr_move)
```
prints the same entries as in the example notebook
```
pr_base.job_table(all_columns=True)
```
![Capture_2](https://user-images.githubusercontent.com/53989475/91706308-82239c80-eb7e-11ea-9f1d-00954341482e.PNG)

However, when I execute the job_table command after 
```
pr_copy_to = Project('demo_3')
pr_new = pr_move.copy_to(pr_copy_to)
```
I get more entries in the job table 
```
pr_base.job_table(all_columns=True)
```
![Capture](https://user-images.githubusercontent.com/53989475/91705961-fd388300-eb7d-11ea-96a8-88cbf56c99d5.PNG)

This is the same issue I was facing in my notebook as well.

**Comment by jan-janssen** [comment]
Please use https://github.com/pyiron/pyiron/pull/919

**Comment by sravankumarkb** [comment]
My issue is resolved after using the branch @jan-janssen suggested. Can I close this issue?
