### ISSUE TITLE
loading project from path

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#914]
I am trying to load project from a different folder. It works when I do the following.

```
pr_Mg_bulk = Project(path='../../../Mg_bulk/encut_kpts_loop/Encut_kpts_variation')
```

However, when I tried the following, I got an error. Ideally, I would like to give the full address without having to count how many folders I have to go back. Please let me know if there is a way to do this. Thank you.

```
pr_Mg_bulk = Project(path='/u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation')
```
Error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-259ee8ff028f> in <module>
----> 1 pr_Mg_bulk = Project(path='/u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation')
      2 #pr_Mg_bulk = Project(path='../../../Mg_bulk/encut_kpts_loop/Encut_kpts_variation')

~/software/pyiron/pyiron/project.py in __init__(self, path, user, sql_query, default_working_directory)
    113             user=user,
    114             sql_query=sql_query,
--> 115             default_working_directory=default_working_directory
    116         )
    117         self.job_type = JobTypeChoice()

~/software/pyiron/pyiron/base/project/generic.py in __init__(self, path, user, sql_query, default_working_directory)
    130                 path = "."
    131 
--> 132         super(Project, self).__init__(path=path)
    133 
    134         self.user = user

~/software/pyiron/pyiron/base/project/path.py in __init__(self, path)
    226         if path == "":
    227             raise ValueError("ProjectPath: path is not allowed to be empty!")
--> 228         generic_path = self._convert_str_to_generic_path(path)
    229         super(ProjectPath, self).__init__(
    230             generic_path.root_path, generic_path.project_path

~/software/pyiron/pyiron/base/project/path.py in _convert_str_to_generic_path(self, path)
    380             #     raise ValueError(path, ' does not exist!')
    381             path = self._windows_path_to_unix_path(path)
--> 382             root_path, project_path = self._get_project_from_path(path)
    383             return GenericPath(root_path, project_path)
    384         else:

~/software/pyiron/pyiron/base/project/path.py in _get_project_from_path(full_path)
    413             str, str: root_path, project_path
    414         """
--> 415         root = Settings().top_path(full_path)
    416         if root is not None:
    417             pr_path = posixpath.relpath(full_path, root)

~/software/pyiron/pyiron/base/settings/generic.py in top_path(self, full_path)
    309         raise ValueError(
    310             "the current path {0} is not included in the .pyiron configuration. {1}".format(
--> 311                 full_path, self._configuration["project_paths"]
    312             )
    313         )

ValueError: the current path /u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation/ is not included in the .pyiron configuration. ['/cmmc/u/']
```

**Comment by jan-janssen** [comment]
The file system on CMTI is a bit different the absolute path is defined as: 
```
/cmmc/u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation/
```
rather than 
```
/u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation/
```

**Comment by sudarsan-surendralal** [comment]
Use `'/cmmc/u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation'`

**Comment by jan-janssen** [comment]
@sravankumarkb Maybe you have a suggestion how to make the current error message a bit more intuitive? 
```
ValueError: the current path /u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation/ is not included in the .pyiron configuration. ['/cmmc/u/']
```

**Comment by sravankumarkb** [comment]
> @sravankumarkb Maybe you have a suggestion how to make the current error message a bit more intuitive?
> 
> ```
> ValueError: the current path /u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation/ is not included in the .pyiron configuration. ['/cmmc/u/']
> ```

Thanks, Jan for asking.
I got the address by doing 'pwd'
Maybe we can say in the error that the address should be '/cmmc'+str(pwd) and throw in an example perhaps?

Eg: pwd = /u/skanchar/pyiron/project/example_project
address = '/cmmc'+str(pwd) = /cmmc/u/skanchar/pyiron/project/example_project

Unless you think it will be too long of error with the example, I think example makes it straight forward for the user.

**Comment by sravankumarkb** [comment]
> > @sravankumarkb Maybe you have a suggestion how to make the current error message a bit more intuitive?
> > ```
> > ValueError: the current path /u/skanchar/pyiron/projects/research/Mg_bulk/encut_kpts_loop/Encut_kpts_variation/ is not included in the .pyiron configuration. ['/cmmc/u/']
> > ```
> 
> Thanks, Jan for asking.
> I got the address by doing 'pwd'
> Maybe we can say in the error that the address should be '/cmmc'+str(pwd) and throw in an example perhaps?
> 
> Eg: pwd = /u/skanchar/pyiron/project/example_project
> address = '/cmmc'+str(pwd) = /cmmc/u/skanchar/pyiron/project/example_project
> 
> Unless you think it will be too long of error with the example, I think example makes it straight forward for the user.

Sorry, I realised instead of pwd it should be address of the project we are loading in the example. I see that pwd can be confusing for the user, as the user might just add the address of the directory current project is in and not the project the user wants to load.

**Comment by jan-janssen** [comment]
If you do the same in python it returns the right path: 
```
os.path.abspath(os.path.curdir)
```

**Comment by sravankumarkb** [comment]
> If you do the same in python it returns the right path:
> 
> ```
> os.path.abspath(os.path.curdir)
> ```

Thanks @jan-janssen . this command is useful. Maybe the error can ask the user to run that command to give the address to the path variable.
One of the main things with all these errors/issues is once you know what the problem is, the solution looks simple. That might not be the case for new users!
