### ISSUE TITLE
Issue with decimals in VASP incar generated by pyiron

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#916]
Hi all,
I tried specifying the force criterion to 1e-4 in my VASP calc using the ionic_force_tolerance tag. But the EDIFFG of the INCAR is 0.001 instead of 0.0001!
It is off by one decimal. Is the same happening with the EDIFF as well? Thanks.
```
temp_job_name = 'temp_job'
job = pr.create_job(pr.job_type.Vasp, temp_job_name)
job.set_convergence_precision(electronic_energy=1e-7)
job.calc_minimize(ionic_force_tolerance=1e-4)
job.input.incar
```
```
	Parameter	Value	Comment
0	SYSTEM	temp_job	jobname
1	PREC	Accurate	
2	ALGO	Fast	
3	LREAL	False	
4	LWAVE	False	
5	LORBIT	0	
6	EDIFF	1e-07	
7	EDIFFG	0.001	
8	ISIF	2	
9	IBRION	2	
10	NELM	400	
11	NSW	100	
```

**Comment by sravankumarkb** [comment]
I guess the EDIFF is okay, but the EDIFFG is not. Here is what I have upon doing 

```
grep EDIFF OUTCAR
```

```
   EDIFF  = 0.1E-06   stopping-criterion for ELM
   EDIFFG = 0.1E-02   stopping-criterion for IOM
```

**Comment by sravankumarkb** [comment]
Am I better off doing the following?

```
temp_job_name = 'temp_job'
job = pr.create_job(pr.job_type.Vasp, temp_job_name)
#job.set_convergence_precision(electronic_energy=1e-7)
#job.calc_minimize(ionic_force_tolerance=1e-4)
job.input.incar['EDIFFG'] = 1e-4
job.input.incar['EDIFF'] = 1e-7
job.input.incar
```
```
SYSTEM | temp_job | jobname
PREC | Accurate |  
ALGO | Fast |  
LREAL | False |  
LWAVE | False |  
LORBIT | 0 |  
EDIFFG | 0.0001 |  
EDIFF | 1e-07
```

**Comment by sravankumarkb** [comment]
One still has to be careful, because just setting the 'EDIFFG' tag is not sufficient to do a relaxation as the default 'NSW' is 0 in VASP. So, I think the following is what one has to do to be able to run the relaxation with the correct EDIFFG.
Even though I found a solution, I am keeping this issue open as the job.calc_minimize(ionic_force_tolerance=1e-4) setting could be fixed/clarified to me. Thanks.

```
temp_job_name = 'temp_job'
job = pr.create_job(pr.job_type.Vasp, temp_job_name)
job.calc_minimize()
job.input.incar['EDIFFG'] = 1e-4
job.input.incar['EDIFF'] = 1e-7
job.input.incar
```
```
SYSTEM | temp_job | jobname
PREC | Accurate |  
ALGO | Fast |  
LREAL | False |  
LWAVE | False |  
LORBIT | 0 |  
ISIF | 2 |  
IBRION | 2 |  
NELM | 400 |  
NSW | 100 |  
EDIFFG | 0.0001 |  
EDIFF | 1e-07
```

**Comment by sudarsan-surendralal** [comment]
This is definitely a bug. Temporarily (while we fix this) you can call `set_convergence_precision` after `calc_minimize` and then you are done.

```
job.calc_minimize()
job.set_convergence_precision(electronic_energy=1e-7, ionic_force_tolerance=1e-4)
```

**Comment by sravankumarkb** [comment]
Thanks @sudarsan-surendralal  
You can close this issue once it gets fixed. Have a good weekend.
