### ISSUE TITLE
Question about time limit of queues on cmti

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#927]
Hi all,

When I do 

```
temp_job.server.view_queues()
```
```
       cores_max cores_min run_time_max memory_max
cm          1200         1         5760       None
cmfe        1200         1         5760       None
cmti        1200         1         5760       None
s_cmfe        40         1         5760       None
p_cmfe      1200        40         5760       None
```
Is the run_time_max in seconds or hours? I am guessing in seconds. 😆

I am wondering what the default run_time_max is if I don't specify it explicitly.
If I want to set a run_time_max manually, do I just do the following? Thanks.

```
temp_job.server.run_time = 5000 # in seconds?
```

PS: I don't recall the announcement being made in the CM meeting as discussed in the pyiron meeting on Friday. The announcement about the change from hours to seconds in something which I don't remember the details of! Please ignore this PS if the announcement was made.

**Comment by jan-janssen** [comment]
It is in seconds now - it was changed yesterday and I forgot to update the limits - it is fixed now https://github.com/pyiron/pyiron-resources-mpie/commit/bfc454c95aff63120e28db443469c009c63fa7bf

Can you try again?

**Comment by sravankumarkb** [comment]
Thanks @jan-janssen 
The time limit is now back to 4 days. What if I want to change my timelimit though?

**Comment by jan-janssen** [comment]
```
job.server.run_time 
```
