### ISSUE TITLE
No need to specify number of nodes?

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#929]
Hi all,
I am wondering if I there is no need to specify the number of nodes.
Upon doing

```
scontrol show node | grep CoresPerSocket=
```
I see that each node has 20 cores. Upon doing, 
```
temp_job.server.queue_view
```
![Capture](https://user-images.githubusercontent.com/53989475/91867862-60a4dc80-ec74-11ea-966b-bfc9e823e602.PNG)

I see that the max cores are more than 20. So, I am guessing whenever I specify the number of cores, the pyiron code figures out the number of nodes to be requested? Thanks.

**Comment by jan-janssen** [comment]
Yes, pyiron is designed to simplify the process for the user so we calculate the number of nodes for you.
