### ISSUE TITLE
Ugly Lammps architecture

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron#935]
So I was putting together a demo notebook for the website to couple to a recent paper, as discussed at the last developer meeting.

When I went to run a VC-SGC (i.e. MD/MC) Lammps calculation, I got a strange error that my `pressure` argument wasn't iterable.

Digging into it, it didn't take long to figure out that this is because every Lammps `calc_X` method (except `calc_static`) not needs the line `rotation_matrix = self._get_rotation_matrix(pressure=pressure)` so that `lammps.base.calc_X` (which is publicly facing and doesn't have a `rotation_matrix` argument) can pass it to `lammps.input.control.calc_X` (which *does* take that argument).

The problem is that back when this rotation business got added ([pull 666](https://github.com/pyiron/pyiron/pull/666)), `calc_vcsgc` got left out, and we apparently don't have the integration tests to catch this problem.

To be 100% clear, I'm not casting any stones here -- I reviewed pull 666 myself and still didn't notice this side effect -- but regardless the current code smells real bad. I made a [hotfix for the issue here](https://github.com/pyiron/pyiron/pull/934), but we should think about the underlying problem.

At a minimum we should move around the responsibility for who calculates `rotation_matrix`. Right now the `base` module calculates it and passes it to the `input.control` module in (almost) *every* case. This is just asking to be forgotten -- as it already has once 😝  

At a higher level, we should probably dig in a little bit to the entire interaction between `lammps.base` and `lammps.input.control`. I find it difficult to keep track of all the identical names with different signatures, and there's lots of code that's just passing these giant (sometimes subtly changing) parameter sets from one module to another. There's also the undesirable workaround I rigged to (imperfectly!!!) programmatically reference the docstrings so they stay synchronized. I don't have a specific suggestion atm for how to improve it, but I'm confident there's room to make this easier to understand and maintain.

**Comment by jan-janssen** [comment]
I agree that the LAMMPS parser could be updated. Based on the recent success of deriving our Atoms class from the ASE atoms class I would even think about deriving our parser from the pymatgen LAMMPS parser:
https://github.com/materialsproject/pymatgen/tree/master/pymatgen/io/lammps
I have not tested the pymatgen LAMMPS parser but given the performance of their VASP parser I believe it might be worth taking a look. In addition it would suite our strategy of combining the most powerful tools available in the community.

**Comment by liamhuber** [comment]
Nice insight! I also have never looked at their parser, but I was super impressed with how the pivot to inherit directly from ASE Atoms went and would be keen to see that success repeated.

**Comment by jan-janssen** [comment]
@liamhuber Can we somehow take action on this issue? Otherwise I would like to close it for now until we find somebody can spend some time on it. Or we could add it to the open issues towards 1.0 https://github.com/pyiron/pyiron/issues/795 . I just try to keep the issues somewhat limited to things we can address more or less quickly.

**Comment by liamhuber** [comment]
Yes, we can close it. I wish there was an "archive issue" option as it's really not resolved, but I'm fine with using the issues as an immediate action list.
