### ISSUE TITLE
pyiron 0.3.0 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#939]
pyiron version 0.3.0 is released, this includes the latest changes of the current master branch: 

- The atoms class is now derived from the ASE atoms class. 
- Remote HPC clusters without a local database can be accessed via SSH. 
- SPHInX is the first simulation code to use the newly introduced InputList class which superseeds the GenericParameters class and adds support for hierarchical input structures within a single instance of the class.  

Besides these new features many bugs were fixed to improve the stability of the code. Still as core components of pyiron changed with this release, we suggest caution when updating. Bug fixes are going to be distributed as 0.3.X .

**Comment by pmrv** [comment]
Does that mean we want to add an additional step in backwards compatibility testings to include 0.2.17?

**Comment by jan-janssen** [comment]
I guess 0.3.X is mainly used in the transition to 1.X so testing with 0.2.17 should be sufficient.
