### ISSUE TITLE
Using more core for faster calculation 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#940]
I know using more cores doesn’t always mean a faster calculation - it’s all about efficiency. I guess SPHInX can only parallelize over k-points, and in my case, I  only have 13 irreducible points in the reciprocal cell. So for my calculation, 13 is the best I can do. but I still have a question which do I have any choice to have a faster calculation? right now it takes almost 7 days: 
here is piece of code 

job_sphinx.version = "2.6.2_default_mpi"
job_sphinx.server.cores = 13
job_sphinx.run(run_mode="queue", run_again=True)

**Comment by ashtonmv** [comment]
Hi @mostafajoulaian, without seeing the rest of the notebook this is a tough question to answer.

There are several ways to speed up a DFT calculation, but not all of them are always a good idea. One possibility would be to fix the coordinates of more atoms in your cell. In pyiron this could look like the following:
```python
# try increasing this until ~1/3 of your atoms are fixed.
eps = 1

pos_z = structure.positions[:, 2]
z_min, z_max = np.min(pos_z), np.max(pos_z)

relax_indices = np.argwhere((pos_z - eps) > z_min).flatten()
structure.selective_dynamics[relax_indices] = [True, True, True]
```

To visualize which atoms have been fixed in pyiron, try this. Blue atoms will move around during the relaxation and black atoms will not.
```python
colors = np.array(["black" for atom in structure])
colors[relax_indices] = "blue"
structure.plot3d(colors=colors)
```

**Comment by liamhuber** [comment]
Good question. Like @ashtonmv, I agree it's hard to give specifics without seeing the actual notebook.

Is your calculation making multiple ionic steps, e.g. in a structure minimization? One "cheat" you can do in this case is to "pre-minimize" your structure, either with a known analytic displacement field, or -- if available -- a decent EAM potential. (In the second case, be sure not to relax cell size or shape unless the EAM has the exact same lattice parameters as your DFT!). A final suggestion, and this may or may not actually speed things up, is to pre-relax with DFT itself, but just at lower convergence settings.

**Comment by mostafajoulaian** [comment]
@ashtonmv thank you for your suggestion I will do it.
@liamhuber yes exactly in my calculation I do multiple ionic steps. I want to give a shot to pre-minimize my structure and see does it effective or not.
