### ISSUE TITLE
VASP output positions - CONTCAR vs. OUTCAR

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#944]
Following the same discussion as in https://github.com/pyiron/pyiron/issues/894 I noticed that the CONTCAR includes high precision results for the output positions compared to the OUTCAR. So in particular for high precision calculations but also for fitting machine learning potentials these limitations can cause issues.

**Comment by jan-janssen** [comment]
@sudarsan-surendralal Can you take a look at this?

**Comment by sudarsan-surendralal** [comment]
I checked this. Such precision is only available in the CONTCAR files (not XDATCAR or vasprun.xml). So such precision in the positions will only be available for the final structure and not for the rest of the ionic steps. We can then store this structure in `output/structure`. Is this okay?

**Comment by jan-janssen** [comment]
That would be great - I guess it really only affects a few of us, mainly those who do high-precision calculation and those who want to fit machine learning potentials.
