### ISSUE TITLE
writing data from "not converged" jobs into project table

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#946]
Hi all,

Is there a way to write the data from "not converged" jobs in the project table?
I see that some of the jobs are "not converged" upon doing pr.job_table() after the execution of all jobs finishes.
However, when I update the project table, only the data from finished jobs gets written in the project table.

Thanks.

**Comment by jan-janssen** [comment]
```
pyiron_table.update_table(job_status_list=["finished", "not_converged"])
```

**Comment by sravankumarkb** [comment]
Thanks @jan-janssen 
It works, but I think there is a trick, when I tried to use it as it is, it did not work.
But when I did 
```
pyiron_table.update_table(job_status_list=["finished"])
pyiron_table.update_table(job_status_list=["finished", "not_converged"])
```
Then it worked. Anyways, I thought I would leave this as a comment in case someone in the future wants to do this. Thanks.
