### ISSUE TITLE
Warning when atoms are added

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#951]
I have an Fe structure to which I'd like to add one C atom:

```
job.structure = pr.create_structure('Fe', 'bcc', a_0).repeat(n_repeat)
job.structure += pr.create_atoms(positions=[[0, 0, 0.5*a_0]], elements=['C'])
```

Here, since `create_atoms` has an undefined cell (i.e. [0, 0, 0]), pyiron complains, because of the incompatibility of cell sizes, which is something we added recently. But in this case I find it not only bothering, but also potentially confusing, because adding atoms at least for me doesn't have a notion of cell.

My suggestion: if the volume of the second structure is 0 with periodic boundary conditions, we don't issue the warning. What do you think?

**Comment by sudarsan-surendralal** [comment]
This warning was included on request so I'm okay with changing it. But the resulting cell depends on the order of addition. This info is not communicated to the user if we suppress warnings. The below code will give a different structure

```
job.structure = pr.create_atoms(positions=[[0, 0, 0.5*a_0]], elements=['C'])
job.structure += pr.create_structure('Fe', 'bcc', a_0).repeat(n_repeat)
```
>
>My suggestion: if the volume of the second structure is 0 with periodic boundary conditions, we don't issue the warning. What do you think?

You mean if the second structure has no defined cell? Not sure if PBC makes sense in that case though.

**Comment by samwaseda** [comment]
> This warning was included on request so I'm okay with changing it. But the resulting cell depends on the order of addition. This info is not communicated to the user if we suppress warnings. The below code will give a different structure
> 
> ```
> job.structure = pr.create_atoms(positions=[[0, 0, 0.5*a_0]], elements=['C'])
> job.structure += pr.create_structure('Fe', 'bcc', a_0).repeat(n_repeat)
> ```
> 
> > My suggestion: if the volume of the second structure is 0 with periodic boundary conditions, we don't issue the warning. What do you think?
> 
> You mean if the second structure has no defined cell? Not sure if PBC makes sense in that case though.

Changing order not only changes the structure, but it's also semantically wrong (i.e. "adding an atom to a structure" makes sense but "adding a structure to an atom" doesn't).

Without PBC it's possible that the user specifically didn't want to define a cell, which would make sense in LAMMPS, in which case there's basically no notion of "cell", but I don't know if it's allowed in pyiron.

**Comment by sudarsan-surendralal** [comment]
I tend to agree with you but I'm pretty certain this warning was requested by other users. Let's discuss this in the pyiron meeting.
