### ISSUE TITLE
Reducing size of static test files

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#953]
Some of the files we have in `tests/static` are quite large and we could benefit from reducing their size. Some of these files are from simulation outputs, so we could repeat such simulations such that only modestly sized outputs are generated while retaining the complexity of the type of simulation.

**Comment by samwaseda** [comment]
I guess SPHInX files are not particularly large, but do you have specific files in mind?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> I guess SPHInX files are not particularly large, but do you have specific files in mind?

I think Sphinx files are fine. The vasp test files (especially those in `tests/static/vasp_test_files`) on the other hand are huge.
