### ISSUE TITLE
 500 : Internal Server Error

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron#967]
Notebooks do not open and I get an error message "500 : Internal Server Error"

**Comment by sudarsan-surendralal** [comment]
I too am facing the same problem

**Comment by jan-janssen** [comment]
We had a user with extended permissions writing directly to the conda environment which broke the environment when I updated to the latest pyiron version. I contacted the user to fix this and implemented a workaround for the meantime. Everything should be back to normal now. Can you confirm this?

**Comment by liamhuber** [comment]
It is still not working for me.

I have my own pyiron repos in my python path ahead of the default locations, and I haven't yet pulled in the pyiron-vs-pyiron_base split --- Do I still already need to do this?

**Comment by jan-janssen** [comment]
Have you tried restarting your jupyter server?

**Comment by ibrsam** [comment]
I pulled pyiron_base and restarted the server, but it still not working.

**Comment by jan-janssen** [comment]
@ibrsam You try to modify a file in the conda directory, is this required? 
```
    HTTPServerRequest(protocol='https', host='localhost:8000', method='GET', uri='/user/ibrsam/notebooks/ibrsam/projects/ions_in_water/data_import.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/base/handlers.py", line 512, in render_template
        return template.render(**ns)
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "<template>", line 2, in top-level template code
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
        for name in get_export_names():
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 323, in __init__
        super().__init__(config=config, **kw)
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 115, in __init__
        self._init_preprocessors()
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 489, in _init_preprocessors
        conf = self._get_conf()
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
        if conf_path.exists():
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/pathlib.py", line 1361, in exists
        self.stat()
      File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/pathlib.py", line 1183, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/jupyter/nbconvert/templates/conf.json'
```

**Comment by liamhuber** [comment]
Restarted the server, still getting the problem.

To verify: is it OK to *not* have my own pyiron_base repo, as long as my pyiron repo head is back before the split?

**Comment by jan-janssen** [comment]
@liamhuber Sure, the python path is not effected - I have the feeling it is more related to user storing jupyter themes in the central conda installation

**Comment by ibrsam** [comment]
> @ibrsam You try to modify a file in the conda directory, is this required?
> 
> ```
>     HTTPServerRequest(protocol='https', host='localhost:8000', method='GET', uri='/user/ibrsam/notebooks/ibrsam/projects/ions_in_water/data_import.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1')
>     Traceback (most recent call last):
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
>         result = await result
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
>         yielded = self.gen.send(value)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 101, in get
>         get_frontend_exporters=get_frontend_exporters
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/base/handlers.py", line 512, in render_template
>         return template.render(**ns)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
>         self.environment.handle_exception()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
>         reraise(*rewrite_traceback_stack(source=source))
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
>         raise value.with_traceback(tb)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
>         {% extends "page.html" %}
>       File "<template>", line 2, in top-level template code
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/page.html", line 154, in top-level template code
>         {% block header %}
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 115, in block "header"
>         {% for exporter in get_frontend_exporters() %}
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
>         for name in get_export_names():
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
>         e = get_exporter(exporter_name)(config=config)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
>         if getattr(exporter(config=config), 'enabled', True):
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 323, in __init__
>         super().__init__(config=config, **kw)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 115, in __init__
>         self._init_preprocessors()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 489, in _init_preprocessors
>         conf = self._get_conf()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
>         if conf_path.exists():
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/pathlib.py", line 1361, in exists
>         self.stat()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/pathlib.py", line 1183, in stat
>         return self._accessor.stat(self)
>     PermissionError: [Errno 13] Permission denied: '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/jupyter/nbconvert/templates/conf.json'
> ```

No, I did not try to modify anything in the conda envirnment. I am using x-forwarding to get access to my notebooks.

**Comment by liamhuber** [comment]
> @liamhuber Sure, the python path is not effected - I have the feeling it is more related to user storing jupyter themes in the central conda installation

Ok, thanks for the confirmation!

I have to confess, it is not clear to me what is the source of my own jupyterthemes. In `.../lhuber/.jupyter` I set up the theme chesterish. Do I need to deactivate this or something to get my notebooks opening again?

> Everything should be back to normal now. Can you confirm this?

Can anyone this yet? @sudarsan-surendralal?

**Comment by sudarsan-surendralal** [comment]
I can confirm that it's working now! Thanks @jan-janssen for the fix!

**Comment by ibrsam** [comment]
It is working for me as well! Thanks @jan-janssen!

**Comment by sudarsan-surendralal** [comment]
Re-opening this before we confirm that this works for others as well (eg. @liamhuber).

> 
> 
> @ibrsam You try to modify a file in the conda directory, is this required?
> 
> ```
>     HTTPServerRequest(protocol='https', host='localhost:8000', method='GET', uri='/user/ibrsam/notebooks/ibrsam/projects/ions_in_water/data_import.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1')
>     Traceback (most recent call last):
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
>         result = await result
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
>         yielded = self.gen.send(value)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 101, in get
>         get_frontend_exporters=get_frontend_exporters
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/base/handlers.py", line 512, in render_template
>         return template.render(**ns)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
>         self.environment.handle_exception()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
>         reraise(*rewrite_traceback_stack(source=source))
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
>         raise value.with_traceback(tb)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
>         {% extends "page.html" %}
>       File "<template>", line 2, in top-level template code
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/page.html", line 154, in top-level template code
>         {% block header %}
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 115, in block "header"
>         {% for exporter in get_frontend_exporters() %}
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
>         for name in get_export_names():
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
>         e = get_exporter(exporter_name)(config=config)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
>         if getattr(exporter(config=config), 'enabled', True):
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 323, in __init__
>         super().__init__(config=config, **kw)
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 115, in __init__
>         self._init_preprocessors()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 489, in _init_preprocessors
>         conf = self._get_conf()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
>         if conf_path.exists():
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/pathlib.py", line 1361, in exists
>         self.stat()
>       File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/pathlib.py", line 1183, in stat
>         return self._accessor.stat(self)
>     PermissionError: [Errno 13] Permission denied: '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/jupyter/nbconvert/templates/conf.json'
> ```

Could this happen if any users accidentally invokes conda commands in the cluster?

**Comment by liamhuber** [comment]
Also for me, so updating to the post-split environment was indeed not necessary.

Thanks for the fast fix, @jan-janssen!

**Comment by liamhuber** [comment]
@sudarsan-surendralal Thanks for the re-open 😉 I was already drafting my confirmation post 😄

**Comment by ibrsam** [comment]
Sorry if I closed the issue fast! I should have waited for more time :))
