### ISSUE TITLE
IndexError after appending to another structure

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#969]
I was implementing [this](https://github.com/pyiron/pyiron/issues/951) and realized that the following lines return an `IndexError`:

```
a_0 = 2.86
structure = Project('.').create_structure('Fe', 'bcc', a_0)
C = Project('.').create_atoms(symbols=['C'], positions=[[0, 0, 0.5*a_0]])
C # returns one C structure
structure += C
C # IndexError
```

It looks likes an ASE problem but maybe there's someone (aka @sudarsan-surendralal) who knows how to fix it on the pyiron side?

**Comment by sudarsan-surendralal** [comment]
This works fine for me. Can't debug this unless I know what you changed in the source code

**Comment by samwaseda** [comment]
I'm using master...

**Comment by sudarsan-surendralal** [comment]
Somehow the indices are wrong `print(C.indices)` does not make sense!

**Comment by sudarsan-surendralal** [comment]
@samwaseda, it should work with the branch in the linked PR. The problem was that we were modifying the numpy array which was a pointer to the original array and not a copy
