### ISSUE TITLE
reading cell

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#981]
Hi all,

I came across the following error in one of my jobs. Upon checking the "error.out", I understand that the calculation finished and I believe the error has to do with pyiron reading the OUTCAR from VASP. More specifically, due to the lack of space between the numbers in OUTCAR. 

Error:
```
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 842, in <listcomp>
    cell.append([float(l) for l in line.split()[0:3]])
ValueError: could not convert string to float: '0.000000000100.600000000'
```
Part of my OUTCAR: (please have a look at the z direct lattice vector)
```
  energy-cutoff  :      200.00
  volume of cell :      886.56
      direct lattice vectors                 reciprocal lattice vectors
     3.190000000  0.000000000  0.000000000     0.313479624  0.180987545  0.000000000
    -1.595000000  2.762621038  0.000000000     0.000000000  0.361975090  0.000000000
     0.000000000  0.000000000100.600000000     0.000000000  0.000000000  0.009940358
```
I think this problem will repeat if I try any calculations with big cells. Is there a way around this? Thank you.

**Comment by sudarsan-surendralal** [comment]
How does the POSCAR file look line?

**Comment by sravankumarkb** [comment]
beginning of the POSCAR:

```
Poscar file generated with pyiron
1.0
3.190000000000000 0.000000000000000 0.000000000000000
-1.595000000000000 2.762621038072359 0.000000000000000
0.000000000000000 -0.000000000000000 100.600000000000009
Mg
32
Selective dynamics
Cartesian
```

**Comment by sravankumarkb** [comment]
If it helps, here is more verbose "error.out":

```
DAV:  12    -0.479726634030E+02   -0.40803E-07   -0.96812E-07  1976   0.342E-03
  33 F= -.47972663E+02 E0= -.47760127E+02  d E =-.623918E-03
 curvature: ****** expect dE=-0.437E-02 dE for cont linesearch -0.759E-06
 trial: gam= 0.34888 g(F)=  0.359E-04 g(S)=  0.000E+00 ort =-0.306E-05 (trialstep = 0.691E+01)
 search vector abs. value=  0.217E-03
 reached required accuracy - stopping structural energy minimisation

2020-09-21 14:54:34,661 - pyiron_log - INFO - run job: Mg_16 id: 8907771, status: collect
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/skanchar/software/pyiron/pyiron/cli/__main__.py", line 2, in <module>
    main()
  File "/u/skanchar/software/pyiron/pyiron/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/u/skanchar/software/pyiron/pyiron/cli/wrapper.py", line 39, in main
    submit_on_remote=args.submit
  File "/u/skanchar/software/pyiron/pyiron/base/job/wrapper.py", line 150, in job_wrapper_function
    job.run()
  File "/u/skanchar/software/pyiron/pyiron/base/job/wrapper.py", line 116, in run
    self.job.run_static()
  File "/u/skanchar/software/pyiron/pyiron/base/job/generic.py", line 789, in run_static
    self.run()
  File "/u/skanchar/software/pyiron/pyiron/base/job/generic.py", line 700, in run
    self._run_if_collect()
  File "/u/skanchar/software/pyiron/pyiron/base/job/generic.py", line 1468, in _run_if_collect
    self.collect_output()
  File "/u/skanchar/software/pyiron/pyiron/vasp/base.py", line 392, in collect_output
    directory=self.working_directory, sorted_indices=self.sorted_indices
  File "/u/skanchar/software/pyiron/pyiron/vasp/base.py", line 1893, in collect
    self.outcar.from_file(filename=posixpath.join(directory, "OUTCAR"))
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 57, in from_file
    cells = self.get_cells(filename=filename, lines=lines)
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 249, in get_cells
    return self._get_cells_praser(lines=lines, trigger_indices=trigger_indices)
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 842, in _get_cells_praser
    cell.append([float(l) for l in line.split()[0:3]])
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 842, in <listcomp>
    cell.append([float(l) for l in line.split()[0:3]])
ValueError: could not convert string to float: '0.000000000100.600000000'
```

**Comment by sudarsan-surendralal** [comment]
Can you see if the calculation runs if you reduce the number of digits in the `POSCAR`?  

PS: The cell setup seems a bit strange (do you really need 100A of vacuum?)

**Comment by sravankumarkb** [comment]
Thanks @sudarsan-surendralal 
Can you please let me know the code to reduce the number of digits in the POSCAR?

The 100A is not really vacuum, the number of layers is just too high and the vacuum is actually just 10A.

**Comment by sudarsan-surendralal** [comment]
Can you try with this branch: https://github.com/pyiron/pyiron/tree/vasp_precision

**Comment by sravankumarkb** [comment]
Just leaving the code here for switching to the vasp_precision branch as it did not show up when I did
```
git fetch
```
Code to switch to the vasp_precision branch

```
git checkout -b vasp_precision origin/vasp_precision
```

**Comment by sravankumarkb** [comment]
Thank you @sudarsan-surendralal for helping me switch to the branch. 

So I have switched to the vasp_precision branch with the commands in the above comment.  I stopped the server and launched the jupyter notebook server again.

Unfortunately I get the same error again. Should I change anything with the setup of the calcs after I switch to the vasp_precision branch? Thanks.

Error
```
  33 F= -.47972663E+02 E0= -.47760128E+02  d E =-.623849E-03
 curvature: ****** expect dE=-0.437E-02 dE for cont linesearch -0.773E-06
 trial: gam= 0.34901 g(F)=  0.359E-04 g(S)=  0.000E+00 ort =-0.309E-05 (trialstep = 0.691E+01)
 search vector abs. value=  0.217E-03
 reached required accuracy - stopping structural energy minimisation

2020-09-28 15:32:20,320 - pyiron_log - INFO - run job: Mg_16 id: 8917789, status: collect
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__main__.py", line 2, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/wrapper.py", line 39, in main
    submit_on_remote=args.submit
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 150, in job_wrapper_function
    job.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 116, in run
    self.job.run_static()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 789, in run_static
    self.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 700, in run
    self._run_if_collect()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 1487, in _run_if_collect
    self.collect_output()
  File "/u/skanchar/software/pyiron/pyiron/vasp/base.py", line 383, in collect_output
    directory=self.working_directory, sorted_indices=self.sorted_indices
  File "/u/skanchar/software/pyiron/pyiron/vasp/base.py", line 1890, in collect
    self.outcar.from_file(filename=posixpath.join(directory, "OUTCAR"))
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 57, in from_file
    cells = self.get_cells(filename=filename, lines=lines)
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 253, in get_cells
    return self._get_cells_praser(lines=lines, trigger_indices=trigger_indices)
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 883, in _get_cells_praser
    cell.append([float(l) for l in line.split()[0:3]])
  File "/u/skanchar/software/pyiron/pyiron/vasp/outcar.py", line 883, in <listcomp>
    cell.append([float(l) for l in line.split()[0:3]])
ValueError: could not convert string to float: '0.000000000100.600000000'
```
This is how the POSCAR looks

```
Poscar file generated with pyiron
1.0
3.190000000000000e+00 0.000000000000000e+00 0.000000000000000e+00
-1.595000000000000e+00 2.762621038072359e+00 0.000000000000000e+00
0.000000000000000e+00 -0.000000000000000e+00 1.006000000000000e+02
```
and this is how the OUTCAR looks
```
      direct lattice vectors                 reciprocal lattice vectors
     3.190000000  0.000000000  0.000000000     0.313479624  0.180987545  0.000000000
    -1.595000000  2.762621038  0.000000000     0.000000000  0.361975090  0.000000000
     0.000000000  0.000000000100.600000000     0.000000000  0.000000000  0.009940358
```

**Comment by sudarsan-surendralal** [comment]
That's bad. It looks like the Vasp output is the problem. We should quickly discuss this in the pyiron meeting!

**Comment by sravankumarkb** [comment]
Yeah, I figured it has to do with reading the Vasp output. 
Okay, I can show the notebook and the OUTCAR files in the pyiron meeting on Friday. The notebook is a little messy. 
If you want, I can make a separate notebook just for this specific issue. 
Let me know if I need to send an email to Sam about this issue or contribution. Thanks.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Yeah, I figured it has to do with reading the Vasp output.
> Okay, I can show the notebook and the OUTCAR files in the pyiron meeting on Friday. The notebook is a little messy.
> If you want, I can make a separate notebook just for this specific issue.
> Let me know if I need to send an email to Sam about this issue or contribution. Thanks.

Just put your contribution in this thread: https://github.com/orgs/pyiron/teams/pyiron/discussions/24?from_comment=1

**Comment by niklassiemer** [comment]
Knowing how VASP is writing the OUTCAR (probably Fortran 13.10F) one could change the parser to split after max 13 characters, but this is not a nice or robust way to solve this.

**Comment by pmrv** [comment]
Imho this is a VASP bug and we should report it to them as such.  Anyone has experience if they are responsive to these things at all?

**Comment by samwaseda** [comment]
Shouldn't you guys first report this bug to Georg Kresse before talking about it at the pyiron meeting (since this is obviously a VASP problem)? I mean you're welcome to talk about it at the pyiron meeting as well, but it's unlikely that the discussion goes beyond "beware of this problem" and "who's gonna contact Georg Kresse?"

**Comment by sudarsan-surendralal** [comment]
@sravankumarkb: Can you  try with the updated changes (`get fetch; git pull`). I've added an exception and now the cells will be parsed from the vasprun.xml file. Don't run the job again. Just type `job.collect_output()` and see.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Shouldn't you guys first report this bug to Georg Kresse before talking about it at the pyiron meeting (since this is obviously a VASP problem)? I mean you're welcome to talk about it at the pyiron meeting as well, but it's unlikely that the discussion goes beyond "beware of this problem" and "who's gonna contact Georg Kresse?"

Since we now know this is a VASP problem, yes we should raise it with VASP developers. But since VASP is propreitery software, I think there are certain rules as to how to raise such specific issues with the developers rather than simply emailing Georg Kresse. For example, only users with registered VASP licences in their names are eligible for VASP support. Maybe by briefly mentioning this issue (time permitting) in the meeting we can at least know what to do next.

**Comment by sravankumarkb** [comment]
Here is the output of the 

```
job.collect_output()
```

Output for a calculation that finished without an error
```
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/generic/hdfio.py:694: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([np.array(v) for v in value]),
```
Output for a calculation that finished with an error
```
/u/skanchar/software/pyiron/pyiron/vasp/outcar.py:888: UserWarning: Unable to parse the cells from the OUTCAR file
  warnings.warn("Unable to parse the cells from the OUTCAR file")
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/generic/hdfio.py:694: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([np.array(v) for v in value]),
```

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Here is the output of the
> 
> ```
> job.collect_output()
> ```
> 
> Output for a calculation that finished without an error
> 
> ```
> /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/generic/hdfio.py:694: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   np.array([np.array(v) for v in value]),
> ```
> 
> Output for a calculation that finished with an error
> 
> ```
> /u/skanchar/software/pyiron/pyiron/vasp/outcar.py:888: UserWarning: Unable to parse the cells from the OUTCAR file
>   warnings.warn("Unable to parse the cells from the OUTCAR file")
> /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/generic/hdfio.py:694: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   np.array([np.array(v) for v in value]),
> ```

That's good. So if you run the job again, it should work!

**Comment by sravankumarkb** [comment]
Thanks @sudarsan-surendralal

**Comment by sravankumarkb** [comment]
So I have removed the aborted jobs and ran them again, it worked and I don't have the error anymore. Thanks @sudarsan-surendralal 
Do I have to keep using the vasp_precision branch though to avoid this error?
Or can I revert back to the master branch?

**Comment by sudarsan-surendralal** [comment]
yes you can change to the master branch. But remember to pull the latest changes.
