### ISSUE TITLE
phonopy.py creates jobs with always the same name

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#982]
https://github.com/pyiron/pyiron/blob/8e3e7678b50ceebd106bdd341e19d4990988f495/pyiron/atomistics/master/phonopy.py#L97

I created two phonopy jobs with different structures. These jobs have different names, but the child jobs are both called `supercell_phonon_0`, which makes it impossible to load by job name. Can I change it to something like `"supercell_{}_{}".format(self._job.job_name, ind)`?

**Comment by jan-janssen** [comment]
I like the idea. Another option would be using the name of the reference job as a prefix like it was originally planned: https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/master/parallel.py#L930

**Comment by samwaseda** [comment]
That's in fact what I ended up doing in the pull request :D

**Comment by jan-janssen** [comment]
Can you also update the Murnaghan class? https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/master/murnaghan.py#L316

**Comment by jan-janssen** [comment]
And the convergence masters https://github.com/pyiron/pyiron/blob/master/pyiron/dft/master/convergence_encut_parallel.py#L49 and https://github.com/pyiron/pyiron/blob/master/pyiron/dft/master/convergence_kpoint_parallel.py#L49

**Comment by samwaseda** [comment]
ok
