### ISSUE TITLE
Creating AtomisticExampleJob which acts more like a real job

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#984]
Just a thought.

Currently `AtomisticExampleJob` does not give anything meaningful - we get always the same energy, random forces etc. This class cannot be used when we want to test for example a new energy minimizer class. How about using instead Einstein crystal? In this case we only have to calculate the displacements from the ideal positions, which means we hardly waste computational power, but still we get physically more meaningful values.

**Comment by jan-janssen** [comment]
I like the idea. The example job was mainly implemented to test the code ParallelMaster and SerialMaster jobs at a time when we did not have the codes included in conda.
