### ISSUE TITLE
Inconsistent behavior in murnaghan jobs

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#986]
While fitting to imported data I got an error when fitting with fit_polynomial instead of fit_birch_murnaghan (or some other EOS).
I think the reason is that fit_polynomial attempts to get the final structure and write it to the resulting hdf5 file, which the other fitting methods don't do. Since my template murnaghan jobs do not have an assigned structure an assertion error is thrown.

IMO the fit_polynomial and fit_EOS functions should behave the same, i.e. both write the final structure to the hdf5 or not.

**Comment by jan-janssen** [comment]
The Murnaghan job is designed to run the calculation, for fitting rather use https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/master/murnaghan.py#L323

**Comment by Leimeroth** [comment]
That solves my fitting problem, but i would still say that the different fitting methods should write the same output to the hdf5 file where applicable.

**Comment by jan-janssen** [comment]
There are many things which can be improved about pyiron and we are happy about everybody who contributes to improving it. So feel free to open a pull request to fix the issue. I just wanted to provide you with a quick solution to continue working.
