### ISSUE TITLE
Why is this line necessary?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#988]
https://github.com/pyiron/pyiron/blob/ad85c411629d7393033e5bed4a6ba522b5f56cef/pyiron/thermodynamics/hessian.py#L36

I guess it has to become `n_atom x 3 x n_atom x 3` but I don't understand why the user wants to set `n_atom x n_atom x 3 x 3` in the first place. Does it follow a certain format? With no example in sight it's difficult to understand the background of this class...

**Comment by jan-janssen** [comment]
That is the output format of phonopy https://github.com/pyiron/pyiron-meeting-mpie/blob/2a9c7423d4cf68f8ede6c5460e0058fce0e14ac0/meetings/2020-02-21-pyiron-meeting/jan-janssen/thermoint.ipynb

**Comment by samwaseda** [comment]
ok thanks
