### ISSUE TITLE
Importing jobs with copy_raw_files=True

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#995]
Imported jobs have the import_directory as working_directory. I think this is completely fine if the raw files are not copied, but it leads to limited functionality for jobs that are copied completely. F.e. job.run(delete_existing_job=True) gives an directory not empty error.
If i set job._import_directory=None  manually, job.working_directory gives me the directory in which the files are copied run(delete_existing_job) works, but it actually deletes the import_directory. I am pretty sure this should not be possible since the import directory is not in my .pyiron project path.
I tried to have a look at the import functions but I do not understand what is happening in import_single_calculation function (https://github.com/pyiron/pyiron/blob/e926873777d8cad79fc1b810eec15433e1c6497e/pyiron/project.py#L256).
Since the import directory is set to None anyway for some reason I do not undestand why it is not None from the start and why me setting it to None manually changes something.
https://github.com/pyiron/pyiron/blob/e926873777d8cad79fc1b810eec15433e1c6497e/pyiron/project.py#L294-L309

I attach the notebook with corresponding error messages
[NotConvergedImports.zip](https://github.com/pyiron/pyiron/files/5274905/NotConvergedImports.zip)

**Comment by jan-janssen** [comment]
I do not understand this part either, because in the case the raw files are copied also the working directory should be updated to the right working directory https://github.com/pyiron/pyiron/blob/master/pyiron/project.py#L299 Can you maybe compile a short example which runs a pyiron calculation decompresses the working directory and then imports this directory? Such a setup would be self consistent and would help us to identify the cause of the error.

**Comment by jan-janssen** [comment]
Can you try if https://github.com/pyiron/pyiron_base/pull/22 resolves this issue?

**Comment by Leimeroth** [comment]
https://github.com/pyiron/pyiron/issues/995#issuecomment-698273582

I tried it with this notebook, does not seem to work.
[ReproduceImportBug.zip](https://github.com/pyiron/pyiron/files/5275609/ReproduceImportBug.zip)

**Comment by jan-janssen** [comment]
Can you try this one https://github.com/pyiron/pyiron/pull/996 ? In addition to the previous one.

**Comment by Leimeroth** [comment]
Not it works.
